import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';
import zlib from 'node:zlib';

const here = path.dirname(fileURLToPath(import.meta.url));
const script = path.join(here, 'games.mjs');

function run(...args) {
  const result = spawnSync(process.execPath, [script, ...args], { encoding: 'utf8' });
  assert.equal(result.status, 0, result.stderr);
  return result.stdout;
}

function viewerLogic() {
  const context = {};
  vm.runInNewContext(fs.readFileSync(path.join(here, 'model.js'), 'utf8'), context);
  return context;
}

function tokenFrames(count, edit = () => {}) {
  const tokens = Buffer.alloc(count * 894);
  for (let i = 0; i < count; i++) {
    for (let cell = 0; cell < 99; cell++) tokens.set([2, 1, 1], i * 894 + cell * 8);
    tokens.writeInt16LE(i + 1, i * 894 + 792);
  }
  edit(tokens);
  return tokens;
}

test('model logic compares token frames and labels annotations', () => {
  const logic = viewerLogic();
  const model = tokenFrames(3);
  const real = tokenFrames(3, tokens => { tokens[2 * 894 + 5 * 8 + 4] = 3; });
  assert.equal(logic.firstDivergence(model, model), -1);
  assert.equal(logic.firstDivergence(model, real), 2);
  assert.equal(logic.firstDivergence(model, real.subarray(0, 2 * 894)), -1);
  const aux = tokenFrames(2, tokens => { tokens.writeInt16LE(-1, 894 + 792 + 2 * 50); });
  assert.equal(logic.firstDivergence(tokenFrames(2), aux), 1);
  assert.equal(logic.tokenAux(aux, 1, 50), -1);
  assert.deepEqual([...logic.cellDiff(model, 2 * 894, real, 2 * 894)].flatMap((d, i) => d ? [i] : []), [5]);
  assert.equal(logic.cellDiff(model, 0, real, 0).reduce((a, b) => a + b), 0);
  const facing = tokenFrames(1, tokens => { tokens.writeInt16LE(1, 792 + 2 * 33); });
  assert.equal(logic.tokenDirection(facing, 0), 3);
  assert.equal(logic.tokenDirection(tokenFrames(1), 0), 0);
  assert.equal(logic.probabilityText(null), '—');
  assert.equal(logic.probabilityText(0.25), '25.0%');
  // A real archived frame is not the model's: its label must not say so.
  assert.equal(logic.frameSourceText('data'), 'a real game frame (data tokens)');
  assert.equal(logic.frameSourceText('model'), 'generated by the model');
  assert.equal(logic.frameSourceText('forced'), 'forced tokens');
  assert.equal(logic.frameSourceText(undefined), '—');
});

function writeModelBundle(directory, { reference = true } = {}) {
  const sha = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
  const frames = Buffer.alloc(2 * 7858);
  frames.writeUInt8(4, 12);
  frames.writeUInt8(255, 7858 + 12);
  frames.writeUInt16LE(3, 7858 + 20);
  const payloads = { frames, tokens: tokenFrames(2) };
  if (reference) payloads.reference = tokenFrames(3, tokens => { tokens[894 + 8] = 9; });
  fs.mkdirSync(directory);
  const digests = {};
  for (const [name, raw] of Object.entries(payloads)) {
    const packed = zlib.gzipSync(raw);
    fs.writeFileSync(path.join(directory, `${name}.bin.gz`), packed);
    digests[name] = [sha(raw), sha(packed)];
  }
  const manifest = {
    schema: 'craftax-model-game/v1', source: 'model', title: 'Dream', description: '1 generated decision',
    endLabel: 'End of generation', provenance: 'World-model generation', frames: 2, actions: 1, tick: 0,
    score: 3, achievements: 0, absent: ['tick', 'map'],
    framesSha256: digests.frames[0], gzipSha256: digests.frames[1],
    tokensSha256: digests.tokens[0], tokensGzipSha256: digests.tokens[1],
    referenceFrames: reference ? 3 : null,
    referenceSha256: reference ? digests.reference[0] : null,
    referenceGzipSha256: reference ? digests.reference[1] : null,
    annotations: {
      actionMarks: ['forced'], reward: [3], done: [false], rewardProb: [0.5], doneProb: [0.01],
      frameSource: ['model', 'model'], invalid: [[], [4]], overrides: [[], []],
    },
  };
  fs.writeFileSync(path.join(directory, 'manifest.json'), JSON.stringify(manifest));
  return manifest;
}

const embeddedGames = html => JSON.parse(html.match(/window\.CRAFTAX_GAMES=(\[.*?\]);window\.CRAFTAX_DEFAULT_GAME/s)[1]);

// An exact game of one decision: frame 1 is the final one (action 255) at tick
// 17, 2 points and one achievement; its health record lists one creature.
function writeExactBundle(directory, { frames = exactFrames(), health = exactHealth(), ...fields } = {}) {
  const sha = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
  const gzip = zlib.gzipSync(frames), healthGzip = zlib.gzipSync(health);
  fs.mkdirSync(directory);
  fs.writeFileSync(path.join(directory, 'frames.bin.gz'), gzip);
  fs.writeFileSync(path.join(directory, 'health.bin.gz'), healthGzip);
  const manifest = {
    schema: 'craftax-exact-game/v1', title: 'Test game', description: '1 recorded action',
    endLabel: 'End of recording', provenance: 'Hand-written frames', frames: 2, actions: 1, tick: 17,
    score: 2, achievements: 1, meanScore: 1.5, meanReturnPct: 100 * 1.5 / 226,
    framesSha256: sha(frames), gzipSha256: sha(gzip), healthSha256: sha(health), healthGzipSha256: sha(healthGzip),
    ...fields,
  };
  fs.writeFileSync(path.join(directory, 'manifest.json'), JSON.stringify(manifest));
  return { healthGzip };
}

function exactFrames() {
  const frames = Buffer.alloc(2 * 7858);
  frames.writeUInt32LE(17, 7858 + 4);
  frames.writeUInt8(255, 7858 + 12);
  frames.writeUInt16LE(2, 7858 + 20);
  frames.writeUInt8(1, 7858 + 832);
  return frames;
}

function exactHealth(records = 2) {
  const health = Buffer.alloc(records * 120);
  health.writeFloatLE(3, 120);
  health.writeFloatLE(5, 120 + 60);
  return health;
}

test('build a self-contained page from an exact and a model bundle', () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'craftax-replay-test-'));
  try {
    const exact = path.join(root, 'exact');
    const { healthGzip } = writeExactBundle(exact);
    const model = path.join(root, 'model');
    writeModelBundle(model);
    const page = path.join(root, 'games.html');
    run('build', '--output', page, '--page-title', 'Craftax across training', '--page-note', 'Five related checkpoints', '--picker-label', 'Checkpoint', '--default-game', 'last', exact, model);
    const html = fs.readFileSync(page, 'utf8');
    assert.match(html, /id="game-picker"/);
    assert.match(html, /Craftax across training/);
    assert.match(html, /Five related checkpoints/);
    assert.match(html, /<label for="game-picker">Checkpoint <\/label>/);
    assert.match(html, /Choose Checkpoint/);
    assert.match(html, /CRAFTAX_DEFAULT_GAME=1/);
    assert.match(html, /"meanScore":1\.5/);
    assert.match(html, /checkpoint average reward/);
    assert.match(html, /Health \/ maximum/);
    const games = embeddedGames(html);
    assert.deepEqual(games.map(game => game.kind), ['exact', 'model']);
    assert.equal(games[0].healthGzip, healthGzip.toString('base64'));
    assert.equal(games[1].healthGzip, null);
    assert.doesNotMatch(html, /src="(?:frames|hud|model|sprites)/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('build embeds model bundles with verified token and reference payloads', () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'craftax-model-test-'));
  try {
    const bundle = path.join(root, 'model');
    writeModelBundle(bundle);
    const plain = path.join(root, 'plain');
    writeModelBundle(plain, { reference: false });
    const page = path.join(root, 'page.html');
    run('build', '--output', page, bundle, plain);
    const html = fs.readFileSync(page, 'utf8');
    const games = embeddedGames(html);
    assert.deepEqual(games.map(game => game.kind), ['model', 'model']);
    assert.equal(games[0].source, 'model');
    assert.deepEqual(games[0].absent, ['tick', 'map']);
    assert.deepEqual(games[0].annotations.invalid, [[], [4]]);
    assert.ok(games[0].tokensGzip && games[0].referenceGzip);
    assert.equal(games[1].referenceGzip, null);
    assert.match(html, /function firstDivergence/);
    assert.doesNotMatch(html, /src="model\.js"/);
    fs.writeFileSync(path.join(bundle, 'reference.bin.gz'), zlib.gzipSync(Buffer.alloc(894)));
    const tampered = spawnSync(process.execPath, [script, 'build', '--output', page, bundle], { encoding: 'utf8' });
    assert.notEqual(tampered.status, 0);
    assert.match(tampered.stderr, /Reference payload hash mismatch/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('build embeds dollar patterns in titles and page text verbatim', () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'craftax-model-test-'));
  try {
    const bundle = path.join(root, 'model');
    const manifest = writeModelBundle(bundle);
    // In a replacement string, $' is the text after the match, $` the text
    // before it, $& the match itself, and $$ one dollar.
    const title = "Dream $' $` $& $$ end";
    fs.writeFileSync(path.join(bundle, 'manifest.json'), JSON.stringify({ ...manifest, title }));
    const page = path.join(root, 'page.html');
    run('build', '--output', page, '--page-title', 'Saved $$ games', bundle);
    const html = fs.readFileSync(page, 'utf8');
    assert.equal(embeddedGames(html)[0].title, title);
    assert.match(html, /<h1>Saved \$\$ games<\/h1>/);
    assert.equal(html.split('window.CRAFTAX_GAMES=').length, 2);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('build rejects annotations missing a frame or a decision', () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'craftax-model-test-'));
  try {
    for (const key of ['invalid', 'frameSource', 'overrides', 'actionMarks', 'rewardProb', 'doneProb']) {
      const bundle = path.join(root, key);
      const manifest = writeModelBundle(bundle);
      manifest.annotations[key].pop();
      fs.writeFileSync(path.join(bundle, 'manifest.json'), JSON.stringify(manifest));
      const built = spawnSync(process.execPath, [script, 'build', '--output', path.join(root, 'page.html'), bundle], { encoding: 'utf8' });
      assert.match(built.stderr, /Annotation\/frame mismatch/, key);
    }
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('build rejects an exact bundle whose payloads or summary disagree', () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'craftax-exact-test-'));
  try {
    const unmarked = exactFrames();
    unmarked.writeUInt8(0, 7858 + 12);
    const cases = {
      health: [{}, dir => fs.writeFileSync(path.join(dir, 'health.bin.gz'), zlib.gzipSync(Buffer.alloc(240, 1))), /Health payload hash mismatch/],
      count: [{ health: exactHealth(3) }, () => {}, /Health\/frame mismatch/],
      score: [{ score: 3 }, () => {}, /score mismatch/],
      tick: [{ tick: 18 }, () => {}, /tick mismatch/],
      marker: [{ frames: unmarked }, () => {}, /Missing final frame marker/],
    };
    for (const [name, [fields, damage, message]] of Object.entries(cases)) {
      const bundle = path.join(root, name);
      writeExactBundle(bundle, fields);
      damage(bundle);
      const built = spawnSync(process.execPath, [script, 'build', '--output', path.join(root, 'page.html'), bundle], { encoding: 'utf8' });
      assert.notEqual(built.status, 0, name);
      assert.match(built.stderr, message, name);
    }
    const bare = path.join(root, 'bare');
    writeExactBundle(bare, { healthSha256: null, healthGzipSha256: null });
    run('build', '--output', path.join(root, 'bare.html'), bare);
    assert.equal(embeddedGames(fs.readFileSync(path.join(root, 'bare.html'), 'utf8'))[0].healthGzip, null);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});
