'use strict';
// Viewer logic for model bundles: token-frame comparison and the model
// annotation text. The functions are pure so games.test.mjs can run them
// outside a browser.
const TOKEN_RECORD = 894;
function cellDiff(a, aOffset, b, bOffset) {
  const differs = new Uint8Array(99);
  for (let cell = 0; cell < 99; cell++) {
    for (let k = 0; k < 8; k++) {
      if (a[aOffset + cell * 8 + k] !== b[bOffset + cell * 8 + k]) { differs[cell] = 1; break; }
    }
  }
  return differs;
}
function firstDivergence(model, reference) {
  if (!model || !reference) return -1;
  const frames = Math.min(model.length, reference.length) / TOKEN_RECORD;
  for (let i = 0; i < frames; i++) {
    for (let b = i * TOKEN_RECORD; b < (i + 1) * TOKEN_RECORD; b++) {
      if (model[b] !== reference[b]) return i;
    }
  }
  return -1;
}
function tokenAux(tokens, frame, field) {
  const at = frame * TOKEN_RECORD + 792 + 2 * field;
  return (tokens[at] | (tokens[at + 1] << 8)) << 16 >> 16;
}
function tokenDirection(tokens, frame) {
  for (let k = 0; k < 4; k++) if (tokenAux(tokens, frame, 31 + k)) return k + 1;
  return 0;
}
function probabilityText(p) {
  return p === null || p === undefined ? '—' : `${(100 * p).toFixed(p < 0.001 || p > 0.999 ? 3 : 1)}%`;
}
// Where a frame's tokens came from, as the model annotations name it.
const FRAME_SOURCES = { model: 'generated by the model', data: 'a real game frame (data tokens)' };
function frameSourceText(source) {
  return source === undefined ? '—' : FRAME_SOURCES[source] ?? `${source} tokens`;
}
