from collections.abc import (
    Callable as Callable,
    Generator,
)
from typing import Any, Generic, Protocol, TypeVar

import dataclasses
import enum

from flax.core import FrozenDict as FrozenDict
from flax.errors import (
    CursorFindError as CursorFindError,
    TraverseTreeError as TraverseTreeError,
)

A = TypeVar("A")
type Key = Any

class Indexable(Protocol):
    def __getitem__(self, key) -> Any: ...

class AccessType(enum.Enum):
    ITEM = ...
    ATTR = ...

@dataclasses.dataclass
class ParentKey(Generic[A]):
    parent: Cursor[A]
    key: Key
    access_type: AccessType

def is_named_tuple(obj): ...

class Cursor(Generic[A]):
    def __init__(self, obj: A, parent_key: ParentKey[A] | None) -> None: ...
    def __getitem__(self, key) -> Cursor[A]: ...
    def __getattr__(self, name) -> Cursor[A]: ...
    def __setitem__(self, key, value) -> None: ...
    def __setattr__(self, name, value) -> None: ...
    def set(self, value) -> A: ...
    def build(self) -> A: ...
    def apply_update(self, update_fn: Callable[[str, Any], Any]) -> Cursor[A]: ...
    def find(self, cond_fn: Callable[[str, Any], bool]) -> Cursor[A]: ...
    def find_all(self, cond_fn: Callable[[str, Any], bool]) -> Generator[Cursor[A]]: ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def __reversed__(self): ...
    def __add__(self, other): ...
    def __sub__(self, other): ...
    def __mul__(self, other): ...
    def __matmul__(self, other): ...
    def __truediv__(self, other): ...
    def __floordiv__(self, other): ...
    def __mod__(self, other): ...
    def __divmod__(self, other): ...
    def __pow__(self, other): ...
    def __lshift__(self, other): ...
    def __rshift__(self, other): ...
    def __and__(self, other): ...
    def __xor__(self, other): ...
    def __or__(self, other): ...
    def __radd__(self, other): ...
    def __rsub__(self, other): ...
    def __rmul__(self, other): ...
    def __rmatmul__(self, other): ...
    def __rtruediv__(self, other): ...
    def __rfloordiv__(self, other): ...
    def __rmod__(self, other): ...
    def __rdivmod__(self, other): ...
    def __rpow__(self, other): ...
    def __rlshift__(self, other): ...
    def __rrshift__(self, other): ...
    def __rand__(self, other): ...
    def __rxor__(self, other): ...
    def __ror__(self, other): ...
    def __neg__(self): ...
    def __pos__(self): ...
    def __abs__(self): ...
    def __invert__(self): ...
    def __round__(self, ndigits=None): ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

def cursor(obj: A) -> Cursor[A]: ...
