class FlaxError(Exception):
    def __init__(self, message) -> None: ...
    def __reduce__(self): ...

class TraceContextError(FlaxError): ...

class LazyInitError(FlaxError):
    def __init__(self, partial_val) -> None: ...

class InvalidRngError(FlaxError):
    def __init__(self, msg) -> None: ...

class ApplyScopeInvalidVariablesTypeError(FlaxError):
    def __init__(self) -> None: ...

class ApplyScopeInvalidVariablesStructureError(FlaxError):
    def __init__(self, variables) -> None: ...

class ScopeParamNotFoundError(FlaxError):
    def __init__(self, param_name, scope_path) -> None: ...

class ScopeCollectionNotFound(FlaxError):
    def __init__(self, col_name, var_name, scope_path) -> None: ...

class ScopeParamShapeError(FlaxError):
    def __init__(self, param_name, scope_path, value_shape, init_shape) -> None: ...

class ScopeVariableNotFoundError(FlaxError):
    def __init__(self, name, col, scope_path) -> None: ...

class InvalidFilterError(FlaxError):
    def __init__(self, filter_like) -> None: ...

class InvalidScopeError(FlaxError):
    def __init__(self, scope_name) -> None: ...

class ModifyScopeVariableError(FlaxError):
    def __init__(self, col, variable_name, scope_path) -> None: ...

class ImmutableVariableError(FlaxError):
    def __init__(self, message) -> None: ...

class JaxTransformError(FlaxError):
    def __init__(self) -> None: ...

class PartitioningUnspecifiedError(FlaxError):
    def __init__(self, target) -> None: ...

class NameInUseError(FlaxError):
    def __init__(self, key_type, value, module_name) -> None: ...

class AssignSubModuleError(FlaxError):
    def __init__(self, cls) -> None: ...

class SetAttributeInModuleSetupError(FlaxError):
    def __init__(self) -> None: ...

class SetAttributeFrozenModuleError(FlaxError):
    def __init__(self, module_cls, attr_name, attr_val) -> None: ...

class MultipleMethodsCompactError(FlaxError):
    def __init__(self) -> None: ...

class ReservedModuleAttributeError(FlaxError):
    def __init__(self, annotations) -> None: ...

class ApplyModuleInvalidMethodError(FlaxError):
    def __init__(self, method) -> None: ...

class CallCompactUnboundModuleError(FlaxError):
    def __init__(self) -> None: ...

class CallSetupUnboundModuleError(FlaxError):
    def __init__(self) -> None: ...

class CallUnbindOnUnboundModuleError(FlaxError):
    def __init__(self) -> None: ...

class CallShareScopeOnUnboundModuleError(FlaxError):
    def __init__(self) -> None: ...

class InvalidInstanceModuleError(FlaxError):
    def __init__(self) -> None: ...

class IncorrectPostInitOverrideError(FlaxError):
    def __init__(self) -> None: ...

class DescriptorAttributeError(FlaxError):
    def __init__(self) -> None: ...

class InvalidCheckpointError(FlaxError):
    def __init__(self, path, step) -> None: ...

class MPACheckpointingRequiredError(FlaxError):
    def __init__(self, path, step) -> None: ...

class MPARestoreTargetRequiredError(FlaxError):
    def __init__(self, path, step, key=None) -> None: ...

class MPARestoreDataCorruptedError(FlaxError):
    def __init__(self, step, path) -> None: ...

class TransformedMethodReturnValueError(FlaxError):
    def __init__(self, name) -> None: ...

class TransformTargetError(FlaxError):
    def __init__(self, target) -> None: ...

class AlreadyExistsError(FlaxError):
    def __init__(self, path) -> None: ...

class CursorFindError(FlaxError):
    def __init__(self, cursor=None, cursor2=None) -> None: ...

class TraverseTreeError(FlaxError):
    def __init__(self, update_fn, cond_fn) -> None: ...
