from enum import Enum

import contextlib

from _typeshed import Incomplete

from . import errors as errors

class BackendMode(Enum):
    DEFAULT = 0
    TF = 1

io_mode: Incomplete
gfile: Incomplete
NotFoundError: Incomplete
NotFoundError = FileNotFoundError

@contextlib.contextmanager
def override_mode(override: BackendMode): ...
def set_mode(override: BackendMode): ...
def GFile(name, mode): ...
def listdir(path): ...
def isdir(path): ...
def copy(src, dst, overwrite: bool = False): ...
def rename(src, dst, overwrite: bool = False): ...
def exists(path): ...
def makedirs(path): ...
def glob(pattern): ...
def remove(path): ...
def rmtree(path): ...
def getsize(path): ...
