from _typeshed import Incomplete
from flax import config as config

api_boundary: Incomplete

def register_exclusion(path) -> None: ...
def hide_flax_in_tracebacks() -> None: ...
def show_flax_in_tracebacks() -> None: ...
