from collections.abc import (
    Callable as Callable,
    Generator,
)
from typing import Any

import abc

from _typeshed import Incomplete
from flax.core.scope import VariableDict as VariableDict
from flax.typing import PathParts as PathParts

from . import struct as struct

@struct.dataclass
class _EmptyNode: ...

empty_node: Incomplete

def flatten_dict(xs, keep_empty_nodes: bool = False, is_leaf=None, sep=None): ...
def unflatten_dict(xs, sep=None): ...
def path_aware_map(
    f: Callable[[PathParts, Any], Any],
    nested_dict: VariableDict,
) -> VariableDict: ...

class Traversal(abc.ABC, metaclass=abc.ABCMeta):
    def __new__(cls, *args, **kwargs): ...
    @abc.abstractmethod
    def update(self, fn, inputs): ...
    @abc.abstractmethod
    def iterate(self, inputs): ...
    def set(self, values, inputs): ...
    def compose(self, other): ...
    def merge(self, *traversals): ...
    def each(self): ...
    def tree(self): ...
    def filter(self, fn): ...
    def __getattr__(self, attr): ...
    def __getitem__(self, key): ...

class TraverseId(Traversal):
    def update(self, fn, inputs): ...
    def iterate(self, inputs) -> Generator[Incomplete]: ...

t_identity: Incomplete

class TraverseMerge(Traversal):
    def __init__(self, *traversals) -> None: ...
    def update(self, fn, inputs): ...
    def iterate(self, inputs) -> Generator[Incomplete, Incomplete]: ...

class TraverseCompose(Traversal):
    def __init__(self, x, y) -> None: ...
    def update(self, fn, inputs): ...
    def iterate(self, inputs) -> Generator[Incomplete, Incomplete]: ...

class TraverseFilter(Traversal):
    def __init__(self, fn) -> None: ...
    def update(self, fn, inputs): ...
    def iterate(self, inputs) -> Generator[Incomplete]: ...

class TraverseAttr(Traversal):
    def __init__(self, attr) -> None: ...
    def update(self, fn, inputs): ...
    def iterate(self, inputs) -> Generator[Incomplete]: ...

class TraverseItem(Traversal):
    def __init__(self, key) -> None: ...
    def update(self, fn, inputs): ...
    def iterate(self, inputs) -> Generator[Incomplete, Incomplete]: ...

class TraverseEach(Traversal):
    def update(self, fn, inputs): ...
    def iterate(self, inputs) -> Generator[Incomplete, Incomplete]: ...

class TraverseTree(Traversal):
    def update(self, fn, inputs): ...
    def iterate(self, inputs) -> Generator[Incomplete, Incomplete]: ...

class ModelParamTraversal(Traversal):
    def __init__(self, filter_fn) -> None: ...
    def iterate(self, inputs) -> Generator[Incomplete]: ...
    def update(self, fn, inputs): ...
