from collections.abc import Callable
from enum import Enum
from functools import lru_cache

import functools

import torch

logger = ...
FLA_CI_ENV = ...
FLA_CACHE_RESULTS = ...
FLA_DISABLE_TENSOR_CACHE = ...
TRITON_ABOVE_3_4_0 = ...
TRITON_ABOVE_3_5_1 = ...
SUPPORTS_AUTOTUNE_CACHE = ...
autotune_cache_kwargs = ...

@lru_cache(maxsize=1)
def check_environments() -> None: ...
def get_abs_err(x, y): ...
def get_err_ratio(x, y): ...
def assert_close(prefix, ref, tri, ratio, warning=..., err_atol=...) -> None: ...
def tensor_cache(fn: Callable[..., torch.Tensor]) -> Callable[..., torch.Tensor]: ...
def input_guard(
    fn: Callable[..., torch.Tensor] | None = ...,
    *,
    no_guard_contiguous: bool | list[str] = ...,
) -> (
    Callable[[Callable[..., torch.Tensor]], Callable[..., torch.Tensor]]
    | Callable[..., torch.Tensor]
): ...
def contiguous(fn: Callable[..., torch.Tensor]) -> Callable[..., torch.Tensor]: ...
def require_version(version, hint) -> Callable[..., _Wrapped[..., Any, ..., Any]]: ...

class Action(Enum):
    NONE = ...
    NOTIFY = ...
    NOTIFY_ALWAYS = ...
    RAISE = ...

def deprecate_kwarg(
    old_name: str,
    version: str,
    new_name: str | None = ...,
    warn_if_greater_or_equal_version: bool = ...,
    raise_if_greater_or_equal_version: bool = ...,
    raise_if_both_names: bool = ...,
    additional_message: str | None = ...,
) -> Callable[..., _Wrapped[..., Any, ..., Any]]: ...
def checkpoint(fn) -> Callable[..., Any]: ...
@functools.cache
def check_pytorch_version(version_s: str = ...) -> bool: ...
@functools.cache
def get_multiprocessor_count(tensor_idx: int = ...) -> int: ...
@functools.cache
def get_available_device() -> str: ...
def map_triton_backend_to_torch_device() -> str: ...

device = ...
device_torch_lib = ...
device_platform = ...
device_name = ...
IS_AMD = ...
IS_INTEL = ...
IS_NVIDIA = ...
IS_INTEL_ALCHEMIST = ...
IS_NVIDIA_HOPPER = ...
IS_NVIDIA_BLACKWELL = ...
USE_CUDA_GRAPH = ...
IS_TF32_SUPPORTED = ...
IS_GATHER_SUPPORTED = ...
IS_TMA_SUPPORTED = ...
if IS_TMA_SUPPORTED: ...
else: ...

def get_all_max_shared_mem() -> list[Any] | list[int]: ...

class Backend(Enum):
    ADA = ...
    AMPERE = ...
    HOPPER = ...
    DEFAULT = ...
    @classmethod
    def get_shared_memory(cls, arch: str) -> int: ...

@functools.cache
def check_shared_mem(arch: str = ..., tensor_idx: int = ...) -> bool: ...

if check_pytorch_version("2.4"):
    device = ...
    autocast_custom_fwd = ...
    autocast_custom_bwd = ...
    def custom_device_ctx(index: int) -> Any: ...

else:
    autocast_custom_fwd = ...
    autocast_custom_bwd = ...
    def custom_device_ctx(index: int) -> device: ...
