import jax.numpy as jnp

def is_tpu() -> bool: ...
def tpu_kind() -> str: ...
def tpu_generation() -> int: ...
def supports_bfloat16_matmul() -> bool: ...
def assert_is_supported_dtype(dtype: jnp.dtype) -> None: ...
def select_input_dtype(lhs: jnp.ndarray, rhs: jnp.ndarray) -> jnp.dtype: ...
