"""Per-floor terrain recipes.

The world has two kinds of floor, generated by two different procedures, and
each floor supplies the procedure with its own blocks and thresholds. That is
what makes the ice realm read as ice and the fire realm as fire while both run
the same code: only the values differ.

These are frozen dataclasses rather than configgle configs because they are
part of the game's definition, not an experiment's choice -- a run that alters
them is playing a different game and its score is not comparable.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final

from priml.baselines.craftax.constants import BlockType


@dataclass(frozen=True, slots=True, kw_only=True)
class SmoothWorldConfig:
    """Blocks and thresholds for a floor grown from terrain noise.

    Attributes:
      default_block: What a tile is when no other rule claims it.
      sea_block: Fills the low ground below ``water_threshold``.
      coast_block: Rings the sea, between the two thresholds.
      mountain_block: Fills the high ground.
      path_block: Carved through the mountains.
      inner_mountain_block: Fills caves inside the mountains.
      ore_requirement_blocks: Which block each ore may replace.
      ores: The five ores placed on this floor.
      ore_chances: Probability of each ore per eligible tile.
      tree_requirement_block: Which block a tree may grow on.
      tree: The tree-like block for this floor.
      lava: The hazard block; some floors use water instead.
      player_spawn: Forced under the player so they never spawn inside rock.
      valid_ladder: Which block a ladder may be placed on.
      ladder_up: Whether this floor has an ascent.
      ladder_down: Whether this floor has a descent.
      player_proximity_map_water_strength: How far from the player the sea is
        suppressed; larger keeps water further away.
      player_proximity_map_water_max: Cap on that suppression.
      player_proximity_map_mountain_strength: The same, for mountains.
      player_proximity_map_mountain_max: Cap on that suppression.
      default_light: Ambient light; zero means the floor is dark.
      water_threshold: Noise level above which a tile becomes sea.
      sand_threshold: Noise level above which a tile becomes coast.
      tree_threshold_uniform: Per-tile draw a tree must beat.
      tree_threshold_perlin: Noise level a tree needs.

    """

    default_block: int
    sea_block: int
    coast_block: int
    mountain_block: int
    path_block: int
    inner_mountain_block: int
    ore_requirement_blocks: tuple[int, ...]
    ores: tuple[int, ...]
    ore_chances: tuple[float, ...]
    tree_requirement_block: int
    tree: int
    lava: int
    player_spawn: int
    valid_ladder: int
    ladder_up: bool
    ladder_down: bool
    player_proximity_map_water_strength: float
    player_proximity_map_water_max: float
    player_proximity_map_mountain_strength: float
    player_proximity_map_mountain_max: float
    default_light: float
    water_threshold: float
    sand_threshold: float
    tree_threshold_uniform: float
    tree_threshold_perlin: float


@dataclass(frozen=True, slots=True, kw_only=True)
class DungeonConfig:
    """Blocks for a floor built from rooms and corridors.

    Attributes:
      special_block: Placed once, in the first room; the enchantment tables
        sit here on the floors that have them.
      fountain_block: What fills the fountain alcoves.
      rare_path_replacement_block: Scattered over the corridors for texture.

    """

    special_block: int
    fountain_block: int
    rare_path_replacement_block: int


OVERWORLD: Final = SmoothWorldConfig(
    default_block=BlockType.GRASS,
    sea_block=BlockType.WATER,
    coast_block=BlockType.SAND,
    mountain_block=BlockType.STONE,
    path_block=BlockType.PATH,
    inner_mountain_block=BlockType.PATH,
    ore_requirement_blocks=(BlockType.STONE,) * 5,
    ores=(
        BlockType.COAL,
        BlockType.IRON,
        BlockType.DIAMOND,
        # The last two slots are unused here: the overworld has no gems, and
        # an impossible requirement block plus a zero chance disables them.
        BlockType.OUT_OF_BOUNDS,
        BlockType.OUT_OF_BOUNDS,
    ),
    ore_chances=(0.03, 0.02, 0.001, 0.0, 0.0),
    tree_requirement_block=BlockType.GRASS,
    tree=BlockType.TREE,
    lava=BlockType.LAVA,
    player_spawn=BlockType.GRASS,
    valid_ladder=BlockType.PATH,
    ladder_up=False,
    ladder_down=True,
    player_proximity_map_water_strength=5,
    player_proximity_map_water_max=1,
    player_proximity_map_mountain_strength=5,
    player_proximity_map_mountain_max=1,
    default_light=1.0,
    water_threshold=0.7,
    sand_threshold=0.6,
    tree_threshold_uniform=0.8,
    tree_threshold_perlin=0.5,
)

GNOMISH_MINES: Final = SmoothWorldConfig(
    default_block=BlockType.PATH,
    sea_block=BlockType.WATER,
    coast_block=BlockType.PATH,
    mountain_block=BlockType.STONE,
    path_block=BlockType.STONE,
    inner_mountain_block=BlockType.STONE,
    ore_requirement_blocks=(BlockType.STONE,) * 5,
    ores=(
        BlockType.COAL,
        BlockType.IRON,
        BlockType.DIAMOND,
        BlockType.SAPPHIRE,
        BlockType.RUBY,
    ),
    ore_chances=(0.04, 0.02, 0.005, 0.0025, 0.0025),
    tree_requirement_block=BlockType.PATH,
    tree=BlockType.STALAGMITE,
    lava=BlockType.LAVA,
    player_spawn=BlockType.PATH,
    valid_ladder=BlockType.PATH,
    ladder_up=True,
    ladder_down=True,
    player_proximity_map_water_strength=5,
    player_proximity_map_water_max=1,
    player_proximity_map_mountain_strength=17,
    player_proximity_map_mountain_max=1.5,
    default_light=0.0,
    water_threshold=0.7,
    sand_threshold=0.6,
    tree_threshold_uniform=0.8,
    tree_threshold_perlin=0.5,
)

TROLL_MINES: Final = SmoothWorldConfig(
    default_block=BlockType.PATH,
    sea_block=BlockType.WATER,
    coast_block=BlockType.PATH,
    mountain_block=BlockType.STONE,
    path_block=BlockType.STONE,
    inner_mountain_block=BlockType.STONE,
    ore_requirement_blocks=(BlockType.STONE,) * 5,
    ores=(
        BlockType.COAL,
        BlockType.IRON,
        BlockType.DIAMOND,
        BlockType.SAPPHIRE,
        BlockType.RUBY,
    ),
    ore_chances=(0.04, 0.03, 0.01, 0.01, 0.01),
    tree_requirement_block=BlockType.PATH,
    tree=BlockType.STALAGMITE,
    lava=BlockType.LAVA,
    player_spawn=BlockType.PATH,
    valid_ladder=BlockType.PATH,
    ladder_up=True,
    ladder_down=True,
    player_proximity_map_water_strength=5,
    player_proximity_map_water_max=1,
    player_proximity_map_mountain_strength=17,
    player_proximity_map_mountain_max=1.5,
    default_light=0.0,
    water_threshold=0.7,
    sand_threshold=0.6,
    tree_threshold_uniform=0.8,
    tree_threshold_perlin=0.5,
)

FIRE_REALM: Final = SmoothWorldConfig(
    default_block=BlockType.FIRE_GRASS,
    sea_block=BlockType.LAVA,
    coast_block=BlockType.SAND,
    mountain_block=BlockType.STONE,
    path_block=BlockType.STONE,
    inner_mountain_block=BlockType.STONE,
    ore_requirement_blocks=(BlockType.STONE,) * 5,
    ores=(
        BlockType.COAL,
        BlockType.IRON,
        BlockType.DIAMOND,
        BlockType.SAPPHIRE,
        BlockType.RUBY,
    ),
    ore_chances=(0.05, 0.0, 0.0, 0.0, 0.025),
    tree_requirement_block=BlockType.FIRE_GRASS,
    tree=BlockType.FIRE_TREE,
    lava=BlockType.LAVA,
    player_spawn=BlockType.FIRE_GRASS,
    valid_ladder=BlockType.FIRE_GRASS,
    ladder_up=True,
    ladder_down=True,
    player_proximity_map_water_strength=5,
    player_proximity_map_water_max=1,
    player_proximity_map_mountain_strength=5,
    player_proximity_map_mountain_max=1,
    default_light=1.0,
    water_threshold=0.5,
    sand_threshold=0.6,
    tree_threshold_uniform=0.8,
    tree_threshold_perlin=0.5,
)

ICE_REALM: Final = SmoothWorldConfig(
    default_block=BlockType.ICE_GRASS,
    sea_block=BlockType.WATER,
    coast_block=BlockType.ICE_GRASS,
    mountain_block=BlockType.STONE,
    path_block=BlockType.STONE,
    inner_mountain_block=BlockType.STONE,
    ore_requirement_blocks=(BlockType.STONE,) * 5,
    ores=(
        BlockType.COAL,
        BlockType.IRON,
        BlockType.DIAMOND,
        BlockType.SAPPHIRE,
        BlockType.RUBY,
    ),
    ore_chances=(0.0, 0.0, 0.005, 0.02, 0.0),
    tree_requirement_block=BlockType.ICE_GRASS,
    tree=BlockType.ICE_SHRUB,
    # The ice realm has no lava: its hazard rule reuses the same slot with
    # water, which is why the lava light-map contribution vanishes here.
    lava=BlockType.WATER,
    player_spawn=BlockType.ICE_GRASS,
    valid_ladder=BlockType.ICE_GRASS,
    ladder_up=True,
    ladder_down=True,
    player_proximity_map_water_strength=5,
    player_proximity_map_water_max=1,
    player_proximity_map_mountain_strength=17,
    player_proximity_map_mountain_max=1.5,
    default_light=0.0,
    water_threshold=0.5,
    sand_threshold=0.6,
    tree_threshold_uniform=0.4,
    tree_threshold_perlin=0.5,
)

GRAVEYARD: Final = SmoothWorldConfig(
    default_block=BlockType.PATH,
    sea_block=BlockType.PATH,
    coast_block=BlockType.PATH,
    mountain_block=BlockType.WALL,
    path_block=BlockType.WALL,
    inner_mountain_block=BlockType.WALL,
    # The ore rule is repurposed to scatter graves and mossy walls rather than
    # minerals, which is why the requirement blocks differ per slot here.
    ore_requirement_blocks=(
        BlockType.WALL,
        BlockType.GRAVE,
        BlockType.GRAVE,
        BlockType.WALL,
        BlockType.WALL,
    ),
    ores=(
        BlockType.WALL_MOSS,
        BlockType.GRAVE2,
        BlockType.GRAVE3,
        BlockType.SAPPHIRE,
        BlockType.RUBY,
    ),
    ore_chances=(0.1, 0.333, 0.5, 0.0, 0.0),
    tree_requirement_block=BlockType.PATH,
    tree=BlockType.GRAVE,
    lava=BlockType.WALL,
    player_spawn=BlockType.NECROMANCER,
    valid_ladder=BlockType.PATH,
    ladder_up=False,
    ladder_down=False,
    player_proximity_map_water_strength=5,
    player_proximity_map_water_max=1,
    player_proximity_map_mountain_strength=10,
    player_proximity_map_mountain_max=10,
    default_light=0.0,
    water_threshold=0.7,
    sand_threshold=0.6,
    tree_threshold_uniform=0.95,
    # Negative, so every tile clears the noise test and only the uniform draw
    # decides: graves are scattered rather than clustered like a forest.
    tree_threshold_perlin=-1.0,
)

SMOOTH_WORLD_CONFIGS: Final = (
    OVERWORLD,
    GNOMISH_MINES,
    TROLL_MINES,
    FIRE_REALM,
    ICE_REALM,
    GRAVEYARD,
)
"""Noise-grown floors, in the order the world builder consumes them."""

DUNGEON: Final = DungeonConfig(
    special_block=BlockType.PATH,
    fountain_block=BlockType.FOUNTAIN,
    rare_path_replacement_block=BlockType.PATH,
)

SEWERS: Final = DungeonConfig(
    special_block=BlockType.ENCHANTMENT_TABLE_ICE,
    fountain_block=BlockType.WATER,
    rare_path_replacement_block=BlockType.WATER,
)

VAULTS: Final = DungeonConfig(
    special_block=BlockType.ENCHANTMENT_TABLE_FIRE,
    fountain_block=BlockType.FOUNTAIN,
    rare_path_replacement_block=BlockType.PATH,
)

DUNGEON_CONFIGS: Final = (DUNGEON, SEWERS, VAULTS)
"""Room-and-corridor floors, in the order the world builder consumes them."""

LEVEL_CONFIGS: Final = (
    OVERWORLD,
    DUNGEON,
    GNOMISH_MINES,
    SEWERS,
    VAULTS,
    TROLL_MINES,
    FIRE_REALM,
    ICE_REALM,
    GRAVEYARD,
)
"""Every floor in descent order, which is the order the player meets them."""
