from absl.testing import parameterized
from optax import assignment as assignment

class HungarianAlgorithmTest(parameterized.TestCase):
    def test_hungarian_algorithm(self, fn, n, m) -> None: ...
    def test_hungarian_algorithm_vmap(self, fn, k, n, m) -> None: ...
    def test_hungarian_algorithm_jit(self, fn) -> None: ...
