import dataclasses
import typing as tp

from _typeshed import Incomplete
from flax.typing import (
    Key as Key,
    PathParts as PathParts,
)

ellipsis: Incomplete
type Predicate = tp.Callable[[PathParts, tp.Any], bool]
type FilterLiteral = type | str | Predicate | bool | ellipsis | None
Filter: Incomplete

def to_predicate(filter: Filter) -> Predicate: ...
def filters_to_predicates(filters: tp.Sequence[Filter]) -> tuple[Predicate, ...]: ...

class HasTag(tp.Protocol):
    tag: str

@dataclasses.dataclass(frozen=True)
class WithTag:
    tag: str
    def __call__(self, path: PathParts, x: tp.Any): ...

@dataclasses.dataclass(frozen=True)
class PathContains:
    key: Key | str
    exact: bool = ...
    def __call__(self, path: PathParts, x: tp.Any): ...

class PathIn:
    paths: Incomplete
    def __init__(self, *paths: PathParts) -> None: ...
    def __call__(self, path: PathParts, x: tp.Any): ...
    def __eq__(self, other): ...
    def __hash__(self): ...

@dataclasses.dataclass(frozen=True)
class OfType:
    type: type
    def __call__(self, path: PathParts, x: tp.Any): ...

class Any:
    predicates: Incomplete
    def __init__(self, *filters: Filter) -> None: ...
    def __call__(self, path: PathParts, x: tp.Any): ...
    def __eq__(self, other): ...
    def __hash__(self): ...

class All:
    predicates: Incomplete
    def __init__(self, *filters: Filter) -> None: ...
    def __call__(self, path: PathParts, x: tp.Any): ...
    def __eq__(self, other): ...
    def __hash__(self): ...

class Not:
    predicate: Incomplete
    def __init__(self, collection_filter: Filter, /) -> None: ...
    def __call__(self, path: PathParts, x: tp.Any): ...
    def __eq__(self, other): ...
    def __hash__(self): ...

class Everything:
    def __call__(self, path: PathParts, x: tp.Any): ...
    def __eq__(self, other): ...
    def __hash__(self): ...

class Nothing:
    def __call__(self, path: PathParts, x: tp.Any): ...
    def __eq__(self, other): ...
    def __hash__(self): ...
