from _typeshed import Incomplete

class UUIDManager:
    def __init__(self) -> None: ...
    def __call__(self): ...

uuid: Incomplete

class UUID:
    id: Incomplete
    def __init__(self, rawid) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def __deepcopy__(self, memo): ...
    def __copy__(self): ...
