import dataclasses
import typing as tp

A = tp.TypeVar("A", covariant=True)

@dataclasses.dataclass(frozen=True)
class GetItem:
    key: tp.Any

@dataclasses.dataclass(frozen=True)
class GetAttr:
    name: str

@dataclasses.dataclass(frozen=True)
class DelayedAccessor:
    actions: tuple[GetItem | GetAttr, ...] = ...
    def __call__(self, x): ...
    def __getattr__(self, name): ...
    def __getitem__(self, key): ...

class _AccessorCall(tp.Protocol):
    def __call__(self, accessor: DelayedAccessor, /, *args, **kwargs) -> tp.Any: ...

class CallableProxy:
    def __init__(
        self,
        callable: _AccessorCall,
        accessor: DelayedAccessor | None = None,
    ) -> None: ...
    def __call__(self, *args, **kwargs): ...
    def __getattr__(self, name) -> CallableProxy: ...
    def __getitem__(self, key) -> CallableProxy: ...

class ApplyCaller(tp.Protocol, tp.Generic[A]):
    def __getattr__(self, __name) -> ApplyCaller[A]: ...
    def __getitem__(self, __name) -> ApplyCaller[A]: ...
    def __call__(self, *args, **kwargs) -> tuple[tp.Any, A]: ...
