from collections.abc import Generator

from _typeshed import Incomplete
from flax.nnx import reprlib as reprlib

def current_jax_trace(): ...

class TraceState(reprlib.Representable):
    def __init__(self) -> None: ...
    @property
    def jax_trace(self): ...
    def is_valid(self) -> bool: ...
    def __nnx_repr__(self) -> Generator[Incomplete]: ...
    def __treescope_repr__(self, path, subtree_renderer): ...
    def __eq__(self, other): ...
