_HAS_CPU_VIDEO_DECODER = ...
_HAS_VIDEO_OPT = ...
default_timebase = ...

class Timebase:
    __annotations__ = ...
    __slots__ = ...
    def __init__(self, numerator: int, denominator: int) -> None: ...

class VideoMetaData:
    __annotations__ = ...
    __slots__ = ...
    def __init__(self) -> None: ...
