from fractions import Fraction
from typing import Any

import av
import torch

"""
This type stub file was generated by pyright.
"""
if not hasattr(av.video.frame.VideoFrame, "pict_type"):
    av = ...
FFmpegError = ...
_CALLED_TIMES = ...
_GC_COLLECTION_INTERVAL = ...

def write_video(
    filename: str,
    video_array: torch.Tensor,
    fps: float,
    video_codec: str = ...,
    options: dict[str, Any] | None = ...,
    audio_array: torch.Tensor | None = ...,
    audio_fps: float | None = ...,
    audio_codec: str | None = ...,
    audio_options: dict[str, Any] | None = ...,
) -> None: ...
def read_video(
    filename: str,
    start_pts: float | Fraction = ...,
    end_pts: float | Fraction | None = ...,
    pts_unit: str = ...,
    output_format: str = ...,
) -> tuple[torch.Tensor, torch.Tensor, dict[str, Any]]: ...
def read_video_timestamps(
    filename: str, pts_unit: str = ...
) -> tuple[list[int], float | None]: ...
