from typing import IO, Any

import cmd

from _typeshed import Incomplete

DebuggerFrame: Incomplete

class CliDebugger(cmd.Cmd):
    prompt: str
    use_rawinput: Incomplete
    frames: Incomplete
    frame_index: int
    thread_id: Incomplete
    intro: str
    def __init__(
        self,
        frames: list[DebuggerFrame],
        thread_id,
        stdin: IO[str] | None = None,
        stdout: IO[str] | None = None,
        completekey: str = "tab",
    ) -> None: ...
    def current_frame(self): ...
    def evaluate(self, expr): ...
    def default(self, line) -> None: ...
    def print_backtrace(self) -> None: ...
    def print_context(self, num_lines: int = 2) -> None: ...
    def do_p(self, arg) -> None: ...
    def do_pp(self, arg) -> None: ...
    def do_up(self, arg, /) -> None: ...
    do_u = do_up
    def do_down(self, arg, /) -> None: ...
    do_d = do_down
    def do_list(self, _) -> None: ...
    do_l = do_list
    def do_continue(self, _): ...
    do_c = do_continue
    do_cont = do_continue
    def do_quit(self, _) -> None: ...
    do_q = do_quit
    do_EOF = do_quit
    do_exit = do_quit
    def do_where(self, _) -> None: ...
    do_w = do_where
    do_bt = do_where
    def run(self) -> None: ...

def run_debugger(frames: list[DebuggerFrame], thread_id: int | None, **kwargs: Any): ...
