from _typeshed import Incomplete
from jax._src.debugger import (
    cli_debugger as cli_debugger,
    colab_lib as colab_lib,
    core as debugger_core,
)

IS_PYGMENTS_ENABLED: bool

class CodeViewer(colab_lib.DynamicDOMElement):
    def __init__(
        self,
        code_: str,
        highlights: list[int],
        linenostart: int = 1,
    ) -> None: ...
    def render(self) -> None: ...
    def clear(self) -> None: ...
    def append(self, child) -> None: ...
    def update(self, elem) -> None: ...
    def update_code(self, code_, highlights, *, linenostart: int = 1): ...

class FramePreview(colab_lib.DynamicDOMElement):
    frame: Incomplete
    def __init__(self, frame) -> None: ...
    def clear(self) -> None: ...
    def append(self, child) -> None: ...
    def update(self, elem) -> None: ...
    def update_frame(self, frame) -> None: ...
    def render(self) -> None: ...

class DebuggerView(colab_lib.DynamicDOMElement):
    def __init__(self, frame, *, log_color: str = "") -> None: ...
    def render(self) -> None: ...
    def append(self, child) -> None: ...
    def update(self, elem) -> None: ...
    def clear(self) -> None: ...
    def update_frame(self, frame) -> None: ...
    def write(self, text) -> None: ...
    def read(self) -> None: ...
    def readline(self): ...
    def isatty(self): ...
    def flush(self) -> None: ...

class ColabDebugger(cli_debugger.CliDebugger):
    stdout: Incomplete
    def __init__(
        self,
        frames: list[debugger_core.DebuggerFrame],
        thread_id: int,
    ) -> None: ...
    def do_up(self, arg, /): ...
    def do_down(self, arg, /): ...
    def run(self) -> None: ...
