import typing as tp

from _typeshed import Incomplete
from flax import struct as struct
from flax.nnx import (
    filterlib as filterlib,
    graphlib as graphlib,
)
from flax.nnx.pytreelib import Pytree as Pytree
from flax.nnx.variablelib import Variable as Variable

import jax
import jax.numpy as jnp

class MetricState(Variable): ...

class Metric(Pytree):
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    def update(self, **kwargs) -> None: ...
    def compute(self) -> None: ...
    def split(self, *filters: filterlib.Filter): ...

class Average(Metric):
    argname: Incomplete
    total: Incomplete
    count: Incomplete
    def __init__(self, argname: str = "values") -> None: ...
    def reset(self) -> None: ...
    def update(self, **kwargs) -> None: ...
    def compute(self) -> jax.Array: ...

@struct.dataclass
class Statistics:
    mean: jnp.float32
    standard_error_of_mean: jnp.float32
    standard_deviation: jnp.float32

class Welford(Metric):
    argname: Incomplete
    count: Incomplete
    mean: Incomplete
    m2: Incomplete
    def __init__(self, argname: str = "values") -> None: ...
    def reset(self) -> None: ...
    def update(self, **kwargs) -> None: ...
    def compute(self) -> Statistics: ...

class Accuracy(Average):
    threshold: Incomplete
    def __init__(self, threshold: float | None = None, *args, **kwargs) -> None: ...
    def update(self, *, logits: jax.Array, labels: jax.Array, **_) -> None: ...

class MultiMetric(Metric):
    def __init__(self, **metrics) -> None: ...
    def reset(self) -> None: ...
    def update(self, **updates) -> None: ...
    def compute(self) -> dict[str, tp.Any]: ...
