from optax._src import (
    alias as alias,
    combine as combine,
    transform as transform,
    update as update,
)

import chex
import flax

class Loss(flax.linen.Module):
    @flax.linen.compact
    def __call__(self, x, dtype=..., param_dtype=...): ...

class AccumulationTest(chex.TestCase):
    @chex.all_variants
    def test_ema(self) -> None: ...
    @chex.all_variants
    def test_ema_debias(self) -> None: ...
    def test_skip_not_finite(self) -> None: ...
    def test_skip_large_updates(self) -> None: ...
    def test_multi_steps(self): ...
    def test_multi_steps_every_k_schedule(self): ...
    def test_multi_steps_zero_nans(self) -> None: ...
    def test_multi_steps_computes_mean(self) -> None: ...
    def test_multi_steps_skip_not_finite(self) -> None: ...
    def test_multi_steps_mixed_precision(self): ...
