from _typeshed import Incomplete
from absl.testing import absltest
from optax._src import linear_algebra as linear_algebra

STEPS: int
LR: float

class ClippingTest(absltest.TestCase):
    init_params: Incomplete
    per_step_updates: Incomplete
    def setUp(self) -> None: ...
    def test_clip(self) -> None: ...
    def test_clip_by_block_rms(self): ...
    def test_clip_by_global_norm(self) -> None: ...
    def test_adaptive_grad_clip_with_axis(self) -> None: ...
    def test_unitwise_norm_with_axis(self) -> None: ...
    def test_adaptive_grad_clip(self): ...
    def test_per_example_global_norm_clip(self) -> None: ...
    def test_per_example_layer_norm_clip(self) -> None: ...
