from optax._src import (
    alias as alias,
    base as base,
    combine as combine,
    transform as transform,
    update as update,
)

import chex

class MaskedTest(chex.TestCase):
    def test_tree_map_params(self): ...
    @chex.all_variants
    def test_masked(self, opt_builder, use_fn): ...
    @chex.all_variants
    def test_prefix_mask(self, opt_builder): ...
    @chex.all_variants
    def test_update_requires_params(self): ...
    def test_empty(self, container) -> None: ...
    def test_tree_mismatch_fails(self, extra_key_in_mask, use_fn): ...
    @chex.all_variants
    def test_mask_fn(self): ...
    @chex.all_variants
    def test_nested_mask(self, opt_builder): ...
    @chex.all_variants
    def test_masked_state_structure(self) -> None: ...
    def test_mask_compatible_callable_pytree(self): ...
