from torch._inductor.custom_graph_pass import CustomGraphPass
from torch._inductor.pattern_matcher import PatternMatcherPass
from torchao.utils import torch_version_at_least

import torch

if torch_version_at_least("2.7.0"): ...
else: ...
__all__ = ["_qsdpa_init"]
aten = ...
quantize_dtypes = ...
custom_pass = ...
if torch_version_at_least("2.7.0"):
    class _CustomPass(PatternMatcherPass, CustomGraphPass):
        def __init__(self) -> None: ...
        def __call__(self, g: torch.fx.graph.Graph):  # -> None:
            ...
        def uuid(self) -> bytes: ...

    custom_pass = ...
