from transformers.configuration_utils import PretrainedConfig

class Mamba2Config(PretrainedConfig):
    def __init__(
        self,
        head_dim: int = ...,
        vocab_size: int = ...,
        hidden_size: int = ...,
        state_size: int = ...,
        num_hidden_layers: int = ...,
        norm_eps: float = ...,
        pad_token_id: int = ...,
        bos_token_id: int = ...,
        eos_token_id: int = ...,
        expand: int = ...,
        conv_kernel: int = ...,
        n_groups: int = ...,
        use_bias: bool = ...,
        use_conv_bias: bool = ...,
        conv_init: float | None = ...,
        A_init_range: tuple[float, float] = ...,
        D_has_hdim: bool = ...,
        hidden_act: str = ...,
        initializer_range: float = ...,
        residual_in_fp32: bool = ...,
        dt_min: float = ...,
        dt_max: float = ...,
        dt_init_floor: float = ...,
        dt_limit: tuple[float, float] = ...,
        rescale_prenorm_residual: bool = ...,
        use_cache: bool = ...,
        rmsnorm: bool = ...,
        norm_before_gate: bool = ...,
        chunk_size: int = ...,
        fuse_norm: bool = ...,
        fuse_cross_entropy: bool = ...,
        fuse_linear_cross_entropy: bool = ...,
        use_l2warp: bool = ...,
        tie_word_embeddings: bool = ...,
        **kwargs,
    ) -> None: ...
