from dataclasses import dataclass

import torch

@dataclass(frozen=True)
class Marlin24Constants:
    TILE: int = ...
    MIN_THREAD_N: int = ...
    MAX_PARALLEL: int = ...
    SUPPORTED_NUM_BITS: list[int] = ...
    SUPPORTED_GROUP_SIZES: list[int] = ...

const = ...

def get_pack_factor(num_bits: int) -> int: ...
def marlin_permute_weights(
    q_w: torch.Tensor, size_k: int, size_n: int, perm: torch.Tensor, tile: int = ...
) -> torch.Tensor: ...
def reverse_marlin_permute_weights(
    q_w_unpacked: torch.Tensor,
    size_k: int,
    size_n: int,
    reverse_perm: torch.Tensor,
    tile: int = ...,
) -> torch.Tensor: ...
def get_perms_24(num_bits: int) -> tuple[torch.Tensor, list[int], list[int]]: ...
def get_reverse_perms_24(
    num_bits: int,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]: ...
def sparse_semi_structured_from_dense_cutlass(dense):  # -> tuple[Tensor | Any, Any]:
    ...
def sparse_semi_structured_to_dense_cutlass(sparse, meta_reordered):  # -> Tensor:
    ...
