from typing import Any, Literal

_log = ...
CharMetrics = ...
CompositePart = ...

class AFM:
    def __init__(self, fh) -> None: ...
    def get_bbox_char(self, c, isord=...): ...
    def string_width_height(
        self,
        s,
    ) -> tuple[Literal[0], Literal[0]] | tuple[Any | Literal[0], float]: ...
    def get_str_bbox_and_descent(
        self,
        s,
    ) -> (
        tuple[Literal[0], Literal[0], Literal[0], Literal[0], Literal[0]]
        | tuple[int, float, Any | Literal[0], float, float]
    ): ...
    def get_str_bbox(
        self,
        s,
    ) -> (
        tuple[Literal[0], Literal[0], Literal[0], Literal[0]]
        | tuple[int, float, Any | Literal[0], float]
    ): ...
    def get_name_char(self, c, isord=...): ...
    def get_width_char(self, c, isord=...): ...
    def get_width_from_char_name(self, name): ...
    def get_height_char(self, c, isord=...): ...
    def get_kern_dist(self, c1, c2): ...
    def get_kern_dist_from_name(self, name1, name2): ...
    def get_fontname(self): ...
    @property
    def postscript_name(self): ...
    def get_fullname(self): ...
    def get_familyname(self) -> str: ...
    @property
    def family_name(self) -> str: ...
    def get_weight(self): ...
    def get_angle(self): ...
    def get_capheight(self): ...
    def get_xheight(self): ...
    def get_underline_thickness(self): ...
    def get_horizontal_stem_width(self) -> None: ...
    def get_vertical_stem_width(self) -> None: ...
