import matplotlib as mpl

type _LUTSIZE = mpl.rcParams[image.lut]
_2VarAddA0_data = ...
_2VarAddA1_data = ...
_2VarSubA0_data = ...
_2VarSubA1_data = ...
_3VarAddA0_data = ...
_3VarAddA1_data = ...
_3VarAddA2_data = ...
cmaps = ...
cmap_families = ...
