from enum import StrEnum

class JoinStyle(StrEnum):
    miter = ...
    round = ...
    bevel = ...
    @staticmethod
    def demo() -> None: ...

class CapStyle(StrEnum):
    butt = ...
    projecting = ...
    round = ...
    @staticmethod
    def demo() -> None: ...
