from functools import lru_cache
from typing import Any

"""
A module for parsing and generating `fontconfig patterns`_.

.. _fontconfig patterns:
   https://www.freedesktop.org/software/fontconfig/fontconfig-user.html
"""
_family_punc = ...
_family_unescape = ...
_family_escape = ...
_value_punc = ...
_value_unescape = ...
_value_escape = ...
_CONSTANTS = ...

@lru_cache
def parse_fontconfig_pattern(pattern) -> dict[Any, Any]: ...
def generate_fontconfig_pattern(d) -> str: ...
