_log = ...

class LayoutGrid:
    def __init__(
        self,
        parent=...,
        parent_pos=...,
        parent_inner=...,
        name=...,
        ncols=...,
        nrows=...,
        h_pad=...,
        w_pad=...,
        width_ratios=...,
        height_ratios=...,
    ) -> None: ...
    def reset_margins(self) -> None: ...
    def add_constraints(self, parent) -> None: ...
    def hard_constraints(self) -> None: ...
    def add_child(self, child, i=..., j=...) -> None: ...
    def parent_constraints(self, parent) -> None: ...
    def grid_constraints(self) -> None: ...
    def edit_margin(self, todo, size, cell) -> None: ...
    def edit_margin_min(self, todo, size, cell=...) -> None: ...
    def edit_margins(self, todo, size) -> None: ...
    def edit_all_margins_min(self, todo, size) -> None: ...
    def edit_outer_margin_mins(self, margin, ss) -> None: ...
    def get_margins(self, todo, col): ...
    def get_outer_bbox(self, rows=..., cols=...) -> Bbox: ...
    def get_inner_bbox(self, rows=..., cols=...) -> Bbox: ...
    def get_bbox_for_cb(self, rows=..., cols=...) -> Bbox: ...
    def get_left_margin_bbox(self, rows=..., cols=...) -> Bbox: ...
    def get_bottom_margin_bbox(self, rows=..., cols=...) -> Bbox: ...
    def get_right_margin_bbox(self, rows=..., cols=...) -> Bbox: ...
    def get_top_margin_bbox(self, rows=..., cols=...) -> Bbox: ...
    def update_variables(self) -> None: ...

_layoutboxobjnum = ...

def seq_id() -> str: ...
def plot_children(fig, lg=..., level=...) -> None: ...
