latex_to_bakoma = ...
type12uni = ...
uni2type1 = ...
tex2uni = ...
type _EntryTypeIn = tuple[str, str, str, str | int]
type _EntryTypeOut = tuple[int, int, str, int]
_stix_virtual_fonts: dict[str, dict[str, list[_EntryTypeIn]] | list[_EntryTypeIn]] = ...
stix_virtual_fonts: dict[str, dict[str, list[_EntryTypeOut]] | list[_EntryTypeOut]]
stix_virtual_fonts = ...
stix_glyph_fixes = ...
