from typing import Any, Literal

import functools

"""
A class representing a Type 1 font.

This version reads pfa and pfb files and splits them for embedding in
pdf files. It also supports SlantFont and ExtendFont transformations,
similarly to pdfTeX and friends. There is no support yet for subsetting.

Usage::

    font = Type1Font(filename)
    clear_part, encrypted_part, finale = font.parts
    slanted_font = font.transform({'slant': 0.167})
    extended_font = font.transform({'extend': 1.2})

Sources:

* Adobe Technical Note #5040, Supporting Downloadable PostScript
  Language Fonts.

* Adobe Type 1 Font Format, Adobe Systems Incorporated, third printing,
  v1.1, 1993. ISBN 0-201-57044-0.
"""
_log = ...

class _Token:
    __slots__ = ...
    kind = ...
    def __init__(self, pos, raw) -> None: ...
    def endpos(self): ...
    def is_keyword(self, *names) -> Literal[False]: ...
    def is_slash_name(self) -> Literal[False]: ...
    def is_delim(self) -> Literal[False]: ...
    def is_number(self) -> Literal[False]: ...
    def value(self) -> Any: ...

class _NameToken(_Token):
    kind = ...
    def is_slash_name(self): ...
    def value(self): ...

class _BooleanToken(_Token):
    kind = ...
    def value(self): ...

class _KeywordToken(_Token):
    kind = ...
    def is_keyword(self, *names) -> bool: ...

class _DelimiterToken(_Token):
    kind = ...
    def is_delim(self) -> Literal[True]: ...
    def opposite(self) -> str: ...

class _WhitespaceToken(_Token):
    kind = ...

class _StringToken(_Token):
    kind = ...
    _escapes_re = ...
    _replacements = ...
    _ws_re = ...
    @functools.lru_cache  # noqa: B019 -- mirrors upstream @lru_cache on a method; not executed in a stub
    def value(self) -> str | bytes: ...

class _BinaryToken(_Token):
    kind = ...
    def value(self): ...

class _NumberToken(_Token):
    kind = ...
    def is_number(self) -> Literal[True]: ...
    def value(self) -> int | float: ...

class _BalancedExpression(_Token): ...

class Type1Font:
    __slots__ = ...
    def __init__(self, input) -> None: ...
    def transform(self, effects) -> Type1Font: ...

_StandardEncoding = ...
