from typing import Any

from matplotlib.legend import Legend
from matplotlib.lines import Line2D
from matplotlib.text import Text

class Axes:
    def plot(self, *args: Any, **kwargs: Any) -> list[Line2D]: ...
    def scatter(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_xlabel(self, xlabel: str, **kwargs: Any) -> Text: ...
    def set_ylabel(self, ylabel: str, **kwargs: Any) -> Text: ...
    def set_title(self, label: str, **kwargs: Any) -> Text: ...
    def legend(self, *args: Any, **kwargs: Any) -> Legend: ...
    def grid(self, visible: bool | None = ..., **kwargs: Any) -> None: ...
    def axhline(self, y: float = ..., **kwargs: Any) -> Line2D: ...
    def axvline(self, x: float = ..., **kwargs: Any) -> Line2D: ...
    def fill_between(self, x: Any, y1: Any, y2: Any = ..., **kwargs: Any) -> Any: ...
    def set_xticks(self, ticks: Any, **kwargs: Any) -> None: ...
    def set_xticklabels(self, labels: Any, **kwargs: Any) -> list[Text]: ...
