from typing import Any

from matplotlib import ticker, units

"""
Plotting of string "category" data: ``plot(['d', 'f', 'a'], [1, 2, 3])`` will
plot three points with x-axis values of 'd', 'f', 'a'.

See :doc:`/gallery/lines_bars_and_markers/categorical_variables` for an
example.

The module uses Matplotlib's `matplotlib.units` mechanism to convert from
strings to integers and provides a tick locator, a tick formatter, and the
`.UnitData` class that creates and stores the string-to-integer mapping.
"""
_log = ...

class StrCategoryConverter(units.ConversionInterface):
    @staticmethod
    def convert(value, unit, axis) -> Incomplete: ...
    @staticmethod
    def axisinfo(unit, axis) -> AxisInfo: ...
    @staticmethod
    def default_units(data, axis): ...

class StrCategoryLocator(ticker.Locator):
    def __init__(self, units_mapping) -> None: ...
    def __call__(self) -> list[Any]: ...
    def tick_values(self, vmin, vmax) -> list[Any]: ...

class StrCategoryFormatter(ticker.Formatter):
    def __init__(self, units_mapping) -> None: ...
    def __call__(self, x, pos=...) -> str: ...
    def format_ticks(self, values) -> list[str]: ...

class UnitData:
    def __init__(self, data=...) -> None: ...
    def update(self, data) -> None: ...
