"""Five DPPO updates checked against the pinned upstream trainer's arithmetic.

Before any result counts, this baseline must match upstream source on the
packed data, the model logits, the DPPO mask and loss, the gradients, and
five updates. ``source_parity_test`` pins the first and the third on the
tensors upstream's functions were handed. This file covers the rest: it
drives five sequential updates through ``TMaxDPPOTrainStep`` and compares
against ``update_parity.pt``. That record was generated by the pinned
TMax commit ``6d3d606`` objective running the actual Hugging Face Qwen3.5
class, then mapped into the native parameter layout.

Not a cluster run, and not a claim that one happened: single process,
float32, one trajectory per row, and torch's AdamW where upstream uses
DeepSpeed. What it does claim is that the objective, the trust-region mask,
the global token denominator, the gradient, the clip, and the optimizer
order are upstream's -- measured, not assumed. The record was verified to
catch errors: perturbing an initial weight, the temperature, or the clip
bound makes this test fail.

Two things it deliberately does not cover, both stated rather than implied.
The fixture's divergences sit at ~0.79, so the trust-region radius cannot be
detected here (its value is pinned by exp000's config). And the released
launcher's own stack -- DeepSpeed ZeRO-3, bf16, sequence parallelism, and
the vLLM rollout writer -- is not in this comparison at all.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Final

import torch

from priml.baselines.tmax.train_step import TMaxDPPOTrainStep, tiny_qwen35_config
from priml.testing.bfb import host_agnostic_numerics
from priml.testing.golden import read_tensors
from priml.train.parallelism import NoParallel


if TYPE_CHECKING:
    from torch import Tensor

_TESTDATA: Final = Path(__file__).resolve().parent / "testdata"
_HIDDEN_SIZE: Final = 8
"""Fixture width the record was generated at; half the shared fixture's 16."""
UPDATES: Final = 5
"""Updates the record covers."""
ROW_FIELDS: Final = (
    "query_responses",
    "attention_mask",
    "position_ids",
    "response_mask",
    "vllm_logprobs",
    "advantages",
)
"""The packed-row fields the training step reads, in stored order."""


def _step() -> TMaxDPPOTrainStep:
    """Build the tiny training step exactly as the minting script built it."""
    config = TMaxDPPOTrainStep.Config()
    config.model = tiny_qwen35_config(hidden_size=_HIDDEN_SIZE)
    config.parallelism = NoParallel.Config(device="cpu")
    config.dtype_autocast = None
    return config.make()


def _batch(record: dict[str, Tensor]) -> tuple[dict[str, Tensor], ...]:
    """Return the recorded update's rows, in the order the record stores them."""
    return tuple(
        {name: record[f"input/row{index}/{name}"] for name in ROW_FIELDS}
        for index in range(2)
    )


def _state(record: dict[str, Tensor], prefix: str) -> dict[str, Tensor]:
    """Return the record's stored parameters under one prefix, keys stripped."""
    return {
        name.removeprefix(prefix): value
        for name, value in record.items()
        if name.startswith(prefix)
    }


def test_five_updates_match_the_pinned_upstream_record() -> None:
    """Every loss, the first gradient, and the final weights match upstream."""
    record = read_tensors(_TESTDATA / "update_parity.pt")
    rows = _batch(record)
    initial = _state(record, "state/initial/")
    # The record is evidence only if the trust region did something: the
    # minting script refuses to write a record whose first update masks
    # nothing or everything.
    kept = float(record["fixture/kept_tokens"])
    response_tokens = float(sum(row["response_mask"][1:].sum() for row in rows))
    assert 0.0 < kept < response_tokens

    with host_agnostic_numerics():
        # The objective's gradient at the initialized policy, whole, before any
        # clipping or AdamW arithmetic has touched it.
        gradient_step = _step()
        gradient_step.model.load_state_dict(initial)
        loss = gradient_step.train_loss(rows=rows)["loss"]
        torch.testing.assert_close(loss, record["steps/0/loss"], rtol=0.0, atol=0.0)
        loss.backward()
        for name, parameter in gradient_step.model.named_parameters():
            assert parameter.grad is not None, name
            torch.testing.assert_close(
                parameter.grad,
                record[f"grad/first/{name}"],
                rtol=0.0,
                atol=0.0,
            )

        step = _step()
        step.model.load_state_dict(initial)
        for update in range(UPDATES):
            result = step.train_step(**step.preprocess_batch({"rows": rows}))
            torch.testing.assert_close(
                result["loss"],
                record[f"steps/{update}/loss"],
                rtol=0.0,
                atol=0.0,
            )
            assert step.last_grad_norm is not None
            torch.testing.assert_close(
                step.last_grad_norm,
                record[f"steps/{update}/grad_norm"],
                rtol=0.0,
                atol=0.0,
            )
        for name, value in step.model.state_dict().items():
            torch.testing.assert_close(
                value,
                record[f"state/final/{name}"],
                rtol=0.0,
                atol=0.0,
            )
