import os

from fla.utils import IS_GATHER_SUPPORTED

import triton

if os.environ.get("FLA_USE_FAST_OPS", "0") == "1":
    @triton.jit
    def exp(x) -> None: ...
    @triton.jit
    def exp2(x) -> None: ...
    @triton.jit
    def log(x) -> None: ...
    @triton.jit
    def log2(x) -> None: ...
    @triton.jit
    def tanh(x) -> None: ...

else:
    @triton.jit
    def exp(x) -> tensor: ...
    @triton.jit
    def exp2(x) -> tensor: ...
    @triton.jit
    def log(x) -> tensor: ...
    @triton.jit
    def log2(x) -> tensor: ...
    @triton.jit
    def tanh(x) -> None: ...

if not IS_GATHER_SUPPORTED:
    @triton.jit
    def gather(src, index, axis, _builder=...) -> None: ...

else:
    gather = ...
if hasattr(triton.language, "_experimental_make_tensor_descriptor"):
    make_tensor_descriptor = ...
else:
    make_tensor_descriptor = ...
    @triton.jit
    def make_tensor_descriptor(
        base, shape, strides, block_shape, _builder=...
    ) -> None: ...
