from fla.utils import IS_NVIDIA
from triton import language as tl

import triton

_NUM_REG = ...
s_softplus: tl.constexpr = ...
s_softplus2: tl.constexpr = ...
s_constraints: tl.constexpr = ...
NUM_REG: tl.constexpr = ...

@triton.jit
def softplus_nv(x) -> tensor | tuple: ...
@triton.jit
def softplus_triton(x): ...
@triton.jit
def softplus2_nv(x) -> tensor | tuple: ...
@triton.jit
def softplus2_triton(x): ...

if IS_NVIDIA:
    softplus = ...
    softplus2 = ...
else:
    softplus = ...
    softplus2 = ...
