from torch.distributed import ProcessGroup

import torch
import torch.distributed as dist

def all_gather_into_tensor(
    inp: torch.Tensor,
    out: torch.Tensor | None = ...,
    group: ProcessGroup | None = ...,
    async_op: bool = ...,
) -> tuple[torch.Tensor, dist.Work | None]: ...
def all_reduce_sum(
    inp: torch.Tensor, group: ProcessGroup | None = ..., async_op: bool = ...
) -> tuple[torch.Tensor, dist.Work | None]: ...
def send_recv_fwd(
    send_tensor: torch.Tensor, group: ProcessGroup, recv_from_prev: bool = ...
) -> torch.Tensor: ...
def send_recv_bwd(
    send_tensor: torch.Tensor, group: ProcessGroup, recv_from_next: bool = ...
) -> torch.Tensor: ...
def conv_cp_send_recv_fwd(tails: torch.Tensor, group: ProcessGroup) -> torch.Tensor: ...
def conv_cp_send_recv_bwd(
    d_initial_state: torch.Tensor, group: ProcessGroup
) -> torch.Tensor: ...
