from dataclasses import dataclass

from fla.utils import tensor_cache
from torch.distributed import ProcessGroup

import torch
import torch.distributed as dist

@dataclass
class FLACPContext:
    group: ProcessGroup | None = ...
    cu_seqlens: torch.Tensor | None = ...
    cu_seqlens_cpu: torch.Tensor | None = ...
    is_last_rank: bool | None = ...
    pre_num_ranks: int | None = ...
    is_first_rank: bool | None = ...
    post_num_ranks: int | None = ...
    conv1d_kernel_size: int | None = ...
    pre_num_conv_tokens: int | None = ...
    def copy_for_backward(self) -> FLACPContext: ...
    @property
    def num_seqs(self) -> int: ...
    @property
    def is_cp_enabled(self) -> bool: ...

@tensor_cache
def get_cp_cu_seqlens(
    cu_seqlens: torch.LongTensor,
    cu_seqlens_cpu: torch.LongTensor | None = ...,
    world_size: int | None = ...,
    rank: int | None = ...,
    group: dist.ProcessGroup | None = ...,
    conv1d_kernel_size: int | None = ...,
) -> FLACPContext: ...
def build_cp_context(
    cu_seqlens: torch.Tensor,
    group: ProcessGroup,
    conv1d_kernel_size: int | None = ...,
    cu_seqlens_cpu: torch.Tensor | None = ...,
) -> FLACPContext: ...
