from collections.abc import (
    Callable as Callable,
    Sequence,
)
from typing import Any

import dataclasses

import numpy as np

class Mask:
    @property
    def shape(self) -> tuple[int, ...]: ...
    def __getitem__(self, idx) -> np.ndarray: ...
    def __bool__(self) -> bool: ...
    def __or__(self, other: Mask) -> Mask: ...
    def __and__(self, other: Mask) -> Mask: ...

def make_causal_mask(shape: tuple[int, int], offset: int = 0) -> np.ndarray: ...
def make_local_attention_mask(
    shape: tuple[int, int],
    window_size: tuple[int | None, int | None],
    *,
    offset: int = 0,
) -> np.ndarray: ...
def make_chunk_attention_mask(
    shape: tuple[int, int],
    chunk_size: int,
) -> np.ndarray: ...
def make_random_mask(
    shape: tuple[int, int],
    sparsity: float,
    seed: int,
) -> np.ndarray: ...

@dataclasses.dataclass
class LogicalOr(Mask):
    left: Mask
    right: Mask
    def __init__(self, left: Mask, right: Mask) -> None: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    def __getitem__(self, idx) -> np.ndarray: ...
    def __hash__(self): ...

@dataclasses.dataclass
class LogicalAnd(Mask):
    left: Mask
    right: Mask
    def __init__(self, left: Mask, right: Mask) -> None: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    def __getitem__(self, idx) -> np.ndarray: ...
    def __hash__(self): ...

@dataclasses.dataclass
class MultiHeadMask(Mask):
    masks: Sequence[Mask]
    def __post_init__(self) -> None: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    def __getitem__(self, idx) -> np.ndarray: ...
    def __eq__(self, other: object): ...
    def __hash__(self): ...

class _ComputableMask(Mask):
    q_sequence: np.ndarray
    mask_function: Callable[..., Any]
    def __init__(
        self,
        shape: tuple[int, int],
        mask_function: Callable[..., Any],
        shard_count: int = 1,
    ) -> None: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    def __getitem__(self, idx) -> np.ndarray: ...
    def __eq__(self, other: object): ...
    def __hash__(self): ...

class CausalMask(_ComputableMask):
    offset: int
    def __init__(
        self,
        shape: tuple[int, int],
        offset: int = 0,
        shard_count: int = 1,
    ) -> None: ...
    def __eq__(self, other: object): ...
    def __hash__(self): ...

class ChunkedCausalMask(_ComputableMask):
    chunk_size: int
    def __init__(
        self,
        shape: tuple[int, int],
        chunk_size: int,
        shard_count: int = 1,
    ) -> None: ...
    def __eq__(self, other: object): ...
    def __hash__(self): ...

class LocalMask(_ComputableMask):
    window_size: tuple[int | None, int | None]
    offset: int
    def __init__(
        self,
        shape: tuple[int, int],
        window_size: tuple[int | None, int | None],
        offset: int,
        shard_count: int = 1,
    ) -> None: ...
    def __eq__(self, other: object): ...
    def __hash__(self): ...

@dataclasses.dataclass
class NumpyMask(Mask):
    array: np.ndarray
    def __post_init__(self) -> None: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    def __getitem__(self, idx) -> np.ndarray: ...
    def __eq__(self, other: object): ...
    def __hash__(self): ...

@dataclasses.dataclass(frozen=True)
class FullMask(Mask):
    def __post_init__(self) -> None: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    def __getitem__(self, idx) -> np.ndarray: ...
    def __eq__(self, other: object): ...
    def __hash__(self): ...
