from collections.abc import Generator

from _typeshed import Incomplete

from ..utils import ObjectWrapper

__all__ = ["tenumerate", "tmap", "tzip"]

class DummyTqdmFile(ObjectWrapper):
    def __init__(self, wrapped) -> None: ...
    def write(self, x, nolock: bool = False) -> None: ...
    def __del__(self) -> None: ...

def tenumerate(iterable, start: int = 0, total=None, tqdm_class=..., **tqdm_kwargs): ...
def tzip(iter1, *iter2plus, **tqdm_kwargs) -> Generator[Incomplete, Incomplete]: ...
def tmap(function, *sequences, **tqdm_kwargs) -> Generator[Incomplete]: ...
