from typing import Any

class PRNGKey:
    def __new__(cls, seed: int) -> Any: ...

def key(seed: int) -> Any: ...
def split(key: Any, num: int = ...) -> Any: ...
def categorical(key: Any, logits: Any, *args: Any, **kwargs: Any) -> Any: ...
def normal(key: Any, shape: Any = ..., dtype: Any = ...) -> Any: ...
def permutation(
    key: Any,
    x: Any,
    axis: int = ...,
    *args: Any,
    **kwargs: Any,
) -> Any: ...
