from collections.abc import Callable
from typing import Any

def tree_leaves(tree: Any, *args: Any, **kwargs: Any) -> list[Any]: ...
def tree_flatten_with_path(
    tree: Any,
    *args: Any,
    **kwargs: Any,
) -> tuple[list[tuple[Any, Any]], Any]: ...
def tree_map(f: Callable[..., Any], tree: Any, *rest: Any, **kwargs: Any) -> Any: ...
def tree_flatten(tree: Any, *args: Any, **kwargs: Any) -> tuple[list[Any], Any]: ...
