from enum import StrEnum

class IntxPackingFormat(StrEnum):
    UNPACKED_TO_INT8 = ...
    OPAQUE_ATEN_KLEIDIAI = ...
    OPAQUE_TORCHAO_AUTO = ...
    OPAQUE_TORCHAO_KLEIDIAI = ...
    OPAQUE_TORCHAO_LOWBIT = ...
