from tokenizers import AddedToken, EncodeInput, Encoding, InputSequence, Tokenizer
from tokenizers.decoders import Decoder
from tokenizers.models import Model
from tokenizers.normalizers import Normalizer
from tokenizers.pre_tokenizers import PreTokenizer
from tokenizers.processors import PostProcessor

type Offsets = tuple[int, int]

class BaseTokenizer:
    def __init__(self, tokenizer: Tokenizer, parameters=...) -> None: ...
    def num_special_tokens_to_add(self, is_pair: bool) -> int: ...
    def get_vocab(self, with_added_tokens: bool = ...) -> dict[str, int]: ...
    def get_added_tokens_decoder(self) -> dict[int, AddedToken]: ...
    def get_vocab_size(self, with_added_tokens: bool = ...) -> int: ...
    def enable_padding(
        self,
        direction: str | None = ...,
        pad_to_multiple_of: int | None = ...,
        pad_id: int | None = ...,
        pad_type_id: int | None = ...,
        pad_token: str | None = ...,
        length: int | None = ...,
    ) -> None: ...
    def no_padding(self) -> None: ...
    @property
    def padding(self) -> dict | None: ...
    def enable_truncation(
        self,
        max_length: int,
        stride: int | None = ...,
        strategy: str | None = ...,
    ) -> None: ...
    def no_truncation(self) -> None: ...
    @property
    def truncation(self) -> dict | None: ...
    def add_tokens(self, tokens: list[str | AddedToken]) -> int: ...
    def add_special_tokens(self, special_tokens: list[str | AddedToken]) -> int: ...
    def normalize(self, sequence: str) -> str: ...
    def encode(
        self,
        sequence: InputSequence,
        pair: InputSequence | None = ...,
        is_pretokenized: bool = ...,
        add_special_tokens: bool = ...,
    ) -> Encoding: ...
    def encode_batch(
        self,
        inputs: list[EncodeInput],
        is_pretokenized: bool = ...,
        add_special_tokens: bool = ...,
    ) -> list[Encoding]: ...
    async def async_encode_batch(
        self,
        inputs: list[EncodeInput],
        is_pretokenized: bool = ...,
        add_special_tokens: bool = ...,
    ) -> list[Encoding]: ...
    async def async_encode_batch_fast(
        self,
        inputs: list[EncodeInput],
        is_pretokenized: bool = ...,
        add_special_tokens: bool = ...,
    ) -> list[Encoding]: ...
    def decode(self, ids: list[int], skip_special_tokens: bool | None = ...) -> str: ...
    def decode_batch(
        self,
        sequences: list[list[int]],
        skip_special_tokens: bool | None = ...,
    ) -> str: ...
    async def async_decode_batch(
        self,
        sequences: list[list[int]],
        skip_special_tokens: bool = ...,
    ) -> list[str]: ...
    def token_to_id(self, token: str) -> int | None: ...
    def id_to_token(self, id: int) -> str | None: ...
    def save_model(self, directory: str, prefix: str | None = ...) -> Any: ...
    def save(self, path: str, pretty: bool = ...) -> None: ...
    def to_str(self, pretty: bool = ...) -> str: ...
    def post_process(
        self,
        encoding: Encoding,
        pair: Encoding | None = ...,
        add_special_tokens: bool = ...,
    ) -> Encoding: ...
    @property
    def model(self) -> Model: ...
    @model.setter
    def model(self, model: Model) -> None: ...
    @property
    def normalizer(self) -> Normalizer: ...
    @normalizer.setter
    def normalizer(self, normalizer: Normalizer) -> None: ...
    @property
    def pre_tokenizer(self) -> PreTokenizer: ...
    @pre_tokenizer.setter
    def pre_tokenizer(self, pre_tokenizer: PreTokenizer) -> None: ...
    @property
    def post_processor(self) -> PostProcessor: ...
    @post_processor.setter
    def post_processor(self, post_processor: PostProcessor) -> None: ...
    @property
    def decoder(self) -> Decoder: ...
    @decoder.setter
    def decoder(self, decoder: Decoder) -> None: ...
