import os

import torch

def storage_ptr(tensor: torch.Tensor) -> int: ...
def storage_size(tensor: torch.Tensor) -> int: ...
def save_model(
    model: torch.nn.Module,
    filename: str,
    metadata: dict[str, str] | None = ...,
    force_contiguous: bool = ...,
) -> None: ...
def load_model(
    model: torch.nn.Module,
    filename: str | os.PathLike[str],
    strict: bool = ...,
    device: str | int = ...,
    *,
    backend: str = ...,
) -> tuple[list[str], list[str]]: ...
def save(
    tensors: dict[str, torch.Tensor], metadata: dict[str, str] | None = ...
) -> bytes: ...
def save_file(
    tensors: dict[str, torch.Tensor],
    filename: str | os.PathLike[str],
    metadata: dict[str, str] | None = ...,
) -> None: ...
def load_file(
    filename: str | os.PathLike[str], device: str | int = ..., *, backend: str = ...
) -> dict[str, torch.Tensor]: ...
def load(data: bytes) -> dict[str, torch.Tensor]: ...
