from collections.abc import (
    Callable as Callable,
    Hashable,
    Sequence,
)
from typing import Any, ClassVar, Literal

import abc
import collections
import dataclasses
import enum
import functools

from _typeshed import Incomplete
from jax._src import (
    core as jax_core,
    custom_batching as custom_batching,
    dtypes as dtypes,
    effects as effects,
    frozen_dict as frozen_dict,
    lax as lax,
    pretty_printer as pp,
    state as state,
    tree_util as tree_util,
    util as util,
)
from jax._src.pallas import (
    core as pallas_core,
    primitives as pallas_primitives,
)
from jax._src.state import (
    indexing as indexing,
    types as state_types,
)
from jax.experimental.mosaic.gpu import tcgen05 as tcgen05
from jaxlib.mlir import ir

import jax
import jax.experimental.mosaic.gpu as mgpu
import jax.numpy as jnp

DimensionSemantics: Incomplete
TransposeTransform: Incomplete
SMEM_ALIGNMENT: int
TMEM_COL_ALIGNMENT: int

def is_trivial_index(idx, shape) -> bool: ...

@dataclasses.dataclass(frozen=True, kw_only=True)
class CompilerParams:
    approx_math: bool = ...
    dimension_semantics: Sequence[DimensionSemantics] | None = ...
    max_concurrent_steps: int = ...
    unsafe_no_auto_barriers: bool = ...
    reduction_scratch_bytes: int = ...
    profile_space: int = ...
    profile_dir: str = ...
    lowering_semantics: mgpu.core.LoweringSemantics = ...
    def __post_init__(self) -> None: ...

class MemorySpace(enum.Enum):
    GMEM = "gmem"
    SMEM = "smem"
    TMEM = "tmem"
    REGS = "regs"
    def __call__(
        self,
        shape: Sequence[int],
        dtype: jnp.dtype,
        *,
        transforms: Sequence[state_types.Transform] = (),
        packed: bool | None = None,
        collective: bool | None = None,
        layout: TMEMLayout | None = None,
    ) -> pallas_core.MemoryRef: ...

class SemaphoreType(enum.Enum):
    REGULAR = "regular"
    BARRIER = "barrier"
    def __call__(self, shape: tuple[int, ...]): ...
    def get_array_aval(self) -> jax_core.ShapedArray: ...
    def get_ref_aval(self) -> _Ref: ...

class PrimitiveSemantics(enum.Enum):
    Warp = ...
    Warpgroup = ...

LANExWG_SEMANTICS: Incomplete
LANExWARP_SEMANTICS: Incomplete
WGxWG_SEMANTICS: Incomplete

def kernel(
    body: Callable[..., None],
    out_shape: object,
    *,
    scratch_shapes: pallas_core.ScratchShapeTree = (),
    compiler_params: pallas_core.CompilerParams | None = None,
    grid: tuple[int, ...] = (),
    grid_names: tuple[str, ...] = (),
    cluster: tuple[int, ...] = (),
    cluster_names: tuple[str, ...] = (),
    num_threads: int | None = None,
    thread_name: str | None = None,
    interpret: Any = None,
    **mesh_kwargs: Any,
): ...

@dataclasses.dataclass(frozen=True)
class GPUMemoryRef(pallas_core.MemoryRef):
    transforms: Sequence[state_types.Transform] = ...
    layout: tcgen05.TMEMLayout | None = ...
    collective: bool | None = ...
    def __post_init__(self) -> None: ...
    def get_ref_aval(self) -> _Ref: ...

def align_to(x: int, alignment: int): ...
def infer_tmem_layout(
    shape: tuple[int, ...],
    dtype: jnp.dtype,
    *,
    packed: bool,
    collective: bool,
) -> tcgen05.TMEMLayout: ...
def flatten_ref_union(ref_union: AbstractRefUnion) -> tuple[_Ref, ...]: ...

class AbstractRefUnion(state.AbstractRef):
    refs: Sequence[_GPUMemoryRefTree]
    def __init__(
        self,
        aval,
        refs: Sequence[_GPUMemoryRefTree],
        memory_space,
    ) -> None: ...
    def update(self, inner_aval=None, memory_space=None, kind=None): ...
    @functools.cached_property
    def layout(self) -> tcgen05.TMEMLayout: ...
    @functools.cached_property
    def collective(self) -> bool: ...

@dataclasses.dataclass(init=False, frozen=True)
class RefUnion(GPUMemoryRef):
    refs: Sequence[_GPUMemoryRefTree] = ...
    def __init__(self, *refs: _GPUMemoryRefTree) -> None: ...
    def get_ref_aval(self) -> AbstractRefUnion: ...

Index: Incomplete

@dataclasses.dataclass(frozen=True)
class TilingTransform(state_types.Transform):
    tiling: tuple[int, ...]
    def transform_type(self, x): ...
    def undo(self, x: jax_core.AbstractValue) -> state_types.Transform: ...

@dataclasses.dataclass(frozen=True)
class UntilingTransform(state_types.Transform):
    tiling: tuple[int, ...] = ...
    def transform_type(self, x): ...
    def undo(self, x: jax_core.AbstractValue) -> state_types.Transform: ...
    def commute_transpose(
        self,
        _: jax_core.AbstractValue,
        transpose: state_types.TransposeTransform,
    ) -> tuple[state_types.TransposeTransform, UntilingTransform]: ...
    def commute_ndindexer(
        self,
        aval: jax_core.AbstractValue,
        indexer: indexing.NDIndexer,
    ) -> tuple[indexing.NDIndexer, UntilingTransform]: ...
    def pretty_print(self, context: jax_core.JaxprPpContext) -> pp.Doc: ...

def batch_transform(
    transform: state_types.Transform,
    leading_rank: int,
) -> state_types.Transform: ...
def to_gpu_transform(transform: state_types.Transform) -> mgpu.MemRefTransform: ...
def commute_transpose_indexer(
    _: jax_core.AbstractValue,
    transpose: state_types.TransposeTransform,
    indexer: indexing.NDIndexer,
) -> tuple[indexing.NDIndexer, state_types.TransposeTransform]: ...

@dataclasses.dataclass
class PeerMemRef(state_types.Transform):
    device_id: Any
    device_id_type: pallas_primitives.DeviceIdType = ...
    def undo(self, x: jax_core.AbstractValue) -> state_types.Transform: ...
    def transform_type(self, x): ...
    def commute_ndindexer(
        self,
        _: jax_core.AbstractValue,
        indexer: indexing.NDIndexer,
    ) -> tuple[indexing.NDIndexer, PeerMemRef]: ...

@dataclasses.dataclass
class MulticastRef(state_types.Transform):
    collective_axes: tuple[Hashable, ...] = ...
    def transform_type(self, x): ...
    def undo(self, x: jax_core.AbstractValue) -> state_types.Transform: ...
    def commute_ndindexer(
        self,
        _: jax_core.AbstractValue,
        indexer: indexing.NDIndexer,
    ) -> tuple[indexing.NDIndexer, MulticastRef]: ...

def remote_ref(
    ref: _Ref,
    device_id: jax.typing.ArrayLike,
    device_id_type: pallas_primitives.DeviceIdType = ...,
) -> pallas_core.TransformedRef: ...
def multicast_ref(
    ref: _Ref,
    collective_axes: Hashable | tuple[Hashable, ...],
) -> pallas_core.TransformedRef: ...
def transform_ref(
    ref: pallas_core.TransformedRef,
    transform: state_types.Transform,
) -> pallas_core.TransformedRef: ...
def transpose_ref(
    ref: pallas_core.TransformedRef | Any,
    permutation: tuple[int, ...],
) -> pallas_core.TransformedRef: ...
def untile_ref(ref, tiling: tuple[int, ...]) -> pallas_core.TransformedRef: ...
def unswizzle_ref(ref, swizzle: int) -> pallas_core.TransformedRef: ...

@dataclasses.dataclass(frozen=True)
class ExtractAliasedRef(state_types.Transform, metaclass=abc.ABCMeta):
    dtype: dtypes.DType = ...
    shape: tuple[int, ...] = ...
    offset: int = ...
    layout: tcgen05.TMEMLayout | None = ...
    @classmethod
    def from_transformed_ref(
        cls,
        ref: pallas_core.TransformedRef,
        byte_offset: int,
        layout: tcgen05.TMEMLayout | None = None,
    ): ...
    def transform_type(self, x): ...

@dataclasses.dataclass(frozen=True)
class SwizzleTransform(state_types.Transform):
    swizzle: int
    def __post_init__(self) -> None: ...
    def transform_type(self, x: jax_core.AbstractValue) -> jax_core.AbstractValue: ...
    def undo(self, x: jax_core.AbstractValue) -> state_types.Transform: ...

@dataclasses.dataclass(frozen=True)
class UnswizzleRef(state_types.Transform):
    swizzle: int = ...
    def transform_type(self, x: jax_core.AbstractValue) -> jax_core.AbstractValue: ...
    def undo(self, x: jax_core.AbstractValue) -> state_types.Transform: ...
    def swizzle_elems(self, dtype: jnp.dtype | ir.Type) -> int: ...
    def commute_transpose(
        self,
        _: jax_core.AbstractValue,
        transpose: state_types.TransposeTransform,
    ) -> tuple[state_types.TransposeTransform, UnswizzleRef]: ...
    def commute_reshape(
        self,
        aval: jax_core.ShapedArray,
        transform: state_types.ReshapeTransform,
    ) -> tuple[state_types.ReshapeTransform, UnswizzleRef]: ...
    def commute_ndindexer(
        self,
        aval: jax_core.AbstractValue,
        indexer: indexing.NDIndexer,
    ) -> tuple[indexing.NDIndexer, UnswizzleRef]: ...
    def pretty_print(self, context: jax_core.JaxprPpContext) -> pp.Doc: ...

@dataclasses.dataclass
class BlockSpec(pallas_core.BlockSpec):
    transforms: Sequence[state_types.Transform] = ...
    delay_release: int = ...
    collective_axes: tuple[Hashable, ...] = ...
    def to_block_mapping(
        self,
        origin: pallas_core.OriginStr,
        array_aval: jax_core.ShapedArray,
        *,
        index_map_avals: Sequence[jax_core.AbstractValue],
        index_map_tree: tree_util.PyTreeDef,
        grid: pallas_core.GridMappingGrid,
        vmapped_dims: tuple[int, ...],
        debug: bool = False,
    ) -> pallas_core.BlockMapping: ...

GMEM: Incomplete
SMEM: Incomplete
TMEM: Incomplete
REGS: Incomplete

class barrier_dtype(dtypes.extended, metaclass=abc.ABCMeta): ...

@dataclasses.dataclass(frozen=True)
class BarrierType(dtypes.ExtendedDType):
    type: ClassVar[Any] = ...
    name: ClassVar[str] = ...
    num_arrivals: int
    orders_tensor_core: bool

@dataclasses.dataclass(frozen=True)
class ClusterBarrierType(dtypes.ExtendedDType):
    type: ClassVar[Any] = ...
    name: ClassVar[str] = ...
    collective_axes: tuple[str | tuple[str, ...], ...]
    num_arrivals: int
    orders_tensor_core: bool

@dataclasses.dataclass(frozen=True, kw_only=True)
class Barrier:
    num_arrivals: int = ...
    num_barriers: int = ...
    orders_tensor_core: bool = ...
    def get_array_aval(self) -> jax_core.ShapedArray: ...
    def get_ref_aval(self) -> state.AbstractRef: ...
    def __post_init__(self) -> None: ...

@dataclasses.dataclass(frozen=True, kw_only=True)
class ClusterBarrier:
    collective_axes: tuple[str | tuple[str, ...], ...]
    num_barriers: int = ...
    num_arrivals: int = ...
    orders_tensor_core: bool = ...
    def get_array_aval(self) -> jax_core.ShapedArray: ...
    def get_ref_aval(self) -> state.AbstractRef: ...

@dataclasses.dataclass(frozen=True)
class WGMMAAccumulatorRef:
    shape: tuple[int, int]
    dtype: jnp.dtype = ...
    def get_ref_aval(self) -> state.AbstractRef: ...
    @staticmethod
    def init(array): ...

class WGMMAAbstractAccumulatorRef(state.AbstractRef):
    def update(self, inner_aval=None, memory_space=None, kind=None): ...

class AbstractTMEMRef(state.AbstractRef):
    layout: Incomplete
    collective: Incomplete
    def __init__(self, inner_aval, memory_space, layout, collective) -> None: ...
    def update(self, inner_aval=None, memory_space=None, kind=None): ...

@dataclasses.dataclass(frozen=True, kw_only=True)
class Mesh:
    grid: Sequence[int] = ...
    grid_names: Sequence[str] = ...
    cluster: Sequence[int] = ...
    cluster_names: Sequence[str] = ...
    num_threads: int | None = ...
    thread_name: str | None = ...
    kernel_name: str | None = ...
    def __post_init__(self) -> None: ...
    @property
    def default_memory_space(self) -> MemorySpace: ...
    @property
    def shape(self) -> collections.OrderedDict[object, int]: ...
    def discharges_effect(self, effect: jax_core.Effect) -> bool: ...

@dataclasses.dataclass(frozen=True, kw_only=True)
class WarpMesh:
    axis_name: str
    @property
    def shape(self): ...
    @property
    def default_memory_space(self) -> MemorySpace: ...
    def discharges_effect(self, effect: jax_core.Effect) -> Literal[False]: ...

class MemoryEffect(jax_core.Effect): ...
class _WGMMAPipelineEffect(effects.Effect): ...

layout_cast_p: Incomplete

def layout_cast(x: Any, new_layout: SomeLayout): ...

class SomeLayout:
    def reduce(self, axes: int | Sequence[int]) -> SomeLayout: ...
    def to_mgpu(self, *args, **kwargs) -> mgpu.FragmentedLayout: ...

@dataclasses.dataclass(frozen=True)
class ParameterizedLayout(SomeLayout):
    layout_cls: Layout | TMEMLayout
    args: Sequence[Any]
    kwargs: Any
    def __post_init__(self) -> None: ...
    def to_mgpu(self, *args, **kwargs) -> mgpu.FragmentedLayout: ...

@dataclasses.dataclass(frozen=True)
class ReducedLayout(SomeLayout):
    layout: SomeLayout
    axes: Sequence[int]
    def to_mgpu(self, *args, **kwargs) -> mgpu.FragmentedLayout: ...

class Layout(SomeLayout, enum.Enum):
    WGMMA = ...
    WGMMA_8BIT = ...
    WGMMA_UPCAST_2X = ...
    WGMMA_UPCAST_4X = ...
    WGMMA_TRANSPOSED = ...
    WG_SPLAT = ...
    WG_STRIDED = ...
    TILED = ...
    TCGEN05 = ...
    TCGEN05_TRANSPOSED = ...
    TCGEN05_M64_COLLECTIVE = ...
    TCGEN05_TMEM_NATIVE = ...
    TCGEN05_M64_COLLECTIVE_NATIVE = ...
    SMEM_GMEM_COPY = ...
    TMA_GATHER_INDICES = ...
    def __call__(self, *args, **kwargs) -> ParameterizedLayout: ...
    def to_mgpu(self, *args, **kwargs) -> mgpu.FragmentedLayout: ...

class TMEMLayout(enum.Enum):
    SCALES_LAYOUT = ...
    SPARSE_METADATA_LAYOUT = ...
    M64_COLLECTIVE_LAYOUT = ...
    def __call__(self, *args, **kwargs) -> ParameterizedLayout: ...
    def to_mgpu(self, *args, **kwargs) -> tcgen05.TMEMLayout: ...

def TryClusterCancelResult(num_buffers: int | None = None) -> pallas_core.MemoryRef: ...
