from flax import io as io

class SummaryWriter:
    def __init__(self, log_dir, auto_flush: bool = True) -> None: ...
    def close(self) -> None: ...
    def flush(self) -> None: ...
    def scalar(self, tag, value, step) -> None: ...
    def image(self, tag, image, step, max_outputs: int = 3) -> None: ...
    def audio(
        self,
        tag,
        audiodata,
        step,
        sample_rate: int = 44100,
        max_outputs: int = 3,
    ) -> None: ...
    def histogram(self, tag, values, step, bins=None) -> None: ...
    def text(self, tag, textdata, step) -> None: ...
    def write(self, tag, tensor, step, metadata=None) -> None: ...
    def hparams(self, hparams) -> None: ...
