from typing import Any

from pyarrow import compute as compute

def table(data: dict[str, list[Any] | Array]) -> Table: ...
def array(data: list[Any], type: DataType | None = None) -> Array: ...
def int32() -> DataType: ...
def int64() -> DataType: ...

class DataType: ...

class Field:
    name: str
    type: DataType

class Schema:
    def field(self, name: str) -> Field: ...

class Array:
    type: DataType
    def __getitem__(self, index: int) -> Any: ...
    def as_py(self) -> Any: ...
    def to_pylist(self) -> list[Any]: ...

class Table:
    column_names: list[str]
    num_rows: int
    schema: Schema

    @classmethod
    def from_pandas(
        cls,
        df: Any,
        preserve_index: bool = ...,
    ) -> Table: ...
    @classmethod
    def from_pydict(cls, mapping: dict[str, Any]) -> Table: ...
    def to_pandas(self) -> Any: ...
    def column(self, name: str) -> Array: ...
    def filter(self, mask: Any) -> Table: ...
    def drop(self, name: str) -> Table: ...
    def append_column(self, name: str, column: Any) -> Table: ...
