from typing import Any, Self

from pyarrow import compute as compute

def table(data: dict[str, list[Any]]) -> Table: ...
def array(data: list[Any]) -> Array: ...

class NativeFile:
    def read(self, nbytes: int | None = ...) -> bytes: ...
    def read1(self, nbytes: int | None = ...) -> bytes: ...
    def readall(self) -> bytes: ...
    def readinto(self, buffer: Any) -> int: ...
    def write(self, data: bytes) -> int: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def tell(self) -> int: ...
    def seek(self, offset: int, whence: int = ...) -> int: ...
    def readable(self) -> bool: ...
    def writable(self) -> bool: ...
    def seekable(self) -> bool: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *args: object) -> None: ...

def OSFile(path: str, mode: str = ...) -> NativeFile: ...

class CompressedInputStream(NativeFile):
    def __init__(self, stream: NativeFile, compression: str = ...) -> None: ...

class CompressedOutputStream(NativeFile):
    def __init__(self, stream: NativeFile, compression: str = ...) -> None: ...

class Array:
    def __getitem__(self, index: int) -> Any: ...
    def as_py(self) -> Any: ...
    def to_pylist(self) -> list[Any]: ...

class Table:
    column_names: list[str]
    num_rows: int

    @classmethod
    def from_pandas(
        cls,
        df: Any,
        preserve_index: bool = ...,
    ) -> Table: ...
    @classmethod
    def from_pydict(cls, mapping: dict[str, Any]) -> Table: ...
    def to_pandas(self) -> Any: ...
    def column(self, name: str) -> Array: ...
    def filter(self, mask: Any) -> Table: ...
    def drop(self, name: str) -> Table: ...
    def append_column(self, name: str, column: Any) -> Table: ...
