from collections.abc import Sequence
from typing import Any

import enum

class Client:
    @property
    def platform(self) -> str: ...
    @property
    def platform_version(self) -> str: ...
    @property
    def runtime_type(self) -> str: ...
    @property
    def process_index(self) -> int: ...
    def device_count(self) -> int: ...
    def local_device_count(self) -> int: ...
    def devices(self) -> list[Device]: ...
    def local_devices(self) -> list[Device]: ...

class Device:
    @property
    def id(self) -> int: ...
    @property
    def device_kind(self) -> str: ...
    @property
    def platform(self) -> str: ...
    @property
    def process_index(self) -> int: ...
    @property
    def local_hardware_id(self) -> int | None: ...
    @property
    def client(self) -> Client: ...

class DeviceList(Sequence[Device]):
    def __init__(self, devices: Sequence[Device]) -> None: ...
    def __getitem__(self, index: Any) -> Any: ...
    def __len__(self) -> int: ...

class ArrayCopySemantics(enum.IntEnum):
    ALWAYS_COPY = ...
    REUSE_INPUT = ...
    DONATE_INPUT = ...

class ArrayImpl: ...
class CompileOptions: ...
class Executable: ...
class HloSharding: ...
class LoadedExecutable: ...
class OpSharding: ...
class PjRtLayout: ...
class Traceback: ...
class XlaComputation: ...
