from collections.abc import (
    Hashable,
    ItemsView,
    Iterator,
    KeysView,
    Mapping,
    ValuesView,
)
from typing import Any, TypeVar, overload

import collections

from flax import serialization as serialization

class FrozenKeysView(collections.abc.KeysView): ...
class FrozenValuesView(collections.abc.ValuesView): ...

K = TypeVar("K")
V = TypeVar("V")
T = TypeVar("T")

class FrozenDict(Mapping[K, V]):
    def __init__(self, *args, __unsafe_skip_copy__: bool = False, **kwargs) -> None: ...
    def __getitem__(self, key: K) -> V: ...
    def __setitem__(self, key: K, value: V) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> Iterator[K]: ...
    def __len__(self) -> int: ...
    def __reduce__(self): ...
    @overload
    def get(self, key: K, default: None = None) -> V | None: ...
    @overload
    def get(self, key: K, default: V | T) -> V | T: ...
    def pretty_repr(self, num_spaces: int = 4) -> str: ...
    def __hash__(self) -> int: ...
    def copy(self, add_or_replace: Mapping[K, V] = ...) -> FrozenDict[K, V]: ...
    def keys(self) -> KeysView[K]: ...
    def values(self) -> ValuesView[V]: ...
    def items(self) -> ItemsView[K, V]: ...
    def pop(self, key: K) -> tuple[FrozenDict[K, V], V]: ...
    def unfreeze(self) -> dict[K, V]: ...
    def tree_flatten_with_keys(self) -> tuple[tuple[Any, ...], Hashable]: ...
    @classmethod
    def tree_unflatten(cls, keys, values): ...

def freeze(xs: Mapping[Any, Any]) -> FrozenDict[Any, Any]: ...
def unfreeze(x: FrozenDict | dict[str, Any]) -> dict[Any, Any]: ...
def copy(
    x: FrozenDict | dict[str, Any],
    add_or_replace: FrozenDict[str, Any] | dict[str, Any] = ...,
) -> FrozenDict | dict[str, Any]: ...
def pop(
    x: FrozenDict | dict[str, Any],
    key: str,
) -> tuple[FrozenDict | dict[str, Any], Any]: ...
def pretty_repr(x: Any, num_spaces: int = 4) -> str: ...
