from collections.abc import Callable as Callable
from typing import Any, Generic, TypeVar

import abc

from flax import (
    errors as errors,
    struct as struct,
)
from flax.typing import LogicalNames as LogicalNames

import jax

A = TypeVar("A")
B = TypeVar("B")
TAxisMetadata = TypeVar("TAxisMetadata", bound=AxisMetadata[Any])

class AxisMetadata(Generic[A], metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def unbox(self) -> A: ...
    @abc.abstractmethod
    def replace_boxed(self, val: B) -> AxisMetadata[B]: ...
    @abc.abstractmethod
    def add_axis(self, index: int, params: dict[Any, Any]) -> TAxisMetadata: ...
    @abc.abstractmethod
    def remove_axis(self, index: int, params: dict[Any, Any]) -> TAxisMetadata: ...

def is_axis_metadata(val: Any) -> bool: ...
def map_axis_meta(fn: Callable[[AxisMetadata[Any]], Any], tree: Any) -> Any: ...
def add_axis(tree: Any, index: int, params: dict[Any, Any]) -> Any: ...
def remove_axis(tree: Any, index: int, params: dict[Any, Any]) -> Any: ...
def unbox(tree: Any) -> Any: ...
def replace_boxed(tree: Any, updates: Any) -> Any: ...

PARTITION_NAME: str

def get_global_mesh() -> jax.sharding.AbstractMesh | jax.sharding.Mesh | None: ...
def global_mesh_defined() -> bool: ...

class Partitioned(struct.PyTreeNode, AxisMetadata[A]):
    value: Any
    names: LogicalNames = struct.field(pytree_node=False)
    mesh: jax.sharding.Mesh | None = struct.field(default=None, pytree_node=False)
    def unbox(self, apply_constraint: bool = True) -> A: ...
    def replace_boxed(self, val: B) -> Partitioned[B]: ...
    def add_axis(self, index: int, params: dict[Any, Any]) -> Partitioned[A]: ...
    def remove_axis(self, index: int, params: dict[Any, Any]) -> Partitioned[A]: ...
    def get_partition_spec(self) -> jax.sharding.PartitionSpec: ...
    def get_sharding(self, mesh: jax.sharding.Mesh) -> jax.sharding.Sharding: ...
    def to_nnx_metadata(self) -> dict[str, Any]: ...
    @classmethod
    def from_nnx_metadata(cls, metadata: dict[str, Any]): ...

def with_partitioning(
    fn: Callable[..., Any],
    names: LogicalNames,
    mesh: jax.sharding.Mesh | None = None,
) -> Callable[..., Partitioned[Any]]: ...
def get_partition_spec(tree: Any) -> Any: ...
def get_sharding(tree: Any, mesh: jax.sharding.Mesh) -> Any: ...
