import typing

from jax._src import config as config
from jax._src.typing import Array as Array

class Rotation(typing.NamedTuple):
    quat: Array
    @classmethod
    def concatenate(cls, rotations: typing.Sequence): ...
    @classmethod
    def from_euler(cls, seq: str, angles: Array, degrees: bool = False): ...
    @classmethod
    def from_matrix(cls, matrix: Array): ...
    @classmethod
    def from_mrp(cls, mrp: Array): ...
    @classmethod
    def from_quat(cls, quat: Array): ...
    @classmethod
    def from_rotvec(cls, rotvec: Array, degrees: bool = False): ...
    @classmethod
    def identity(cls, num: int | None = None, dtype=...): ...
    @classmethod
    def random(cls, random_key: Array, num: int | None = None): ...
    def __getitem__(self, indexer): ...
    def __len__(self) -> int: ...
    def __mul__(self, other) -> Rotation: ...
    def apply(self, vectors: Array, inverse: bool = False) -> Array: ...
    def as_euler(self, seq: str, degrees: bool = False): ...
    def as_matrix(self) -> Array: ...
    def as_mrp(self) -> Array: ...
    def as_rotvec(self, degrees: bool = False) -> Array: ...
    def as_quat(self, canonical: bool = False, scalar_first: bool = False) -> Array: ...
    def inv(self): ...
    def magnitude(self) -> Array: ...
    def mean(self, weights: Array | None = None): ...
    @property
    def single(self) -> bool: ...

class Slerp(typing.NamedTuple):
    times: Array
    timedelta: Array
    rotations: Rotation
    rotvecs: Array
    @classmethod
    def init(cls, times: Array, rotations: Rotation): ...
    def __call__(self, times: Array): ...
