class Trainer:
    def __getstate__(self): ...
    def __setstate__(self, state): ...

class BpeTrainer(Trainer):
    def __init__(
        self,
        vocab_size=...,
        min_frequency=...,
        show_progress=...,
        special_tokens=...,
        limit_alphabet=...,
        initial_alphabet=...,
        continuing_subword_prefix=...,
        end_of_word_suffix=...,
        max_token_length=...,
        words=...,
    ) -> None: ...
    def __getstate__(self): ...
    def __setstate__(self, state): ...
    @property
    def continuing_subword_prefix(self): ...
    @continuing_subword_prefix.setter
    def continuing_subword_prefix(self, value): ...
    @property
    def end_of_word_suffix(self): ...
    @end_of_word_suffix.setter
    def end_of_word_suffix(self, value): ...
    @property
    def initial_alphabet(self): ...
    @initial_alphabet.setter
    def initial_alphabet(self, value): ...
    @property
    def limit_alphabet(self): ...
    @limit_alphabet.setter
    def limit_alphabet(self, value): ...
    @property
    def max_token_length(self): ...
    @max_token_length.setter
    def max_token_length(self, value): ...
    @property
    def min_frequency(self): ...
    @min_frequency.setter
    def min_frequency(self, value): ...
    @property
    def show_progress(self): ...
    @show_progress.setter
    def show_progress(self, value): ...
    @property
    def special_tokens(self): ...
    @special_tokens.setter
    def special_tokens(self, value): ...
    @property
    def vocab_size(self): ...
    @vocab_size.setter
    def vocab_size(self, value): ...

class UnigramTrainer(Trainer):
    def __init__(
        self,
        vocab_size=...,
        show_progress=...,
        special_tokens=...,
        initial_alphabet=...,
        shrinking_factor=...,
        unk_token=...,
        max_piece_length=...,
        n_sub_iterations=...,
    ) -> None: ...
    def __getstate__(self): ...
    def __setstate__(self, state): ...
    @property
    def initial_alphabet(self): ...
    @initial_alphabet.setter
    def initial_alphabet(self, value): ...
    @property
    def show_progress(self): ...
    @show_progress.setter
    def show_progress(self, value): ...
    @property
    def special_tokens(self): ...
    @special_tokens.setter
    def special_tokens(self, value): ...
    @property
    def vocab_size(self): ...
    @vocab_size.setter
    def vocab_size(self, value): ...

class WordLevelTrainer(Trainer):
    def __init__(
        self,
        vocab_size=...,
        min_frequency=...,
        show_progress=...,
        special_tokens=...,
    ) -> None: ...
    def __getstate__(self): ...
    def __setstate__(self, state): ...
    @property
    def min_frequency(self): ...
    @min_frequency.setter
    def min_frequency(self, value): ...
    @property
    def show_progress(self): ...
    @show_progress.setter
    def show_progress(self, value): ...
    @property
    def special_tokens(self): ...
    @special_tokens.setter
    def special_tokens(self, value): ...
    @property
    def vocab_size(self): ...
    @vocab_size.setter
    def vocab_size(self, value): ...

class ParityBpeTrainer:
    def __init__(
        self,
        num_merges=...,
        variant=...,
        min_frequency=...,
        ratio=...,
        global_merges=...,
        window_size=...,
        alpha=...,
        total_symbols=...,
        special_tokens=...,
        show_progress=...,
        limit_alphabet=...,
        initial_alphabet=...,
        continuing_subword_prefix=...,
        end_of_word_suffix=...,
        max_token_length=...,
    ) -> None: ...
    def __getstate__(self): ...
    def __setstate__(self, state): ...
    def train_from_iterator(
        self,
        tokenizer,
        train_iterators,
        dev_iterators=...,
        ratio=...,
    ): ...
    @property
    def special_tokens(self): ...
    @special_tokens.setter
    def special_tokens(self, value): ...
    @property
    def show_progress(self): ...
    @show_progress.setter
    def show_progress(self, value): ...
    @property
    def limit_alphabet(self): ...
    @limit_alphabet.setter
    def limit_alphabet(self, value): ...
    @property
    def initial_alphabet(self): ...
    @initial_alphabet.setter
    def initial_alphabet(self, value): ...
    @property
    def continuing_subword_prefix(self): ...
    @continuing_subword_prefix.setter
    def continuing_subword_prefix(self, value): ...
    @property
    def end_of_word_suffix(self): ...
    @end_of_word_suffix.setter
    def end_of_word_suffix(self, value): ...
    @property
    def max_token_length(self): ...
    @max_token_length.setter
    def max_token_length(self, value): ...
    @property
    def min_frequency(self): ...
    @min_frequency.setter
    def min_frequency(self, value): ...
    @property
    def num_merges(self): ...
    @num_merges.setter
    def num_merges(self, value): ...
    @property
    def variant(self): ...
    @property
    def global_merges(self): ...
    @global_merges.setter
    def global_merges(self, value): ...
    @property
    def window_size(self): ...
    @window_size.setter
    def window_size(self, value): ...
    @property
    def alpha(self): ...
    @alpha.setter
    def alpha(self, value): ...
    @property
    def total_symbols(self): ...
    @total_symbols.setter
    def total_symbols(self, value): ...

class WordPieceTrainer(Trainer):
    def __init__(
        self,
        vocab_size=...,
        min_frequency=...,
        show_progress=...,
        special_tokens=...,
        limit_alphabet=...,
        initial_alphabet=...,
        continuing_subword_prefix=...,
        end_of_word_suffix=...,
    ) -> None: ...
    def __getstate__(self): ...
    def __setstate__(self, state): ...
    @property
    def continuing_subword_prefix(self): ...
    @continuing_subword_prefix.setter
    def continuing_subword_prefix(self, value): ...
    @property
    def end_of_word_suffix(self): ...
    @end_of_word_suffix.setter
    def end_of_word_suffix(self, value): ...
    @property
    def initial_alphabet(self): ...
    @initial_alphabet.setter
    def initial_alphabet(self, value): ...
    @property
    def limit_alphabet(self): ...
    @limit_alphabet.setter
    def limit_alphabet(self, value): ...
    @property
    def min_frequency(self): ...
    @min_frequency.setter
    def min_frequency(self, value): ...
    @property
    def show_progress(self): ...
    @show_progress.setter
    def show_progress(self, value): ...
    @property
    def special_tokens(self): ...
    @special_tokens.setter
    def special_tokens(self, value): ...
    @property
    def vocab_size(self): ...
    @vocab_size.setter
    def vocab_size(self, value): ...
