from collections.abc import Sequence as Sequence2
from typing import Any, final

from _typeshed import Incomplete
from tokenizers import Regex, Tokenizer

"""
Decoders Module
"""

@final
class BPEDecoder(Decoder):
    def __new__(cls, /, suffix: str = ...) -> BPEDecoder: ...
    @property
    def suffix(self, /) -> str: ...
    @suffix.setter
    def suffix(self, /, suffix: str) -> None: ...

@final
class ByteFallback(Decoder):
    def __new__(cls, /) -> ByteFallback: ...

@final
class ByteLevel(Decoder):
    def __new__(cls, /, **_kwargs) -> ByteLevel: ...

@final
class CTC(Decoder):
    def __new__(
        cls,
        /,
        pad_token: str = ...,
        word_delimiter_token: str = ...,
        cleanup: bool = ...,
    ) -> CTC: ...
    @property
    def cleanup(self, /) -> bool: ...
    @cleanup.setter
    def cleanup(self, /, cleanup: bool) -> None: ...
    @property
    def pad_token(self, /) -> str: ...
    @pad_token.setter
    def pad_token(self, /, pad_token: str) -> None: ...
    @property
    def word_delimiter_token(self, /) -> str: ...
    @word_delimiter_token.setter
    def word_delimiter_token(self, /, word_delimiter_token: str) -> None: ...

@final
class DecodeStream:
    def __copy__(self, /) -> DecodeStream: ...
    def __deepcopy__(self, /, _memo: dict) -> DecodeStream: ...
    def __new__(
        cls,
        /,
        ids: Sequence2[int] | None = ...,
        skip_special_tokens: bool | None = ...,
    ) -> DecodeStream: ...
    def step(self, /, tokenizer: Tokenizer, id: Incomplete) -> str | None: ...

class Decoder:
    def __getstate__(self, /) -> Any: ...
    def __setstate__(self, /, state: Any) -> None: ...
    @staticmethod
    def custom(decoder: Any) -> Decoder: ...
    def decode(self, /, tokens: Sequence2[str]) -> str: ...

@final
class Fuse(Decoder):
    def __new__(cls, /) -> Fuse: ...

@final
class Metaspace(Decoder):
    def __new__(
        cls,
        /,
        replacement: str = ...,
        prepend_scheme: str = ...,
        split: bool = ...,
    ) -> Metaspace: ...
    @property
    def prepend_scheme(self, /) -> str: ...
    @prepend_scheme.setter
    def prepend_scheme(self, /, prepend_scheme: str) -> None: ...
    @property
    def replacement(self, /) -> str: ...
    @replacement.setter
    def replacement(self, /, replacement: str) -> None: ...
    @property
    def split(self, /) -> bool: ...
    @split.setter
    def split(self, /, split: bool) -> None: ...

@final
class Replace(Decoder):
    def __new__(cls, /, pattern: str | Regex, content: str) -> Replace: ...

@final
class Sequence(Decoder):
    def __getnewargs__(self, /) -> tuple: ...
    def __new__(cls, /, decoders_py: list) -> Sequence: ...

@final
class Strip(Decoder):
    def __new__(
        cls,
        /,
        content: str = ...,
        left: int = ...,
        right: int = ...,
    ) -> Strip: ...
    @property
    def content(self, /) -> str: ...
    @content.setter
    def content(self, /, content: str) -> None: ...
    @property
    def start(self, /) -> int: ...
    @start.setter
    def start(self, /, start: int) -> None: ...
    @property
    def stop(self, /) -> int: ...
    @stop.setter
    def stop(self, /, stop: int) -> None: ...

@final
class WordPiece(Decoder):
    def __new__(cls, /, prefix: str = ..., cleanup: bool = ...) -> WordPiece: ...
    @property
    def cleanup(self, /) -> bool: ...
    @cleanup.setter
    def cleanup(self, /, cleanup: bool) -> None: ...
    @property
    def prefix(self, /) -> str: ...
    @prefix.setter
    def prefix(self, /, prefix: str) -> None: ...
