from absl.testing import parameterized

class CastingTest(parameterized.TestCase):
    def test_tree_cast(self, dtype, b, c, new_b, new_c): ...
    def test_tree_cast_like(self, dtype, b, c): ...
    def test_tree_dtype(self) -> None: ...
    def test_tree_dtype_utilities_with_empty_trees(self, tree) -> None: ...
