from _typeshed import Incomplete
from absl.testing import parameterized

class TreeUtilsTest(parameterized.TestCase):
    rng_jax: Incomplete
    tree_a: Incomplete
    tree_b: Incomplete
    tree_a_dict: Incomplete
    tree_b_dict: Incomplete
    array_a: Incomplete
    array_b: Incomplete
    tree_a_dict_jax: Incomplete
    tree_b_dict_jax: Incomplete
    data: Incomplete
    def setUp(self) -> None: ...
    def test_tree_add(self) -> None: ...
    def test_tree_sub(self) -> None: ...
    def test_tree_mul(self) -> None: ...
    def test_tree_div(self) -> None: ...
    def test_tree_scale(self) -> None: ...
    def test_tree_add_scale(self) -> None: ...
    def test_tree_add_scale_dtype(self) -> None: ...
    def test_tree_vdot(self) -> None: ...
    def test_tree_sum(self) -> None: ...
    def test_tree_max(self, key) -> None: ...
    def test_tree_min(self, key) -> None: ...
    def test_tree_size(self, key) -> None: ...
    def test_tree_allclose(self) -> None: ...
    def test_tree_conj(self) -> None: ...
    def test_tree_real(self) -> None: ...
    def test_tree_l2_norm(self) -> None: ...
    def test_tree_l1_norm(self, key) -> None: ...
    def test_tree_linf_norm(self, key) -> None: ...
    def test_tree_zeros_like(self) -> None: ...
    def test_tree_ones_like(self) -> None: ...
    def test_add_multiple_trees(self) -> None: ...
    def test_tree_clip(self) -> None: ...
    def test_update_infinity_moment(self) -> None: ...
    def test_bias_correction_bf16(self) -> None: ...
    def test_empty_tree_reduce(self) -> None: ...
    def test_none_arguments(self, operation) -> None: ...
