from typing import Any

from optax._src import numerics as numerics

import chex
import jax

def tree_add(tree_x: Any, tree_y: Any, *other_trees: Any) -> Any: ...
def tree_sub(tree_x: Any, tree_y: Any) -> Any: ...
def tree_mul(tree_x: Any, tree_y: Any) -> Any: ...
def tree_div(tree_x: Any, tree_y: Any) -> Any: ...
def tree_scale(scalar: float | jax.Array, tree: Any) -> Any: ...
def tree_add_scale(tree_x: Any, scalar: float | jax.Array, tree_y: Any) -> Any: ...
def tree_vdot(tree_x: Any, tree_y: Any) -> chex.Numeric: ...
def tree_sum(tree: Any) -> chex.Numeric: ...
def tree_max(tree: Any) -> chex.Numeric: ...
def tree_min(tree: Any) -> chex.Numeric: ...
def tree_size(tree: Any) -> int: ...
def tree_conj(tree: Any) -> Any: ...
def tree_real(tree: Any) -> Any: ...
def tree_norm(
    tree: Any,
    ord: str | float | None = None,
    squared: bool = False,
) -> jax.Array: ...
def tree_batch_shape(tree: Any, shape: tuple[int, ...] = ()): ...
def tree_zeros_like(tree: Any, dtype: jax.typing.DTypeLike | None = None) -> Any: ...
def tree_ones_like(tree: Any, dtype: jax.typing.DTypeLike | None = None) -> Any: ...
def tree_full_like(
    tree: Any,
    fill_value: jax.typing.ArrayLike,
    dtype: jax.typing.DTypeLike | None = None,
) -> Any: ...
def tree_clip(
    tree: Any,
    min_value: jax.typing.ArrayLike | None = None,
    max_value: jax.typing.ArrayLike | None = None,
) -> Any: ...
def tree_update_moment(updates, moments, decay, order): ...
def tree_update_infinity_moment(updates, moments, decay, eps): ...
def tree_update_moment_per_elem_norm(updates, moments, decay, order): ...
def tree_bias_correction(moment, decay, count): ...
def tree_where(condition, tree_x, tree_y): ...
def tree_allclose(
    a: Any,
    b: Any,
    rtol: jax.typing.ArrayLike = 1e-05,
    atol: jax.typing.ArrayLike = 1e-08,
    equal_nan: bool = False,
): ...
