from dataclasses import dataclass
from enum import Enum
from typing import Any

from torchao.core.config import AOBaseConfig

class MXGemmKernelChoice(Enum):
    EMULATED = ...
    CUTLASS = ...
    CUBLAS = ...

class MXFP8Dim1CastKernelChoice(Enum):
    TRITON = ...
    CUDA = ...
    TORCH = ...

class MXLinearRecipeName(Enum):
    MXFP8_EMULATED = ...
    MXFP8_CUBLAS = ...
    MXFP8_CUBLAS_RCEIL = ...
    MXFP4_EMULATED = ...
    MXFP4_CUTLASS = ...

class ScaleCalculationMode(Enum):
    FLOOR = ...
    RCEIL = ...
    CEIL = ...
    EVEN = ...

@dataclass
class MXLinearConfig(AOBaseConfig):
    block_size: int = ...
    elem_dtype: Any = ...
    elem_dtype_weight_override: Any | None = ...
    elem_dtype_grad_output_override: Any | None = ...
    gemm_kernel_choice: MXGemmKernelChoice = ...
    mxfp8_cast_kernel_choice: MXFP8Dim1CastKernelChoice = ...
    scale_calculation_mode: ScaleCalculationMode = ...
    def __post_init__(self):  # -> None:
        ...
    @staticmethod
    def from_recipe_name(recipe_name: MXLinearRecipeName | str) -> MXLinearConfig: ...
    def short_str(self) -> str: ...
