from dataclasses import dataclass

from torchao.core.config import AOBaseConfig
from torchao.prototype.mx_formats import MXGemmKernelChoice
from torchao.prototype.mx_formats.nvfp4_tensor import NVFP4MMConfig

import torch

@dataclass
class MXFPInferenceConfig(AOBaseConfig):
    block_size: int = ...
    activation_dtype: torch.dtype = ...
    weight_dtype: torch.dtype = ...
    gemm_kernel_choice: MXGemmKernelChoice = ...
    def __post_init__(self):  # -> None:
        ...

@dataclass
class NVFP4InferenceConfig(AOBaseConfig):
    mm_config: NVFP4MMConfig = ...
    use_triton_kernel: bool = ...
    use_dynamic_per_tensor_scale: bool = ...
    def __post_init__(self):  # -> None:
        ...
