from dataclasses import dataclass
from enum import Enum
from typing import Any

from torchao.quantization.quantize_.common import QuantizeTensorKwargs
from torchao.utils import TorchAOBaseTensor

import torch

E4M3_EPS = ...
aten = ...
NVFP4_OPS_TABLE: dict[Any, Any] = ...

class NVFP4MMConfig(Enum):
    DYNAMIC = ...
    WEIGHT_ONLY = ...

@dataclass
class QuantizeTensorToNVFP4Kwargs(QuantizeTensorKwargs):
    block_size: int = ...
    is_swizzled_scales: bool = ...
    use_triton_kernel: bool = ...
    use_dynamic_per_tensor_scale: bool = ...

def implements(aten_ops):  # -> Callable[..., Any]:
    ...

class NVFP4Tensor(TorchAOBaseTensor):
    tensor_data_names = ...
    tensor_attribute_names = ...
    optional_tensor_data_names = ...
    optional_tensor_attribute_names = ...
    def __new__(
        cls,
        qdata,
        blockwise_scales,
        block_size,
        orig_dtype,
        _per_tensor_scale=...,
        _act_per_tensor_scale=...,
        _is_swizzled_scales=...,
        use_triton_kernel=...,
        act_quant_kwargs=...,
    ):  # -> Self:
        ...
    def __repr__(self):  # -> str:
        ...
    @classmethod
    def __torch_dispatch__(cls, func, types, args, kwargs=...):  # -> Any:
        ...
    @staticmethod
    def to_nvfp4(
        data_hp: torch.Tensor,
        block_size: int = ...,
        per_tensor_scale: torch.Tensor | None = ...,
        act_per_tensor_scale: torch.Tensor | None = ...,
        is_swizzled_scales: bool = ...,
        use_triton_kernel: bool = ...,
        act_quant_kwargs: QuantizeTensorToNVFP4Kwargs | None = ...,
    ):  # -> NVFP4Tensor:
        ...
    def to_dtype(self, target_dtype: torch.dtype) -> torch.Tensor: ...
    def get_hp_scales(self) -> torch.Tensor: ...

@implements([aten.detach.default, aten.alias.default])
def nvfp4_detach_alias(func, types, args, kwargs):  # -> tuple[Any, ...] | Any:
    ...
@implements([aten._to_copy.default])
def nvfp4_to_copy(func, types, args, kwargs):  # -> NVFP4Tensor | tuple[Any, ...] | Any:
    ...
@implements([aten.copy_.default])
def nvfp4_copy_(func, types, args, kwargs): ...
@implements([aten.clone.default])
def nvfp4_clone(func, types, args, kwargs): ...
@implements([aten.slice.Tensor])
def nvfp4_slice(func, types, args, kwargs): ...
@implements([aten.t.default])
def nvfp4_t(func, types, args, kwargs):  # -> NVFP4Tensor:
    ...
@implements([aten.transpose.int])
def nvfp4_transpose(func, types, args, kwargs):  # -> NVFP4Tensor:
    ...
@implements([aten.view.default])
def nvfp4_view_op(func, types, args, kwargs):  # -> NVFP4Tensor:
    ...
@implements([aten.select.int])
def nvfp4_select(func, types, args, kwargs):  # -> tuple[Any, ...] | Any:
    ...
@implements([torch.nn.functional.linear, aten.linear.default])
def nvfp4_linear(func, types, args, kwargs):  # -> Tensor:
    ...
@implements([aten.mm.default, aten.matmul.default])
def nvfp4_mm(func, types, args, kwargs):  # -> Tensor:
    ...
@implements([aten.addmm.default])
def nvfp4_addmm(func, types, args, kwargs):  # -> Tensor:
    ...
def per_tensor_amax_to_scale(amax: torch.Tensor) -> torch.Tensor: ...
def nvfp4_quantize(
    data_hp: torch.Tensor,
    block_size: int = ...,
    per_tensor_scale: torch.Tensor | None = ...,
) -> tuple[torch.Tensor, torch.Tensor]: ...
