import torch

Tensor = torch.Tensor

def ceil_div(a, b): ...
def to_blocked(input_matrix, use_triton_kernel: bool = ...) -> Tensor: ...
def from_blocked(
    blocked_tensor: Tensor, original_rows: int, original_cols: int
) -> Tensor: ...
def hp_data_dims_to_swizzled_scale_dims_nvfp4(
    hp_data_M, hp_data_K
) -> tuple[int, int]: ...
