from types import ModuleType

from jax._src import config as config
from jax._src.lib import xla_client as xc
from jax._src.sharding import Sharding as Sharding

__array_api_version__: str

def __array_namespace__(self, *, api_version: str | None = None) -> ModuleType: ...
def __array_namespace_info__() -> ArrayNamespaceInfo: ...

class ArrayNamespaceInfo:
    def default_device(self) -> None: ...
    def devices(self) -> list[xc.Device | None]: ...
    def capabilities(self): ...
    def default_dtypes(self, *, device: xc.Device | Sharding | None = None): ...
    def dtypes(
        self,
        *,
        device: xc.Device | Sharding | None = None,
        kind: str | tuple[str, ...] | None = None,
    ): ...
