from collections.abc import Callable as Callable
from typing import Any

from _typeshed import Incomplete
from jax._src import (
    core as core,
    dtypes as dtypes,
)
from jax._src.api import jit as jit
from jax._src.custom_derivatives import custom_jvp as custom_jvp
from jax._src.lax import lax as lax
from jax._src.numpy import (
    array_constructors as array_constructors,
    reductions as reductions,
)
from jax._src.numpy.ufunc_api import ufunc as ufunc
from jax._src.numpy.util import (
    check_arraylike as check_arraylike,
    check_no_float0s as check_no_float0s,
    ensure_arraylike as ensure_arraylike,
    promote_args as promote_args,
    promote_args_inexact as promote_args_inexact,
    promote_args_numeric as promote_args_numeric,
    promote_dtypes_inexact as promote_dtypes_inexact,
    promote_dtypes_numeric as promote_dtypes_numeric,
    promote_shapes as promote_shapes,
)
from jax._src.typing import (
    Array as Array,
    ArrayLike as ArrayLike,
)
from jax._src.util import set_module as set_module

export: Incomplete

def unary_ufunc(func: Callable[[ArrayLike], Array]) -> ufunc: ...
def binary_ufunc(
    identity: Any,
    reduce: Callable[..., Any] | None = None,
    accumulate: Callable[..., Any] | None = None,
    at: Callable[..., Any] | None = None,
    reduceat: Callable[..., Any] | None = None,
) -> Callable[[Callable[[ArrayLike, ArrayLike], Array]], ufunc]: ...
@export
def fabs(x: ArrayLike, /) -> Array: ...
@export
def bitwise_invert(x: ArrayLike, /) -> Array: ...
@export
def bitwise_not(x: ArrayLike, /) -> Array: ...
@export
def invert(x: ArrayLike, /) -> Array: ...
@unary_ufunc
def negative(x: ArrayLike, /) -> Array: ...
@export
def positive(x: ArrayLike, /) -> Array: ...
@export
def sign(x: ArrayLike, /) -> Array: ...
@export
def floor(x: ArrayLike, /) -> Array: ...
@export
def ceil(x: ArrayLike, /) -> Array: ...
@export
def exp(x: ArrayLike, /) -> Array: ...
@export
def log(x: ArrayLike, /) -> Array: ...
@export
def expm1(x: ArrayLike, /) -> Array: ...
@export
def log1p(x: ArrayLike, /) -> Array: ...
@export
def sin(x: ArrayLike, /) -> Array: ...
@export
def cos(x: ArrayLike, /) -> Array: ...
@export
def tan(x: ArrayLike, /) -> Array: ...
@export
def arcsin(x: ArrayLike, /) -> Array: ...
@export
def arccos(x: ArrayLike, /) -> Array: ...
@export
def arctan(x: ArrayLike, /) -> Array: ...
@export
def sinh(x: ArrayLike, /) -> Array: ...
@export
def cosh(x: ArrayLike, /) -> Array: ...
@export
def arcsinh(x: ArrayLike, /) -> Array: ...
@export
@jit
def arccosh(x: ArrayLike, /) -> Array: ...
@export
def tanh(x: ArrayLike, /) -> Array: ...
@export
def arctanh(x: ArrayLike, /) -> Array: ...
@export
def sqrt(x: ArrayLike, /) -> Array: ...
@export
def cbrt(x: ArrayLike, /) -> Array: ...
def add(x: ArrayLike, y: ArrayLike, /) -> Array: ...
def multiply(x: ArrayLike, y: ArrayLike, /) -> Array: ...
def bitwise_and(x: ArrayLike, y: ArrayLike, /) -> Array: ...
def bitwise_or(x: ArrayLike, y: ArrayLike, /) -> Array: ...
def bitwise_xor(x: ArrayLike, y: ArrayLike, /) -> Array: ...
@export
def left_shift(x: ArrayLike, y: ArrayLike, /) -> Array: ...
@export
def bitwise_left_shift(x: ArrayLike, y: ArrayLike, /) -> Array: ...
@export
def equal(x: ArrayLike, y: ArrayLike, /) -> Array: ...
@export
def not_equal(x: ArrayLike, y: ArrayLike, /) -> Array: ...
def subtract(x: ArrayLike, y: ArrayLike, /) -> Array: ...
@export
def arctan2(x1: ArrayLike, x2: ArrayLike, /) -> Array: ...
def minimum(x: ArrayLike, y: ArrayLike, /) -> Array: ...
def maximum(x: ArrayLike, y: ArrayLike, /) -> Array: ...
@export
def float_power(x: ArrayLike, y: ArrayLike, /) -> Array: ...
@export
def nextafter(x: ArrayLike, y: ArrayLike, /) -> Array: ...
@export
def spacing(x: ArrayLike, /) -> Array: ...
def logical_and(x: ArrayLike, y: ArrayLike, /) -> Array: ...
def logical_or(x: ArrayLike, y: ArrayLike, /) -> Array: ...
def logical_xor(x: ArrayLike, y: ArrayLike, /) -> Array: ...
@export
def logical_not(x: ArrayLike, /) -> Array: ...
@export
def greater_equal(x: ArrayLike, y: ArrayLike, /) -> Array: ...
@export
def greater(x: ArrayLike, y: ArrayLike, /) -> Array: ...
@export
def less_equal(x: ArrayLike, y: ArrayLike, /) -> Array: ...
@export
def less(x: ArrayLike, y: ArrayLike, /) -> Array: ...
@export
def acos(x: ArrayLike, /) -> Array: ...
@export
def acosh(x: ArrayLike, /) -> Array: ...
@export
def asin(x: ArrayLike, /) -> Array: ...
@export
def asinh(x: ArrayLike, /) -> Array: ...
@export
def atan(x: ArrayLike, /) -> Array: ...
@export
def atanh(x: ArrayLike, /) -> Array: ...
@export
def atan2(x1: ArrayLike, x2: ArrayLike, /) -> Array: ...
@export
@jit
def bitwise_count(x: ArrayLike, /) -> Array: ...
@export
def right_shift(x1: ArrayLike, x2: ArrayLike, /) -> Array: ...
@export
def bitwise_right_shift(x1: ArrayLike, x2: ArrayLike, /) -> Array: ...
@export
def absolute(x: ArrayLike, /) -> Array: ...
@export
def abs(x: ArrayLike, /) -> Array: ...
@export
@jit
def rint(x: ArrayLike, /) -> Array: ...
@export
@jit
def copysign(x1: ArrayLike, x2: ArrayLike, /) -> Array: ...
@export
def true_divide(x1: ArrayLike, x2: ArrayLike, /) -> Array: ...
@export
def divide(x1: ArrayLike, x2: ArrayLike, /) -> Array: ...
@export
@jit
def floor_divide(x1: ArrayLike, x2: ArrayLike, /) -> Array: ...
@export
@jit
def divmod(x1: ArrayLike, x2: ArrayLike, /) -> tuple[Array, Array]: ...
@export
def power(x1: ArrayLike, x2: ArrayLike, /) -> Array: ...
@export
def pow(x1: ArrayLike, x2: ArrayLike, /) -> Array: ...
def logaddexp(x1: ArrayLike, x2: ArrayLike, /) -> Array: ...
def logaddexp2(x1: ArrayLike, x2: ArrayLike, /) -> Array: ...
@export
def log2(x: ArrayLike, /) -> Array: ...
@export
def log10(x: ArrayLike, /) -> Array: ...
@export
def exp2(x: ArrayLike, /) -> Array: ...
@export
@jit
def signbit(x: ArrayLike, /) -> Array: ...
@export
@jit
def ldexp(x1: ArrayLike, x2: ArrayLike, /) -> Array: ...
@export
@jit
def frexp(x: ArrayLike, /) -> tuple[Array, Array]: ...
@export
@jit
def remainder(x1: ArrayLike, x2: ArrayLike, /) -> Array: ...
@export
def mod(x1: ArrayLike, x2: ArrayLike, /) -> Array: ...
@export
@jit
def fmod(x1: ArrayLike, x2: ArrayLike, /) -> Array: ...
@export
def square(x: ArrayLike, /) -> Array: ...
@export
def deg2rad(x: ArrayLike, /) -> Array: ...
@export
def rad2deg(x: ArrayLike, /) -> Array: ...
@export
def degrees(x: ArrayLike, /) -> Array: ...
@export
def radians(x: ArrayLike, /) -> Array: ...
@export
def conjugate(x: ArrayLike, /) -> Array: ...
@export
def conj(x: ArrayLike, /) -> Array: ...
@export
def imag(val: ArrayLike, /) -> Array: ...
@export
def real(val: ArrayLike, /) -> Array: ...
@export
@jit
def modf(x: ArrayLike, /, out=None) -> tuple[Array, Array]: ...
@export
def isfinite(x: ArrayLike, /) -> Array: ...
@export
@jit
def isinf(x: ArrayLike, /) -> Array: ...
@export
def isposinf(x, /, out=None): ...
@export
def isneginf(x, /, out=None): ...
@export
def isnan(x: ArrayLike, /) -> Array: ...
@export
@jit
def heaviside(x1: ArrayLike, x2: ArrayLike, /) -> Array: ...
@export
@jit
def hypot(x1: ArrayLike, x2: ArrayLike, /) -> Array: ...
@export
def reciprocal(x: ArrayLike, /) -> Array: ...
@export
@jit
def sinc(x: ArrayLike, /) -> Array: ...
