import typing as _typing

import cv2.typing

__all__: list[str] = ...

class CoreML:
    def __init__(self) -> None: ...
    def cfgUseCPUOnly(self) -> CoreML: ...
    def cfgEnableOnSubgraph(self) -> CoreML: ...
    def cfgEnableOnlyNeuralEngine(self) -> CoreML: ...

class CUDA:
    @_typing.overload
    def __init__(self) -> None: ...
    @_typing.overload
    def __init__(self, dev_id: int) -> None: ...

class TensorRT:
    @_typing.overload
    def __init__(self) -> None: ...
    @_typing.overload
    def __init__(self, dev_id: int) -> None: ...

class OpenVINO:
    @_typing.overload
    def __init__(self) -> None: ...
    @_typing.overload
    def __init__(self, dev_type: str) -> None: ...
    @_typing.overload
    def __init__(self, params: cv2.typing.map_string_and_string) -> None: ...
    def cfgCacheDir(self, dir: str) -> OpenVINO: ...
    def cfgNumThreads(self, nthreads: int) -> OpenVINO: ...
    def cfgEnableOpenCLThrottling(self) -> OpenVINO: ...
    def cfgEnableDynamicShapes(self) -> OpenVINO: ...

class DirectML:
    @_typing.overload
    def __init__(self) -> None: ...
    @_typing.overload
    def __init__(self, device_id: int) -> None: ...
    @_typing.overload
    def __init__(self, adapter_name: str) -> None: ...
