from dataclasses import dataclass
from typing import Any, Literal, NoReturn, Self

import enum
import re

import numpy as np

IS_NUMPY_INSTALLED = ...
if IS_NUMPY_INSTALLED: ...
_array_name_format = ...

def get_array_name_format() -> str: ...
def set_array_name_format(value) -> None: ...

class _AnyDtype:
    _instance: Self | None = ...
    def __new__(cls) -> Self: ...
    def __reduce__(self) -> tuple[type[_AnyDtype], tuple[()]]: ...

class _AnonymousDim:
    _instance: Self | None = ...
    def __new__(cls) -> Self: ...
    def __reduce__(self) -> tuple[type[_AnonymousDim], tuple[()]]: ...

class _AnonymousVariadicDim:
    _instance: Self | None = ...
    def __new__(cls) -> Self: ...
    def __reduce__(self) -> tuple[type[_AnonymousVariadicDim], tuple[()]]: ...

_any_dtype = ...
_anonymous_dim = ...
_anonymous_variadic_dim = ...

class _DimType(enum.Enum):
    named = ...
    fixed = ...
    symbolic = ...

@dataclass(frozen=True)
class _NamedDim:
    name: str
    broadcastable: bool
    treepath: Any

@dataclass(frozen=True)
class _NamedVariadicDim:
    name: str
    broadcastable: bool
    treepath: Any

@dataclass(frozen=True)
class _FixedDim:
    size: int
    broadcastable: bool

@dataclass(frozen=True)
class _SymbolicDim:
    elem: Any
    broadcastable: bool

_AbstractDimOrVariadicDim = ...
_AbstractDim = ...

class _MetaAbstractArray(type):
    _skip_instancecheck: bool = ...
    def make_transparent(cls) -> None: ...
    def __instancecheck__(cls, obj: Any) -> bool: ...
    def __instancecheck_str__(cls, obj: Any) -> str: ...

class AbstractArray(metaclass=_MetaAbstractArray):
    dtype: type[AbstractDtype]
    array_type: Any
    dim_str: str
    dtypes: list[str]
    dims: tuple[_AbstractDimOrVariadicDim, ...]
    index_variadic: int | None
    def __new__(cls, *args, **kwargs): ...

_not_made = ...
_union_types = ...

class _MetaAbstractDtype(type):
    def __instancecheck__(cls, obj: Any) -> NoReturn: ...
    def __getitem__(
        cls, item: tuple[Any, str]
    ) -> (
        type[__class__MetaAbstractArray]
        | tuple[
            type[__class__MetaAbstractArray] | Any,
            type[__class__MetaAbstractArray] | Any,
            *tuple[type[__class__MetaAbstractArray] | Any, ...],
        ]
    ): ...

class AbstractDtype(metaclass=_MetaAbstractDtype):
    dtypes: Literal[_any_dtype] | list[str | re.Pattern]
    def __init__(self, *args, **kwargs) -> None: ...
    def __init_subclass__(cls, **kwargs) -> None: ...

_prng_key = ...
_bool = ...
_bool_ = ...
_uint2 = ...
_uint4 = ...
_uint8 = ...
_uint16 = ...
_uint32 = ...
_uint64 = ...
_int2 = ...
_int4 = ...
_int8 = ...
_int16 = ...
_int32 = ...
_int64 = ...
_float4_e2m1fn = ...
_float8_e4m3b11fnuz = ...
_float8_e4m3fn = ...
_float8_e4m3fnuz = ...
_float8_e5m2 = ...
_float8_e5m2fnuz = ...
_bfloat16 = ...
_float16 = ...
_float32 = ...
_float64 = ...
_complex64 = ...
_complex128 = ...
UInt2 = ...
UInt4 = ...
UInt8 = ...
UInt16 = ...
UInt32 = ...
UInt64 = ...
Int2 = ...
Int4 = ...
Int8 = ...
Int16 = ...
Int32 = ...
Int64 = ...
Float4e2m1fn = ...
Float8e4m3b11fnuz = ...
Float8e4m3fn = ...
Float8e4m3fnuz = ...
Float8e5m2 = ...
Float8e5m2fnuz = ...
BFloat16 = ...
Float16 = ...
Float32 = ...
Float64 = ...
Complex64 = ...
Complex128 = ...
bools = ...
uints = ...
ints = ...
float8 = ...
floats = ...
complexes = ...
Bool = ...
UInt = ...
Int = ...
Integer = ...
Float = ...
Complex = ...
Inexact = ...
Real = ...
Num = ...
Shaped = ...
Key = ...

def make_numpy_struct_dtype(dtype: np.dtype, name: str) -> type[_Cls]: ...
