from collections.abc import Callable
from contextlib import AbstractContextManager
from typing import Any, Literal, ParamSpec, TypeVar, overload

_Params = ParamSpec("_Params")
_Return = TypeVar("_Return")
_T = TypeVar("_T")
_TypeOrCallable = TypeVar("_TypeOrCallable", bound=type | Callable)

class _Sentinel:
    def __repr__(self) -> Literal["sentinel"]: ...

_sentinel = ...
_tb_flag = ...

@overload
def jaxtyped(
    *, typechecker: Callable[..., Any] | _Sentinel = ...
) -> Callable[[_TypeOrCallable], _TypeOrCallable]: ...
@overload
def jaxtyped(
    fn: type[_T], *, typechecker: Callable[..., Any] | _Sentinel = ...
) -> type[_T]: ...
@overload
def jaxtyped(
    fn: Callable[_Params, _Return], *, typechecker: Callable[..., Any] | _Sentinel = ...
) -> Callable[_Params, _Return]: ...
@overload
def jaxtyped(fn: Literal["context"]) -> AbstractContextManager[None]: ...
def jaxtyped(
    fn=..., *, typechecker=...
) -> (
    type[DataclassInstance | object]
    | _JaxtypingContext
    | partial[Callable[[_TypeOrCallable], _TypeOrCallable]]
    | classmethod[Any, ..., object]
    | staticmethod[..., object]
    | property
    | _Wrapped
): ...

class _JaxtypingContext:
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type, exc_value, exc_tb) -> None: ...

class _jaxtyping_note_str(str): ...

_spacer = ...
