from collections.abc import Sequence
from importlib.abc import MetaPathFinder
from importlib.machinery import SourceFileLoader

import ast

class Typechecker:
    lookup = ...
    def __init__(self, typechecker) -> None: ...
    def get_hash(self) -> str: ...
    def get_ast(self): ...

class JaxtypingTransformer(ast.NodeVisitor):
    def __init__(self, *, typechecker: Typechecker) -> None: ...
    def visit_Module(self, node: ast.Module) -> Module: ...
    def visit_ClassDef(self, node: ast.ClassDef) -> ClassDef: ...
    def visit_FunctionDef(self, node: ast.FunctionDef) -> FunctionDef: ...

class _JaxtypingLoader(SourceFileLoader):
    def __init__(self, *args, typechecker: Typechecker, **kwargs) -> None: ...
    def source_to_code(self, data, path, *, _optimize=...): ...
    def exec_module(self, module) -> None: ...

class _JaxtypingFinder(MetaPathFinder):
    def __init__(
        self, modules, original_pathfinder, typechecker: Typechecker
    ) -> None: ...
    def find_spec(self, fullname, path=..., target=...) -> None: ...
    def should_instrument(self, module_name: str) -> bool: ...

class ImportHookManager:
    def __init__(self, hook: MetaPathFinder) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
    def uninstall(self) -> None: ...

def install_import_hook(
    modules: str | Sequence[str], typechecker: str | None
) -> ImportHookManager: ...
