from typing import Generic, NoReturn, TypeVar

import typing

import wadler_lindig as wl

_T = TypeVar("_T")
_S = TypeVar("_S")

class _FakePyTree1(Generic[_T]): ...
class _FakePyTree2(Generic[_T, _S]): ...

class _MetaPyTree(type):
    # Every annotation below is read off ``jaxtyping/_pytree_type.py``. The
    # generator emitted bare parameters and a return type naming
    # ``_MetaPyTree.X``, an attribute that does not exist.
    def __call__(cls, *args: object, **kwargs: object) -> NoReturn: ...
    def __instancecheck__(cls, obj: object) -> bool: ...
    def __getitem__(cls, item: type | tuple[type, str]) -> type: ...
    def __pdoc__(cls, **kwargs: object) -> wl.AbstractDoc: ...

PyTree = ...
# The generator emitted a bare tuple in the ``in`` operand, which does not
# parse. A stub with a syntax error is SILENTLY SKIPPED by both checkers, so
# the whole module resolved Unknown while the error count looked clean.
if getattr(typing, "GENERATING_DOCUMENTATION", "") in ("", "jaxtyping"): ...
else: ...
