from typing import Any

_shape_storage = ...

def get_shape_memo() -> tuple[
    Any | dict[Any, Any],
    Any | dict[Any, Any],
    Any | dict[Any, Any],
    Any | dict[Any, Any],
]: ...
def set_shape_memo(single_memo, variadic_memo, pytree_memo, arg_memo) -> None: ...
def push_shape_memo(
    arguments: dict[str, Any],
) -> tuple[dict[Any, Any], dict[Any, Any], dict[Any, Any], dict[str, Any]]: ...
def pop_shape_memo() -> None: ...
def shape_str(memos) -> str: ...
def print_bindings() -> None: ...

_treepath_storage = ...

def clear_treepath_memo() -> None: ...
def set_treepath_memo(index: int | None, structure: str) -> None: ...
def get_treepath_memo() -> str: ...

_treeflatten_storage = ...

def clear_treeflatten_memo() -> None: ...
def set_treeflatten_memo() -> None: ...
def get_treeflatten_memo() -> Any | Literal[False]: ...
