from _typeshed import Incomplete

from .std import tqdm as std_tqdm

__all__ = ["tqdm", "tqdm_tk", "trange", "ttkrange"]

class tqdm_tk(std_tqdm):
    def __init__(self, *args, **kwargs) -> None: ...
    disable: bool
    def close(self) -> None: ...
    def clear(self, *_, **__) -> None: ...
    def display(self, *_, **__) -> None: ...
    def set_description(self, desc=None, refresh: bool = True) -> None: ...
    desc: Incomplete
    def set_description_str(self, desc=None, refresh: bool = True) -> None: ...
    def cancel(self) -> None: ...
    def reset(self, total=None) -> None: ...

def ttkrange(*args, **kwargs): ...

tqdm = tqdm_tk
trange = ttkrange
