from collections.abc import (
    AsyncGenerator,
    Callable,
    Generator,
    Sequence,
)
from enum import Enum
from functools import partial
from types import CodeType, FunctionType
from typing import (
    TYPE_CHECKING,
    Any,
    Literal,
    TextIO,
    TypeVar,
    overload,
)

import collections.abc

__all__ = (
    "ForwardRefPolicy",
    "TypeChecker",
    "TypeHintWarning",
    "TypeWarning",
    "check_argument_types",
    "check_return_type",
    "check_type",
    "typechecked",
    "typeguard_ignore",
)
evaluate_forwardref = ...
if TYPE_CHECKING:
    _F = TypeVar("_F")
    def typeguard_ignore(f: _F) -> _F: ...

else: ...
_type_hints_map: dict[FunctionType, dict[str, Any]] = ...
_functions_map: dict[CodeType, FunctionType] = ...
_missing = ...
T_CallableOrType = TypeVar("T_CallableOrType", bound=Callable[..., Any])
BINARY_MAGIC_METHODS = ...

class ForwardRefPolicy(Enum):
    ERROR = ...
    WARN = ...
    GUESS = ...

class TypeHintWarning(UserWarning): ...

class _TypeCheckMemo:
    __slots__ = ...
    def __init__(self, globals: dict[str, Any], locals: dict[str, Any]) -> None: ...

class _CallMemo(_TypeCheckMemo):
    __slots__ = ...
    def __init__(
        self,
        func: Callable,
        frame_locals: dict[str, Any] | None = ...,
        args: tuple = ...,
        kwargs: dict[str, Any] = ...,
        forward_refs_policy=...,
    ) -> None: ...

def resolve_forwardref(maybe_ref, memo: _TypeCheckMemo): ...
def get_type_name(type_): ...
def find_function(frame) -> Callable | None: ...
def qualified_name(obj) -> str: ...
def function_name(func: Callable) -> str: ...
def check_callable(
    argname: str, value, expected_type, memo: _TypeCheckMemo
) -> None: ...
def check_dict(argname: str, value, expected_type, memo: _TypeCheckMemo) -> None: ...
def check_typed_dict(
    argname: str, value, expected_type, memo: _TypeCheckMemo
) -> None: ...
def check_list(argname: str, value, expected_type, memo: _TypeCheckMemo) -> None: ...
def check_sequence(
    argname: str, value, expected_type, memo: _TypeCheckMemo
) -> None: ...
def check_set(argname: str, value, expected_type, memo: _TypeCheckMemo) -> None: ...
def check_tuple(argname: str, value, expected_type, memo: _TypeCheckMemo) -> None: ...
def check_union(argname: str, value, expected_type, memo: _TypeCheckMemo) -> None: ...
def check_class(argname: str, value, expected_type, memo: _TypeCheckMemo) -> None: ...
def check_typevar(
    argname: str,
    value,
    typevar: TypeVar,
    memo: _TypeCheckMemo,
    subclass_check: bool = ...,
) -> None: ...
def check_literal(argname: str, value, expected_type, memo: _TypeCheckMemo) -> None: ...
def check_number(argname: str, value, expected_type) -> None: ...
def check_io(argname: str, value, expected_type) -> None: ...
def check_protocol(argname: str, value, expected_type) -> None: ...

origin_type_checkers = ...
_subclass_check_unions = ...
if Literal is not None: ...
generator_origin_types = ...
asyncgen_origin_types = ...
if AsyncGenerator is not None: ...
if hasattr(collections.abc, "AsyncGenerator"): ...

def check_type(
    argname: str,
    value,
    expected_type,
    memo: _TypeCheckMemo | None = ...,
    *,
    globals: dict[str, Any] | None = ...,
    locals: dict[str, Any] | None = ...,
) -> None: ...
def check_return_type(retval, memo: _CallMemo | None = ...) -> bool: ...
def check_argument_types(memo: _CallMemo | None = ...) -> bool: ...

class TypeCheckedGenerator:
    def __init__(self, wrapped: Generator, memo: _CallMemo) -> None: ...
    def __iter__(self) -> Self: ...
    def __next__(self): ...
    def __getattr__(self, name: str) -> Any: ...
    def throw(self, *args): ...
    def close(self) -> None: ...
    def send(self, obj): ...

class TypeCheckedAsyncGenerator:
    def __init__(self, wrapped: AsyncGenerator, memo: _CallMemo) -> None: ...
    def __aiter__(self) -> Self: ...
    def __anext__(self) -> CoroutineType[Any, Any, Any]: ...
    def __getattr__(self, name: str) -> Any: ...
    def athrow(self, *args): ...
    def aclose(self): ...
    async def asend(self, obj): ...

@overload
def typechecked(
    *, always: bool = ...
) -> Callable[[T_CallableOrType], T_CallableOrType]: ...
@overload
def typechecked(func: T_CallableOrType, *, always: bool = ...) -> T_CallableOrType: ...
def typechecked(
    func=..., *, always=..., _localns: dict[str, Any] | None = ...
) -> (
    partial[Callable[[T_CallableOrType], T_CallableOrType]] | type[object] | _Wrapped
): ...

class TypeWarning(UserWarning):
    __slots__ = ...
    def __init__(
        self,
        memo: _CallMemo | None,
        event: str,
        frame,
        exception: str | TypeError,
    ) -> None: ...
    @property
    def stack(self) -> StackSummary: ...
    def print_stack(self, file: TextIO = ..., limit: int = ...) -> None: ...

class TypeChecker:
    def __init__(
        self,
        packages: str | Sequence[str],
        *,
        all_threads: bool = ...,
        forward_refs_policy: ForwardRefPolicy = ...,
    ) -> None: ...
    @property
    def active(self) -> bool: ...
    def should_check_type(self, func: Callable) -> bool: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
    def __call__(self, frame, event: str, arg) -> None: ...
