from typing import Any

def softmax(x: Any, axis: int = ...) -> Any: ...
def log_softmax(x: Any, axis: int = ...) -> Any: ...
def sigmoid(x: Any) -> Any: ...
def log_sigmoid(x: Any) -> Any: ...
def silu(x: Any) -> Any: ...
def relu(x: Any) -> Any: ...
def gelu(x: Any, approximate: bool = ...) -> Any: ...
def swish(x: Any) -> Any: ...
def elu(x: Any, alpha: float = ...) -> Any: ...
def celu(x: Any, alpha: float = ...) -> Any: ...
def selu(x: Any) -> Any: ...
def leaky_relu(x: Any, negative_slope: float = ...) -> Any: ...
def hard_sigmoid(x: Any) -> Any: ...
def hard_silu(x: Any) -> Any: ...
def hard_swish(x: Any) -> Any: ...
def hard_tanh(x: Any) -> Any: ...
def relu6(x: Any) -> Any: ...
def soft_sign(x: Any) -> Any: ...
def softplus(x: Any) -> Any: ...
def one_hot(x: Any, num_classes: int, *args: Any, **kwargs: Any) -> Any: ...
def logsumexp(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def standardize(x: Any, *args: Any, **kwargs: Any) -> Any: ...
