from typing import Any

def orthogonal(scale: float = ..., column_axis: int = ...) -> Any: ...
def zeros(key: Any, shape: Any, dtype: Any = ...) -> Any: ...
def ones(key: Any, shape: Any, dtype: Any = ...) -> Any: ...
def constant(value: Any, dtype: Any = ...) -> Any: ...
def normal(stddev: float = ..., dtype: Any = ...) -> Any: ...
def glorot_uniform(*args: Any, **kwargs: Any) -> Any: ...
def he_normal(*args: Any, **kwargs: Any) -> Any: ...
