AUTOTUNER_DATA_PATH = ...

def do_bench_triton(
    fn,
    warmup=...,
    rep=...,
    grad_to_none=...,
    quantiles=...,
    fast_flush=...,
    return_mode=...,
):  # -> list[Any] | Any:
    ...

BEST_CONFIGS = ...

def get_arg_key(a):  # -> tuple[dtype, Size, tuple[int, ...]] | tuple[Any]:
    ...
def get_args_key(
    args,
):  # -> tuple[dtype, Size, tuple[int, ...]] | tuple[Any] | tuple[()]:
    ...
def do_bench_basic(fn, rep): ...
def do_bench(fn, args, config, best_time=...):  # -> float | list[Any] | Any:
    ...
def get_best_config_by_key(key):  # -> None:
    ...
def get_best_config_fn(fn, args, configs):  # -> None:
    ...
