import torch

logger = ...
AUTOTUNER_ENABLE = ...

def safe_int_mm(input: torch.Tensor, mat2: torch.Tensor) -> torch.Tensor: ...
def int_matmul(a: torch.Tensor, b: torch.Tensor) -> torch.Tensor: ...
def int_scaled_matmul(
    a: torch.Tensor, b: torch.Tensor, scales1: torch.Tensor
) -> torch.Tensor: ...
