import dataclasses

from jax import lax as lax
from jax._src.lib import cuda_versions as cuda_versions
from jax.experimental.mosaic.gpu import profiler as profiler

@dataclasses.dataclass(frozen=True)
class TuningConfig:
    block_q: int
    block_kv: int
    max_concurrent_steps: int
    use_schedule_barrier: bool = ...
    causal: bool = ...
    compute_wgs_bwd: int = ...
    block_q_dkv: int | None = ...
    block_kv_dkv: int | None = ...
    block_q_dq: int | None = ...
    block_kv_dq: int | None = ...
    def __post_init__(self) -> None: ...
    @property
    def has_backward_blocks(self) -> bool: ...

def attention(q, k, v, config: TuningConfig, save_residuals: bool = False): ...
def attention_with_pipeline_emitter(
    q,
    k,
    v,
    config: TuningConfig,
    save_residuals: bool = False,
): ...
def attention_reference(
    q,
    k,
    v,
    causal: bool = False,
    save_residuals: bool = False,
): ...
def main(unused_argv) -> None: ...
