import torch

maskbits = ...
unpack_mask = ...
numbits = ...
shifts = ...

def abs_lsh(data, shift): ...
def abs_rsh(data, shift): ...
def pack_cpu(
    data: torch.Tensor, elem_size: int, dim: int | None = ...
) -> list[torch.Tensor]: ...
def unpack_cpu(
    data: list[torch.Tensor], elem_size: int, dim: int | None = ...
) -> torch.Tensor: ...
def pack(
    data: torch.Tensor, elem_size: int, dim: int | None = ...
) -> list[torch.Tensor]: ...
def unpack(
    data: list[torch.Tensor], elem_size: int, dim: int | None = ...
) -> torch.Tensor: ...
