from collections.abc import Sequence
from typing import TypeVar

import enum

"""
This type stub file was generated by pyright.
"""
T = TypeVar("T", bound=enum.Enum)

class StrEnumMeta(enum.EnumMeta):
    auto = enum.auto
    def from_str(cls: type[T], member: str) -> T: ...

class StrEnum(enum.Enum, metaclass=StrEnumMeta): ...

def sequence_to_str(seq: Sequence, separate_last: str = ...) -> str: ...
