from typing import BinaryIO

import pathlib

from PIL import ImageDraw

import torch

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "_Image_fromarray",
    "draw_bounding_boxes",
    "draw_keypoints",
    "draw_segmentation_masks",
    "flow_to_image",
    "make_grid",
    "save_image",
]

@torch.no_grad()
def make_grid(
    tensor: torch.Tensor | list[torch.Tensor],
    nrow: int = ...,
    padding: int = ...,
    normalize: bool = ...,
    value_range: tuple[int, int] | None = ...,
    scale_each: bool = ...,
    pad_value: float = ...,
) -> torch.Tensor: ...

class _ImageDrawTV(ImageDraw.ImageDraw):
    def oriented_rectangle(self, xy, fill=..., outline=..., width=...): ...
    def dashed_line(
        self, xy, fill=..., width=..., joint=..., dash_length=..., space_length=...
    ): ...

@torch.no_grad()
def save_image(
    tensor: torch.Tensor | list[torch.Tensor],
    fp: str | pathlib.Path | BinaryIO,
    format: str | None = ...,
    **kwargs,
) -> None: ...
@torch.no_grad()
def draw_bounding_boxes(
    image: torch.Tensor,
    boxes: torch.Tensor,
    labels: list[str] | None = ...,
    colors: list[str | tuple[int, int, int]] | str | tuple[int, int, int] | None = ...,
    fill: bool | None = ...,
    width: int = ...,
    font: str | None = ...,
    font_size: int | None = ...,
    label_colors: list[str | tuple[int, int, int]]
    | str
    | tuple[int, int, int]
    | None = ...,
    fill_labels: bool = ...,
) -> torch.Tensor: ...
@torch.no_grad()
def draw_segmentation_masks(
    image: torch.Tensor,
    masks: torch.Tensor,
    alpha: float = ...,
    colors: list[str | tuple[int, int, int]] | str | tuple[int, int, int] | None = ...,
) -> torch.Tensor: ...
@torch.no_grad()
def draw_keypoints(
    image: torch.Tensor,
    keypoints: torch.Tensor,
    connectivity: list[tuple[int, int]] | None = ...,
    colors: str | tuple[int, int, int] | None = ...,
    radius: int = ...,
    width: int = ...,
    visibility: torch.Tensor | None = ...,
) -> torch.Tensor: ...
@torch.no_grad()
def flow_to_image(flow: torch.Tensor) -> torch.Tensor: ...
