from typing import Any

from torch import Tensor, nn

"""
This type stub file was generated by pyright.
"""

class _SimpleSegmentationModel(nn.Module):
    __constants__ = ...
    def __init__(
        self,
        backbone: nn.Module,
        classifier: nn.Module,
        aux_classifier: nn.Module | None = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> dict[str, Tensor]: ...
    def __call__(self, *args: Any, **kwargs: Any) -> dict[str, Tensor]: ...
