from collections.abc import Sequence
from typing import Any

from torch import nn

import torch

from ._utils import _SimpleSegmentationModel
from .._api import WeightsEnum, register_model
from .._utils import handle_legacy_interface
from ..mobilenetv3 import MobileNet_V3_Large_Weights
from ..resnet import ResNet50_Weights, ResNet101_Weights

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "DeepLabV3",
    "DeepLabV3_MobileNet_V3_Large_Weights",
    "DeepLabV3_ResNet50_Weights",
    "DeepLabV3_ResNet101_Weights",
    "deeplabv3_mobilenet_v3_large",
    "deeplabv3_resnet50",
    "deeplabv3_resnet101",
]

class DeepLabV3(_SimpleSegmentationModel): ...

class DeepLabHead(nn.Sequential):
    def __init__(
        self, in_channels: int, num_classes: int, atrous_rates: Sequence[int] = ...
    ) -> None: ...

class ASPPConv(nn.Sequential):
    def __init__(self, in_channels: int, out_channels: int, dilation: int) -> None: ...

class ASPPPooling(nn.Sequential):
    def __init__(self, in_channels: int, out_channels: int) -> None: ...
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...

class ASPP(nn.Module):
    def __init__(
        self, in_channels: int, atrous_rates: Sequence[int], out_channels: int = ...
    ) -> None: ...
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...

_COMMON_META = ...

class DeepLabV3_ResNet50_Weights(WeightsEnum):
    COCO_WITH_VOC_LABELS_V1 = ...
    DEFAULT = ...

class DeepLabV3_ResNet101_Weights(WeightsEnum):
    COCO_WITH_VOC_LABELS_V1 = ...
    DEFAULT = ...

class DeepLabV3_MobileNet_V3_Large_Weights(WeightsEnum):
    COCO_WITH_VOC_LABELS_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(
    weights=("pretrained", DeepLabV3_ResNet50_Weights.COCO_WITH_VOC_LABELS_V1),
    weights_backbone=("pretrained_backbone", ResNet50_Weights.IMAGENET1K_V1),
)
def deeplabv3_resnet50(
    *,
    weights: DeepLabV3_ResNet50_Weights | None = ...,
    progress: bool = ...,
    num_classes: int | None = ...,
    aux_loss: bool | None = ...,
    weights_backbone: ResNet50_Weights | None = ...,
    **kwargs: Any,
) -> DeepLabV3: ...
@register_model()
@handle_legacy_interface(
    weights=("pretrained", DeepLabV3_ResNet101_Weights.COCO_WITH_VOC_LABELS_V1),
    weights_backbone=("pretrained_backbone", ResNet101_Weights.IMAGENET1K_V1),
)
def deeplabv3_resnet101(
    *,
    weights: DeepLabV3_ResNet101_Weights | None = ...,
    progress: bool = ...,
    num_classes: int | None = ...,
    aux_loss: bool | None = ...,
    weights_backbone: ResNet101_Weights | None = ...,
    **kwargs: Any,
) -> DeepLabV3: ...
@register_model()
@handle_legacy_interface(
    weights=(
        "pretrained",
        DeepLabV3_MobileNet_V3_Large_Weights.COCO_WITH_VOC_LABELS_V1,
    ),
    weights_backbone=("pretrained_backbone", MobileNet_V3_Large_Weights.IMAGENET1K_V1),
)
def deeplabv3_mobilenet_v3_large(
    *,
    weights: DeepLabV3_MobileNet_V3_Large_Weights | None = ...,
    progress: bool = ...,
    num_classes: int | None = ...,
    aux_loss: bool | None = ...,
    weights_backbone: MobileNet_V3_Large_Weights | None = ...,
    **kwargs: Any,
) -> DeepLabV3: ...
