from typing import Any

from torch import nn

from ._utils import _SimpleSegmentationModel
from .._api import WeightsEnum, register_model
from .._utils import handle_legacy_interface
from ..resnet import ResNet50_Weights, ResNet101_Weights

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "FCN",
    "FCN_ResNet50_Weights",
    "FCN_ResNet101_Weights",
    "fcn_resnet50",
    "fcn_resnet101",
]

class FCN(_SimpleSegmentationModel): ...

class FCNHead(nn.Sequential):
    def __init__(self, in_channels: int, channels: int) -> None: ...

_COMMON_META = ...

class FCN_ResNet50_Weights(WeightsEnum):
    COCO_WITH_VOC_LABELS_V1 = ...
    DEFAULT = ...

class FCN_ResNet101_Weights(WeightsEnum):
    COCO_WITH_VOC_LABELS_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(
    weights=("pretrained", FCN_ResNet50_Weights.COCO_WITH_VOC_LABELS_V1),
    weights_backbone=("pretrained_backbone", ResNet50_Weights.IMAGENET1K_V1),
)
def fcn_resnet50(
    *,
    weights: FCN_ResNet50_Weights | None = ...,
    progress: bool = ...,
    num_classes: int | None = ...,
    aux_loss: bool | None = ...,
    weights_backbone: ResNet50_Weights | None = ...,
    **kwargs: Any,
) -> FCN: ...
@register_model()
@handle_legacy_interface(
    weights=("pretrained", FCN_ResNet101_Weights.COCO_WITH_VOC_LABELS_V1),
    weights_backbone=("pretrained_backbone", ResNet101_Weights.IMAGENET1K_V1),
)
def fcn_resnet101(
    *,
    weights: FCN_ResNet101_Weights | None = ...,
    progress: bool = ...,
    num_classes: int | None = ...,
    aux_loss: bool | None = ...,
    weights_backbone: ResNet101_Weights | None = ...,
    **kwargs: Any,
) -> FCN: ...
