from typing import Any

from torch import Tensor, nn

from .._api import WeightsEnum, register_model
from .._utils import handle_legacy_interface
from ..mobilenetv3 import MobileNet_V3_Large_Weights

"""
This type stub file was generated by pyright.
"""
__all__ = ["LRASPP", "LRASPP_MobileNet_V3_Large_Weights", "lraspp_mobilenet_v3_large"]

class LRASPP(nn.Module):
    def __init__(
        self,
        backbone: nn.Module,
        low_channels: int,
        high_channels: int,
        num_classes: int,
        inter_channels: int = ...,
    ) -> None: ...
    def forward(self, input: Tensor) -> dict[str, Tensor]: ...

class LRASPPHead(nn.Module):
    def __init__(
        self,
        low_channels: int,
        high_channels: int,
        num_classes: int,
        inter_channels: int,
    ) -> None: ...
    def forward(self, input: dict[str, Tensor]) -> Tensor: ...

class LRASPP_MobileNet_V3_Large_Weights(WeightsEnum):
    COCO_WITH_VOC_LABELS_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(
    weights=("pretrained", LRASPP_MobileNet_V3_Large_Weights.COCO_WITH_VOC_LABELS_V1),
    weights_backbone=("pretrained_backbone", MobileNet_V3_Large_Weights.IMAGENET1K_V1),
)
def lraspp_mobilenet_v3_large(
    *,
    weights: LRASPP_MobileNet_V3_Large_Weights | None = ...,
    progress: bool = ...,
    num_classes: int | None = ...,
    weights_backbone: MobileNet_V3_Large_Weights | None = ...,
    **kwargs: Any,
) -> LRASPP: ...
