from torch import nn

import torch

SCORES_MIN = ...
SCORES_MAX = ...

def percentile(t, q): ...

class GetSubnet(torch.autograd.Function):
    @staticmethod
    def forward(ctx, scores, zeros, ones, sparsity):  # -> Tensor:
        ...
    @staticmethod
    def backward(ctx, g):  # -> tuple[Any, None, None, None]:
        ...

class ApplyMask(torch.autograd.Function):
    @staticmethod
    def forward(ctx, weight, scores): ...
    @staticmethod
    def backward(ctx, grad_output):  # -> tuple[Any | None, Any | None]:
        ...

class SupermaskLinear(nn.Linear):
    def __init__(
        self, sparsity_level, blocksize, fixed_mask, fixed_weight, *args, **kwargs
    ) -> None: ...
    def get_mask(self):  # -> Any | Tensor | None:
        ...
    def forward(self, x):  # -> Tensor:
        ...
    @classmethod
    def from_linear(
        cls, linear, sparsity_level=..., blocksize=...
    ):  # -> SupermaskLinear:
        ...
    @classmethod
    def to_linear(cls, supermask_linear):  # -> Linear:
        ...
