import torch

logger = ...
aten = ...
_AQT_QLINEAR_DISPATCH_TABLE = ...

def register_aqt_quantized_linear_dispatch(dispatch_condition, impl):  # -> None:
    ...
def deregister_aqt_quantized_linear_dispatch(dispatch_condition):  # -> None:
    ...

class QuantizedLinearNotImplementedError(NotImplementedError): ...

implements = ...

@implements([torch.nn.functional.linear, aten.linear.default])
def _(func, types, args, kwargs):  # -> Tensor:
    ...
@implements(torch.nn.functional.embedding)
def _(func, types, args, kwargs):  # -> Tensor:
    ...
@implements(aten.addmm.default)
def _(func, types, args, kwargs): ...
@implements(aten.mm.default)
def _(func, types, args, kwargs): ...
@implements([aten.detach.default, aten.alias.default])
def _(func, types, args, kwargs):  # -> tuple[Any, ...] | Any:
    ...
@implements(aten.clone.default)
def _(func, types, args, kwargs):  # -> tuple[Any, ...] | Any:
    ...
@implements(aten.copy_.default)
def _(func, types, args, kwargs):  # -> tuple[Any, ...] | Any:
    ...
@implements(aten._to_copy.default)
def _(func, types, args, kwargs):  # -> tuple[Any, ...] | Any:
    ...
@implements(aten.copy_.default)
def _(func, types, args, kwargs):  # -> None:
    ...
@implements(aten.t.default)
def _(func, types, args, kwargs):  # -> tuple[Any, ...] | Any:
    ...
@implements(aten.slice.Tensor)
def _(func, types, args, kwargs):  # -> tuple[Any, ...] | Any:
    ...
@implements(aten.index.Tensor)
def _(func, types, args, kwargs):  # -> tuple[Any, ...] | Any:
    ...
@implements(aten.select.int)
def _(func, types, args, kwargs):  # -> tuple[Any, ...] | Any:
    ...
@implements(aten.view.default)
def _(func, types, args, kwargs): ...
