from _typeshed import Incomplete

def ndim_at_least(x, num_dims): ...
def arbitrary_mergeable_leaf(min_num_dims, args, kwargs): ...
def merge_leading_dims(x, num_dims): ...
def split_leading_dim(x, to_dim): ...

class BatchApply:
    num_dims: Incomplete
    def __init__(self, f, num_dims: int = 2) -> None: ...
    def __call__(self, *args, **kwargs): ...
