from typing import Any

import dataclasses

from _typeshed import Incomplete
from flax.linen import (
    initializers as initializers,
    module as module,
)
from jax import (
    lax,
    numpy as jnp,
)
from jax._src import core, dtypes
from jax.typing import DTypeLike as DTypeLike

type DType = Any
CAN_USE_EARRAY: bool
OVERWRITE_WITH_GRADIENT: str

class Fp8MetaTyRules:
    @staticmethod
    def physical_element_aval(dtype) -> core.ShapedArray: ...
    @staticmethod
    def replicate_trailing_dims(ctx, val, aval): ...
    @staticmethod
    def logical_sharding(aval, phys_sharding): ...
    @staticmethod
    def physical_sharding(aval, sharding): ...
    @staticmethod
    def convert_from(fp8_meta_dtype, other_dtype) -> bool: ...
    @staticmethod
    def convert_to(other_dtype, fp8_meta_dtype) -> bool: ...
    @staticmethod
    def add(dt, x, y): ...
    @staticmethod
    def zero(dt): ...
    @staticmethod
    def tangent_dtype(dtype): ...
    @staticmethod
    def full(shape, fill_value, dtype): ...
    @staticmethod
    def global_sharded_result_handler(aval, out_sharding, committed): ...

class fp8_meta_dtype(dtypes.extended): ...

@dataclasses.dataclass(frozen=True)
class fp8_meta_dtype_wrapper(dtypes.ExtendedDType):
    float_dtype: dtypes.DType
    type: type = ...
    name = ...

fm32: Incomplete
fp32_max_grad: Incomplete

def get_fp8_max(fp8_dtype, out_dtype): ...
def quantize(x, q_dtype, scale, compute_dtype): ...
def dequantize(x, dq_dtype, scale): ...
def qdq(x, q_dtype, scale, compute_dtype): ...
def compute_scale(amax, scale, fp8_max, margin: int = 0): ...
def compute_amax_history(x, amax_history): ...
def update_fp8_meta(x, q_dtype, scale, amax_history): ...
def quantize_dequantize_update(x, q_dtype, scale, amax_history, compute_dtype): ...
def dot_general_transpose_lhs(
    g,
    x,
    y,
    *,
    dimension_numbers,
    precision,
    preferred_element_type: DTypeLike | None,
    swap_ans: bool = False,
): ...
def dot_general_transpose_rhs(
    g,
    x,
    y,
    *,
    dimension_numbers,
    precision,
    preferred_element_type: DTypeLike | None,
): ...
def in_qdq(compute_dtype, q_dtype, inp, scale, amax_history): ...
def in_qdq_fwd(compute_dtype, q_dtype, inp, scale, amax_history): ...
def in_qdq_bwd(compute_dtype, q_dtype, res, g): ...
def out_qdq(compute_dtype, q_dtype, out, scale, amax_history): ...
def out_qdq_fwd(compute_dtype, q_dtype, out, scale, amax_history): ...
def out_qdq_bwd(compute_dtype, q_dtype, res, g): ...
def in_q(compute_dtype, q_dtype, inp, scale, amax_history): ...
def in_q_fwd(compute_dtype, q_dtype, inp, scale, amax_history): ...
def in_q_bwd(compute_dtype, q_dtype, res, _): ...
def out_dq(dq_type, lhs_scale, rhs_scale, out): ...
def out_dq_fwd(dq_type, lhs_scale, rhs_scale, out): ...
def out_dq_bwd(dq_type, _, g): ...
def quantized_dot(
    lhs,
    q_lhs,
    lhs_scale,
    rhs,
    q_rhs,
    rhs_scale,
    out_grad_scale,
    out_grad_amax_history,
    dimension_numbers,
    preferred_element_type=None,
): ...
def quantized_dot_fwd(
    lhs,
    q_lhs,
    lhs_scale,
    rhs,
    q_rhs,
    rhs_scale,
    out_grad_scale,
    out_grad_amax_history,
    dimension_numbers,
    preferred_element_type,
): ...
def quantized_dot_bwd(dimension_numbers, preferred_element_type, res, g): ...
def fp8_scaled_dot_general(
    lhs,
    rhs,
    dimension_numbers,
    precision=None,
    preferred_element_type=None,
    *,
    lhs_scale=None,
    rhs_scale=None,
    grad_scale=None,
    lhs_amax_history=None,
    rhs_amax_history=None,
    grad_amax_history=None,
    quantize_compute_type=...,
): ...
def dot_general_with_precision(
    lhs,
    rhs,
    dimension_numbers,
    precision=None,
    preferred_element_type=None,
): ...
@dot_general_with_precision.defjvp
def dot_general_with_precision_jvp(
    dimension_numbers,
    precision,
    preferred_element_type,
    primals,
    tangents,
): ...

class Fp8DotGeneralBase(module.Module):
    amax_history_length: int = ...
    e4m3_dtype: DType = ...
    e5m2_dtype: DType = ...
    input_amax_history = ...
    kernel_amax_history = ...
    output_grad_amax_history = ...
    input_scale = ...
    kernel_scale = ...
    output_grad_scale = ...
    def setup(self) -> None: ...

class Fp8DotGeneralOp(Fp8DotGeneralBase):
    def __post_init__(self) -> None: ...
    def __call__(self, *args, **kwargs): ...

class Fp8DirectDotGeneralOp(Fp8DotGeneralBase):
    def __call__(self, *args, **kwargs): ...

class NANOOFp8DotGeneralOp(Fp8DotGeneralOp):
    e4m3_dtype: DType = ...
    e5m2_dtype: DType = ...

class Fp8Einsum(Fp8DotGeneralBase):
    def __call__(
        self,
        eqn,
        lhs: jnp.ndarray,
        rhs: jnp.ndarray,
        precision: lax.Precision | None = None,
        preferred_element_type: DTypeLike | None = None,
    ) -> jnp.ndarray: ...

Fp8DotGeneral = Fp8DirectDotGeneralOp
