from collections.abc import Sequence
from typing import Any, Protocol

from _typeshed import Incomplete
from flax.core import meta as meta
from flax.linen import (
    initializers as initializers,
    module as module,
)
from flax.linen.dtypes import promote_dtype as promote_dtype
from flax.linen.module import (
    Module as Module,
    compact as compact,
)
from flax.typing import (
    Array as Array,
    ConvGeneralDilatedT as ConvGeneralDilatedT,
    DotGeneralT as DotGeneralT,
    Dtype as Dtype,
    Initializer as Initializer,
    LaxPadding as LaxPadding,
    PaddingLike as PaddingLike,
    PrecisionLike as PrecisionLike,
    Shape as Shape,
)

import jax

class PromoteDtypeFn(Protocol):
    def __call__(
        self,
        *args: jax.Array | None,
        dtype: Any = None,
        inexact: bool = True,
    ) -> list[jax.Array | None]: ...

default_kernel_init: Incomplete

class DenseGeneral(Module):
    features: int | Sequence[int]
    axis: int | Sequence[int] = ...
    batch_dims: Sequence[int] = ...
    use_bias: bool = ...
    dtype: Dtype | None = ...
    param_dtype: Dtype = ...
    kernel_init: Initializer = ...
    bias_init: Initializer = ...
    precision: PrecisionLike = ...
    promote_dtype: PromoteDtypeFn = ...
    dot_general: DotGeneralT | None = ...
    dot_general_cls: Any = ...
    @compact
    def __call__(self, inputs: Array) -> Array: ...

class Dense(Module):
    features: int
    use_bias: bool = ...
    dtype: Dtype | None = ...
    param_dtype: Dtype = ...
    precision: PrecisionLike = ...
    kernel_init: Initializer = ...
    bias_init: Initializer = ...
    promote_dtype: PromoteDtypeFn = ...
    dot_general: DotGeneralT | None = ...
    dot_general_cls: Any = ...
    @compact
    def __call__(self, inputs: Array) -> Array: ...

class Einsum(Module):
    shape: Shape
    einsum_str: str | None = ...
    use_bias: bool = ...
    dtype: Dtype | None = ...
    param_dtype: Dtype = ...
    precision: PrecisionLike = ...
    kernel_init: Initializer = ...
    bias_init: Initializer = ...
    promote_dtype: PromoteDtypeFn = ...
    preferred_element_type: Dtype | None = ...
    @compact
    def __call__(self, inputs: Array, einsum_str: str | None = None) -> Array: ...

def canonicalize_padding(padding: PaddingLike, rank: int) -> LaxPadding: ...

class _Conv(Module):
    features: int
    kernel_size: int | Sequence[int]
    strides: int | Sequence[int] | None = ...
    padding: PaddingLike = ...
    input_dilation: int | Sequence[int] | None = ...
    kernel_dilation: int | Sequence[int] | None = ...
    feature_group_count: int = ...
    use_bias: bool = ...
    mask: Array | None = ...
    dtype: Dtype | None = ...
    param_dtype: Dtype = ...
    precision: PrecisionLike = ...
    kernel_init: Initializer = ...
    bias_init: Initializer = ...
    promote_dtype: PromoteDtypeFn = ...
    conv_general_dilated: ConvGeneralDilatedT | None = ...
    conv_general_dilated_cls: Any = ...
    @property
    def shared_weights(self) -> bool: ...
    @compact
    def __call__(self, inputs: Array) -> Array: ...

class Conv(_Conv):
    @property
    def shared_weights(self) -> bool: ...

class ConvLocal(_Conv):
    @property
    def shared_weights(self) -> bool: ...

class ConvTranspose(Module):
    features: int
    kernel_size: int | Sequence[int]
    strides: Sequence[int] | None = ...
    padding: PaddingLike = ...
    kernel_dilation: Sequence[int] | None = ...
    use_bias: bool = ...
    mask: Array | None = ...
    dtype: Dtype | None = ...
    param_dtype: Dtype = ...
    precision: PrecisionLike = ...
    kernel_init: Initializer = ...
    bias_init: Initializer = ...
    transpose_kernel: bool = ...
    promote_dtype: PromoteDtypeFn = ...
    preferred_element_type: Dtype | None = ...
    @compact
    def __call__(self, inputs: Array) -> Array: ...

default_embed_init: Incomplete

class Embed(Module):
    num_embeddings: int
    features: int
    dtype: Dtype | None = ...
    param_dtype: Dtype = ...
    embedding_init: Initializer = ...
    promote_dtype: PromoteDtypeFn = ...
    embedding = ...
    def setup(self) -> None: ...
    def __call__(self, inputs: Array) -> Array: ...
    def attend(self, query: Array) -> Array: ...
