from collections.abc import Iterable
from typing import Any

from _typeshed import Incomplete
from flax.linen import (
    dtypes as dtypes,
    module as module,
    transforms as transforms,
)
from flax.typing import (
    Array as Array,
    Axes as Axes,
    Dtype as Dtype,
    Initializer as Initializer,
)

import jax

field: Incomplete
canonicalize_dtype = dtypes.canonicalize_dtype
compact = module.compact
Module = module.Module
merge_param = module.merge_param
map_variables = transforms.map_variables

class BatchNorm(Module):
    use_running_average: bool | None = ...
    axis: int = ...
    momentum: float = ...
    epsilon: float = ...
    dtype: Dtype | None = ...
    param_dtype: Dtype = ...
    use_bias: bool = ...
    use_scale: bool = ...
    bias_init: Initializer = ...
    scale_init: Initializer = ...
    axis_name: str | None = ...
    axis_index_groups: Any = ...
    use_fast_variance: bool = ...
    force_float32_reductions: bool = ...
    @compact
    def __call__(
        self,
        x,
        use_running_average: bool | None = None,
        *,
        mask: jax.Array | None = None,
    ) -> jax.Array: ...

class LayerNorm(Module):
    epsilon: float = ...
    dtype: Dtype | None = ...
    param_dtype: Dtype = ...
    use_bias: bool = ...
    use_scale: bool = ...
    bias_init: Initializer = ...
    scale_init: Initializer = ...
    reduction_axes: Axes = ...
    feature_axes: Axes = ...
    axis_name: str | None = ...
    axis_index_groups: Any = ...
    use_fast_variance: bool = ...
    force_float32_reductions: bool = ...
    @compact
    def __call__(self, x, *, mask: jax.Array | None = None) -> jax.Array: ...

class RMSNorm(Module):
    epsilon: float = ...
    dtype: Dtype | None = ...
    param_dtype: Dtype = ...
    use_scale: bool = ...
    scale_init: Initializer = ...
    reduction_axes: Axes = ...
    feature_axes: Axes = ...
    axis_name: str | None = ...
    axis_index_groups: Any = ...
    use_fast_variance: bool = ...
    force_float32_reductions: bool = ...
    @compact
    def __call__(self, x, *, mask: jax.Array | None = None) -> jax.Array: ...

class GroupNorm(Module):
    num_groups: int | None = ...
    group_size: int | None = ...
    epsilon: float = ...
    dtype: Dtype | None = ...
    param_dtype: Dtype = ...
    use_bias: bool = ...
    use_scale: bool = ...
    bias_init: Initializer = ...
    scale_init: Initializer = ...
    reduction_axes: Axes | None = ...
    axis_name: str | None = ...
    axis_index_groups: Any = ...
    use_fast_variance: bool = ...
    force_float32_reductions: bool = ...
    @compact
    def __call__(self, x, *, mask: jax.Array | None = None) -> jax.Array: ...

class InstanceNorm(Module):
    epsilon: float = ...
    dtype: Dtype | None = ...
    param_dtype: Dtype = ...
    use_bias: bool = ...
    use_scale: bool = ...
    bias_init: Initializer = ...
    scale_init: Initializer = ...
    feature_axes: Axes = ...
    axis_name: str | None = ...
    axis_index_groups: Any = ...
    use_fast_variance: bool = ...
    force_float32_reductions: bool = ...
    @compact
    def __call__(self, x, *, mask: jax.Array | None = None) -> jax.Array: ...

class SpectralNorm(Module):
    layer_instance: Module
    n_steps: int = ...
    epsilon: float = ...
    dtype: Dtype | None = ...
    param_dtype: Dtype = ...
    error_on_non_matrix: bool = ...
    collection_name: str = ...
    @compact
    def __call__(self, *args, update_stats: bool, **kwargs): ...

class WeightNorm(Module):
    layer_instance: Module
    epsilon: float = ...
    dtype: Dtype | None = ...
    param_dtype: Dtype = ...
    use_scale: bool = ...
    scale_init: Initializer = ...
    feature_axes: Axes | None = ...
    variable_filter: Iterable | None = ...
    @compact
    def __call__(self, *args, **kwargs): ...
