def pool(inputs, init, reduce_fn, window_shape, strides, padding): ...
def avg_pool(
    inputs,
    window_shape,
    strides=None,
    padding: str = "VALID",
    count_include_pad: bool = True,
): ...
def max_pool(inputs, window_shape, strides=None, padding: str = "VALID"): ...
def min_pool(inputs, window_shape, strides=None, padding: str = "VALID"): ...
