from collections.abc import (
    Callable as Callable,
    Mapping,
    Sequence,
)
from typing import Any, Protocol, TypeVar

from flax.core.frozen_dict import FrozenDict as FrozenDict
from flax.core.scope import (
    CollectionFilter as CollectionFilter,
    PRNGSequenceFilter as PRNGSequenceFilter,
)
from flax.linen import (
    initializers as initializers,
    transforms as transforms,
)
from flax.linen.activation import (
    sigmoid as sigmoid,
    tanh as tanh,
)
from flax.linen.dtypes import promote_dtype as promote_dtype
from flax.linen.linear import (
    Conv as Conv,
    Dense as Dense,
    default_kernel_init as default_kernel_init,
)
from flax.linen.module import (
    Module as Module,
    compact as compact,
    nowrap as nowrap,
)
from flax.typing import (
    Array as Array,
    Dtype as Dtype,
    Initializer as Initializer,
    InOutScanAxis as InOutScanAxis,
    PrecisionLike as PrecisionLike,
    PRNGKey as PRNGKey,
)

import jax

A = TypeVar("A")
type Carry = Any
type CarryHistory = Any
type Output = Any

class RNNCellBase(Module):
    @nowrap
    def initialize_carry(self, rng: PRNGKey, input_shape: tuple[int, ...]) -> Carry: ...
    @property
    def num_feature_axes(self) -> int: ...

class LSTMCell(RNNCellBase):
    features: int
    gate_fn: Callable[..., Any] = ...
    activation_fn: Callable[..., Any] = ...
    kernel_init: Initializer = ...
    recurrent_kernel_init: Initializer = ...
    bias_init: Initializer = ...
    dtype: Dtype | None = ...
    param_dtype: Dtype = ...
    carry_init: Initializer = ...
    @compact
    def __call__(self, carry, inputs): ...
    @nowrap
    def initialize_carry(
        self,
        rng: PRNGKey,
        input_shape: tuple[int, ...],
    ) -> tuple[Array, Array]: ...
    @property
    def num_feature_axes(self) -> int: ...

class DenseParams(Module):
    features: int
    use_bias: bool = ...
    param_dtype: Dtype = ...
    precision: PrecisionLike = ...
    kernel_init: Initializer = ...
    bias_init: Initializer = ...
    @compact
    def __call__(self, inputs: Array) -> tuple[Array, Array | None]: ...

class OptimizedLSTMCell(RNNCellBase):
    features: int
    gate_fn: Callable[..., Any] = ...
    activation_fn: Callable[..., Any] = ...
    kernel_init: Initializer = ...
    recurrent_kernel_init: Initializer = ...
    bias_init: Initializer = ...
    dtype: Dtype | None = ...
    param_dtype: Dtype = ...
    carry_init: Initializer = ...
    @compact
    def __call__(
        self,
        carry: tuple[Array, Array],
        inputs: Array,
    ) -> tuple[tuple[Array, Array], Array]: ...
    @nowrap
    def initialize_carry(
        self,
        rng: PRNGKey,
        input_shape: tuple[int, ...],
    ) -> tuple[Array, Array]: ...
    @property
    def num_feature_axes(self) -> int: ...

class SimpleCell(RNNCellBase):
    features: int
    activation_fn: Callable[..., Any] = ...
    kernel_init: Initializer = ...
    recurrent_kernel_init: Initializer = ...
    bias_init: Initializer = ...
    dtype: Dtype | None = ...
    param_dtype: Dtype = ...
    carry_init: Initializer = ...
    residual: bool = ...
    @compact
    def __call__(self, carry, inputs): ...
    @nowrap
    def initialize_carry(self, rng: PRNGKey, input_shape: tuple[int, ...]): ...
    @property
    def num_feature_axes(self) -> int: ...

class GRUCell(RNNCellBase):
    features: int
    gate_fn: Callable[..., Any] = ...
    activation_fn: Callable[..., Any] = ...
    kernel_init: Initializer = ...
    recurrent_kernel_init: Initializer = ...
    bias_init: Initializer = ...
    dtype: Dtype | None = ...
    param_dtype: Dtype = ...
    carry_init: Initializer = ...
    @compact
    def __call__(self, carry, inputs): ...
    @nowrap
    def initialize_carry(self, rng: PRNGKey, input_shape: tuple[int, ...]): ...
    @property
    def num_feature_axes(self) -> int: ...

class MGUCell(RNNCellBase):
    features: int
    gate_fn: Callable[..., Any] = ...
    activation_fn: Callable[..., Any] = ...
    kernel_init: Initializer = ...
    recurrent_kernel_init: Initializer = ...
    forget_bias_init: Initializer = ...
    activation_bias_init: Initializer = ...
    dtype: Dtype | None = ...
    param_dtype: Dtype = ...
    carry_init: Initializer = ...
    reset_gate: bool = ...
    @compact
    def __call__(self, carry, inputs): ...
    @nowrap
    def initialize_carry(self, rng: PRNGKey, input_shape: tuple[int, ...]): ...
    @property
    def num_feature_axes(self) -> int: ...

class ConvLSTMCell(RNNCellBase):
    features: int
    kernel_size: Sequence[int]
    strides: Sequence[int] | None = ...
    padding: str | Sequence[tuple[int, int]] = ...
    use_bias: bool = ...
    dtype: Dtype | None = ...
    param_dtype: Dtype = ...
    carry_init: Initializer = ...
    @compact
    def __call__(self, carry, inputs): ...
    @nowrap
    def initialize_carry(self, rng: PRNGKey, input_shape: tuple[int, ...]): ...
    @property
    def num_feature_axes(self) -> int: ...

class RNN(Module):
    cell: RNNCellBase
    time_major: bool = ...
    return_carry: bool = ...
    reverse: bool = ...
    keep_order: bool = ...
    unroll: int = ...
    variable_axes: Mapping[CollectionFilter, InOutScanAxis] = ...
    variable_broadcast: CollectionFilter = ...
    variable_carry: CollectionFilter = ...
    split_rngs: Mapping[PRNGSequenceFilter, bool] = ...
    def __call__(
        self,
        inputs: jax.Array,
        *,
        initial_carry: Carry | None = None,
        init_key: PRNGKey | None = None,
        seq_lengths: Array | None = None,
        return_carry: bool | None = None,
        time_major: bool | None = None,
        reverse: bool | None = None,
        keep_order: bool | None = None,
    ) -> Output | tuple[Carry, Output]: ...

def flip_sequences(
    inputs: Array,
    seq_lengths: Array | None,
    num_batch_dims: int,
    time_major: bool,
) -> Array: ...

class RNNBase(Protocol):
    def __call__(
        self,
        inputs: jax.Array,
        *,
        initial_carry: Carry | None = None,
        init_key: PRNGKey | None = None,
        seq_lengths: Array | None = None,
        return_carry: bool | None = None,
        time_major: bool | None = None,
        reverse: bool | None = None,
        keep_order: bool | None = None,
    ) -> Output | tuple[Carry, Output]: ...

class Bidirectional(Module):
    forward_rnn: RNNBase
    backward_rnn: RNNBase
    merge_fn: Callable[[Array, Array], Array] = ...
    time_major: bool = ...
    return_carry: bool = ...
    def __call__(
        self,
        inputs: jax.Array,
        *,
        initial_carry: Carry | None = None,
        init_key: PRNGKey | None = None,
        seq_lengths: Array | None = None,
        return_carry: bool | None = None,
        time_major: bool | None = None,
        reverse: bool | None = None,
        keep_order: bool | None = None,
    ) -> Output | tuple[Carry, Output]: ...
