from typing import Any

from fla.utils import checkpoint
from torch import Tensor, nn

import torch

@checkpoint
def flatten_diag_outer_product(x, y) -> Tensor: ...
@checkpoint
def flatten_diag_outer_product_off1(x, y) -> tuple[Tensor, Tensor]: ...
def is_power_of_2(n): ...

class HedgehogFeatureMap(nn.Module):
    def __init__(self, head_dim: int) -> HedgehogFeatureMap: ...
    def init_weights_(self) -> None: ...
    def forward(self, x: torch.Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class T2RFeatureMap(nn.Module):
    def __init__(
        self, head_dim: int, dot_dim: int = ..., bias: bool | None = ...
    ) -> T2RFeatureMap: ...
    def forward(self, x: torch.Tensor) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class DPFPFeatureMap(nn.Module):
    def __init__(self, head_dim: int, nu: int = ...) -> DPFPFeatureMap: ...
    def forward(self, x: torch.Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class HadamardFeatureMap(nn.Module):
    def __init__(self, head_dim: int) -> HadamardFeatureMap: ...
    def forward(self, x: torch.Tensor) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class LearnableOuterProductFeatureMap(nn.Module):
    def __init__(
        self, head_dim: int, feature_dim: int
    ) -> LearnableOuterProductFeatureMap: ...
    def forward(self, x: torch.Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class LearnablePolySketchNonNegativeFeatureMap(nn.Module):
    def __init__(
        self, head_dim: int, sketch_size: int | None = ..., degree: int | None = ...
    ) -> LearnablePolySketchNonNegativeFeatureMap: ...
    def forward(self, x: torch.Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class TaylorFeatureMap(nn.Module):
    def __init__(self, head_dim: int) -> TaylorFeatureMap: ...
    def forward(self, x: torch.Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class RebasedFeatureMap(nn.Module):
    def __init__(
        self,
        head_dim: int,
        use_gamma: bool | None = ...,
        use_beta: bool | None = ...,
        normalize: bool | None = ...,
    ) -> RebasedFeatureMap: ...
    def forward(self, x: torch.Tensor, flatten: bool | None = ...) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class ReLUFeatureMap(nn.Module):
    def __init__(self) -> ReLUFeatureMap: ...
    def forward(self, x: torch.Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class SquaredReLUFeatureMap(nn.Module):
    def __init__(self) -> SquaredReLUFeatureMap: ...
    def forward(self, x: torch.Tensor) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> None: ...

class GELUFeatureMap(nn.Module):
    def __init__(self) -> GELUFeatureMap: ...
    def forward(self, x: torch.Tensor) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> None: ...

class SwishFeatureMap(nn.Module):
    def __init__(self) -> SwishFeatureMap: ...
    def forward(self, x: torch.Tensor) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> None: ...

class SigmoidFeatureMap(nn.Module):
    def __init__(self) -> SigmoidFeatureMap: ...
    def forward(self, x: torch.Tensor) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> None: ...
