from collections.abc import Callable
from typing import Any

def map(f: Callable[..., Any], tree: Any, *rest: Any, **kwargs: Any) -> Any: ...
def leaves(tree: Any, *args: Any, **kwargs: Any) -> list[Any]: ...
