from abc import ABCMeta
from collections.abc import Callable, Sequence
from typing import ClassVar, Self

class _CacheLocator(metaclass=ABCMeta):
    def ensure_cache_path(self) -> None: ...
    def get_cache_path(self) -> str: ...
    # Numba's contract (caching.py): "Can return any picklable Python object".
    def get_source_stamp(self) -> object: ...
    def get_disambiguator(self) -> str: ...
    @classmethod
    def from_function(
        cls,
        py_func: Callable[..., object],
        py_file: str,
    ) -> Self | None: ...

class UserProvidedCacheLocator(_CacheLocator):
    _py_file: str
    def __init__(self, py_func: Callable[..., object], py_file: str) -> None: ...

class InTreeCacheLocator(_CacheLocator):
    _py_file: str
    def __init__(self, py_func: Callable[..., object], py_file: str) -> None: ...

class UserWideCacheLocator(_CacheLocator):
    _py_file: str
    def __init__(self, py_func: Callable[..., object], py_file: str) -> None: ...

class CacheImpl(metaclass=ABCMeta):
    _locator_classes: ClassVar[Sequence[type[_CacheLocator]]]
    def __init__(self, py_func: Callable[..., object]) -> None: ...
    @property
    def filename_base(self) -> str: ...
    @property
    def locator(self) -> _CacheLocator: ...

class CompileResultCacheImpl(CacheImpl): ...

class Cache:
    _impl_class: ClassVar[type[CacheImpl]]
    _impl: CacheImpl
    def __init__(self, py_func: Callable[..., object]) -> None: ...
    @property
    def cache_path(self) -> str: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def flush(self) -> None: ...

class FunctionCache(Cache): ...
