from transformers.configuration_utils import PretrainedConfig

class DeltaFormerConfig(PretrainedConfig):
    keys_to_ignore_at_inference = ...
    def __init__(
        self,
        hidden_size: int = ...,
        hidden_ratio: int | None = ...,
        intermediate_size: int | None = ...,
        num_hidden_layers: int = ...,
        num_heads: int = ...,
        num_kv_heads: int | None = ...,
        attn_mode: str = ...,
        hidden_act: str = ...,
        max_position_embeddings: int = ...,
        elementwise_affine: bool | None = ...,
        norm_eps: float = ...,
        qkv_bias: bool = ...,
        qk_norm: bool = ...,
        rope_theta: float = ...,
        rope_max_position_embeddings: int | None = ...,
        attn: dict | None = ...,
        use_cache: bool = ...,
        pad_token_id: int | None = ...,
        bos_token_id: int = ...,
        eos_token_id: int = ...,
        tie_word_embeddings: bool = ...,
        initializer_range: float = ...,
        fuse_norm: bool = ...,
        fuse_swiglu: bool = ...,
        fuse_cross_entropy: bool = ...,
        fuse_linear_cross_entropy: bool = ...,
        use_l2warp: bool = ...,
        vocab_size: int = ...,
        output_attentions: bool = ...,
        output_hidden_states: bool = ...,
        **kwargs,
    ) -> None: ...
