from collections.abc import Callable, Generator, Iterable, Sequence
from typing import Any, Protocol, TypeVar, overload

import dataclasses
import functools

from _typeshed import Incomplete
from jaxlib.mlir import ir
from jaxlib.mlir.dialects import gpu

import jax.experimental.mosaic.gpu as mgpu
import numpy as np

from . import utils as utils

T = TypeVar("T")
WARPGROUP_SIZE: Incomplete
WARP_SIZE: int
WARPS_IN_WARPGROUP: Incomplete
SMEM_BANKS: int
SMEM_BANK_BYTES: int
c = utils.c
ReductionKind: Incomplete
Tiling: Any

def enumerate_negative(elems: Sequence[T]) -> Iterable[tuple[int, T]]: ...

Replicated: Any

@dataclasses.dataclass(frozen=True)
class TiledLayoutImpl:
    tiling: Tiling
    warp_dims: tuple[int | Replicated, ...]
    lane_dims: tuple[int | Replicated, ...]
    vector_dim: int
    def __post_init__(self, _check_canonical: bool): ...
    @functools.cached_property
    def partitioned_warp_dims(self) -> tuple[int, ...]: ...
    @functools.cached_property
    def partitioned_lane_dims(self) -> tuple[int, ...]: ...
    def thread_idxs(self, shape: tuple[int, ...]) -> Iterable[tuple[ir.Value, ...]]: ...
    @property
    def base_tile_shape(self) -> tuple[int, ...]: ...
    @functools.cached_property
    def tiled_tiling_shape(self) -> tuple[int, ...]: ...
    @functools.cached_property
    def tiled_tiling_rank(self) -> int: ...
    @property
    def vector_length(self) -> int: ...
    def registers_element_type(self, t: ir.Type) -> ir.Type: ...
    def registers_shape(self, shape: tuple[int, ...]) -> tuple[int, ...]: ...
    def shape_from_registers_shape(self, shape: tuple[int, ...]) -> tuple[int, ...]: ...
    def lane_indices(self) -> tuple[ir.Value, ...]: ...
    def warp_indices(self) -> tuple[ir.Value, ...]: ...
    def remove_dimension(self, dim: int) -> TiledLayoutImpl: ...
    def reduce(self, axes: Sequence[int]) -> TiledLayoutImpl: ...
    def canonicalize(self) -> TiledLayoutImpl: ...

TiledLayout: Any
TiledLayout = TiledLayoutImpl

@dataclasses.dataclass(frozen=True)
class WGSplatFragLayout:
    shape: tuple[int, ...] = ...
    def can_broadcast_to(self, shape) -> bool: ...
    def registers_element_type(self, t: ir.Type) -> ir.Type: ...
    def registers_shape(self, shape: tuple[int, ...]) -> tuple[int, ...]: ...
    def shape_from_registers_shape(self, shape: tuple[int, ...]) -> tuple[int, ...]: ...
    def thread_idxs(self, shape) -> None: ...

@dataclasses.dataclass(frozen=True)
class WGStridedFragLayout:
    shape: tuple[int, ...]
    vec_size: int
    def __post_init__(self) -> None: ...
    @classmethod
    def from_shaped_type(cls, shaped_ty: ir.Type) -> WGStridedFragLayout | None: ...
    def registers_element_type(self, t: ir.Type) -> ir.Type: ...
    def registers_shape(self, shape: tuple[int, ...]) -> tuple[int, ...]: ...
    def shape_from_registers_shape(self, shape: tuple[int, ...]) -> tuple[int, ...]: ...
    def thread_idxs(self, shape) -> Generator[Incomplete]: ...
    def linear_thread_idxs(self) -> Generator[Incomplete]: ...

type FragmentedLayout = WGSplatFragLayout | WGStridedFragLayout | TiledLayout
WGMMA_COL_LAYOUT: Incomplete
WGMMA_ROW_LAYOUT: Incomplete
WGMMA_LAYOUT: Incomplete
WGMMA_LAYOUT_ACC_32BIT: Incomplete
WGMMA_LAYOUT_8BIT: Incomplete
WGMMA_LAYOUT_UPCAST_2X: Incomplete
WGMMA_LAYOUT_UPCAST_4X: Incomplete
WGMMA_TRANSPOSED_LAYOUT: Incomplete
TCGEN05_LAYOUT: Incomplete
TCGEN05_TRANSPOSED_LAYOUT: Incomplete
TCGEN05_ROW_LAYOUT: Incomplete
TCGEN05_COL_LAYOUT: Incomplete

def tmem_native_layout(vector_length: int): ...

TMEM_NATIVE_LAYOUT: Incomplete
TMA_GATHER_INDICES_LAYOUT: Incomplete

def can_relayout_wgmma_4x_to_wgmma_2x(bitwidth: int) -> bool: ...
def can_relayout_wgmma_2x_to_wgmma(bitwidth: int) -> bool: ...

@dataclasses.dataclass(init=False, frozen=True, slots=True)
class FragmentedArray:
    registers: np.ndarray = ...
    layout: FragmentedLayout
    is_signed: bool | None
    def __init__(
        self,
        *,
        _registers: np.ndarray,
        _layout: FragmentedLayout,
        _is_signed: bool | None,
    ) -> None: ...
    @classmethod
    def load_strided(
        cls,
        ref: ir.Value,
        *,
        is_signed: bool | None = None,
        vec_size: int | None = None,
    ) -> FragmentedArray: ...
    @classmethod
    def splat(
        cls,
        value,
        shape,
        layout=None,
        *,
        is_signed: bool | None = None,
    ) -> FragmentedArray: ...
    @staticmethod
    def broadcasted_iota(
        dtype: ir.Type,
        shape: tuple[int, ...],
        dimension: int,
        layout: FragmentedLayout | None = None,
        *,
        is_signed: bool | None = None,
    ) -> FragmentedArray: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def mlir_dtype(self) -> ir.Type: ...
    def to_layout(self, new_layout: FragmentedLayout) -> FragmentedArray: ...
    def __pos__(self): ...
    def __neg__(self): ...
    def __add__(self, other): ...
    def __radd__(self, other): ...
    def __mul__(self, other): ...
    def __rmul__(self, other): ...
    def __sub__(self, other): ...
    def __rsub__(self, other): ...
    def __truediv__(self, other): ...
    def __rtruediv__(self, other): ...
    def __floordiv__(self, other): ...
    def __rfloordiv__(self, other): ...
    def __mod__(self, other): ...
    def __rmod__(self, other): ...
    def __invert__(self): ...
    def __or__(self, other): ...
    def __ror__(self, other): ...
    def __and__(self, other): ...
    def __rand__(self, other): ...
    def __xor__(self, other): ...
    def __rxor__(self, other): ...
    def __lshift__(self, other): ...
    def __rshift__(self, other): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
    def max(self, other) -> FragmentedArray: ...
    def min(self, other) -> FragmentedArray: ...
    def copysign(self, other: FragmentedArray) -> FragmentedArray: ...
    def exp(self, *, approx: bool = False) -> FragmentedArray: ...
    def exp2(self, *, approx: bool = False) -> FragmentedArray: ...
    def log(self, *, approx: bool = False) -> FragmentedArray: ...
    def log2(self, *, approx: bool = False) -> FragmentedArray: ...
    def sin(self, *, approx: bool = False) -> FragmentedArray: ...
    def cos(self, *, approx: bool = False) -> FragmentedArray: ...
    def tanh(self, *, approx: bool = False) -> FragmentedArray: ...
    def rsqrt(self, *, approx: bool = False) -> FragmentedArray: ...
    def abs(self) -> FragmentedArray: ...
    def round(self) -> FragmentedArray: ...
    def round_even(self) -> FragmentedArray: ...
    def erf(self) -> FragmentedArray: ...
    def atan2(self, other: FragmentedArray) -> FragmentedArray: ...
    def bitcast(
        self,
        elt: ir.Type,
        *,
        output_is_signed: bool | None = None,
    ) -> FragmentedArray: ...
    def __getitem__(self, idx) -> FragmentedArray: ...
    def __setitem__(self, idx: object, value: FragmentedArray) -> None: ...
    def copy(self) -> FragmentedArray: ...
    def astype(
        self,
        new_dtype: ir.Type,
        *,
        is_signed: bool | None = None,
    ) -> FragmentedArray: ...
    def reduce(
        self,
        op: str | Callable[[ir.Value, ir.Value], ir.Value],
        axis: int | Sequence[int],
        scratch: ir.Value | None = None,
    ) -> FragmentedArray: ...
    def broadcast(self, shape) -> FragmentedArray: ...
    def reshape(self, shape: tuple[int, ...]) -> FragmentedArray: ...
    def broadcast_minor(self, n) -> FragmentedArray: ...
    def broadcast_in_dim(
        self,
        shape,
        source_dimensions,
        layout: FragmentedLayout,
    ) -> FragmentedArray: ...
    def select(self, on_true, on_false): ...
    @classmethod
    def build(
        cls,
        shape: tuple[int, ...],
        layout: FragmentedLayout,
        fn: Callable[..., ir.Value],
        *,
        is_signed: bool | None = None,
    ) -> FragmentedArray: ...
    def foreach(
        self,
        fn: Callable[[ir.Value, tuple[ir.Value, ...]], ir.Value | None],
        *,
        create_array: bool = False,
        is_signed=None,
    ): ...
    def debug_print(self, fmt: str) -> None: ...
    def store_untiled(
        self,
        ref: ir.Value | utils.MultimemRef,
        *,
        swizzle: int = 16,
        optimized: bool = True,
    ) -> None: ...
    @classmethod
    def load_reduce_untiled(
        cls,
        ref: utils.MultimemRef,
        layout: TiledLayout | WGStridedFragLayout,
        reduction: utils.MultimemReductionOp,
        swizzle: int = 16,
        is_signed: bool | None = None,
    ): ...
    @classmethod
    def load_untiled(
        cls,
        ref: ir.Value,
        *,
        layout: TiledLayout,
        swizzle: int = 16,
        is_signed: bool | None = None,
        optimized: bool = True,
    ) -> FragmentedArray: ...
    def store_tiled_async(
        self,
        ref: ir.Value,
        barrier: utils.BarrierRef,
        cluster_dim: gpu.Dimension,
        cluster_idx: ir.Value,
        swizzle: int | None,
        optimized: bool = True,
        tiling_rank: int | None = None,
    ): ...
    def store_tiled(
        self,
        ref: ir.Value | utils.MultimemRef,
        swizzle: int | None,
        optimized: bool = True,
        tiling_rank: int | None = None,
    ): ...
    @classmethod
    def load_tiled(
        cls,
        ref,
        swizzle: int | None,
        *,
        is_signed: bool | None = None,
        layout: FragmentedLayout = ...,
        optimized: bool = True,
        tiling_rank: int | None = None,
        _load_fun: Callable[[ir.VectorType, ir.Value], ir.Value] = ...,
        _narrow_float_as_int: bool = True,
    ) -> FragmentedArray: ...
    @classmethod
    def transfer_strided(cls, ref: ir.Value, vec_size: int): ...
    @staticmethod
    def transfer_tiled(
        ref: ir.Value,
        swizzle: int | None,
        layout: TiledLayout,
        shape: tuple[int, ...],
        optimized: bool = True,
        ref_tiling_rank: int | None = None,
    ): ...
    def tree_flatten(self): ...
    @classmethod
    def tree_unflatten(cls, aux, flat_registers): ...

type IndexTransform = Callable[[tuple[int, ...]], tuple[int, ...]]

class TransferPlan(Protocol):
    @property
    def tile_index_transforms(self) -> tuple[IndexTransform, ...]: ...
    def select(self, group_elems: Sequence[ir.Value], /) -> ir.Value: ...
    def select_if_group(
        self,
        group_idx: int,
        old: ir.Value,
        new: ir.Value,
        /,
    ) -> ir.Value: ...

@dataclasses.dataclass(frozen=True)
class TrivialTransferPlanImpl(TransferPlan):
    @property
    def tile_index_transforms(self): ...
    def select(self, group_elems: Sequence[ir.Value]) -> ir.Value: ...
    def select_if_group(
        self,
        group_idx: int,
        old: ir.Value,
        new: ir.Value,
    ) -> ir.Value: ...

@dataclasses.dataclass(frozen=True)
class StaggeredTransferPlanImpl(TransferPlan):
    stagger: int
    dim: int
    size: int
    group_pred: ir.Value
    @property
    def tile_index_transforms(self): ...
    def select(self, group_elems: Sequence[ir.Value]) -> ir.Value: ...
    def select_if_group(
        self,
        group_idx: int,
        old: ir.Value,
        new: ir.Value,
    ) -> ir.Value: ...

TrivialTransferPlan: type[TransferPlan]
StaggeredTransferPlan: type[TransferPlan]
TrivialTransferPlan = TrivialTransferPlanImpl
StaggeredTransferPlan = StaggeredTransferPlanImpl

def plan_tiled_transfer(
    tiles_shape: Sequence[int],
    tiles_strides: Sequence[int],
    warp_shape: Sequence[int],
    warp_strides: Sequence[int],
    lane_shape: Sequence[int],
    lane_strides: Sequence[int],
    vector_length: int,
    element_bits: int,
    swizzle: int,
) -> TransferPlan: ...
def addf(a: ir.Value, b: ir.Value): ...
def subf(a: ir.Value, b: ir.Value): ...
def mulf(a: ir.Value, b: ir.Value): ...
@overload
def optimization_barrier(
    a: mgpu.FragmentedArray,
    b: mgpu.FragmentedArray,
    /,
    *arrays: mgpu.FragmentedArray,
) -> Sequence[mgpu.FragmentedArray]: ...
@overload
def optimization_barrier(a: mgpu.FragmentedArray) -> mgpu.FragmentedArray: ...
def tiled_copy_smem_gmem_layout(
    row_tiles: int,
    col_tiles: int,
    swizzle: int,
    bitwidth: int,
) -> TiledLayout: ...
def copy_tiled(src: ir.Value, dst: ir.Value, swizzle: int = 16): ...
