from collections.abc import Sequence

from _typeshed import Incomplete
from jax._src.lib.mlir import ir as ir

from . import (
    fragmented_array as fa,
    tcgen05 as tcgen05,
    utils as utils,
)

MlirOperation: Incomplete

def in_layouts(op: MlirOperation) -> Sequence[ir.Attribute]: ...
def out_layouts(op: MlirOperation) -> Sequence[ir.Attribute]: ...
def in_transforms(op: MlirOperation) -> Sequence[ir.Attribute]: ...
def out_transforms(op: MlirOperation) -> Sequence[ir.Attribute]: ...
def in_tmem_layouts(op: MlirOperation) -> Sequence[ir.Attribute]: ...
def out_tmem_layouts(op: MlirOperation) -> Sequence[ir.Attribute]: ...
def should_have_in_tmem_layout(op: MlirOperation) -> bool: ...
def should_have_out_tmem_layout(op: MlirOperation) -> bool: ...
def should_have_tmem_layout(op: MlirOperation) -> bool: ...
def has_in_tmem_layouts_set(op: MlirOperation) -> bool: ...
def has_out_tmem_layouts_set(op: MlirOperation) -> bool: ...
def should_have_in_layout(op: MlirOperation) -> bool: ...
def should_have_out_layout(op: MlirOperation) -> bool: ...
def should_have_layout(op: MlirOperation) -> bool: ...
def has_in_layouts_set(op: MlirOperation) -> bool: ...
def has_out_layouts_set(op: MlirOperation) -> bool: ...
def has_any_layout_set(op: MlirOperation) -> bool: ...
def has_in_transforms_set(op: MlirOperation) -> bool: ...
def has_out_transforms_set(op: MlirOperation) -> bool: ...
def attr_element(
    attr_name: str,
    op: MlirOperation,
    index: int,
) -> ir.Attribute | None: ...

in_layout_for_operand: Incomplete
in_transforms_for_operand: Incomplete

def should_have_in_transforms(op: ir.OpView) -> bool: ...
def should_have_out_transforms(op: ir.OpView) -> bool: ...
def should_have_transforms(op: ir.OpView) -> bool: ...
def is_transformable_smem_memref(v: ir.Value) -> bool: ...
def is_mma_layout(layout: fa.FragmentedLayout) -> bool: ...
