from jax._src.lib import mosaic_gpu_dialect as mgpu
from jax._src.lib.mlir import ir as ir

from . import (
    fragmented_array as fa,
    launch_context as launch_context,
)

def to_splat_fragmented_layout_attr(layout: fa.WGSplatFragLayout) -> ir.Attribute: ...
def from_splat_fragmented_layout_attr(attr: ir.Attribute) -> fa.WGSplatFragLayout: ...
def is_splat_fragmented_layout(attr: ir.Attribute) -> bool: ...
def to_strided_fragmented_layout_attr(
    layout: fa.WGStridedFragLayout,
) -> ir.Attribute: ...
def from_strided_fragmented_layout_attr(
    attr: ir.Attribute,
) -> fa.WGStridedFragLayout: ...
def is_strided_fragmented_layout(attr: ir.Attribute) -> bool: ...
def to_tiled_layout_attr(layout: fa.TiledLayout) -> ir.Attribute: ...
def from_tiled_layout_attr(attr: ir.Attribute) -> fa.TiledLayout: ...
def is_tiled_layout(attr: ir.Attribute) -> bool: ...
def to_layout_attr(layout: fa.FragmentedLayout) -> ir.Attribute: ...
def from_layout_attr(attr: ir.Attribute) -> fa.FragmentedLayout: ...
def splat_is_compatible_with_tiled(
    l1: fa.WGSplatFragLayout,
    l2: fa.TiledLayout,
) -> bool: ...
def is_tile_transform(attr: ir.Attribute) -> bool: ...
def is_transpose_transform(attr: ir.Attribute) -> bool: ...
def is_swizzle_transform(attr: ir.Attribute) -> bool: ...
def to_transform_attr(
    transform: launch_context.MemRefTransform | mgpu.SwizzlingMode,
) -> ir.Attribute: ...
def from_transform_attr(
    transform: ir.Attribute,
) -> launch_context.MemRefTransform | mgpu.SwizzlingMode: ...
