from collections.abc import Generator, Iterator, Sequence
from typing import Any, Literal

import contextlib
import dataclasses
import enum

from _typeshed import Incomplete
from jax.interpreters import mlir as mlir
from jaxlib.mlir import ir
from jaxlib.mlir.dialects import gpu, scf

import jax

WARP_SIZE: int
WARPGROUP_SIZE: int
WARPS_IN_WARPGROUP: int
DYNAMIC: int
DYNAMIC32: int
MBARRIER_BYTES: int

def gpu_address_space_to_nvptx(address_space: gpu.AddressSpace) -> int: ...

WORKGROUP_NVPTX_ADDRESS_SPACE: Incomplete

def ptr_as_memref(
    ptr,
    memref_ty: ir.MemRefType,
    ptr_memory_space: int | None = None,
): ...
def pack_array(values): ...
def get_contiguous_strides(xs): ...
def c(val: float, ty): ...
def debug_print(fmt, *args, uniform: bool = True, scope=None) -> None: ...

@dataclasses.dataclass(frozen=True)
class MultimemRef:
    ref: ir.Value
    @property
    def type(self) -> ir.Type: ...
    def store(self, value: ir.Value, indices: Sequence[ir.Value]): ...

def multimem_store(ptr: ir.Value, value: ir.Value): ...

MultimemReductionOp: Incomplete

def multimem_load_reduce(
    ty: ir.Type,
    ptr: ir.Value,
    reduction: MultimemReductionOp,
    is_signed: bool | None = None,
): ...

@dataclasses.dataclass(frozen=True)
class ForResult:
    op: scf.ForOp
    results: tuple[Any, ...]
    @property
    def result(self): ...

def fori(bound, carrys): ...
@contextlib.contextmanager
def when(cond) -> Generator[None]: ...

thread_idx: Incomplete
block_idx: Incomplete

def warp_idx(sync: bool = True): ...
def warpgroup_idx(sync: bool = True): ...

class ThreadSubset(enum.IntEnum):
    WARP = ...
    WARPGROUP = ...
    BLOCK = ...

def single_thread_predicate(scope: ThreadSubset = ...): ...
@contextlib.contextmanager
def single_thread(scope: ThreadSubset = ...): ...
def clock(): ...
def smid(): ...
def globaltimer(kind: Literal["low", "high"] | None = None): ...
def bytewidth(ty: ir.Type): ...
def bitwidth_impl(ty: ir.Type): ...
def bitwidth(ty: ir.Type): ...

@dataclasses.dataclass(frozen=True)
class DynamicSlice:
    base: ir.Value | int
    length: int
    def __post_init__(self) -> None: ...

ds = DynamicSlice

def memref_slice(ref: ir.Value, index) -> ir.Value: ...
def memref_reshape(
    ref: ir.Value | MultimemRef,
    shape: tuple[int, ...],
) -> ir.Value | MultimemRef: ...
def memref_fold(
    ref: ir.Value | MultimemRef,
    dim,
    fold_rank,
) -> ir.Value | MultimemRef: ...
def memref_unfold(ref: ir.Value, dim, factors) -> ir.Value: ...
def memref_unsqueeze(ref: ir.Value, dim) -> ir.Value: ...
def is_memref_transposed(ref: ir.MemRefType) -> bool: ...
def memref_transpose(ref: ir.Value, permutation: Sequence[int]) -> ir.Value: ...
def parse_indices(
    index,
    shape: tuple[int, ...],
    *,
    check_oob: bool = True,
) -> tuple[list[ir.Value | int], list[int], list[bool]]: ...
def commit_shared() -> None: ...
def warpgroup_barrier() -> None: ...
def warp_barrier() -> None: ...

@dataclasses.dataclass(frozen=True)
class BarrierRef:
    base_address: ir.Value
    offset: ir.Value
    phases: ir.Value
    num_barriers: int
    @staticmethod
    def initialize(barrier_memref: ir.Value, arrival_count: int = 1) -> BarrierRef: ...
    def __iter__(self) -> Iterator[BarrierRef]: ...
    def __getitem__(self, offset: ir.Value | int) -> BarrierRef: ...
    def wait_parity(self, parity, orders_tensor_core: bool = False) -> None: ...
    def wait(self, orders_tensor_core: bool = False): ...
    def update_parities(self, parities: ir.Value) -> tuple[ir.Value, ir.Value]: ...
    def arrive(
        self,
        arrival_count: int = 1,
        can_complete: bool = True,
        orders_tensor_core: bool = False,
        predicate: ir.Value | None = None,
    ): ...
    def arrive_expect_tx(
        self,
        bytes: int | ir.Value,
        predicate: ir.Value | None = None,
    ): ...
    def complete_tx(self, bytes: int | ir.Value, predicate: ir.Value | None = None): ...
    def get_ptr(self): ...

@dataclasses.dataclass(frozen=True)
class DialectBarrierRef:
    barrier_ref: BarrierRef
    @staticmethod
    def initialize(
        barrier_memref: ir.Value,
        arrival_count: int = 1,
    ) -> DialectBarrierRef: ...
    def __iter__(self) -> Iterator[DialectBarrierRef]: ...
    def __getitem__(self, offset: ir.Value | int) -> DialectBarrierRef: ...
    def wait_parity(self, parity, orders_tensor_core: bool = False) -> None: ...
    def wait(self, orders_tensor_core: bool = False): ...
    def update_parities(self, parities: ir.Value) -> tuple[ir.Value, ir.Value]: ...
    def arrive(self, orders_tensor_core: bool = False): ...
    def arrive_expect_tx(self, bytes: int | ir.Value): ...
    def get_ptr(self): ...
    def as_barrier_memref(self) -> ir.Value: ...
    @classmethod
    def from_barrier_memref(cls, barrier: ir.Value): ...

@dataclasses.dataclass(frozen=True)
class CollectiveBarrierRef:
    barrier: BarrierRef
    cluster_mask: ir.Value | None
    @staticmethod
    def initialize(
        barrier_memref: ir.Value,
        arrival_count: int,
        dims: Sequence[gpu.Dimension | Sequence[gpu.Dimension]],
        cluster_shape: tuple[int, int, int],
    ) -> CollectiveBarrierRef: ...
    def __iter__(self): ...
    def __getitem__(self, offset): ...
    def arrive(self, orders_tensor_core: bool = False): ...
    def wait(self, *args, **kwargs) -> None: ...
    def wait_parity(self, *args, **kwargs) -> None: ...

@dataclasses.dataclass(frozen=True)
class SemaphoreRef:
    ptr: ir.Value
    def signal(
        self,
        value: ir.Value | int,
        predicate: ir.Value | None = None,
        relaxed: bool = False,
    ): ...
    @staticmethod
    def signal_multimem(ptr, value, predicate: ir.Value | None = None): ...
    def wait(
        self,
        value: ir.Value | int = 1,
        *,
        decrement: bool = True,
        scope: ThreadSubset = ...,
    ): ...

def fence_release_sys() -> None: ...

class Partition:
    source_bounds: tuple[int, ...]
    target_bounds: tuple[int, ...]
    partition: tuple[int | None, ...]
    base_offset: tuple[ir.Value, ...] | None
    def __init__(
        self,
        elements: tuple[int, ...],
        *,
        partition: tuple[int | None, ...],
        base_offset: tuple[ir.Value, ...] | None = None,
        num_chunks: tuple[int, ...] | None = None,
        chunk_size: tuple[int, ...] | None = None,
    ) -> None: ...
    @property
    def num_chunks(self) -> tuple[int, ...]: ...
    @property
    def target_block_shape(self): ...
    def get_base(self, *source_coords: ir.Value | int) -> list[ir.Value]: ...

class Partition1D:
    partition: Partition
    base_offset: Incomplete
    def __init__(
        self,
        elements: int,
        *,
        base_offset: ir.Value | None = None,
        num_chunks: int | None = None,
        chunk_size: int | None = None,
    ) -> None: ...
    @property
    def num_chunks(self) -> int: ...
    def get_base(self, source_coords: ir.Value) -> ir.Value: ...
    def refine(
        self,
        *,
        chunk: ir.Value | None = None,
        num_chunks: int | None = None,
        chunk_size: int | None = None,
    ): ...

def tile_shape(shape, tiling): ...
def warp_tree_reduce(value, op, group_size): ...
def memref_ptr(memref_arg, memory_space=None): ...
def cluster_collective_mask(
    cluster_shape: tuple[int, int, int],
    collective: Sequence[gpu.Dimension] | gpu.Dimension,
): ...
def dtype_to_ir_type(dtype: jax.typing.DTypeLike) -> ir.Type: ...
def is_signed(dtype: jax.typing.DTypeLike) -> bool | None: ...
def getelementptr(
    ptr: ir.Value,
    indices: Sequence[ir.Value | int],
    dtype: ir.Type,
) -> ir.Value: ...
def dyn_dot(x, y): ...
def shfl_bfly(x: ir.Value, distance: int | ir.Value): ...

ReductionKind: Incomplete

def redux(x: ir.Value, mask: ir.Value, kind: ReductionKind): ...
def prmt(high: ir.Value, low: ir.Value, permutation: ir.Value): ...
def bitcast(x: ir.Value, new_type: ir.Type): ...
def ceil_div(x: int, y: int): ...
def vector_slice(v: ir.Value, s: slice): ...
def vector_concat(vectors: Sequence[ir.Value]) -> ir.Value: ...
def is_known_divisible(value: ir.Value, divisor: int, max_depth: int = 10) -> bool: ...
def smem() -> ir.Attribute: ...
def tmem() -> ir.Attribute: ...
def is_smem_ref(ref: ir.Value | ir.Type) -> bool: ...
def is_tmem_ref(ref: ir.Value | ir.Type) -> bool: ...
def try_cluster_cancel(
    result_ref,
    barrier: BarrierRef,
    predicate: ir.Value | None = None,
): ...
def query_cluster_cancel(
    result_ref,
) -> tuple[ir.Value, ir.Value, ir.Value, ir.Value]: ...
def nanosleep(nanos: ir.Value): ...
def nvvm_mbarrier_arrive_expect_tx(
    barrier: ir.Value,
    expect_tx: ir.Value,
    predicate: ir.Value | None = None,
): ...
def cluster_idx(
    dim: gpu.Dimension | Sequence[gpu.Dimension] | None = None,
    dim_idx: ir.Value | Sequence[ir.Value] | None = None,
) -> ir.Value: ...
def get_cluster_ptr(ptr: ir.Value, cluster_block: ir.Value, generic: bool = True): ...
def get_cluster_ref(
    ref: ir.Value,
    dim: gpu.Dimension,
    idx: ir.Value,
    generic: bool = True,
): ...

@dataclasses.dataclass(frozen=True)
class Arch:
    major: int
    minor: int

def get_arch() -> Arch: ...
