from dataclasses import dataclass

from torchao.quantization.granularity import Granularity

import torch

@dataclass(frozen=True)
class MarlinQQQConstants:
    TILE: int = ...
    MIN_THREAD_N: int = ...
    MAX_PARALLEL: int = ...
    SUPPORTED_NUM_BITS: list[int] = ...
    SUPPORTED_GROUP_SIZES: list[int] = ...

const = ...

def get_pack_factor(num_bits: int) -> int: ...
def marlin_permute_weights(
    q_w: torch.Tensor, size_k: int, size_n: int, perm: torch.Tensor, tile: int = ...
) -> torch.Tensor: ...
def reverse_marlin_permute_weights(
    q_w_unpacked: torch.Tensor,
    size_k: int,
    size_n: int,
    reverse_perm: torch.Tensor,
    tile: int = ...,
) -> torch.Tensor: ...
def get_qqq_weight_perm(num_bits: int, granularity: Granularity) -> torch.Tensor: ...
def get_qqq_scale_perms(num_bits: int) -> tuple[list[int], list[int]]: ...
def get_qqq_weight_reverse_perm(
    num_bits: int, granularity: Granularity
) -> torch.Tensor: ...
def get_qqq_scale_reverse_perms(num_bits: int) -> tuple[torch.Tensor, torch.Tensor]: ...
