from dataclasses import dataclass

import enum
import logging

import torch

logger: logging.Logger = ...

class ScalingType(enum.Enum):
    DYNAMIC = ...
    DISABLED = ...
    def short_str(self):  # -> Literal['dyn', 'dis']:
        ...

class ScalingGranularity(enum.Enum):
    TENSORWISE = ...
    AXISWISE = ...
    def short_str(self):  # -> Literal['ten', 'axs']:
        ...

@dataclass
class Float8TypeConfig:
    e4m3_dtype = ...
    e5m2_dtype = ...
    def __post_init__(self):  # -> None:
        ...

type_config = ...
e4m3_dtype = ...
e5m2_dtype = ...

@dataclass(frozen=True)
class CastConfig:
    scaling_type: ScalingType = ...
    scaling_granularity: ScalingGranularity = ...
    target_dtype: torch.dtype | None = ...
    def short_str(self):  # -> str:
        ...
    def __post_init__(self):  # -> None:
        ...

@dataclass(frozen=True)
class Float8GemmConfig:
    use_fast_accum: bool = ...

class Float8LinearRecipeName(enum.Enum):
    TENSORWISE = ...
    ROWWISE = ...
    ROWWISE_WITH_GW_HP = ...

@dataclass(frozen=True)
class Float8LinearConfig:
    cast_config_input: CastConfig = ...
    cast_config_input_for_grad_weight: CastConfig | None = ...
    cast_config_weight: CastConfig = ...
    cast_config_weight_for_grad_input: CastConfig | None = ...
    cast_config_grad_output: CastConfig = ...
    cast_config_grad_output_for_grad_weight: CastConfig | None = ...
    gemm_config_output: Float8GemmConfig = ...
    gemm_config_grad_input: Float8GemmConfig = ...
    gemm_config_grad_weight: Float8GemmConfig = ...
    enable_fsdp_float8_all_gather: bool = ...
    pad_inner_dim: bool = ...
    emulate: bool = ...
    force_recompute_fp8_weight_in_bwd: bool = ...
    round_scales_to_power_of_2: bool = ...
    def __post_init__(self):  # -> None:
        ...
    @staticmethod
    def from_recipe_name(
        recipe_name: Float8LinearRecipeName | str,
    ) -> Float8LinearConfig: ...
