from typing import Any

from _typeshed import Incomplete
from jax._src.numpy.array_creation import (
    full as full,
    zeros_like as zeros_like,
)
from jax._src.numpy.array_methods import (
    register_jax_array_methods as register_jax_array_methods,
)
from jax._src.numpy.lax_numpy import finfo as finfo
from jax._src.numpy.ufuncs import (
    abs as abs,
    absolute as absolute,
    isfinite as isfinite,
)

from . import (
    fft as fft,
    linalg as linalg,
)

fix: Incomplete

int32: Any
float32: Any
bool_: Any
complex64: Any
complex128: Any

def array(object: Any, dtype: Any = ..., **kwargs: Any) -> Any: ...
def zeros(shape: Any, dtype: Any = ...) -> Any: ...
def ones(shape: Any, dtype: Any = ...) -> Any: ...
def arange(*args: Any, **kwargs: Any) -> Any: ...
def outer(a: Any, b: Any) -> Any: ...
def exp(x: Any) -> Any: ...
def tanh(x: Any) -> Any: ...
def log(x: Any) -> Any: ...
def sqrt(x: Any) -> Any: ...
def mean(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def std(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def sum(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def matmul(a: Any, b: Any) -> Any: ...
def tril(m: Any, k: int = ...) -> Any: ...
def where(condition: Any, x: Any = ..., y: Any = ...) -> Any: ...
def stack(arrays: Any, axis: int = ...) -> Any: ...
def real(val: Any) -> Any: ...
def imag(val: Any) -> Any: ...
def take_along_axis(arr: Any, indices: Any, axis: int) -> Any: ...
def maximum(x1: Any, x2: Any) -> Any: ...
def minimum(x1: Any, x2: Any) -> Any: ...
def clip(a: Any, a_min: Any = ..., a_max: Any = ...) -> Any: ...
def cumsum(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def searchsorted(a: Any, v: Any, *args: Any, **kwargs: Any) -> Any: ...
def concatenate(arrays: Any, axis: int = ...) -> Any: ...
def pad(array: Any, pad_width: Any, *args: Any, **kwargs: Any) -> Any: ...
def broadcast_to(array: Any, shape: Any) -> Any: ...
def squeeze(a: Any, axis: Any = ...) -> Any: ...
def max(a: Any, *args: Any, **kwargs: Any) -> Any: ...
def conj(x: Any) -> Any: ...

type ndarray = Any
