from transformers.configuration_utils import PretrainedConfig

class MomConfig(PretrainedConfig):
    keys_to_ignore_at_inference = ...
    def __init__(
        self,
        attn_mode: str = ...,
        hidden_size: int = ...,
        conv_size: int = ...,
        num_heads: int = ...,
        head_dim: int = ...,
        expand_v: float = ...,
        use_output_gate: bool = ...,
        use_short_conv: bool = ...,
        max_position_embeddings: int = ...,
        hidden_ratio: int | None = ...,
        intermediate_size: int | None = ...,
        hidden_act: str = ...,
        num_hidden_layers: int = ...,
        norm_eps: float = ...,
        attn: dict | None = ...,
        use_cache: bool = ...,
        pad_token_id: int | None = ...,
        bos_token_id: int = ...,
        eos_token_id: int = ...,
        tie_word_embeddings: bool = ...,
        initializer_range: float = ...,
        num_memories: int = ...,
        topk: int = ...,
        capacity: float = ...,
        use_layer_wise_balance: bool = ...,
        aux_loss_scale: float = ...,
        shared_mem: bool = ...,
        single_kv_proj: bool = ...,
        mom_backend: str = ...,
        fuse_norm: bool = ...,
        fuse_swiglu: bool = ...,
        fuse_cross_entropy: bool = ...,
        vocab_size: int = ...,
        **kwargs,
    ) -> None: ...
