from typing import Any
from torch import Tensor, nn

from . import InterpolationMode

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "ImageClassification",
    "ObjectDetection",
    "OpticalFlow",
    "SemanticSegmentation",
    "VideoClassification",
]

class ObjectDetection(nn.Module):
    def forward(self, img: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def describe(self) -> str: ...

class ImageClassification(nn.Module):
    def __init__(
        self,
        *,
        crop_size: int,
        resize_size: int = ...,
        mean: tuple[float, ...] = ...,
        std: tuple[float, ...] = ...,
        interpolation: InterpolationMode = ...,
        antialias: bool | None = ...,
    ) -> None: ...
    def forward(self, img: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def describe(self) -> str: ...

class VideoClassification(nn.Module):
    def __init__(
        self,
        *,
        crop_size: tuple[int, int],
        resize_size: tuple[int] | tuple[int, int],
        mean: tuple[float, ...] = ...,
        std: tuple[float, ...] = ...,
        interpolation: InterpolationMode = ...,
    ) -> None: ...
    def forward(self, vid: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def describe(self) -> str: ...

class SemanticSegmentation(nn.Module):
    def __init__(
        self,
        *,
        resize_size: int | None,
        mean: tuple[float, ...] = ...,
        std: tuple[float, ...] = ...,
        interpolation: InterpolationMode = ...,
        antialias: bool | None = ...,
    ) -> None: ...
    def forward(self, img: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def describe(self) -> str: ...

class OpticalFlow(nn.Module):
    def forward(self, img1: Tensor, img2: Tensor) -> tuple[Tensor, Tensor]: ...
    def __call__(self, *args: Any, **kwargs: Any) -> tuple[Tensor, Tensor]: ...
    def describe(self) -> str: ...
