from typing import Any
from enum import Enum

from torch import Tensor

import torch

from . import InterpolationMode

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "AugMix",
    "AutoAugment",
    "AutoAugmentPolicy",
    "RandAugment",
    "TrivialAugmentWide",
]

class AutoAugmentPolicy(Enum):
    IMAGENET = ...
    CIFAR10 = ...
    SVHN = ...

class AutoAugment(torch.nn.Module):
    def __init__(
        self,
        policy: AutoAugmentPolicy = ...,
        interpolation: InterpolationMode = ...,
        fill: list[float] | None = ...,
    ) -> None: ...
    @staticmethod
    def get_params(transform_num: int) -> tuple[int, Tensor, Tensor]: ...
    def forward(self, img: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class RandAugment(torch.nn.Module):
    def __init__(
        self,
        num_ops: int = ...,
        magnitude: int = ...,
        num_magnitude_bins: int = ...,
        interpolation: InterpolationMode = ...,
        fill: list[float] | None = ...,
    ) -> None: ...
    def forward(self, img: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class TrivialAugmentWide(torch.nn.Module):
    def __init__(
        self,
        num_magnitude_bins: int = ...,
        interpolation: InterpolationMode = ...,
        fill: list[float] | None = ...,
    ) -> None: ...
    def forward(self, img: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class AugMix(torch.nn.Module):
    def __init__(
        self,
        severity: int = ...,
        mixture_width: int = ...,
        chain_depth: int = ...,
        alpha: float = ...,
        all_ops: bool = ...,
        interpolation: InterpolationMode = ...,
        fill: list[float] | None = ...,
    ) -> None: ...
    def forward(self, orig_img: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...
