from collections.abc import Sequence
from typing import Any

from _typeshed import Incomplete
from jax._src import literals as literals
from jax._src.util import use_cpp_class as use_cpp_class

import numpy as np

type Device = Any
type Shard = Any
type Sharding = Any

class Array:
    __hash__: Incomplete
    @property
    def __numpy_dtype__(self) -> np.dtype: ...
    @property
    def dtype(self) -> np.dtype: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    def addressable_data(self, index: int) -> Array: ...
    @property
    def addressable_shards(self) -> Sequence[Shard]: ...
    @property
    def global_shards(self) -> Sequence[Shard]: ...
    @property
    def is_fully_addressable(self) -> bool: ...
    @property
    def is_fully_replicated(self) -> bool: ...
    @property
    def sharding(self) -> Sharding: ...
    @property
    def committed(self) -> bool: ...
    @property
    def device(self) -> Device | Sharding: ...
    def copy_to_host_async(self) -> None: ...

StaticScalar: Incomplete
ArrayLike: Incomplete
