from jax._src import (
    config as config,
    hardware_utils as hardware_utils,
)

running_in_cloud_tpu_vm: bool

def maybe_import_libtpu(): ...
def get_tpu_library_path() -> str | None: ...
def jax_force_tpu_init() -> bool: ...
def cloud_tpu_init() -> None: ...
def is_cloud_tpu_older_than(year: int, month: int, day: int, backend): ...
