from _typeshed import Incomplete
from jax._src import (
    cache_key as cache_key,
    config as config,
    monitoring as monitoring,
)
from jax._src.compilation_cache_interface import CacheInterface as CacheInterface
from jax._src.lib import xla_client as xla_client
from jax._src.lib.mlir import ir as ir
from jax._src.lru_cache import LRUCache as LRUCache

import numpy as np

logger: Incomplete

def is_cache_used(backend: xla_client.Client) -> bool: ...
def get_file_cache(path: str) -> tuple[CacheInterface, str] | None: ...

class VerificationCache(CacheInterface):
    def __init__(self, base_cache: CacheInterface) -> None: ...
    def get(self, key: str) -> bytes | None: ...
    def put(self, key: str, value: bytes) -> None: ...
    def clear(self) -> None: ...

def set_cache_dir(path) -> None: ...
def initialize_cache(path) -> None: ...
def default_min_cache_entry_size() -> int: ...
def is_persistent_cache_enabled() -> bool: ...
def compress_executable(executable: bytes) -> bytes: ...
def decompress_executable(executable: bytes) -> bytes: ...
def is_executable_in_cache(backend, cache_key: str) -> bool: ...
def get_executable_and_time(
    cache_key: str,
    compile_options,
    backend,
    executable_devices,
) -> tuple[xla_client.LoadedExecutable | None, int | None]: ...
def put_executable_and_time(
    cache_key: str,
    module_name: str,
    executable: xla_client.LoadedExecutable,
    backend,
    compile_time: int,
) -> None: ...
def get_cache_key(
    module: ir.Module,
    devices: np.ndarray,
    compile_options,
    backend,
    ignore_callbacks: cache_key.IgnoreCallbacks = ...,
) -> str: ...
def is_initialized() -> bool: ...
def reset_cache() -> None: ...
def combine_executable_and_time(
    serialized_executable: bytes,
    compile_time: int,
) -> bytes: ...
def extract_executable_and_time(executable_and_time: bytes) -> tuple[bytes, int]: ...
