from collections import defaultdict
from collections.abc import (
    Callable,
    Collection,
    Generator,
    Hashable,
    Iterable,
    Iterator,
    MutableMapping,
    MutableSet,
    Sequence,
)
from contextlib import contextmanager
from dataclasses import dataclass
from typing import Any, ClassVar, Generic, NamedTuple, TypeVar, overload

import threading
import types

from _typeshed import Incomplete
from jax._src import (
    config as config,
    dtypes as dtypes,
    effects as effects,
    linear_util as lu,
    mesh as mesh_lib,
    source_info_util as source_info_util,
    traceback_util as traceback_util,
    xla_metadata_lib as xla_metadata_lib,
)
from jax._src.errors import (
    ConcretizationTypeError as ConcretizationTypeError,
    TracerArrayConversionError as TracerArrayConversionError,
    TracerBoolConversionError as TracerBoolConversionError,
    TracerIntegerConversionError as TracerIntegerConversionError,
    UnexpectedTracerError as UnexpectedTracerError,
)
from jax._src.layout import (
    AutoLayout as AutoLayout,
    Format as Format,
)
from jax._src.lib import (
    jax_jit as jax_jit,
    xla_client as xla_client,
)
from jax._src.memory import Space as MemorySpace
from jax._src.mesh import AxisType as AxisType
from jax._src.named_sharding import NamedSharding as NamedSharding
from jax._src.partition_spec import PartitionSpec as P
from jax._src.sharding import Sharding as Sharding
from jax._src.tree_util import tree_map as tree_map
from jax._src.typing import (
    Array as Array,
    ArrayLike as ArrayLike,
    DimSize as DimSize,
    Shape as Shape,
)
from jax._src.util import (
    HashableFunction as HashableFunction,
    HashableWrapper as HashableWrapper,
    StrictABCMeta as StrictABCMeta,
    cache as cache,
    curry as curry,
    foreach as foreach,
    partition_list as partition_list,
    safe_map as safe_map,
    safe_zip as safe_zip,
    set_module as set_module,
    tuple_delete as tuple_delete,
    tuple_insert as tuple_insert,
    weakref_cache_key_types as weakref_cache_key_types,
    weakref_lru_cache as weakref_lru_cache,
)

import jax._src.pretty_printer as pp

zip: Incomplete
unsafe_zip: Incomplete
map: Incomplete
unsafe_map: Incomplete
config_ext: Incomplete
type PyTree = Any

def identity(x): ...

Effect: Incomplete
Effects: Incomplete
EffectTypeSet: Incomplete
no_effects: Effects
DebugInfo: Incomplete
InitialResultPaths: Incomplete
initial_result_paths: Incomplete

class Jaxpr:
    @property
    def constvars(self) -> list[Var]: ...
    @property
    def invars(self) -> list[Var]: ...
    @property
    def outvars(self) -> list[Atom]: ...
    @property
    def eqns(self) -> list[JaxprEqn]: ...
    @property
    def effects(self) -> Effects: ...
    @property
    def debug_info(self) -> DebugInfo: ...
    @property
    def is_high(self) -> bool: ...
    @property
    def in_avals(self): ...
    @property
    def in_aval_qdds(self) -> list[AbstractValue | AvalQDD]: ...
    @property
    def final_aval_qdds(self) -> list[AbstractValue | AvalQDD]: ...
    @property
    def out_avals(self): ...
    def __init__(
        self,
        constvars: Sequence[Var],
        invars: Sequence[Var],
        outvars: Sequence[Atom],
        eqns: Sequence[JaxprEqn],
        effects: Effects = ...,
        debug_info: DebugInfo = None,
        is_high: bool = False,
    ) -> None: ...
    def pretty_print(
        self,
        *,
        source_info: bool = False,
        print_shapes: bool = True,
        custom_pp_eqn_rules: bool = True,
        name_stack: bool = False,
        print_effects: bool = False,
        **kwargs,
    ): ...
    def replace(self, **kwargs): ...

def join_effects(*effects: Effects) -> Effects: ...
def jaxprs_in_params(params) -> Iterator[Jaxpr]: ...
def subjaxprs(jaxpr: Jaxpr) -> Iterator[Jaxpr]: ...

class ClosedJaxpr:
    jaxpr: Incomplete
    consts: Incomplete
    literals = consts
    constvars: Incomplete
    invars: Incomplete
    outvars: Incomplete
    eqns: Incomplete
    effects: Incomplete
    debug_info: Incomplete
    is_high: Incomplete
    def __init__(self, jaxpr: Jaxpr, consts: Sequence) -> None: ...
    @property
    def in_avals(self): ...
    @property
    def in_aval_qdds(self) -> list[AbstractValue | AvalQDD]: ...
    @property
    def final_aval_qdds(self) -> list[AbstractValue | AvalQDD]: ...
    @property
    def out_avals(self): ...
    def map_jaxpr(self, f): ...
    def replace(self, *, jaxpr=None, consts=None): ...
    def pretty_print(
        self,
        *,
        source_info: bool = False,
        print_shapes: bool = True,
        name_stack: bool = False,
        custom_pp_eqn_rules: bool = True,
        print_effects: bool = False,
        **kwargs,
    ): ...

@curry
def jaxpr_as_fun(closed_jaxpr: ClosedJaxpr, *args): ...

class JaxprEqnContextManager:
    context: Incomplete
    def __init__(self, context) -> None: ...
    prev_compute_type: Incomplete
    prev_threefry_partitionable: Incomplete
    prev_xla_metadata: Incomplete
    prev_abstract_mesh: Incomplete
    prev_remove_size_one_mesh_axis: Incomplete
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: types.TracebackType | None,
    ) -> None: ...

class JaxprEqnContext:
    compute_type: str | None
    threefry_partitionable: bool
    xla_metadata: dict[str, Any] | None
    cur_abstract_mesh: mesh_lib.AbstractMesh
    remove_size_one_mesh_axis: bool
    def __init__(
        self,
        compute_type: str | None,
        threefry_partitionable: bool,
        xla_metadata: dict[str, Any] | None = None,
    ) -> None: ...
    @property
    def manager(self): ...
    def __hash__(self): ...
    def __eq__(self, other): ...

class JaxprEqn:
    invars: list[Atom]
    outvars: list[Var]
    primitive: Primitive
    params: dict[str, Any]
    effects: Effects
    source_info: source_info_util.SourceInfo
    ctx: JaxprEqnContext
    def __init__(
        self,
        invars,
        outvars,
        primitive,
        params,
        effs,
        source_info,
        ctx,
    ) -> None: ...
    def replace(
        self,
        invars: list[Atom] | None = None,
        outvars: list[Var] | None = None,
        primitive: Primitive | None = None,
        params: dict[str, Any] | None = None,
        effects: Effects | None = None,
        source_info: source_info_util.SourceInfo | None = None,
        ctx: JaxprEqnContext | None = None,
    ): ...

def new_jaxpr_eqn(
    invars,
    outvars,
    primitive,
    params,
    effects,
    source_info=None,
    ctx=None,
) -> JaxprEqn: ...

class Var:
    count: int
    aval: AbstractValue
    initial_qdd: QuasiDynamicData | None
    final_qdd: QuasiDynamicData | None
    def __init__(
        self,
        aval: AbstractValue,
        initial_qdd=None,
        final_qdd=None,
    ) -> None: ...
    def pretty_print(self, context: JaxprPpContext, *, print_dtype: bool = True): ...

gensym: Incomplete

class DropVar(Var):
    def __init__(self, aval: AbstractValue) -> None: ...
    def pretty_print(self, context: JaxprPpContext, *, print_dtype: bool = True): ...

class Literal:
    val: Any
    aval: AbstractValue
    def __init__(self, val, aval) -> None: ...
    @property
    def hash(self): ...
    __hash__: Incomplete
    def pretty_print(self, context: JaxprPpContext, *, print_dtype: bool = True): ...

literalable_types: set[type]

def is_literalable(x: Any) -> bool: ...
def jaxpr_const_args(jaxpr: Jaxpr) -> list[tuple[ArrayLike, AbstractValue]]: ...
def eqn_params_const_args(params) -> list[tuple[ArrayLike, AbstractValue]]: ...

type Atom = Var | Literal

class Primitive:
    name: str
    multiple_results: bool
    call_primitive: bool
    map_primitive: bool
    ref_primitive: bool
    skip_canonicalization: bool
    to_lojax: Callable[..., Any] | None
    is_effectful: Incomplete
    def __init__(self, name: str) -> None: ...
    def bind(self, *args, **params): ...
    def bind_with_trace(self, trace, args, params): ...
    def def_impl(self, impl): ...
    def def_abstract_eval(self, abstract_eval): ...
    def def_effectful_abstract_eval(self, effectful_abstract_eval): ...
    def def_effectful_abstract_eval2(self, abstract_eval): ...
    def def_bind_with_trace(self, bind_with_trace): ...
    def impl(self, *args, **params) -> None: ...
    def abstract_eval(self, *args, **params) -> None: ...
    def get_bind_params(self, params): ...
    def is_high(self, *avals, **params) -> bool: ...

@dataclass(frozen=True)
class GenericEffect(Effect):
    prim: Primitive

def traverse_jaxpr_params(f, params): ...
def eval_jaxpr(
    jaxpr: Jaxpr,
    consts,
    *args,
    propagate_source_info: bool = True,
) -> list[Any]: ...
def check_avals_context_mesh(avals, prim_name) -> None: ...

TracerType = TypeVar("TracerType", bound=Tracer)

class Trace(Generic[TracerType]):
    requires_low: bool
    def __init__(self) -> None: ...
    def process_primitive(self, primitive, tracers, params) -> None: ...
    def invalidate(self) -> None: ...
    def is_valid(self): ...
    def process_call(self, call_primitive, f, tracers, params) -> None: ...
    def process_map(self, map_primitive, f, tracers, params) -> None: ...
    def process_custom_jvp_call(
        self,
        primitive,
        fun,
        jvp,
        tracers,
        *,
        symbolic_zeros,
    ) -> None: ...
    def process_custom_transpose(
        self,
        prim: Primitive,
        call: lu.WrappedFun,
        tracers,
        **params,
    ): ...
    def process_custom_vjp_call(
        self,
        primitive,
        fun,
        fwd,
        bwd,
        tracers,
        out_trees,
        symbolic_zeros,
    ) -> None: ...
    def full_raise(self, x): ...
    @property
    def main(self): ...

def escaped_tracer_error(tracer, detail=None): ...
def check_scalar_conversion(arr: Array): ...
def check_integer_conversion(arr: Array): ...
def check_bool_conversion(arr: Array): ...

pytype_aval_mappings: dict[type, Callable[[Any], AbstractValue]]
TracerBase = Array
TracerMeta = StrictABCMeta

class Tracer(TracerBase, metaclass=TracerMeta):
    __array_priority__: int
    __hash__: Incomplete
    dtype: Incomplete
    ndim: Incomplete
    size: Incomplete
    shape: Incomplete
    def __init__(self, trace: Trace) -> None: ...
    def __array__(self, *args, **kw) -> None: ...
    def __dlpack__(self, *args, **kw) -> None: ...
    def tolist(self) -> None: ...
    def tobytes(self, order: str = "C") -> None: ...
    def full_lower(self) -> None: ...
    def __iter__(self): ...
    def __reversed__(self): ...
    def __len__(self) -> int: ...
    def to_concrete_value(self) -> None: ...
    @property
    def sharding(self) -> None: ...
    @property
    def committed(self) -> None: ...
    @property
    def device(self) -> None: ...
    @property
    def addressable_shards(self) -> None: ...
    @property
    def at(self): ...
    @property
    def aval(self) -> None: ...
    def get_referent(self) -> Any: ...
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __complex__(self) -> complex: ...
    def __hex__(self): ...
    def __oct__(self): ...
    def __index__(self) -> int: ...
    def __reduce__(self) -> None: ...
    def __setitem__(self, idx, val) -> None: ...
    def __array_module__(self, types): ...
    def __getattr__(self, name): ...
    def addressable_data(self, index) -> None: ...
    @property
    def block_until_ready(self) -> None: ...
    @property
    def copy_to_host_async(self) -> None: ...
    def delete(self) -> None: ...
    def devices(self) -> None: ...
    @property
    def global_shards(self) -> None: ...
    def is_deleted(self) -> None: ...
    @property
    def is_fully_addressable(self) -> None: ...
    @property
    def is_fully_replicated(self) -> None: ...
    def on_device_size_in_bytes(self) -> None: ...
    @property
    def traceback(self) -> None: ...
    def unsafe_buffer_pointer(self) -> None: ...

class aval_property(NamedTuple):
    fget: Incomplete

class aval_method(NamedTuple):
    fun: Incomplete

def check_eval_args(args) -> None: ...

class EvalTrace(Trace):
    def process_primitive(self, primitive, args, params): ...
    def process_call(self, primitive, f, tracers, params): ...
    process_map = process_call
    def process_custom_transpose(self, primitive, call, tracers, **_): ...
    def process_custom_jvp_call(self, primitive, fun, jvp, tracers, **_): ...
    def process_custom_vjp_call(self, primitive, fun, fwd, bwd, tracers, **_): ...
    def cur_qdd(self, x): ...

class TraceTag:
    def __hash__(self): ...
    def __eq__(self, other): ...

type ParamDict = dict[str, Any]
AxisName = Hashable
no_axis_name: Incomplete

@dataclass(frozen=True)
class AxisEnv:
    axis_sizes: dict[AxisName, int]
    spmd_axis_names: set[AxisName]
    explicit_mesh_axis_names: frozenset[AxisName]
    def axis_size(self, axis_name): ...
    def axis_exists(self, axis_name): ...
    def axis_names(self): ...
    def pop_pure(self, axis_name): ...
    def extend_pure(self, name_size_pairs): ...
    def add_spmd_axis_names(self, axis_names): ...
    def add_explicit_mesh_axis_names(self, axis_names): ...
    def remove_explicit_mesh_axis_names(self, axis_names): ...
    def as_hashable_key(self): ...

eval_trace: Incomplete
top_axis_env: Incomplete

class TracingContext(threading.local):
    trace: Trace | None
    axis_env: AxisEnv
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    def is_top_level(self) -> bool: ...
    def set_trace(self, trace) -> None: ...
    def set_axis_env(self, axis_env) -> None: ...
    def update_thread_local_jit_state(self) -> None: ...

trace_ctx: Incomplete

class TakeCurrentTraceContextManager:
    prev: Incomplete
    def __enter__(self): ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: types.TracebackType | None,
    ) -> None: ...

take_current_trace = TakeCurrentTraceContextManager

class SetCurrentTraceContextManager:
    trace: Incomplete
    check_leaks: Incomplete
    def __init__(self, trace, check_leaks: bool = False) -> None: ...
    prev: Incomplete
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: types.TracebackType | None,
    ) -> None: ...

set_current_trace = SetCurrentTraceContextManager

class ExtendAxisEnvNdContextManager:
    name_size_pairs: Incomplete
    def __init__(self, name_size_pairs: Iterable[tuple[AxisName, int]]) -> None: ...
    prev: Incomplete
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: types.TracebackType | None,
    ) -> None: ...

extend_axis_env_nd = ExtendAxisEnvNdContextManager

class AddSpmdAxisNamesContextManager:
    axis_names: Incomplete
    def __init__(self, axis_names: AxisName | None) -> None: ...
    prev: Incomplete
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: types.TracebackType | None,
    ) -> None: ...

add_spmd_axis_names = AddSpmdAxisNamesContextManager

class AddExplicitMeshAxisNamesContextManager:
    axis_names: Incomplete
    def __init__(self, axis_names: AxisName | None) -> None: ...
    prev: Incomplete
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: types.TracebackType | None,
    ) -> None: ...

add_explicit_mesh_axis_names = AddExplicitMeshAxisNamesContextManager

class RemoveExplicitMeshAxisNamesContextManager:
    axis_names: Incomplete
    def __init__(self, axis_names: AxisName | None) -> None: ...
    prev: Incomplete
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: types.TracebackType | None,
    ) -> None: ...

remove_explicit_mesh_axis_names = RemoveExplicitMeshAxisNamesContextManager

def get_axis_env(): ...
def trace_state_clean() -> bool: ...
def reset_trace_state() -> bool: ...

TRACER_LEAK_DEBUGGER_WARNING: str

@contextmanager
def ensure_no_leaks(trace: Trace): ...
def maybe_find_leaked_tracers(trace: Trace) -> list[Tracer]: ...
def leaked_tracer_error(name: str, t, tracers: list[Tracer]) -> Exception: ...
@contextmanager
def ensure_compile_time_eval() -> Generator[None]: ...
@contextmanager
def eval_context() -> Generator[None]: ...
def full_lower(val): ...
def get_referent(x: Any) -> Any: ...
def same_referent(x: Any, y: Any) -> bool: ...
def dedup_referents(itr: Iterable[Any]) -> list[Any]: ...
def definitely_equal(x, y): ...

class AbstractValue:
    @property
    def is_high(self) -> bool: ...
    @property
    def has_qdd(self) -> bool: ...
    def to_tangent_aval(self) -> None: ...
    def to_cotangent_aval(self) -> None: ...
    def at_least_vspace(self): ...
    def update_weak_type(self, weak_type): ...
    def update_vma(self, vma): ...
    def strip_weak_type(self) -> AbstractValue: ...
    def normalize(self) -> AbstractValue: ...
    def update(self, **kwargs) -> None: ...
    def lo_ty(self): ...
    def lo_ty_qdd(self, qdd) -> None: ...
    def str_short(self, short_dtypes: bool = False, mesh_axis_types: bool = False): ...
    def dec_rank(self, size, spec): ...
    def inc_rank(self, size, spec): ...
    def shard(self, mesh, manual_axes, check_vma, spec): ...
    def unshard(self, mesh, check_vma, spec): ...

type InputType = tuple[AbstractValue]
type OutputType = tuple[AbstractValue]
type Value = Any

def valid_jaxtype(x) -> bool: ...
def mem_kind_to_space(mem_kind: str) -> MemorySpace: ...
def mem_space_to_kind(mem_space: MemorySpace) -> str: ...
def update_aval_with_sharding(aval, sharding, vma=None): ...
def shaped_abstractify(x): ...
def abstractify(x): ...
def get_aval(x: Any) -> Any: ...
def typeof(x: Any, /) -> Any: ...
def is_concrete(x): ...
def to_concrete_value(x): ...
def concretization_function_error(fun, suggest_astype: bool = False): ...
def concrete_or_error(force: Any, val: Any, context: str = ""): ...
def concrete_dim_or_error(val: Any, context: str = ""): ...

class MutableQuasiDynamicData:
    init_val: Incomplete
    cur_val: Incomplete
    def __init__(self, val: QuasiDynamicData | None) -> None: ...
    def update(self, val) -> None: ...

class QuasiDynamicData: ...

@dataclass(frozen=True)
class AvalQDD:
    is_high = ...
    aval: AbstractValue
    qdd: QuasiDynamicData | None
    has_qdd = ...
    def lo_ty(self): ...
    def read_loval(self, val): ...
    def new_from_loval(self, *lovals): ...
    def to_tangent_aval(self): ...

@dataclass(frozen=True)
class AvalMutableQDD:
    aval: AbstractValue
    mutable_qdd: MutableQuasiDynamicData

def cur_qdd(x): ...
def cur_aval_qdd(x): ...
@overload
def physical_aval(aval: ShapedArray) -> ShapedArray: ...
@overload
def physical_aval(aval: AbstractValue) -> AbstractValue: ...
def physical_shape(logical_shape, dtype): ...
def physical_element_aval(edtype: dtypes.ExtendedDType) -> ShapedArray: ...
def canonicalize_shape(shape: Shape, context: str = "") -> tuple[Any, ...]: ...
def canonicalize_dim(d: DimSize, context: str = "") -> DimSize: ...

class ShardingTypeError(Exception): ...

def canonicalize_value(val): ...
def get_cur_mesh_sharding(spec=None): ...
def modify_spec_for_auto_manual(spec, mesh) -> P: ...
def remove_size_one_mesh_axis(spec, mesh) -> P: ...
def get_sharding(sharding, shape): ...
def get_vma(vma, sharding): ...
def get_memory_space(memory_space): ...

class ShapedArray(AbstractValue):
    array_abstraction_level: int
    shape: Incomplete
    dtype: Incomplete
    weak_type: Incomplete
    sharding: Incomplete
    vma: Incomplete
    memory_space: Incomplete
    def __init__(
        self,
        shape,
        dtype,
        weak_type: bool = False,
        *,
        sharding=None,
        vma: frozenset[AxisName] = ...,
        memory_space: MemorySpace = ...,
    ) -> None: ...
    def lower_val(self, val): ...
    def raise_val(self, val): ...
    def lo_ty(self): ...
    def update(self, shape=None, dtype=None, weak_type=None, **kwargs): ...
    ndim: Incomplete
    size: Incomplete
    broadcast: ClassVar[aval_method | None]
    transpose: ClassVar[aval_method | None]
    reshape: ClassVar[aval_method | None]
    def __eq__(self, other): ...
    def __hash__(self): ...
    def __ne__(self, other): ...
    def to_tangent_aval(self): ...
    def to_cotangent_aval(self): ...
    def str_short(self, short_dtypes: bool = False, mesh_axis_types: bool = False): ...
    def update_vma(self, vma): ...
    def update_weak_type(self, weak_type): ...

def str_short_aval(
    shape,
    dtype,
    mesh,
    spec,
    vma,
    memory_space,
    short_dtypes: bool = False,
    mesh_axis_types: bool = False,
) -> str: ...
def order_wrt_mesh(mesh, x): ...
def primal_dtype_to_tangent_dtype(primal_dtype): ...
def primal_spec_to_cotangent_spec(spec): ...
def primal_sharding_to_cotangent_sharding(sharding): ...
def pvary(x, axis_name): ...

pvary_p: Incomplete

def reduced_vary_cast(x, axis_name): ...

reduced_vary_cast_p: Incomplete

def check_unreduced_args(args, axes, name) -> None: ...
def standard_insert_pvary(*args): ...
def standard_vma_rule(prim_name, *avals, **kwargs) -> frozenset[AxisName]: ...

@dataclass(frozen=True)
class bint(dtypes.ExtendedDType):
    bound: int
    @property
    def type(self) -> type: ...
    @property
    def name(self) -> str: ...

type AxisSize = int | Tracer | Var

class RefMeta(type):
    def __instancecheck__(cls, inst): ...

class Ref(metaclass=RefMeta):
    def __init__(self, aval, refs) -> None: ...
    aval: Incomplete
    shape: Incomplete
    size: Incomplete
    ndim: Incomplete
    dtype: Incomplete
    def __getitem__(self, idx): ...
    def __setitem__(self, idx, x) -> None: ...
    def __len__(self) -> int: ...
    def addupdate(self, x, idx=()): ...
    sharding: Incomplete
    format: Incomplete
    committed: Incomplete
    def unsafe_buffer_pointer(self): ...
    @property
    def at(self) -> None: ...

class ArrayRefImpl:
    def __init__(self, aval, buf) -> None: ...

def new_ref(init_val: Any, *, memory_space: Any = None, kind: Any = None): ...

ref_p: Incomplete

def empty_ref(ty, memory_space=None): ...

empty_ref_p: Incomplete

def free_ref(ref: Ref): ...

free_ref_p: Incomplete

class InternalMutableArrayEffect(effects.Effect): ...

array_ref_effect: Incomplete

internal_mutable_array_effect: Incomplete

def freeze(ref: Ref) -> Array: ...

freeze_p: Incomplete

@freeze_p.def_effectful_abstract_eval
def freeze_abstract_eval(ref_aval): ...
def accum_grad_in_ref(x): ...

accum_grad_in_ref_p: Incomplete

class AbstractToken(AbstractValue):
    def str_short(self, short_dtypes: bool = False, mesh_axis_types: bool = False): ...
    def to_tangent_aval(self): ...
    def to_cotangent_aval(self): ...

abstract_token: AbstractToken

def get_token_aval(): ...

class Token:
    def __init__(self, buf) -> None: ...
    def block_until_ready(self) -> None: ...

class AbstractTodo(AbstractValue):
    inner_aval: Incomplete
    def __init__(self, inner_aval) -> None: ...
    def str_short(
        self,
        short_dtypes: bool = False,
        mesh_axis_types: bool = False,
    ) -> str: ...

class InconclusiveDimensionOperation(Exception): ...

def is_symbolic_dim(v: Any) -> bool: ...
def is_constant_dim(d: DimSize) -> bool: ...
def is_dim(v: Any) -> bool: ...
def is_constant_shape(s: Shape) -> bool: ...
def definitely_equal_one_of_dim(d1: DimSize, dlist: Sequence[DimSize]) -> bool: ...
def definitely_equal_shape(s1: Shape, s2: Shape) -> bool: ...
def divide_shape_sizes(s1: Shape, s2: Shape) -> DimSize: ...
def cancel_divide_tracers(num, denom): ...
def is_empty_shape(s: Shape) -> bool: ...
def dilate_dim(d: DimSize, dilation: DimSize) -> DimSize: ...
def stride_dim(d: DimSize, window_size: DimSize, window_stride: DimSize) -> DimSize: ...
def min_dim(d1: DimSize, d2: DimSize) -> DimSize: ...
def max_dim(d1: DimSize, d2: DimSize) -> DimSize: ...
def dimension_as_value(d: DimSize): ...
def canonicalize_slice(
    s: slice,
    axis_size: DimSize,
) -> tuple[DimSize, DimSize, DimSize]: ...

class SomeTracer: ...

def replace_tracer_for_error_message(obj): ...
def evaluate_shape(
    shape: Shape,
    dim_vars: Sequence[str],
    *dim_values: Array,
) -> Sequence[Array]: ...
def dim_value_dtype(): ...
def dim_constant(ct: int): ...
def dim_value_aval() -> AbstractValue: ...

class CallPrimitive(Primitive):
    multiple_results: bool
    call_primitive: bool
    def bind(self, *args, **params): ...
    def bind_with_trace(self, trace, fun_and_args, params): ...
    def get_bind_params(self, params): ...

def call_impl(f: lu.WrappedFun, *args, **params): ...

call_p: CallPrimitive
call: Incomplete

class ClosedCallPrimitive(CallPrimitive):
    def get_bind_params(self, params): ...

closed_call_p: ClosedCallPrimitive

class MapPrimitive(Primitive):
    multiple_results: bool
    map_primitive: bool
    def bind(self, *args, **params): ...
    def bind_with_trace(self, trace, fun_and_args, params): ...
    def process(self, trace, fun, tracers, params): ...
    def get_bind_params(self, params): ...

def mapped_aval(size: AxisSize, axis, aval: AbstractValue) -> AbstractValue: ...
def unmapped_aval(
    size: AxisSize,
    axis: int | None,
    aval: AbstractValue,
    explicit_mesh_axis=None,
) -> AbstractValue: ...

type AvalMapHandlerPair = tuple[Callable, Callable]
aval_mapping_handlers: dict[type, AvalMapHandlerPair]

class _TempAxisName:
    id: Incomplete
    def __init__(self, obj) -> None: ...
    def __hash__(self): ...
    def __eq__(self, other): ...
    def __lt__(self, other): ...

@dataclass(frozen=True)
class NamedAxisEffect(effects.Effect):
    name: AxisName

def filter_named_axis_effects(
    effects: Effects,
    names: Collection[AxisName],
) -> Effects: ...
def remove_named_axis_effects(jaxpr: Jaxpr, names: Collection[AxisName]) -> Jaxpr: ...
def replace_jaxpr_effects(jaxpr: ClosedJaxpr, effects: Effects): ...
def typecheck(aval: AbstractValue, x) -> bool: ...
def typecompat(aval_ref: AbstractValue, aval: AbstractValue) -> bool: ...
def typematch(
    t1: AbstractValue,
    t2: AbstractValue,
    no_dtype_check: bool = False,
) -> bool: ...
def cmp_shape_shd_vma_memsp(t1, t2): ...
def aval_mismatch_extra(a1: AbstractValue, a2: AbstractValue) -> str: ...

class JaxprTypeError(TypeError): ...

custom_typechecks: dict[Primitive, Callable]

def check_jaxpr(jaxpr: Jaxpr): ...

@dataclass(frozen=True)
class MutableTypecheckVal:
    aval: AbstractValue
    mutable_qdd: MutableQuasiDynamicData

def check_type(
    ctx_factory: Callable[[], tuple[JaxprPpContext, JaxprPpSettings]],
    env: dict[Var, Atom | MutableTypecheckVal],
    ty: AbstractValue,
) -> None: ...
def check_eqn(prim, in_avals, params): ...
def eqn_effects(jaxpr): ...

class ShapeDtypeStruct:
    shape: Incomplete
    dtype: Incomplete
    weak_type: Incomplete
    vma: Incomplete
    is_ref: Incomplete
    def __init__(
        self,
        shape,
        dtype,
        *,
        sharding=None,
        weak_type: bool = False,
        vma=None,
        is_ref: bool = False,
    ) -> None: ...
    size: Incomplete
    ndim: Incomplete
    @property
    def sharding(self): ...
    @property
    def format(self): ...
    def __len__(self) -> int: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def __setattr__(self, name, value) -> None: ...
    def update(self, **kwargs): ...

def pp_toplevel_jaxpr(
    jaxpr_to_print: Jaxpr,
    *,
    source_info: bool = False,
    print_shapes: bool = True,
    custom_pp_eqn_rules: bool = True,
    name_stack: bool = False,
    print_effects: bool = False,
) -> pp.Doc: ...

class JaxprPpSettings(NamedTuple):
    print_shapes: bool = ...
    source_info: bool = ...
    name_stack: bool = ...
    custom_pp_eqn_rules: bool = ...
    print_effects: bool = ...

class JaxprPpContext:
    var_names: defaultdict[Var, str]
    shared_jaxprs: MutableMapping[Jaxpr, str]
    shared_jaxpr_names: MutableSet[str]
    def __init__(self) -> None: ...
    def suggest_same_var_names(
        self,
        for_vars: Sequence[Atom],
        like_vars: Sequence[Atom],
    ) -> None: ...

def pp_var(
    v: Var | Literal,
    context: JaxprPpContext,
    *,
    print_literal_dtype: bool = True,
) -> str: ...
def pp_aval(a: AbstractValue, context: JaxprPpContext) -> str: ...
def pp_vars(
    vs: Sequence[Atom],
    context: JaxprPpContext,
    *,
    separator: str = "",
    print_shapes: bool = False,
) -> pp.Doc: ...
def pp_kv_pair(
    k: str,
    v: Any,
    context: JaxprPpContext,
    settings: JaxprPpSettings,
) -> pp.Doc: ...
def pp_kv_pairs(
    kv_pairs,
    context: JaxprPpContext,
    settings: JaxprPpSettings,
) -> pp.Doc: ...
def pp_eqn(
    eqn: JaxprEqn,
    context: JaxprPpContext,
    settings: JaxprPpSettings,
) -> pp.Doc: ...

CustomPpEqnRule: Incomplete
pp_eqn_rules: dict[Primitive, CustomPpEqnRule]

def pp_eqns(
    eqns: Sequence[JaxprEqn],
    context: JaxprPpContext,
    settings: JaxprPpSettings,
) -> pp.Doc: ...
def pp_jaxpr_skeleton(
    jaxpr: Jaxpr,
    eqns_fn,
    context: JaxprPpContext,
    settings: JaxprPpSettings,
) -> pp.Doc: ...
def pp_shared_jaxpr(
    name: str,
    jaxpr: Jaxpr,
    context: JaxprPpContext,
    settings: JaxprPpSettings,
) -> pp.Doc: ...
def pp_jaxpr(
    jaxpr: Jaxpr,
    context: JaxprPpContext,
    settings: JaxprPpSettings,
) -> pp.Doc: ...
def pp_jaxprs(
    jaxprs: Sequence[ClosedJaxpr | Jaxpr],
    context: JaxprPpContext,
    settings: JaxprPpSettings,
) -> pp.Doc: ...
def pp_jaxpr_eqn_range(
    jaxpr: Jaxpr,
    lo: int,
    hi: int,
    context: JaxprPpContext,
    settings: JaxprPpSettings,
) -> pp.Doc: ...
def pp_effect(effect: Effect, context: JaxprPpContext) -> pp.Doc: ...
def last_used(jaxpr: Jaxpr) -> dict[Var, JaxprEqn | None]: ...
def clean_up_dead_vars(
    eqn: JaxprEqn,
    env: dict[Var, Any],
    last_used: dict[Var, JaxprEqn | None],
): ...

shard_aval_handlers: Incomplete
unshard_aval_handlers: Incomplete

def shard_aval(
    mesh,
    manual_axes,
    check_vma,
    spec,
    aval: AbstractValue,
) -> AbstractValue: ...
def unshard_aval(mesh, check_vma, spec, aval: AbstractValue) -> AbstractValue: ...

class OpaqueTraceState:
    def __init__(self, trace_ref) -> None: ...
    def __eq__(self, other): ...

def get_opaque_trace_state(convention=None): ...
def nonempty_axis_env() -> bool: ...
def unsafe_am_i_under_a_jit() -> bool: ...
def unsafe_am_i_under_a_vmap() -> bool: ...
def find_top_trace(_): ...
def unsafe_get_current_trace(): ...
def unsafe_get_trace_stack(trace): ...
def unsafe_get_axis_names() -> list[Any]: ...
def axis_frame(axis_name): ...
