from dataclasses import dataclass
from types import ModuleType

def deprecation_getattr(module, deprecations): ...
def accelerate_getattr_deprecation(module: ModuleType, name: str) -> None: ...
def is_accelerated_attribute(module: ModuleType, name: str) -> bool: ...

@dataclass
class DeprecationState:
    accelerated: bool = ...

def register(deprecation_id: str) -> None: ...
def unregister(deprecation_id: str) -> None: ...
def accelerate(deprecation_id: str) -> None: ...
def is_accelerated(deprecation_id: str) -> bool: ...
def warn(deprecation_id: str, message: str, stacklevel: int) -> None: ...
