from _typeshed import Incomplete
from jax._src import core as core
from jax._src.util import set_module as set_module

export: Incomplete

class _JAXErrorMixin:
    def __init__(self, message: str) -> None: ...

class JAXTypeError(_JAXErrorMixin, TypeError): ...
class JAXIndexError(_JAXErrorMixin, IndexError): ...

class ConcretizationTypeError(JAXTypeError):
    def __init__(self, tracer: core.Tracer, context: str = "") -> None: ...

class NonConcreteBooleanIndexError(JAXIndexError):
    def __init__(self, tracer: core.Tracer) -> None: ...

class TracerArrayConversionError(JAXTypeError):
    def __init__(self, tracer: core.Tracer) -> None: ...

class TracerIntegerConversionError(JAXTypeError):
    def __init__(self, tracer: core.Tracer) -> None: ...

class TracerBoolConversionError(ConcretizationTypeError):
    def __init__(self, tracer: core.Tracer) -> None: ...

class UnexpectedTracerError(JAXTypeError):
    def __init__(self, msg: str) -> None: ...

class KeyReuseError(JAXTypeError): ...
