from collections.abc import Iterator, Mapping
from typing import TypeVar

K = TypeVar("K")
V = TypeVar("V")

class FrozenDict(Mapping[K, V]):
    def __init__(self, d: Mapping[K, V]) -> None: ...
    def __getitem__(self, key: K) -> V: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __iter__(self) -> Iterator[K]: ...
    def __len__(self) -> int: ...
    def get(self, key: K) -> V | None: ...
