from collections.abc import Callable, Hashable
from dataclasses import dataclass
from typing import Any

from _typeshed import Incomplete
from jax._src import (
    ad_util as ad_util,
    api as api,
    config as config,
    core as core,
    dtypes as dtypes,
    effects as effects,
)
from jax._src.api_util import (
    infer_argnums_and_argnames as infer_argnums_and_argnames,
    resolve_kwargs as resolve_kwargs,
)
from jax._src.core import typeof as typeof
from jax._src.custom_derivatives import CustomVJPPrimal as CustomVJPPrimal
from jax._src.errors import UnexpectedTracerError as UnexpectedTracerError
from jax._src.interpreters import (
    ad as ad,
    batching as batching,
    remat as remat,
)
from jax._src.state.types import AbstractRef as AbstractRef
from jax._src.tree_util import (
    broadcast_prefix as broadcast_prefix,
    keystr as keystr,
    register_static as register_static,
    tree_flatten as tree_flatten,
    tree_leaves as tree_leaves,
    tree_leaves_checked as tree_leaves_checked,
    tree_map as tree_map,
    tree_map_with_path as tree_map_with_path,
    tree_structure as tree_structure,
    tree_unflatten as tree_unflatten,
)
from jax._src.util import (
    safe_map as safe_map,
    safe_zip as safe_zip,
    split_list as split_list,
    unzip2 as unzip2,
)

map: Incomplete
unsafe_map: Incomplete
zip: Incomplete
unsafe_zip: Incomplete
type PyTreeOfAvals = Any
type PyTreeDef = Any
type LoVal = Any
type HiVal = Any
Ty: Incomplete
LoType: Incomplete
QDD: Incomplete
ShapedArray: Incomplete

class HiPrimitive(core.Primitive):
    name: Incomplete
    def __init__(self, name) -> None: ...
    def is_high(self, *avals, **params) -> bool: ...
    def is_effectful(self, params) -> bool: ...
    def abstract_eval(self, *arg_avals, **params) -> None: ...
    def to_lojax(self, *lotypes_wrapped_in_hitypes, **params) -> None: ...
    def jvp(self, primals, tangents, **params) -> None: ...
    def transpose(self, *args, **params) -> None: ...

class HiType(core.AbstractValue):
    is_high: bool
    has_qdd: bool
    def __hash__(self): ...
    def __eq__(self, other): ...
    def lo_ty(self) -> list[core.AbstractValue]: ...
    def lower_val(self, hi_val: HiVal) -> list[LoVal]: ...
    def raise_val(self, *lo_vals: LoVal) -> HiVal: ...
    def to_tangent_aval(self) -> HiType: ...
    def to_cotangent_aval(self) -> HiType: ...
    def vspace_zero(self) -> HiVal: ...
    def vspace_add(self, x: HiVal, y: HiVal) -> HiVal: ...
    def dec_rank(self, size: int | None, spec: MappingSpec) -> HiType: ...
    def inc_rank(self, size: int | None, spec: MappingSpec) -> HiType: ...
    def shard(
        self,
        mesh,
        manual_axes: frozenset,
        check_vma: bool,
        spec: HipSpec,
    ) -> HiType: ...
    def unshard(self, mesh, check_vma: bool, spec: HipSpec) -> HiType: ...

class MutableHiType(core.AbstractValue):
    is_high: bool
    has_qdd: bool
    type_state: Incomplete
    def __hash__(self): ...
    def __eq__(self, other): ...
    def lo_ty_qdd(self, state: QDD, /) -> list[core.AbstractValue]: ...
    def lo_ty(self) -> None: ...
    def new_from_loval(self, state: QDD, *vals: LoVal) -> HiVal: ...
    def read_loval(self, state: QDD, val: HiVal) -> list[LoVal]: ...
    def update_from_loval(self, state: QDD, val: HiVal, *lo_vals: LoVal) -> None: ...
    def to_tangent_aval(self) -> HiType: ...
    def to_cotangent_aval(self) -> HiType: ...

def register_hitype(val_cls, typeof_fn) -> None: ...
def hijax_method(f): ...
def new_box(): ...
def box_get(box): ...
def box_set(box, val) -> None: ...

@dataclass(frozen=True)
class BoxTypeState(QDD):
    leaf_avals: tuple[core.AbstractValue, ...]
    treedef: PyTreeDef
    def to_tangent_qdd(self): ...
    def normalize(self): ...

class BoxTy(MutableHiType):
    has_qdd: bool
    get: Incomplete
    set: Incomplete
    def __hash__(self): ...
    def __eq__(self, other): ...
    def str_short(self, short_dtypes: bool = False, **_) -> str: ...
    def lo_ty_qdd(self, box_state): ...
    def new_from_loval(self, box_state: BoxTypeState, *lo_vals) -> Box: ...
    def read_loval(self, box_state: BoxTypeState, box) -> list: ...
    def update_from_loval(self, box_state: BoxTypeState, box, *lo_vals) -> None: ...
    def to_tangent_aval(self): ...

class _BoxMeta(type):
    def __instancecheck__(cls, instance): ...

class Box(metaclass=_BoxMeta):
    def __new__(cls, init_val=None): ...
    def get(self): ...
    def set(self, val) -> None: ...
    def cur_qdd(self): ...
    @property
    def ty(self): ...
    def type_state(self): ...

class BoxEffect(effects.Effect): ...

box_effect: Incomplete

class NewBox(HiPrimitive):
    def is_high(self, *, treedef) -> bool: ...
    def abstract_eval(self, *, treedef): ...
    def to_lojax(self, *, treedef): ...
    def jvp(self, primals, tangents, *, treedef) -> None: ...
    def transpose(self, *args, treedef) -> None: ...

new_box_p: Incomplete

class BoxSet(HiPrimitive):
    multiple_results: bool
    def is_high(self, *leaf_avals, treedef) -> bool: ...
    def abstract_eval(self, box_ty, *leaf_avals, treedef): ...
    def to_lojax(self, box, *leaves, treedef): ...
    def jvp(self, primals, tangents, *, treedef): ...
    def transpose(self, *args, treedef) -> None: ...

box_set_p: Incomplete

class BoxGet(HiPrimitive):
    multiple_results: bool
    def abstract_eval(self, box_ty, *, avals): ...
    def to_lojax(self, box, *, avals): ...
    def jvp(self, primals, tangents, *, avals): ...
    def transpose(self, *args) -> None: ...

box_get_p: Incomplete

class VJPHiPrimitive:
    in_avals: tuple[PyTreeOfAvals, ...]
    out_aval: PyTreeOfAvals
    params: dict[str, Hashable]
    def __init__(self) -> None: ...
    def expand(self, *args) -> None: ...
    def vjp_fwd(self, nzs_in, /, *args) -> None: ...
    def vjp_bwd(self, res, outgrad, *arg_accums): ...
    def vjp_bwd_retval(self, res, outgrad, /) -> None: ...
    def jvp(self, primals, tangents) -> None: ...
    def lin(self, nzs_in, *primals) -> None: ...
    def linearized(self, residuals, *tangents) -> None: ...
    def batch(self, axis_data, args, dims): ...
    def batch_dim_rule(self, axis_data, dims, /) -> None: ...
    def dce(self, used_outs): ...
    def remat(self, _policy, *args): ...
    def __call__(self, *args): ...
    def check(self, *arg_tys) -> None: ...
    def staging(self, trace, source_info, *args): ...
    def __hash__(self): ...
    def __eq__(self, other): ...

class VmapOf(VJPHiPrimitive):
    prim: core.Primitive
    axis_data: batching.AxisData
    in_dims: Any
    out_dim: Any
    in_avals: Incomplete
    out_aval: Incomplete
    params: Incomplete
    def __init__(self, prim, axis_data, in_dims, out_dim) -> None: ...
    def expand(self, *args): ...
    def jvp(self, primals, tangents): ...
    def vjp_fwd(self, in_nzs, *args): ...
    def vjp_bwd_retval(self, res_, g): ...
    def batch_dim_rule(self, axis_data, in_dims): ...

def map_zero(axis_data, d, ct): ...
def unmap_zero(axis_data, d, ct): ...

call_hi_primitive_p: Incomplete

def fake_linear_op(prim, nz_in_flat, rs, *tangents): ...
def flatten_user_linearized(prim, residuals, *tangents_flat): ...

call_hi_primitive_linearized_p: Incomplete

class CustomVJPTraced(VJPHiPrimitive):
    traced: Any
    fwd: Any
    bwd: Any
    symbolic_zeros: Any
    static_argnums: Any
    opt_remat: bool
    in_avals: Incomplete
    out_aval: Incomplete
    params: Incomplete
    def __init__(
        self,
        traced,
        fwd,
        bwd,
        in_avals,
        sym_zeros,
        static_argnums,
        opt_remat,
    ) -> None: ...
    def expand(self, *args): ...
    def vjp_fwd(self, in_nzs, *args): ...
    def vjp_bwd_retval(self, res, out_ct): ...
    def jvp(self, primals, tangents): ...
    def batch_dim_rule(self, axis_data, in_dims): ...

class custom_vjp3:
    fwd: Callable | None
    bwd: Callable | None
    f: Incomplete
    static_argnums: Incomplete
    def __init__(self, f, nondiff_argnums=(), nondiff_argnames=()) -> None: ...
    symz: Incomplete
    opt_remat: Incomplete
    def defvjp(
        self,
        fwd,
        bwd,
        *,
        symbolic_zeros: bool = False,
        optimize_remat: bool = False,
    ): ...
    def __call__(self, *args, **kwargs): ...

class OptRemat(VJPHiPrimitive):
    orig: CustomVJPTraced
    traced_fwd: Any
    in_avals: Incomplete
    out_aval: Incomplete
    params: Incomplete
    def __init__(self, orig, traced_fwd) -> None: ...
    def expand(self, *primals): ...
    def dce(self, used_outs): ...

@dataclass(frozen=True)
class Static:
    val: Any

class MappingSpec: ...

class HipSpec:
    def to_lo(self) -> None: ...
