from collections.abc import (
    Callable as Callable,
    Hashable,
    Sequence,
)
from typing import Any, NamedTuple

from _typeshed import Incomplete
from jax._src import (
    config as config,
    core as core,
    traceback_util as traceback_util,
)
from jax._src.tree_util import (
    KeyPath as KeyPath,
    generate_key_paths as generate_key_paths,
    keystr as keystr,
)
from jax._src.util import (
    curry as curry,
    fun_name as fun_name,
    register_cache as register_cache,
)

class StoreException(Exception): ...
class EmptyStoreValue: ...

class Store:
    def __init__(self) -> None: ...
    def store(self, val) -> None: ...
    def reset(self) -> None: ...
    @property
    def val(self): ...
    def __nonzero__(self): ...
    __bool__ = __nonzero__

class EqualStore:
    def __init__(self) -> None: ...
    @property
    def val(self): ...
    def store(self, val) -> None: ...
    def reset(self) -> None: ...

class WrappedFun:
    f: Callable
    f_transformed: Callable
    transforms: tuple[tuple[Callable, tuple[Hashable, ...]], ...]
    stores: tuple[Store | EqualStore | None, ...]
    params: tuple[tuple[str, Any], ...]
    in_type: core.InputType | None
    debug_info: DebugInfo
    def __init__(
        self,
        f: Callable,
        f_transformed: Callable,
        transforms: tuple[tuple[Callable, tuple[Hashable, ...]], ...],
        stores: tuple[Store | EqualStore | None, ...],
        params: tuple[tuple[str, Hashable], ...],
        in_type: core.InputType | None,
        debug_info: DebugInfo,
    ) -> None: ...
    def wrap(
        self,
        gen,
        gen_static_args,
        out_store: Store | EqualStore | None,
    ) -> WrappedFun: ...
    def populate_stores(self, stores) -> None: ...
    def call_wrapped(self, *args, **kwargs): ...
    def __hash__(self): ...
    def __eq__(self, other): ...
    def replace_debug_info(self, dbg: core.DebugInfo) -> WrappedFun: ...
    def with_unknown_names(self) -> WrappedFun: ...

@curry
def transformation2(gen, fun: WrappedFun, *gen_static_args) -> WrappedFun: ...
@curry
def transformation(gen, fun: WrappedFun, *gen_static_args) -> WrappedFun: ...
@curry
def transformation_with_aux(gen, fun: WrappedFun, *gen_static_args) -> WrappedFun: ...
@curry
def transformation_with_aux2(
    gen,
    fun: WrappedFun,
    *gen_static_args,
    use_eq_store: bool = False,
    unk_names: bool = False,
) -> tuple[WrappedFun, Callable[[], Any]]: ...

class InitialResultPaths: ...

initial_result_paths: Incomplete

class DebugInfo(NamedTuple):
    traced_for: str
    func_src_info: str
    arg_names: tuple[str, ...] | None
    result_paths: (
        tuple[str, ...] | InitialResultPaths | Callable[[], tuple[str, ...]] | None
    )
    def resolve_result_paths(self) -> DebugInfo: ...
    @property
    def func_name(self) -> str: ...
    def replace_func_name(self, name: str) -> DebugInfo: ...
    def set_result_paths(self, ans): ...
    @property
    def func_filename(self) -> str | None: ...
    @property
    def func_lineno(self) -> int | None: ...
    def safe_arg_names(self, expected_count: int) -> tuple[str, ...]: ...
    def assert_arg_names(self, expected_count: int): ...
    def filter_arg_names(self, keep: Sequence[bool]) -> tuple[str, ...] | None: ...
    def safe_result_paths(self, expected_count: int) -> tuple[str, ...]: ...
    def assert_result_paths(self, expected_count: int): ...
    def filter_result_paths(self, keep: Sequence[bool]) -> tuple[str, ...] | None: ...
    def with_unknown_names(self) -> DebugInfo: ...

def wrap_init(f: Callable, params=None, *, debug_info: DebugInfo) -> WrappedFun: ...
def annotate(f: WrappedFun, in_type: core.InputType | None) -> WrappedFun: ...
def cache(
    call: Callable,
    *,
    explain: Callable[[WrappedFun, bool, dict, tuple, float], None] | None = None,
): ...
@transformation2
def hashable_partial(f, *args): ...
def merge_linear_aux(aux1, aux2): ...
