from collections.abc import Sequence

import numpy as np

class TypedInt(int):
    dtype: np.dtype
    def __new__(cls, value: int, dtype: np.dtype): ...
    def __getnewargs__(self): ...

class TypedFloat(float):
    dtype: np.dtype
    def __new__(cls, value: float, dtype: np.dtype): ...
    def __getnewargs__(self): ...

class TypedComplex(complex):
    dtype: np.dtype
    def __new__(cls, value: complex, dtype: np.dtype): ...
    def __getnewargs__(self): ...

typed_scalar_types: set[type]

class TypedNdArray:
    val: np.ndarray
    weak_type: bool
    def __init__(self, val: np.ndarray, weak_type: bool) -> None: ...
    @property
    def dtype(self) -> np.dtype: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def strides(self) -> Sequence[int]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    def __len__(self) -> int: ...
    def __array__(self, dtype=None, copy=None): ...
    def __add__(self, other): ...
    def __sub__(self, other): ...
    def __mul__(self, other): ...
    def __floordiv__(self, other): ...
    def __truediv__(self, other): ...
    def __mod__(self, other): ...
    def __pow__(self, other): ...
    def __radd__(self, other): ...
    def __rsub__(self, other): ...
    def __rmul__(self, other): ...
    def __rtruediv__(self, other): ...
    def __rfloordiv__(self, other): ...
    def __rmod__(self, other): ...
    def __rpow__(self, other): ...
    def __getitem__(self, index): ...
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __complex__(self) -> complex: ...
    def __index__(self) -> int: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
    def __abs__(self): ...
    def reshape(self, *args, **kw): ...
    def item(self, *args): ...
    @property
    def T(self): ...
    @property
    def mT(self): ...
    def clip(self, *args, **kwargs): ...
    def astype(
        self,
        dtype,
        order: str = "K",
        casting: str = "unsafe",
        subok: bool = True,
        copy: bool = True,
    ): ...
    def tobytes(self, order: str = "C"): ...
