from collections.abc import Hashable, Sequence
from typing import Any, NamedTuple

import contextlib
import dataclasses
import enum
import functools
import threading
import types

from _typeshed import Incomplete
from jax._src.lib import xla_client as xc
from jax._src.util import (
    cache as cache,
    safe_zip as safe_zip,
    tuple_delete as tuple_delete,
)

import numpy as np

zip: Incomplete
unsafe_zip: Incomplete
config_ext: Incomplete
type MeshAxisName = Any
ResourceAxisName = Hashable

def show_axes(axes): ...

class ResourceEnv(NamedTuple):
    physical_mesh: Mesh
    def with_mesh(self, mesh: Mesh): ...
    @property
    def physical_resource_axes(self) -> set[ResourceAxisName]: ...
    @property
    def resource_axes(self) -> set[ResourceAxisName]: ...
    @property
    def shape(self): ...
    @property
    def local_shape(self): ...

class AxisType(enum.Enum):
    Auto = ...
    Explicit = ...
    Manual = ...

def all_axis_types_match(axis_types, ty: AxisType) -> bool: ...
def any_axis_types_match(axis_types, ty: AxisType) -> bool: ...

class BaseMesh:
    axis_names: tuple[MeshAxisName, ...]
    shape_tuple: tuple[tuple[str, int], ...]
    axis_types: tuple[AxisType, ...]
    @functools.cached_property
    def are_all_axes_manual(self) -> bool: ...
    @functools.cached_property
    def are_all_axes_auto(self) -> bool: ...
    @functools.cached_property
    def are_all_axes_explicit(self) -> bool: ...
    @functools.cached_property
    def auto_axes(self): ...
    @functools.cached_property
    def explicit_axes(self): ...
    @functools.cached_property
    def manual_axes(self): ...

class Mesh(BaseMesh, contextlib.ContextDecorator):
    devices: np.ndarray
    axis_names: tuple[MeshAxisName, ...]
    axis_types: Incomplete
    def __new__(
        cls,
        devices: np.ndarray | Sequence[xc.Device],
        axis_names: str | Sequence[MeshAxisName],
        axis_types: tuple[AxisType, ...] | None = None,
    ): ...
    def __reduce__(self): ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def __setattr__(self, name, value) -> None: ...
    def __enter__(self): ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: types.TracebackType | None,
    ): ...
    def update(self, devices=None, axis_names=None, axis_types=None): ...
    @functools.cached_property
    def shape(self): ...
    @functools.cached_property
    def shape_tuple(self): ...
    @property
    def axis_sizes(self) -> tuple[int, ...]: ...
    @property
    def size(self): ...
    @property
    def empty(self): ...
    @functools.cached_property
    def is_multi_process(self): ...
    @property
    def local_mesh(self): ...
    @functools.cached_property
    def device_ids(self): ...
    @functools.cached_property
    def local_devices(self): ...
    @functools.cached_property
    def abstract_mesh(self): ...

EMPTY_ENV: Incomplete

class _ThreadResourcesLocalState(threading.local):
    stack: Incomplete
    env: Incomplete
    def __init__(self) -> None: ...

thread_resources: Incomplete

@dataclasses.dataclass(frozen=True)
class AbstractDevice:
    device_kind: str
    num_cores: int | None

class AbstractMesh(BaseMesh):
    axis_sizes: Incomplete
    axis_names: Incomplete
    axis_types: Incomplete
    abstract_device: Incomplete
    size: Incomplete
    def __init__(
        self,
        axis_sizes: tuple[int, ...],
        axis_names: tuple[str, ...],
        axis_types: AxisType | tuple[AxisType, ...] | None = None,
        *,
        abstract_device=None,
    ) -> None: ...
    def __hash__(self): ...
    def __eq__(self, other): ...
    def update(self, axis_sizes=None, axis_names=None, axis_types=None, **kwargs): ...
    @functools.cached_property
    def shape(self): ...
    @functools.cached_property
    def shape_tuple(self): ...
    @property
    def empty(self): ...
    @property
    def abstract_mesh(self): ...
    def update_axis_types(self, name_to_type: dict[MeshAxisName, AxisType]): ...
    @property
    def devices(self) -> None: ...
    @property
    def device_ids(self) -> None: ...
    @property
    def is_multi_process(self) -> None: ...
    @property
    def local_devices(self) -> None: ...
    @property
    def local_mesh(self) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: types.TracebackType | None,
    ) -> None: ...

empty_abstract_mesh: Incomplete
empty_concrete_mesh: Incomplete

class use_abstract_mesh:
    mesh: Incomplete
    def __init__(self, mesh: AbstractMesh) -> None: ...
    prev: Incomplete
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: types.TracebackType | None,
    ) -> None: ...

def get_abstract_mesh() -> AbstractMesh: ...
def get_concrete_mesh() -> Mesh: ...
