from typing import Protocol

class EventListenerWithMetadata(Protocol):
    def __call__(self, event: str, **kwargs: str | int) -> None: ...

class EventDurationListenerWithMetadata(Protocol):
    def __call__(
        self,
        event: str,
        duration_secs: float,
        **kwargs: str | int,
    ) -> None: ...

class EventTimeSpanListenerWithMetadata(Protocol):
    def __call__(
        self,
        event: str,
        start_time: float,
        end_time: float,
        **kwargs: str | int,
    ) -> None: ...

class ScalarListenerWithMetadata(Protocol):
    def __call__(self, event: str, value: float, **kwargs: str | int) -> None: ...

def record_event(event: str, **kwargs: str | int) -> None: ...
def record_event_duration_secs(
    event: str,
    duration: float,
    **kwargs: str | int,
) -> None: ...
def record_event_time_span(
    event: str,
    start_time: float,
    end_time: float,
    **kwargs: str | int,
) -> None: ...
def record_scalar(event: str, value: float, **kwargs: str | int) -> None: ...
def register_event_listener(callback: EventListenerWithMetadata) -> None: ...
def register_event_time_span_listener(
    callback: EventTimeSpanListenerWithMetadata,
) -> None: ...
def register_event_duration_secs_listener(
    callback: EventDurationListenerWithMetadata,
) -> None: ...
def register_scalar_listener(callback: ScalarListenerWithMetadata) -> None: ...
def get_event_duration_listeners() -> list[EventDurationListenerWithMetadata]: ...
def get_event_time_span_listeners() -> list[EventTimeSpanListenerWithMetadata]: ...
def get_event_listeners() -> list[EventListenerWithMetadata]: ...
def get_scalar_listeners() -> list[ScalarListenerWithMetadata]: ...
def clear_event_listeners() -> None: ...
def unregister_event_duration_listener(
    callback: EventDurationListenerWithMetadata,
) -> None: ...
def unregister_event_time_span_listener(
    callback: EventTimeSpanListenerWithMetadata,
) -> None: ...
def unregister_event_listener(callback: EventListenerWithMetadata) -> None: ...
def unregister_scalar_listener(callback: ScalarListenerWithMetadata) -> None: ...
