from typing import Any

from _typeshed import Incomplete
from jax._src.util import (
    use_cpp_class as use_cpp_class,
    use_cpp_method as use_cpp_method,
)

def unpickle_pspec(partitions, unreduced, reduced): ...

type AxisName = Any

class P:
    __match_args__: Incomplete
    UNCONSTRAINED: Incomplete
    unreduced: Incomplete
    reduced: Incomplete
    def __init__(self, *partitions, unreduced=..., reduced=...) -> None: ...
    def __reduce__(self): ...
    def __getitem__(self, i): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def __add__(self, other): ...
    def __radd__(self, other): ...
    def index(self, value): ...
    def count(self, value): ...
    def update(self, **kwargs): ...
    def to_lo(self): ...

PartitionSpec = P
