from collections.abc import (
    Callable as Callable,
    Iterator,
    Sequence,
)
from typing import Any, NamedTuple

from _typeshed import Incomplete
from jax._src import (
    api as api,
    core as core,
    dispatch as dispatch,
    dtypes as dtypes,
    ffi as ffi,
    literals as literals,
    source_info_util as source_info_util,
    tree_util as tree_util,
    typing as typing,
)
from jax._src.api import (
    jit as jit,
    vmap as vmap,
)
from jax._src.dtypes import float0 as float0
from jax._src.export import serialization as serialization
from jax._src.interpreters import (
    ad as ad,
    batching as batching,
    mlir as mlir,
    pxla as pxla,
)
from jax._src.lax import lax as lax
from jax._src.lib import gpu_prng as gpu_prng
from jax._src.lib.mlir import ir as ir
from jax._src.lib.mlir.dialects import hlo as hlo
from jax._src.numpy.array_methods import _IndexUpdateHelper
from jax._src.sharding_impls import (
    NamedSharding as NamedSharding,
    PmapSharding as PmapSharding,
    SingleDeviceSharding as SingleDeviceSharding,
    logical_sharding as logical_sharding,
    physical_sharding as physical_sharding,
)
from jax._src.typing import Array as Array
from jax._src.util import (
    safe_map as safe_map,
    safe_zip as safe_zip,
)

import numpy as np

map: Incomplete
unsafe_map: Incomplete
zip: Incomplete
unsafe_zip: Incomplete
Device: Incomplete
type Shard = Any
type Shape = tuple[int, ...]
UINT_DTYPES: dict[int, np.dtype]

class PRNGImpl(NamedTuple):
    key_shape: Shape
    seed: Callable
    split: Callable
    random_bits: Callable
    fold_in: Callable
    name: str = ...
    tag: str = ...
    def __hash__(self) -> int: ...
    def pprint(self): ...

prngs: dict[str, PRNGImpl]

def register_prng(impl: PRNGImpl): ...

class PRNGKeyArray(Array):
    def __init__(self, impl, key_data: Any) -> None: ...
    def block_until_ready(self): ...
    def copy_to_host_async(self) -> None: ...
    @property
    def aval(self): ...
    @property
    def shape(self): ...
    @property
    def size(self): ...
    @property
    def ndim(self): ...
    @property
    def dtype(self): ...
    @property
    def nbytes(self): ...
    @property
    def itemsize(self): ...
    device: Incomplete
    devices: Incomplete
    is_fully_addressable: Incomplete
    is_fully_replicated: Incomplete
    delete: Incomplete
    is_deleted: Incomplete
    on_device_size_in_bytes: Incomplete
    unsafe_buffer_pointer: Incomplete
    def addressable_data(self, index: int) -> PRNGKeyArray: ...
    @property
    def addressable_shards(self) -> list[Shard]: ...
    @property
    def global_shards(self) -> list[Shard]: ...
    @property
    def sharding(self): ...
    @property
    def committed(self): ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[PRNGKeyArray]: ...
    def pprint(self): ...
    def copy(self): ...
    __hash__: Incomplete
    __array_priority__: int
    def __array__(
        self,
        dtype: np.dtype | None = None,
        copy: bool | None = None,
    ) -> np.ndarray: ...
    @property
    def at(self) -> _IndexUpdateHelper: ...
    @property
    def T(self) -> PRNGKeyArray: ...
    def __getitem__(self, _) -> PRNGKeyArray: ...
    def flatten(self, *_, **__) -> PRNGKeyArray: ...
    def ravel(self, *_, **__) -> PRNGKeyArray: ...
    def reshape(self, *_, **__) -> PRNGKeyArray: ...
    def squeeze(self, *_, **__) -> PRNGKeyArray: ...
    def swapaxes(self, *_, **__) -> PRNGKeyArray: ...
    def take(self, *_, **__) -> PRNGKeyArray: ...
    def transpose(self, *_, **__) -> PRNGKeyArray: ...

def prngkeyarray_flatten(x): ...
def prngkeyarray_unflatten(impl, children): ...
def seed_with_impl(impl: PRNGImpl, seed: int | typing.ArrayLike) -> PRNGKeyArray: ...
def keys_shaped_array(impl, shape, sharding, vma): ...
def base_arr_shape_to_keys_shape(impl, base_arr_shape): ...

class KeyTyRules:
    allow_conversion: bool
    @staticmethod
    def full(shape, fill_value, dtype): ...
    @staticmethod
    def physical_element_aval(dtype) -> core.ShapedArray: ...
    @staticmethod
    def physical_const(val) -> Array: ...
    @staticmethod
    def result_handler(sticky_device, aval): ...
    @staticmethod
    def local_sharded_result_handler(aval, sharding, indices): ...
    @staticmethod
    def global_sharded_result_handler(aval, out_sharding, committed): ...
    @staticmethod
    def make_sharded_array(aval, sharding, arrays, committed): ...
    @staticmethod
    def device_put_sharded(vals, aval, sharding, devices): ...
    @staticmethod
    def device_put_replicated(val, aval, sharding, devices): ...
    @staticmethod
    def tangent_dtype(_): ...
    @staticmethod
    def zero(_): ...

class KeyTy(dtypes.ExtendedDType):
    type: Incomplete
    def __init__(self, impl) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def itemsize(self) -> int: ...
    def __eq__(self, other): ...
    def __hash__(self) -> int: ...

def key_array_shard_arg_handler(
    xs: Sequence[PRNGKeyArray],
    shardings,
    layouts,
    copy_semantics,
): ...
def key_array_constant_handler(x, aval): ...
def iterated_vmap_unary(n, f): ...
def squeeze_vmap(f, left): ...
def iterated_vmap_binary_bcast(shape1, shape2, f): ...
def random_seed(seeds: int | typing.ArrayLike, impl: PRNGImpl) -> PRNGKeyArray: ...

random_seed_p: Incomplete

@random_seed_p.def_abstract_eval
def random_seed_abstract_eval(seeds_aval, *, impl): ...
@random_seed_p.def_impl
def random_seed_impl(seeds, *, impl): ...
def random_seed_impl_base(seeds, *, impl): ...
def random_seed_lowering(ctx, seeds, *, impl): ...
def random_split(keys, shape: Shape): ...

random_split_p: Incomplete

@random_split_p.def_abstract_eval
def random_split_abstract_eval(keys_aval, *, shape): ...
@random_split_p.def_impl
def random_split_impl(keys, *, shape): ...
def random_split_impl_base(impl, base_arr, keys_ndim, *, shape): ...
def random_split_lowering(ctx, keys, *, shape): ...
def random_fold_in(keys, msgs): ...

random_fold_in_p: Incomplete

@random_fold_in_p.def_abstract_eval
def random_fold_in_abstract_eval(keys_aval, msgs_aval): ...
@random_fold_in_p.def_impl
def random_fold_in_impl(keys, msgs): ...
def random_fold_in_impl_base(impl, base_arr, msgs, keys_shape): ...
def random_fold_in_lowering(ctx, keys, msgs): ...
def random_bits(keys, bit_width, shape): ...

random_bits_p: Incomplete

@random_bits_p.def_abstract_eval
def random_bits_abstract_eval(keys_aval, *, bit_width, shape): ...
@random_bits_p.def_impl
def random_bits_impl(keys, *, bit_width, shape): ...
def random_bits_impl_base(impl, base_arr, keys_ndim, *, bit_width, shape): ...
def random_bits_lowering(ctx, keys, *, bit_width, shape): ...
def random_wrap(base_arr, *, impl): ...

random_wrap_p: Incomplete

@random_wrap_p.def_abstract_eval
def random_wrap_abstract_eval(base_arr_aval, *, impl): ...
@random_wrap_p.def_impl
def random_wrap_impl(base_arr, *, impl): ...
def random_wrap_lowering(ctx, base_arr, *, impl): ...
def random_wrap_batch_rule(batched_args, batch_dims, *, impl): ...
def random_unwrap(keys): ...

random_unwrap_p: Incomplete

@random_unwrap_p.def_abstract_eval
def random_unwrap_abstract_eval(keys_aval): ...
@random_unwrap_p.def_impl
def random_unwrap_impl(keys): ...
def random_unwrap_lowering(ctx, keys): ...
def threefry_seed(seed: typing.Array) -> typing.Array: ...

rotate_left: Incomplete

def apply_round(v, rot): ...
def rotate_list(xs): ...
def rolled_loop_step(i, state): ...

threefry2x32_p: Incomplete

def iota_2x32_shape(shape): ...

iota_2x32_shape_p: Incomplete

@iota_2x32_shape_p.def_abstract_eval
def iota_2x32_shape_abstract_eval(*, shape): ...
def bcast_iotas_to_reshaped_iota(
    add: Callable[[ir.Value, ir.Value], ir.Value],
    mul: Callable[[core.DimSize, ir.Value], ir.Value],
    shape: core.Shape,
    iotas: Sequence[ir.Value],
) -> ir.Value: ...
def iota_2x32_shape_lowering(ctx, *, shape): ...
def threefry_2x32(keypair, count): ...
def threefry_split(key: typing.Array, shape: Shape) -> typing.Array: ...
def threefry_fold_in(key: typing.Array, data: typing.Array) -> typing.Array: ...
def threefry_random_bits(key: typing.Array, bit_width, shape): ...

threefry_prng_impl: Incomplete
rbg_prng_impl: Incomplete
unsafe_rbg_prng_impl: Incomplete
