from collections.abc import Callable as Callable
from contextlib import contextmanager
from typing import Any

import http.server
import os

from _typeshed import Incomplete
from jax._src import (
    traceback_util as traceback_util,
    xla_bridge as xla_bridge,
)
from jax._src.lib import (
    _profiler,
    jaxlib_extension_version as jaxlib_extension_version,
)

ProfileData: Incomplete
ProfileEvent: Incomplete
ProfilePlane: Incomplete
logger: Incomplete

class ProfileOptions(_profiler.ProfileOptions): ...

def start_server(port: int) -> _profiler.ProfilerServer: ...
def stop_server() -> None: ...

class _ProfileState:
    profile_session: Incomplete
    log_dir: Incomplete
    create_perfetto_link: bool
    create_perfetto_trace: bool
    lock: Incomplete
    def __init__(self) -> None: ...
    def reset(self) -> None: ...

def set_metadata(key: str, value: str) -> None: ...
def clear_metadata() -> None: ...
def start_trace(
    log_dir: os.PathLike | str,
    create_perfetto_link: bool = False,
    create_perfetto_trace: bool = False,
    profiler_options: ProfileOptions | None = None,
) -> None: ...

class _PerfettoServer(http.server.SimpleHTTPRequestHandler):
    def end_headers(self): ...
    def do_GET(self): ...
    def do_POST(self) -> None: ...

def stop_trace() -> None: ...
def stop_and_get_fdo_profile() -> bytes | str: ...
@contextmanager
def trace(
    log_dir: os.PathLike | str,
    create_perfetto_link: bool = False,
    create_perfetto_trace: bool = False,
    profiler_options: ProfileOptions | None = None,
): ...

class TraceAnnotation(_profiler.TraceMe): ...

class StepTraceAnnotation(TraceAnnotation):
    def __init__(self, name: str, **kwargs) -> None: ...

def annotate_function(func: Callable, name: str | None = None, **decorator_kwargs): ...
def device_memory_profile(backend: str | None = None) -> bytes: ...
def save_device_memory_profile(filename, backend: str | None = None) -> None: ...

class PGLEProfiler:
    retries: int
    percentile: int
    collected_fdo: str | None
    called_times: int
    fdo_profiles: list[Any]
    current_session: _profiler.ProfilerSession | None
    def __init__(self, retries: int, percentile: int) -> None: ...
    def consume_fdo_profile(self) -> str | None: ...
    def is_fdo_consumed(self): ...
    def disable(self) -> None: ...
    def is_enabled(self): ...
    def is_running(self): ...
    @classmethod
    @contextmanager
    def trace(cls, runner: PGLEProfiler | None): ...
