from collections.abc import Iterable, Sequence
from dataclasses import dataclass

from _typeshed import Incomplete

type Segment = tuple[int] | tuple[int, int, int, int] | tuple[int, int, int, int, int]
type Mappings = Sequence[Sequence[Segment]]

@dataclass(frozen=True)
class SourceMap:
    version: int
    sources: Sequence[str]
    sources_content: Sequence[str]
    names: Sequence[str]
    mappings: Mappings
    @classmethod
    def from_json(cls, json_data: str) -> SourceMap: ...
    def to_json(self) -> str: ...

VLQ_SIGN_MASK: int
VLQ_MORE_MASK: int
VLQ_VALUE_MASK: int
VLQ_VALUE_BITWIDTH: int
VLQ_ALPHABET: Incomplete

def make_vlq_decode_table(): ...

VLQ_DECODE_TABLE: Incomplete

def decode_vlq(enc: Iterable[int]) -> int: ...
def encode_vlq(value: int) -> bytes: ...
def decode_segment(enc: Iterable[int]) -> Segment: ...
def encode_segment(seg: Segment) -> bytes: ...
def deserialize_mappings(mappings_str: str) -> Mappings: ...
def serialize_mappings(mappings: Mappings) -> str: ...

class MappingsGenerator:
    def __init__(self) -> None: ...
    def new_group(self) -> None: ...
    def new_segment(self, *seg) -> None: ...
    def mappings(self) -> Mappings: ...
