from collections.abc import (
    Callable as Callable,
    Iterable,
    Iterator,
    Sequence,
)
from typing import Any, Generic, SupportsIndex, TypeVar, overload

import abc
import dataclasses
import weakref

from _typeshed import Incomplete
from jax._src import config as config

logger: Incomplete
Seq = Sequence
type Array = Any
T = TypeVar("T")
T1 = TypeVar("T1")
T2 = TypeVar("T2")
T3 = TypeVar("T3")

@overload
def safe_zip(__arg1: Iterable[T1], /) -> list[tuple[T1]]: ...
@overload
def safe_zip(__arg1: Iterable[T1], __arg2: Iterable[T2], /) -> list[tuple[T1, T2]]: ...
@overload
def safe_zip(
    __arg1: Iterable[T1],
    __arg2: Iterable[T2],
    __arg3: Iterable[T3],
    /,
) -> list[tuple[T1, T2, T3]]: ...
@overload
def safe_zip(
    __arg1: Iterable[Any],
    __arg2: Iterable[Any],
    __arg3: Iterable[Any],
    __arg4: Iterable[Any],
    /,
    *args,
) -> list[tuple[Any, ...]]: ...
@overload
def safe_map(f: Callable[[T1], T], __arg1: Iterable[T1], /) -> list[T]: ...
@overload
def safe_map(
    f: Callable[[T1, T2], T],
    __arg1: Iterable[T1],
    __arg2: Iterable[T2],
    /,
) -> list[T]: ...
@overload
def safe_map(
    f: Callable[[T1, T2, T3], T],
    __arg1: Iterable[T1],
    __arg2: Iterable[T2],
    __arg3: Iterable[T3],
    /,
) -> list[T]: ...
@overload
def safe_map(
    f: Callable[..., T],
    __arg1: Iterable[Any],
    __arg2: Iterable[Any],
    __arg3: Iterable[Any],
    __arg4: Iterable[Any],
    /,
    *args,
) -> list[T]: ...
@overload
def foreach(f: Callable[[T1], Any], __arg1: Iterable[T1], /) -> None: ...
@overload
def foreach(
    f: Callable[[T1, T2], Any],
    __arg1: Iterable[T1],
    __arg2: Iterable[T2],
    /,
) -> None: ...
@overload
def foreach(
    f: Callable[[T1, T2, T3], Any],
    __arg1: Iterable[T1],
    __arg2: Iterable[T2],
    __arg3: Iterable[T3],
    /,
) -> None: ...
@overload
def foreach(
    f: Callable[..., Any],
    __arg1: Iterable[Any],
    __arg2: Iterable[Any],
    __arg3: Iterable[Any],
    __arg4: Iterable[Any],
    /,
    *args,
) -> None: ...
def unzip2(xys: Iterable[tuple[T1, T2]]) -> tuple[tuple[T1, ...], tuple[T2, ...]]: ...
def unzip3(
    xyzs: Iterable[tuple[T1, T2, T3]],
) -> tuple[tuple[T1, ...], tuple[T2, ...], tuple[T3, ...]]: ...
def subvals(lst: Sequence[T], replace: Iterable[tuple[int, T]]) -> tuple[T, ...]: ...
def split_list(args: Sequence[T], ns: Sequence[int]) -> list[list[T]]: ...
def split_list_checked(args: Sequence[T], ns: Sequence[int]) -> list[list[T]]: ...
def partition_list(bs: Sequence[bool], l: Sequence[T]) -> tuple[list[T], list[T]]: ...
def merge_lists(
    bs: Sequence[bool],
    l0: Sequence[T1],
    l1: Sequence[T2],
) -> list[T1 | T2]: ...
def subs_list(
    subs: Sequence[int | None],
    src: Sequence[T],
    base: Sequence[T],
) -> list[T]: ...
def subs_list2(
    subs1: Sequence[int | None],
    subs2: Sequence[int | None],
    src1: Sequence[T],
    src2: Sequence[T],
    base: Sequence[T],
) -> list[T]: ...
def concatenate(xs: Iterable[Sequence[T]]) -> list[T]: ...

flatten = concatenate

def unflatten(xs: Iterable[T], ns: Sequence[int]) -> list[list[T]]: ...
def curry(f): ...

toposort: Callable[[Iterable[Any]], list[Any]]

def cache(max_size: int = 4096, trace_context_in_key: bool | Callable = True): ...
def register_cache(cache: Any, for_what: str): ...
def clear_all_caches() -> None: ...

memoize: Incomplete

def weakref_lru_cache(
    f=None,
    *,
    maxsize: int | None = 2048,
    trace_context_in_key: bool = True,
    explain: Callable | None = None,
): ...

@dataclasses.dataclass(frozen=True, slots=True, weakref_slot=True)
class MultiWeakRefCacheKey:
    weakrefs: tuple[weakref.ref, ...]

class MultiWeakRefPlaceholder: ...

weakref_cache_key_types: set[type]

def is_weakref_cache_key_type(v): ...
def multi_weakref_lru_cache(
    call: Callable,
    *,
    maxsize: int = 2048,
    trace_context_in_key: bool = True,
): ...

class Unhashable:
    val: Incomplete
    def __init__(self, val) -> None: ...
    def __eq__(self, other): ...

class Hashable:
    val: Incomplete
    def __init__(self, val) -> None: ...
    def __hash__(self): ...
    def __eq__(self, other): ...

class WrapKwArgs:
    val: Incomplete
    def __init__(self, val) -> None: ...
    def __hash__(self): ...
    def __eq__(self, other): ...

def wrap_name(transform_name: str, name: str) -> str: ...
def fun_name(fun: Callable, default_name: str = "<unnamed function>") -> str: ...
def fun_qual_name(fun: Callable) -> str: ...
def canonicalize_axis(axis: SupportsIndex, num_dims: int) -> int: ...
def canonicalize_axis_tuple(
    axis: int | Sequence[int] | None,
    ndim: int,
    allow_duplicate: bool = False,
) -> tuple[int, ...]: ...
def moveaxis(x: Array, src: int | Sequence[int], dst: int | Sequence[int]) -> Array: ...
def ceil_of_ratio(x: int, y: int) -> int: ...
def wraps(
    wrapped: Callable,
    namestr: str | None = None,
    docstr: str | None = None,
    **kwargs,
) -> Callable[[T], T]: ...
def assert_unreachable(x) -> None: ...
def tuple_insert(t: tuple[T, ...], idx: int, val: T) -> tuple[T, ...]: ...
def tuple_delete(t: tuple[T, ...], idx: int) -> tuple[T, ...]: ...
def tuple_update(t: tuple[T, ...], idx: int, val: T) -> tuple[T, ...]: ...

class HashableFunction:
    f: Incomplete
    closure: Incomplete
    def __init__(self, f, closure) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def __call__(self, *args, **kwargs): ...

def as_hashable_function(closure): ...

class HashablePartial:
    f: Incomplete
    args: Incomplete
    kwargs: Incomplete
    def __init__(self, f, *args, **kwargs) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def __call__(self, *args, **kwargs): ...

def maybe_named_axis(axis, if_pos, if_named): ...
def distributed_debug_log(*pairs) -> None: ...
def stable_unique(it: Iterable[T]) -> Iterable[T]: ...

class OrderedSet(Generic[T]):
    elts_set: set[T]
    elts_list: list[T]
    def __init__(self) -> None: ...
    def add(self, elt: T) -> None: ...
    def update(self, elts: Seq[T]) -> None: ...
    def __iter__(self) -> Iterator[T]: ...
    def __len__(self) -> int: ...
    def __contains__(self, elt: T) -> bool: ...

class HashableWrapper:
    x: Any
    hash: int | None
    def __init__(self, x) -> None: ...
    def __hash__(self): ...
    def __eq__(self, other): ...

def set_module(module: str) -> Callable[[T], T]: ...
def use_cpp_class(cpp_cls: type[Any]) -> Callable[[type[T]], type[T]]: ...
def use_cpp_method(is_enabled: bool = True) -> Callable[[T], T]: ...

class StrictABCMeta(abc.ABCMeta):
    def register(cls, subclass) -> None: ...
    __instancecheck__: Incomplete
    __subclasscheck__: Incomplete

class StrictABC(metaclass=StrictABCMeta): ...

test_event_listener: Callable | None

def test_event(name: str, *args) -> None: ...

Mutex: Incomplete

def pprint_bytes(num_bytes: float) -> str: ...

install_failure_signal_handler: Incomplete
