from typing import Any

from _typeshed import Incomplete
from jax._src import config as config
from jax._src.lib import xla_client as xla_client

config_ext: Incomplete

class XlaMetadata:
    val: dict[str, Any]
    hash: Incomplete
    def __init__(self, val) -> None: ...
    def __hash__(self): ...
    def __eq__(self, other): ...

def filter_nones(d: dict) -> dict: ...
def update_metadata(a, b: dict[str, Any]): ...
def current_xla_metadata() -> dict[str, Any] | None: ...
