from collections.abc import Callable, Mapping, Sequence
from typing import Any

import dataclasses

from _typeshed import Incomplete
from jax._src import (
    config as config,
    distributed as distributed,
    hardware_utils as hardware_utils,
    traceback_util as traceback_util,
    util as util,
)
from jax._src.cloud_tpu_init import get_tpu_library_path as get_tpu_library_path
from jax._src.lib import (
    jaxlib_extension_version as jaxlib_extension_version,
    xla_client as xla_client,
)

logger: Incomplete
jax_plugins: Any | None
FORCE_FORWARD_COMPAT_LOWERING_PLATFORMS: set[str]
MIN_COMPUTE_CAPABILITY: int
BACKEND_TARGET: Incomplete
CUDA_VISIBLE_DEVICES: Incomplete
MOCK_NUM_GPU_PROCESSES: Incomplete
MOCK_GPU_TOPOLOGY: Incomplete
FORCE_DCN_CROSS_HOST_TRANSFERS: Incomplete
SORT_DEVICES_BY_PROCESS_INDEX: Incomplete
CROSS_HOST_TRANSFER_SOCKET_ADDRESS: Incomplete
CROSS_HOST_TRANSPORT_ADDRESSES: Incomplete
CROSS_HOST_TRANSFER_TIMEOUT_SECONDS: Incomplete
CROSS_HOST_TRANSFER_TRANSFER_SIZE: Incomplete

def make_tpu_client(
    library_path: str | None = None,
    options: _NameValueMapping | None = None,
): ...
def tpu_client_timer_callback(timer_secs: float) -> xla_client.Client | None: ...

BackendFactory: Incomplete
TopologyFactory: Incomplete

@dataclasses.dataclass
class BackendRegistration:
    factory: BackendFactory
    priority: int
    fail_quietly: bool = ...
    experimental: bool = ...
    c_api: Any | None = ...

def register_backend_factory(
    name: str,
    factory: BackendFactory,
    *,
    priority: int = 0,
    fail_quietly: bool = True,
    experimental: bool = False,
    make_topology: TopologyFactory | None = None,
    c_api: Any | None = None,
) -> None: ...
def make_cpu_client(
    collectives: xla_client._xla.CpuCollectives | None = None,
) -> xla_client.Client: ...
def get_num_nodes_from_gpu_topology(topology: str) -> int: ...
def discover_pjrt_plugins() -> None: ...

type OptionsDict = Mapping[str, str | int | list[int] | float | bool]

def make_pjrt_c_api_client(
    plugin_name: str,
    options: OptionsDict | Callable[[], OptionsDict] | None = None,
) -> xla_client.Client: ...
def register_plugin(
    plugin_name: str,
    *,
    priority: int = 400,
    library_path: str | None = None,
    options: OptionsDict | Callable[[], OptionsDict] | None = None,
    c_api: Any | None = None,
    factory: BackendFactory | None = None,
    make_topology: TopologyFactory | None = None,
) -> Any: ...
def register_pjrt_plugin_factories_from_env() -> None: ...
def known_platforms() -> set[str]: ...
def is_known_platform(platform: str) -> bool: ...
def canonicalize_platform(platform: str) -> str: ...
def expand_platform_alias(platform: str) -> list[str]: ...
def backends_are_initialized() -> bool: ...
def register_plugin_callbacks(callback) -> None: ...
def backends() -> dict[str, xla_client.Client]: ...
def get_backend(
    platform: str | xla_client.Client | None = None,
) -> xla_client.Client: ...
def get_device_backend(
    device: xla_client.Device | None = None,
) -> xla_client.Client: ...
def device_count(backend: str | xla_client.Client | None = None) -> int: ...
def local_device_count(backend: str | xla_client.Client | None = None) -> int: ...
def devices(
    backend: str | xla_client.Client | None = None,
) -> list[xla_client.Device]: ...
def default_backend() -> str: ...
def backend_pjrt_c_api_version(platform=None) -> tuple[int, int] | None: ...
def backend_xla_version(platform=None) -> int | None: ...
def backend_stablehlo_version(platform=None) -> Sequence[int] | None: ...
def local_devices(
    process_index: int | None = None,
    backend: str | xla_client.Client | None = None,
    host_id: int | None = None,
) -> list[xla_client.Device]: ...
def process_index(backend: str | xla_client.Client | None = None) -> int: ...
def host_id(backend: str | xla_client.Client | None = None) -> int: ...
def process_count(backend: str | xla_client.Client | None = None) -> int: ...
def host_count(backend: str | xla_client.Client | None = None) -> int: ...
def process_indices(backend: str | xla_client.Client | None = None) -> list[int]: ...
def host_ids(backend: str | xla_client.Client | None = None) -> list[int]: ...
def using_pjrt_c_api(backend=None): ...
def make_pjrt_topology(platform: str, topology_name: str = "", **kwargs): ...
def make_pjrt_tpu_topology(topology_name: str = "", **kwargs): ...

num_cpu_devices: Incomplete
cpu_get_local_topology_timeout_minutes: Incomplete
cpu_get_global_topology_timeout_minutes: Incomplete
