from collections.abc import Sequence
from typing import Any, Literal

import dataclasses
import enum

from _typeshed import Incomplete
from jax import (
    lax as lax,
    tree_util as tree_util,
)
from jax._src import state as state
from jax._src.pallas.mosaic import (
    core as tpu_core,
    tpu_info as tpu_info,
)
from jax.experimental import pallas as pl

import jax

SMEM: Incomplete
VMEM: Incomplete
HBM: Incomplete
ANY: Incomplete
REF: Incomplete
GridDimensionSemantics: Incomplete
PARALLEL: Incomplete
ARBITRARY: Incomplete
SemaphoreType: Incomplete
SemaphoreTuple: Incomplete
ArrayRef: Incomplete
GridIndices: Incomplete
CondVal: Incomplete
PipelineBlockSpecs: Incomplete
type PipelineRefs = Sequence[REF] | Any

class BufferType(enum.Enum):
    INPUT = 1
    OUTPUT = 2
    ACCUMULATOR = 3
    INPUT_OUTPUT = 4
    MANUAL = 5
    @property
    def is_input(self): ...
    @property
    def is_output(self): ...

class BufferedRefBase:
    @property
    def spec(self) -> pl.BlockSpec: ...
    @property
    def buffer_type(self) -> BufferType: ...
    @property
    def is_buffered(self) -> bool: ...
    @property
    def is_input(self): ...
    @property
    def is_output(self): ...
    @property
    def is_accumulator(self): ...
    @property
    def is_input_output(self): ...
    @property
    def is_manual(self): ...
    def init_slots(self) -> None: ...
    def advance_copy_in_slot(self, predicate: bool = True) -> BufferedRefBase: ...
    def advance_wait_in_slot(self, predicate: bool = True) -> BufferedRefBase: ...
    def advance_copy_out_slot(self, predicate: bool = True) -> BufferedRefBase: ...
    def advance_wait_out_slot(self, predicate: bool = True) -> BufferedRefBase: ...
    def load_slots(self, predicate: bool | jax.Array = True) -> BufferedRefBase: ...
    def save_slots(self, predicate: bool | jax.Array = True): ...
    @property
    def block_shape(self) -> Sequence[pl.BlockDim | int | None] | None: ...
    @property
    def compute_index(self): ...
    def get_dma_slice(self, src_ty, grid_indices): ...
    def bind_existing_ref(self, window_ref, indices): ...
    def unbind_refs(self): ...
    def with_spec(self, spec: pl.BlockSpec) -> BufferedRefBase: ...

@dataclasses.dataclass(frozen=True)
class BufferedRef(BufferedRefBase):
    window_ref: ArrayRef | None
    accum_ref: ArrayRef | None
    copy_in_slot: ArrayRef | None
    wait_in_slot: ArrayRef | None
    copy_out_slot: ArrayRef | None
    wait_out_slot: ArrayRef | None
    next_fetch_smem: Sequence[jax.Array] | None
    next_fetch_sreg: Sequence[jax.Array] | None
    sem_recvs: SemaphoreTuple | None
    sem_sends: SemaphoreTuple | None
    swap: ArrayRef | None
    tiling: tpu_info.Tiling | None = ...
    def __post_init__(self) -> None: ...
    @property
    def spec(self): ...
    @property
    def buffer_type(self): ...
    @property
    def is_buffered(self) -> bool: ...
    @property
    def use_lookahead(self) -> bool: ...
    @property
    def buffer_count(self) -> int: ...
    @staticmethod
    def buffer_types() -> type[BufferType]: ...
    @classmethod
    def create(
        cls,
        spec: pl.BlockSpec,
        dtype_or_type,
        buffer_type,
        buffer_count,
        needs_swap_ref: bool = True,
        grid_rank: int = 0,
        use_lookahead: bool = False,
        source_memory_space: tpu_core.MemorySpace | Literal[ANY] = ...,
        tiling: tpu_info.Tiling | None = None,
    ) -> BufferedRef: ...
    @classmethod
    def input(cls, spec, dtype_or_type, buffer_count: int = 2, **kwargs): ...
    @classmethod
    def output(cls, spec, dtype_or_type, buffer_count: int = 2, **kwargs): ...
    @classmethod
    def accumulator(cls, spec, dtype_or_type, buffer_count: int = 2, **kwargs): ...
    @classmethod
    def input_output(cls, spec, dtype_or_type, buffer_count: int = 2, **kwargs): ...
    @property
    def block_shape(self): ...
    @property
    def compute_index(self): ...
    def with_spec(self, spec: pl.BlockSpec) -> BufferedRef: ...
    def with_next_fetch(self, next_fetch: Sequence[jax.Array] | None = None): ...
    def with_slot_index(
        self,
        copy_in_slot: int | jax.Array | None = None,
        copy_out_slot: int | jax.Array | None = None,
        wait_in_slot: int | jax.Array | None = None,
        wait_out_slot: int | jax.Array | None = None,
    ) -> BufferedRef: ...
    @property
    def current_ref(self): ...
    @property
    def cumulative_copy_in(self): ...
    @property
    def current_copy_in_slot(self): ...
    @property
    def cumulative_copy_out(self): ...
    @property
    def current_copy_out_slot(self): ...
    @property
    def cumulative_wait_in(self): ...
    @property
    def current_wait_in_slot(self): ...
    @property
    def cumulative_wait_out(self): ...
    @property
    def current_wait_out_slot(self): ...
    @property
    def next_fetch_indices(self): ...
    def bind_existing_ref(self, window_ref, indices): ...
    def unbind_refs(self): ...
    def compute_slice(self, grid_indices): ...
    def init_slots(self) -> None: ...
    def advance_copy_in_slot(
        self,
        predicate: bool | jax.Array = True,
    ) -> BufferedRef: ...
    def advance_wait_in_slot(
        self,
        predicate: bool | jax.Array = True,
    ) -> BufferedRef: ...
    def advance_copy_out_slot(
        self,
        predicate: bool | jax.Array = True,
    ) -> BufferedRef: ...
    def advance_wait_out_slot(
        self,
        predicate: bool | jax.Array = True,
    ) -> BufferedRef: ...
    def load_slots(self, predicate: bool | jax.Array = True) -> BufferedRef: ...
    def save_slots(self, predicate: bool | jax.Array = True): ...
    def copy_in(self, src_ref, grid_indices) -> None: ...
    def copy_out(self, dst_ref, grid_indices) -> None: ...
    def wait_in(self, src_ref, grid_indices) -> None: ...
    def wait_out(self, dst_ref, grid_indices) -> None: ...
    def set_accumulator(self, init: bool = False) -> None: ...
    def accumulate(self) -> None: ...

def fetch_with_lookahead(
    buffered_ref,
    src_ref,
    grid,
    grid_offsets,
    predicate: jax.Array | bool = True,
    max_num_fetches: int | None = None,
    update_slots: bool = True,
): ...

map_brefs: Incomplete

def map_inputs(f, *args): ...
def map_outputs(f, *args): ...

class Scheduler:
    step: Incomplete
    grid: Incomplete
    grid_offsets: Incomplete
    num_stages: Incomplete
    first_cycle: Incomplete
    last_cycle: Incomplete
    init_accumulators: Incomplete
    trace_scopes: Incomplete
    num_steps: Incomplete
    first_step: Incomplete
    last_step: Incomplete
    first_step_ever: Incomplete
    last_step_ever: Incomplete
    indices: Incomplete
    prev_indices: Incomplete
    next_indices: Incomplete
    add_offset: Incomplete
    fetch_indices: Incomplete
    def __init__(
        self,
        step: jax.Array,
        indices: tuple[int | jax.Array, ...],
        grid: tuple[int | jax.Array, ...],
        grid_offsets: tuple[int | jax.Array, ...],
        num_stages: int,
        first_cycle: jax.Array | bool,
        last_cycle: jax.Array | bool,
        init_accumulators=None,
        trace_scopes: bool = True,
    ) -> None: ...
    def grid_env(self): ...
    def out_of_fetch(self, buffered_ref): ...
    def has_changed(self, buffered_ref): ...
    def will_change_current(self, buffered_ref): ...
    def will_change_fetch(self, buffered_ref): ...
    def alias_local_refs(self, buffered_ref, ref): ...
    def unalias_local_refs(self, buffered_ref): ...
    def initialize_step(self, buffered_ref, src_ref, schedule=None, step: int = 0): ...
    def wait_in(self, buffered_ref, src_ref, schedule=None) -> BufferedRef: ...
    def copy_in(self, buffered_ref, src_ref, schedule=None) -> BufferedRef: ...
    def prefetch(self, buffered_ref, src_ref, schedule=None) -> None: ...
    def wait_out(self, buffered_ref, dst_ref, schedule=None) -> BufferedRef: ...
    def copy_out(self, buffered_ref, dst_ref, schedule=None) -> BufferedRef: ...
    def finalize(self, buffered_ref, dst_ref, schedule=None) -> None: ...
    def advance_slots(self, buffered_ref, schedule=None): ...

def skip_input_copies_when_init_accumulators(schedule) -> Any: ...
def get_pipeline_schedule(schedule) -> Any: ...
def make_pipeline_allocations(
    *refs,
    in_specs=(),
    out_specs=(),
    tiling: tpu_info.Tiling | None = None,
    should_accumulate_out: bool = False,
    needs_swap_ref: bool = True,
    grid=(),
): ...
def sync_copy(src: REF | BufferedRef, dst: REF | BufferedRef, indices): ...
def emit_pipeline(
    body,
    *,
    grid: tuple[int | jax.Array, ...],
    in_specs=(),
    out_specs=(),
    tiling: tpu_info.Tiling | None = None,
    should_accumulate_out: bool = False,
    core_axis: int | None = None,
    core_axis_name: str | None = None,
    dimension_semantics: tuple[GridDimensionSemantics, ...] | None = None,
    trace_scopes: bool = True,
    no_pipelining: bool = False,
): ...
def emit_pipeline_with_allocations(
    body,
    *,
    grid,
    in_specs=(),
    out_specs=(),
    should_accumulate_out: bool = False,
): ...
