from enum import Enum
from typing import Any, Self

import torch

from ._tv_tensor import TVTensor

"""
This type stub file was generated by pyright.
"""

class BoundingBoxFormat(Enum):
    XYXY = ...
    XYWH = ...
    CXCYWH = ...
    XYWHR = ...
    CXCYWHR = ...
    XYXYXYXY = ...

def is_rotated_bounding_format(format: BoundingBoxFormat | str) -> bool: ...

type CLAMPING_MODE_TYPE = str | None

class BoundingBoxes(TVTensor):
    format: BoundingBoxFormat
    canvas_size: tuple[int, int]
    clamping_mode: CLAMPING_MODE_TYPE
    def __new__(
        cls,
        data: Any,
        *,
        format: BoundingBoxFormat | str,
        canvas_size: tuple[int, int],
        clamping_mode: CLAMPING_MODE_TYPE = ...,
        dtype: torch.dtype | None = ...,
        device: torch.device | str | int | None = ...,
        requires_grad: bool | None = ...,
    ) -> Self: ...
    def __repr__(self, *, tensor_contents: Any = ...) -> str: ...
