_TORCHFUNCTION_SUBCLASS = ...

class _ReturnTypeCM:
    def __init__(self, to_restore) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *args): ...

def set_return_type(return_type: str): ...

_FORCE_TORCHFUNCTION_SUBCLASS = ...
