from collections.abc import Callable, Mapping, Sequence
from typing import Any, Self, TypeVar

from torch.types import _device, _dtype, _size

import torch

"""
This type stub file was generated by pyright.
"""
D = TypeVar("D", bound=TVTensor)

class TVTensor(torch.Tensor):
    @classmethod
    def __torch_function__(
        cls,
        func: Callable[..., torch.Tensor],
        types: tuple[type[torch.Tensor], ...],
        args: Sequence[Any] = ...,
        kwargs: Mapping[str, Any] | None = ...,
    ) -> torch.Tensor: ...
    @property
    def shape(self) -> _size: ...
    @property
    def ndim(self) -> int: ...
    @property
    def device(self) -> _device: ...
    @property
    def dtype(self) -> _dtype: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> Self: ...
