from typing import Any, Self

import torch

from ._tv_tensor import TVTensor

"""
This type stub file was generated by pyright.
"""

class Video(TVTensor):
    def __new__(
        cls,
        data: Any,
        *,
        dtype: torch.dtype | None = ...,
        device: torch.device | str | int | None = ...,
        requires_grad: bool | None = ...,
    ) -> Self: ...
    def __repr__(self, *, tensor_contents: Any = ...) -> str: ...
