from typing import Any, TypeVar

import typing as tp

from flax import struct as struct
from flax.core import meta as meta
from flax.nnx import (
    spmd as spmd,
    traversals as traversals,
    variablelib as variablelib,
)
from flax.typing import LogicalNames as LogicalNames

import jax

A = TypeVar("A")
B = TypeVar("B")

def sort_variable_types(types: tp.Iterable[type]): ...

class NNXMeta(struct.PyTreeNode, meta.AxisMetadata[A]):
    var_type: type[variablelib.Variable[tp.Any]] = struct.field(pytree_node=False)
    value: Any = struct.field(pytree_node=True)
    metadata: dict[str, tp.Any] = struct.field(pytree_node=False)
    def unbox(self) -> A: ...
    def replace_boxed(self, val: B) -> NNXMeta[B]: ...
    def add_axis(self, index: int, params: dict[Any, Any]) -> NNXMeta[A]: ...
    def remove_axis(self, index: int, params: dict[Any, Any]) -> NNXMeta[A]: ...
    def get_partition_spec(self) -> jax.sharding.PartitionSpec: ...
    def to_nnx_variable(self) -> variablelib.Variable: ...

def is_vanilla_variable(vs: variablelib.Variable) -> bool: ...
def to_linen_var(vs: variablelib.Variable) -> meta.AxisMetadata: ...
def get_col_name(keypath: tp.Sequence[Any]) -> str: ...
def to_nnx_var(col: str, x: meta.AxisMetadata | Any) -> variablelib.Variable: ...
def linen_vars_to_nnx_attrs(variables: tp.Mapping[str, Any]) -> dict[str, Any]: ...
def nnx_attrs_to_linen_vars(nnx_attrs: dict) -> dict: ...
def with_partitioning(
    fn: tp.Callable[..., tp.Any],
    names: LogicalNames,
    mesh: jax.sharding.Mesh | None = None,
) -> tp.Callable[..., meta.Partitioned[tp.Any]]: ...
