from typing import Any

from packaging import version
from transformers.cache_utils import (
    Cache as HFCacheBase,
    CacheLayerMixin,
)
from transformers.generation import GenerationMixin
from transformers.utils.deprecation import deprecate_kwarg

import torch

_TF_VERSION = ...
_NEED_NEW = ...
_IS_TRANSFORMERS_4_56_PLUS = ...
if version.parse(_TF_VERSION) > version.parse(_NEED_NEW): ...
else:
    CacheLayerMixin = ...

class FLALayer(CacheLayerMixin):
    is_compileable = ...
    is_sliding = ...
    def __init__(self) -> None: ...
    def lazy_initialization(self, key_states: torch.Tensor) -> None: ...
    def update(
        self,
        *,
        recurrent_state: torch.Tensor | tuple[torch.Tensor, ...] | None = ...,
        attn_state: tuple[torch.Tensor, ...] | None = ...,
        conv_state: Any | None = ...,
        ffn_state: Any | None = ...,
        offset: int = ...,
        cache_kwargs: dict[str, Any] | None = ...,
        **_: Any,
    ) -> dict[str, Any]: ...
    def get_seq_length(self, cache_position=...) -> int: ...
    def get_max_cache_shape(self) -> int: ...
    def get_mask_sizes(self, cache_position: torch.Tensor) -> tuple[int, int]: ...
    def offload(self) -> None: ...
    def prefetch(self) -> None: ...
    def reset(self) -> None: ...

class LegacyFLACache(HFCacheBase):
    is_compileable = ...
    def __init__(self, seen_tokens: int = ...) -> LegacyFLACache: ...
    def __getitem__(self, layer_idx: int) -> dict[str, Any]: ...
    def __iter__(self) -> Generator[dict[str, Any], Any, None]: ...
    def __len__(self) -> int: ...
    def update(
        self,
        recurrent_state: tuple[torch.Tensor] | None = ...,
        attn_state: tuple[torch.Tensor] | None = ...,
        conv_state: tuple[torch.Tensor] | None = ...,
        ffn_state: tuple[torch.Tensor] | None = ...,
        layer_idx: int = ...,
        offset: int | None = ...,
        cache_kwargs: dict[str, Any] | None = ...,
    ) -> dict[str, Any]: ...
    def get_seq_length(self, layer_idx: int | None = ...) -> int: ...
    def get_max_cache_shape(self) -> int | None: ...
    def to_legacy_cache(self) -> tuple: ...
    @classmethod
    @torch.compiler.disable
    def from_legacy_cache(
        cls, past_key_values: tuple | None = ..., seen_tokens: int = ...
    ) -> LegacyFLACache: ...

class FLACache(HFCacheBase):
    is_compileable = ...
    def __init__(self, seen_tokens: int = ..., **kwargs) -> None: ...
    def update(
        self,
        recurrent_state: tuple[torch.Tensor] | None = ...,
        attn_state: tuple[torch.Tensor] | None = ...,
        conv_state: tuple[torch.Tensor] | None = ...,
        ffn_state: tuple[torch.Tensor] | None = ...,
        layer_idx: int = ...,
        offset: int | None = ...,
        cache_kwargs: dict[str, Any] | None = ...,
    ) -> dict[str, Any]: ...
    def __getitem__(self, layer_idx: int) -> dict[str, Any]: ...
    def __iter__(self) -> Generator[dict[str, Any], Any, None]: ...
    def __len__(self): ...
    def get_seq_length(
        self, layer_idx: int | None = ..., cache_position=...
    ) -> int: ...
    def get_max_cache_shape(self, layer_idx: int = ...) -> int: ...
    def get_mask_sizes(
        self, cache_position: torch.Tensor, layer_idx: int
    ) -> tuple[int, int]: ...
    def to_legacy_cache(self) -> tuple[dict[str, Any], ...]: ...
    @classmethod
    @torch.compiler.disable
    def from_legacy_cache(
        cls,
        past_key_values: tuple[dict[str, Any], ...] | None = ...,
        seen_tokens: int = ...,
        **kwargs,
    ) -> FLACache: ...

class FLAGenerationMixin(GenerationMixin):
    def __init__(self, *args, **kwargs) -> None: ...
    @deprecate_kwarg("num_logits_to_keep", version="4.50", new_name="logits_to_keep")
    def prepare_inputs_for_generation(
        self,
        input_ids: torch.LongTensor = ...,
        past_key_values: HFCacheBase | None = ...,
        attention_mask: torch.Tensor | None = ...,
        inputs_embeds: torch.Tensor | None = ...,
        use_cache: bool = ...,
        logits_to_keep: int | None = ...,
        cache_position: torch.LongTensor | None = ...,
        **kwargs,
    ) -> dict[str, Tensor]: ...

if version.parse(_TF_VERSION) > version.parse(_NEED_NEW):
    class Cache(FLACache):
        def __init__(self, seen_tokens: int = ..., **kwargs: Any) -> None: ...

else:
    class Cache(LegacyFLACache):
        def __init__(self, seen_tokens: int = ..., **kwargs: Any) -> None: ...
