from collections.abc import Callable
from typing import ClassVar, TypeVar

import threading

"""Generic backend dispatch system for FLA operations."""
logger = ...
F = TypeVar("F", bound=Callable)
_DISPATCH_DISABLED = ...

class BaseBackend:
    backend_type: ClassVar[str] = ...
    package_name: ClassVar[str | None] = ...
    env_var: ClassVar[str | None] = ...
    default_enable: ClassVar[bool] = ...
    priority: ClassVar[int] = ...
    @classmethod
    def is_available(cls) -> bool: ...
    @classmethod
    def is_enabled(cls) -> bool: ...
    @classmethod
    def can_use(cls) -> bool: ...
    def verify(self, func_name: str, *args, **kwargs) -> tuple[bool, str | None]: ...

class BackendRegistry:
    _registries: ClassVar[dict[str, BackendRegistry]] = ...
    _initialized: ClassVar[set[str]] = ...
    _init_lock: ClassVar[threading.Lock] = ...
    def __init__(self, operation_name: str) -> None: ...
    def register(self, backend: BaseBackend) -> None: ...
    def get_active(self) -> BaseBackend | None: ...
    @classmethod
    def ensure_initialized(cls, operation: str) -> None: ...

def dispatch(operation: str) -> Callable[..., F]: ...

__all__ = ["BackendRegistry", "BaseBackend", "dispatch"]
