from typing import NamedTuple

from optax._src import (
    base as base,
    clipping as clipping,
    transform as transform,
    wrappers as wrappers,
)

import chex

class ExampleState(NamedTuple):
    total: chex.Numeric

class ExampleStatefulSchedule(base.StatefulSchedule):
    def init(self) -> ExampleState: ...
    def update(self, state: ExampleState, **extra_args) -> ExampleState: ...
    def __call__(self, state: ExampleState, **extra_args) -> chex.Numeric: ...

class InjectHyperparamsTest(chex.TestCase):
    @chex.all_variants
    def test_updates(self): ...
    @chex.all_variants
    def test_hyperparams_state(self) -> None: ...
    @chex.all_variants
    def test_constant_hyperparams(self) -> None: ...
    @chex.all_variants
    def test_overriding_hyperparam(self) -> None: ...
    @chex.all_variants
    def test_static_args(self, static_args): ...
    @chex.all_variants
    def test_numeric_static_args(self, static_args) -> None: ...
    @chex.all_variants
    def test_prng_key_not_hyperparameter(self): ...
    @chex.all_variants
    def test_hyperparam_dtypes(self, hyperparam_dtype, param_dtype, grad_dtype): ...
    def test_static_args_error(self, static_args) -> None: ...
    @chex.all_variants
    def test_inject_hyperparams_starts_with_step_count_zero(self): ...

class StatefulTest(chex.TestCase):
    def test_wrap_stateless_schedule(self) -> None: ...
    @chex.all_variants
    def test_inject_stateful_hyperparams(self) -> None: ...
