from absl.testing import parameterized
from optax._src import (
    alias as alias,
    alias_test as alias_test,
    base as base,
    update as update,
)

import chex

class ConstantTest(chex.TestCase):
    @chex.all_variants
    def test_constant(self) -> None: ...

class PolynomialTest(chex.TestCase):
    @chex.all_variants
    def test_linear(self) -> None: ...
    @chex.all_variants
    def test_zero_steps_schedule(self) -> None: ...
    @chex.all_variants
    def test_nonlinear(self) -> None: ...
    @chex.all_variants
    def test_with_decay_begin(self) -> None: ...

class PiecewiseConstantTest(chex.TestCase):
    @chex.all_variants
    def test_positive(self) -> None: ...
    @chex.all_variants
    def test_negative(self) -> None: ...

class ExponentialTest(chex.TestCase):
    @chex.all_variants
    def test_constant_schedule(self, staircase) -> None: ...
    @chex.all_variants
    def test_nonvalid_transition_steps(self, staircase) -> None: ...
    @chex.all_variants
    def test_nonvalid_decay_rate(self, staircase) -> None: ...
    @chex.all_variants
    def test_exponential(self, staircase, transition_begin): ...
    @chex.all_variants
    def test_end_value_with_staircase(self, decay_rate, end_value, staircase): ...
    @chex.all_variants
    def test_immutable_count(self) -> None: ...

class CosineDecayTest(chex.TestCase):
    @chex.all_variants
    def test_decay_count_smaller_count(self) -> None: ...
    @chex.all_variants
    def test_decay_count_greater_count(self) -> None: ...
    @chex.all_variants
    def test_decay_count_greater_count_with_alpha(self) -> None: ...
    @chex.all_variants
    def test_with_exponent(self) -> None: ...
    @chex.all_variants
    def test_with_giant_int_steps(self) -> None: ...

class WarmupCosineDecayTest(chex.TestCase):
    @chex.all_variants
    def test_limits(self, init_value, peak_value, end_value) -> None: ...
    @chex.all_variants
    def test_with_exponent(self) -> None: ...
    @chex.all_variants
    def test_zero_peak_value(self) -> None: ...

class SGDRTest(chex.TestCase):
    @chex.all_variants
    def test_limits(self, lr0, lr1, lr2) -> None: ...

class PiecewiseInterpolateTest(chex.TestCase):
    @chex.all_variants
    def test_linear_piecewise(self) -> None: ...
    @chex.all_variants
    def test_cos_piecewise(self) -> None: ...
    @chex.all_variants
    def test_empty_dict(self) -> None: ...
    @chex.all_variants
    def test_no_dict(self) -> None: ...
    def test_invalid_type(self) -> None: ...
    def test_invalid_scale(self) -> None: ...

class OneCycleTest(chex.TestCase):
    @chex.all_variants
    def test_linear(self) -> None: ...
    @chex.all_variants
    def test_cosine(self) -> None: ...
    def test_nonpositive_transition_steps(self) -> None: ...

class ScheduleAsLearningRateTest(parameterized.TestCase):
    def test_optimization(self, opt_name, opt_kwargs): ...
