from _typeshed import Incomplete
from absl.testing import parameterized
from optax import projections as projections

import chex

class SoftmaxCrossEntropyTest(parameterized.TestCase):
    ys: Incomplete
    ts: Incomplete
    exp: Incomplete
    mask: Incomplete
    per_logit_mask: Incomplete
    def setUp(self) -> None: ...
    @chex.all_variants
    def test_scalar(self) -> None: ...
    @chex.all_variants
    def test_batched(self) -> None: ...
    def test_per_logit_mask(self) -> None: ...
    def test_gradient(self): ...
    def test_mask(self, size) -> None: ...
    def test_axis(self, shape, axis) -> None: ...

class SafeSoftmaxCrossEntropyTest(parameterized.TestCase):
    ys: Incomplete
    ts: Incomplete
    exp: Incomplete
    def setUp(self) -> None: ...
    @chex.all_variants
    def test_scalar(self) -> None: ...
    @chex.all_variants
    def test_batched(self) -> None: ...
    def test_gradient(self) -> None: ...
    def test_against_plain_implementation(self) -> None: ...

class SoftmaxCrossEntropyWithIntegerLabelsTest(parameterized.TestCase):
    ys: Incomplete
    ts: Incomplete
    mask: Incomplete
    per_logit_mask: Incomplete
    def setUp(self) -> None: ...
    @chex.all_variants
    def test_consistent_with_softmax_cross_entropy_scalar(self) -> None: ...
    @chex.all_variants
    def test_consistent_with_softmax_cross_entropy_batched(self) -> None: ...
    def test_gradient(self): ...
    def test_per_logit_mask(self) -> None: ...
    def test_axis(self, shape, axis) -> None: ...
    def test_axes(self, shape: tuple[int, ...], axis: tuple[int, ...]): ...

class SigmoidCrossEntropyTest(parameterized.TestCase):
    def test_sigmoid_cross_entropy(self, preds, labels, expected) -> None: ...

class PolyLossTest(parameterized.TestCase):
    logits: Incomplete
    labels: Incomplete
    batched_logits: Incomplete
    batched_labels: Incomplete
    def setUp(self) -> None: ...
    @chex.all_variants
    def test_scalar(self, eps, expected) -> None: ...
    @chex.all_variants
    def test_batched(self, eps, expected) -> None: ...
    @chex.all_variants
    def test_equals_to_cross_entropy_when_eps0(self, logits, labels) -> None: ...
    def test_mask(self, size) -> None: ...
    def test_axis(self, shape, axis) -> None: ...

class HingeTest(parameterized.TestCase):
    def test_binary(self): ...
    def test_batched_binary(self): ...
    def test_multi_class(self): ...
    def test_batched_multi_class(self): ...

class SparsemaxTest(parameterized.TestCase):
    def test_binary(self): ...
    def test_batched_binary(self): ...
    def test_multi_class_zero_loss(self) -> None: ...
    def test_multi_class_gradient(self): ...

class ConvexKLDivergenceTest(parameterized.TestCase):
    log_ps: Incomplete
    qs: Incomplete
    exp: Incomplete
    def setUp(self) -> None: ...
    @chex.all_variants
    def test_scalar(self) -> None: ...
    @chex.all_variants
    def test_batched(self) -> None: ...
    def test_mask(self, size) -> None: ...
    def test_axis(self, shape, axis) -> None: ...

class PerceptronTest(parameterized.TestCase):
    def test_binary(self): ...
    def test_batched_binary(self): ...
    def test_multi_class(self): ...
    def test_batched_multi_class(self): ...

class KLDivergenceTest(parameterized.TestCase):
    log_ps: Incomplete
    qs: Incomplete
    exp: Incomplete
    def setUp(self) -> None: ...
    @chex.all_variants
    def test_scalar(self) -> None: ...
    @chex.all_variants
    def test_batched(self) -> None: ...
    def test_mask(self, size) -> None: ...
    def test_axis(self, shape, axis) -> None: ...

class KLDivergenceWithLogTargetsTest(parameterized.TestCase):
    log_ps: Incomplete
    qs: Incomplete
    exp: Incomplete
    def setUp(self) -> None: ...
    @chex.all_variants
    def test_scalar(self) -> None: ...
    @chex.all_variants
    def test_batched(self) -> None: ...
    def test_mask(self, size) -> None: ...
    def test_axis(self, shape, axis) -> None: ...

class CTCTest(parameterized.TestCase):
    def setUp(self) -> None: ...
    @chex.all_variants
    def test_with_one_to_one_alignment(self) -> None: ...
    @chex.all_variants
    def test_with_one_to_one_alignment_and_paddings(self) -> None: ...
    @chex.all_variants
    def test_repeat_with_one_to_one_alignment(self) -> None: ...

class SigmoidFocalLossTest(parameterized.TestCase):
    ys: Incomplete
    ts: Incomplete
    large_ys: Incomplete
    small_ys: Incomplete
    ones_ts: Incomplete
    def setUp(self): ...
    @chex.all_variants
    def test_focal_equals_ce(self) -> None: ...
    @chex.all_variants
    def test_focal_gamma_zero_matches_binary_cross_entropy(self) -> None: ...
    @chex.all_variants
    def test_scale(self) -> None: ...
    @chex.all_variants
    def test_large_logit_fl_less_than_ce(self) -> None: ...
    @chex.all_variants
    def test_small_logit_fl_less_than_ce(self) -> None: ...
    @chex.all_variants
    def test_alpha_one(self) -> None: ...
    @chex.all_variants
    def test_ignore_positive(self) -> None: ...
    @chex.all_variants
    def test_ignore_negative(self) -> None: ...
    @chex.all_variants
    def test_extreme_logits_finite_gradients(self): ...
