import math

from absl.testing import parameterized

exp = math.exp
log = math.log

class RankingLossesTest(parameterized.TestCase):
    def test_computes_loss_value(self, loss_fn, expected_value) -> None: ...
    def test_computes_loss_with_extreme_inputs(
        self,
        loss_fn,
        expected_value,
    ) -> None: ...
    def test_computes_loss_for_zero_labels(self, loss_fn, expected_value) -> None: ...
    def test_computes_weighted_loss_value(self, loss_fn, expected_value) -> None: ...
    def test_computes_loss_value_with_vmap(self, loss_fn, expected_value) -> None: ...
    def test_computes_reduced_loss(
        self,
        loss_fn,
        expected_value,
        normalizer,
    ) -> None: ...
    def test_computes_unreduced_loss(self, loss_fn, expected_shape) -> None: ...
    def test_computes_loss_value_with_where(self, loss_fn) -> None: ...
    def test_computes_loss_value_with_all_masked(self, loss_fn) -> None: ...
    def test_computes_loss_with_arbitrary_batch_dimensions(self, loss_fn) -> None: ...
    def test_grad_does_not_return_nan_for_zero_labels(self, loss_fn) -> None: ...
    def test_grad_does_not_return_nan_with_all_masked(self, loss_fn) -> None: ...
    def test_ignores_lists_containing_only_invalid_items(self, loss_fn) -> None: ...

def load_tests(loader, tests, ignore): ...
