from _typeshed import Incomplete
from absl.testing import parameterized

import chex

class SquaredErrorTest(parameterized.TestCase):
    ys: Incomplete
    ts: Incomplete
    exp: Incomplete
    def setUp(self) -> None: ...
    @chex.all_variants
    def test_scalar(self) -> None: ...
    @chex.all_variants
    def test_batched(self) -> None: ...
    @chex.all_variants
    def test_shape_mismatch(self) -> None: ...

class L2LossTest(parameterized.TestCase):
    ys: Incomplete
    ts: Incomplete
    exp: Incomplete
    def setUp(self) -> None: ...
    @chex.all_variants
    def test_scalar(self) -> None: ...
    @chex.all_variants
    def test_batched(self) -> None: ...
    @chex.all_variants
    def test_shape_mismatch(self) -> None: ...

class HuberLossTest(parameterized.TestCase):
    ys: Incomplete
    ts: Incomplete
    exp: Incomplete
    def setUp(self) -> None: ...
    @chex.all_variants
    def test_scalar(self) -> None: ...
    @chex.all_variants
    def test_batched(self) -> None: ...

class LogCoshTest(parameterized.TestCase):
    ys: Incomplete
    ts: Incomplete
    exp: Incomplete
    exp_ys_only: Incomplete
    def setUp(self) -> None: ...
    @chex.all_variants
    def test_scalar(self) -> None: ...
    @chex.all_variants
    def test_batched(self) -> None: ...
    @chex.all_variants
    def test_scalar_predictions_only(self) -> None: ...
    @chex.all_variants
    def test_batched_predictions_only(self) -> None: ...

class CosineDistanceTest(parameterized.TestCase):
    ys: Incomplete
    ts: Incomplete
    exp: Incomplete
    def setUp(self) -> None: ...
    @chex.all_variants
    def test_scalar_distance(self) -> None: ...
    @chex.all_variants
    def test_scalar_similarity(self) -> None: ...
    @chex.all_variants
    def test_batched_distance(self) -> None: ...
    @chex.all_variants
    def test_batched_similarity(self) -> None: ...
    def test_mask_distance(self, size) -> None: ...
    def test_mask_similarity(self, size) -> None: ...
    def test_axis(self, shape, axis) -> None: ...
