from _typeshed import Incomplete

import chex

class DiceLossTest(chex.TestCase):
    key: Incomplete
    def setUp(self) -> None: ...
    def test_dice_loss_shapes(self) -> None: ...
    def test_perfect_overlap_binary(self) -> None: ...
    def test_no_overlap_binary(self) -> None: ...
    def test_perfect_overlap_multiclass(self) -> None: ...
    def test_loss_bounds(self) -> None: ...
    def test_smoothing_parameter(self, smooth) -> None: ...
    def test_class_weights(self) -> None: ...
    def test_reduction_modes(self, reduction) -> None: ...
    def test_gradient_computation(self): ...
    def test_numerical_stability(self) -> None: ...
    def test_apply_softmax_flag(self) -> None: ...
    def test_binary_dice_loss_convenience(self) -> None: ...
    def test_multiclass_generalized_dice_loss(self) -> None: ...
    def test_edge_cases(self) -> None: ...
    def test_shape_mismatch_error(self) -> None: ...
    @chex.all_variants
    def test_jit_compilation(self) -> None: ...
    @chex.all_variants
    def test_vmap_compatibility(self): ...
    def test_ignore_background_parameter(self) -> None: ...
    def test_improved_shape_handling(self) -> None: ...
    def test_probability_validation(self) -> None: ...
    def test_generalized_dice_loss_ignore_background(self) -> None: ...
