from _typeshed import Incomplete
from jax._src import (
    api_util as api_util,
    config as config,
    core as core,
    custom_derivatives as custom_derivatives,
    deprecations as deprecations,
    dispatch as dispatch,
    dtypes as dtypes,
    lax as lax,
)
from jax._src.api import (
    jit as jit,
    jvp as jvp,
    vmap as vmap,
)
from jax._src.numpy import vectorize as jnp_vectorize
from jax._src.numpy.ufuncs import (
    isneginf as isneginf,
    isposinf as isposinf,
    sinc as sinc,
)
from jax._src.numpy.util import (
    promote_args_inexact as promote_args_inexact,
    promote_dtypes_inexact as promote_dtypes_inexact,
)
from jax._src.typing import (
    Array as Array,
    ArrayLike as ArrayLike,
)

def gammaln(x: ArrayLike) -> Array: ...
@jit
def gammasgn(x: ArrayLike) -> Array: ...
def gamma(x: ArrayLike) -> Array: ...
def betaln(a: ArrayLike, b: ArrayLike) -> Array: ...
def factorial(n: ArrayLike, exact: bool = False) -> Array: ...
def beta(a: ArrayLike, b: ArrayLike) -> Array: ...
def betainc(a: ArrayLike, b: ArrayLike, x: ArrayLike) -> Array: ...
def digamma(x: ArrayLike) -> Array: ...
def gammainc(a: ArrayLike, x: ArrayLike) -> Array: ...
def gammaincc(a: ArrayLike, x: ArrayLike) -> Array: ...
def erf(x: ArrayLike) -> Array: ...
def erfc(x: ArrayLike) -> Array: ...
def erfinv(x: ArrayLike) -> Array: ...
@custom_derivatives.custom_jvp
def logit(x: ArrayLike) -> Array: ...
def expit(x: ArrayLike) -> Array: ...

logsumexp: Incomplete

@custom_derivatives.custom_jvp
def xlogy(x: ArrayLike, y: ArrayLike) -> Array: ...
@custom_derivatives.custom_jvp
def xlog1py(x: ArrayLike, y: ArrayLike) -> Array: ...
def entr(x: ArrayLike) -> Array: ...
def multigammaln(a: ArrayLike, d: ArrayLike) -> Array: ...
def kl_div(p: ArrayLike, q: ArrayLike) -> Array: ...
def rel_entr(p: ArrayLike, q: ArrayLike) -> Array: ...
@custom_derivatives.custom_jvp
def zeta(x: ArrayLike, q: ArrayLike | None = None) -> Array: ...
def polygamma(n: ArrayLike, x: ArrayLike) -> Array: ...
def ndtr(x: ArrayLike) -> Array: ...
def ndtri(p: ArrayLike) -> Array: ...
def log_ndtr(x: ArrayLike, series_order: int = 3) -> Array: ...
def i0e(x: ArrayLike) -> Array: ...
def i0(x: ArrayLike) -> Array: ...
def i1e(x: ArrayLike) -> Array: ...
def i1(x: ArrayLike) -> Array: ...
def bessel_jn(z: ArrayLike, *, v: int, n_iter: int = 50) -> Array: ...
def lpmn(m: int, n: int, z: Array) -> tuple[Array, Array]: ...
def lpmn_values(m: int, n: int, z: Array, is_normalized: bool) -> Array: ...
def sph_harm_y(
    n: Array,
    m: Array,
    theta: Array,
    phi: Array,
    diff_n: int | None = None,
    n_max: int | None = None,
) -> Array: ...
def sph_harm(
    m: Array,
    n: Array,
    theta: Array,
    phi: Array,
    n_max: int | None = None,
) -> Array: ...
@custom_derivatives.custom_jvp
@jit
def expi(x: ArrayLike) -> Array: ...
@expi.defjvp
@jit
def expi_jvp(primals, tangents): ...
@custom_derivatives.custom_jvp
@jit
def sici(x: ArrayLike) -> tuple[Array, Array]: ...
@sici.defjvp
@jit
def sici_jvp(primals, tangents): ...
@jnp_vectorize.vectorize
@jit
def expn(n: ArrayLike, x: ArrayLike) -> Array: ...
@expn.defjvp
@jit
def expn_jvp(n, primals, tangents): ...
def exp1(x: ArrayLike) -> Array: ...
def spence(x: Array) -> Array: ...
def bernoulli(n: int) -> Array: ...
@custom_derivatives.custom_jvp
def poch(z: ArrayLike, m: ArrayLike) -> Array: ...
@custom_derivatives.custom_jvp
@jit
@jnp_vectorize.vectorize
def hyp1f1(a: ArrayLike, b: ArrayLike, x: ArrayLike) -> Array: ...
@custom_derivatives.custom_jvp
@jit
@jnp_vectorize.vectorize
def hyp2f1(a: ArrayLike, b: ArrayLike, c: ArrayLike, x: ArrayLike) -> Array: ...
def softmax(x: ArrayLike, /, *, axis: int | tuple[int, ...] | None = None) -> Array: ...
def log_softmax(
    x: ArrayLike,
    /,
    *,
    axis: int | tuple[int, ...] | None = None,
) -> Array: ...
