from torchao.kernel import int_scaled_matmul, safe_int_mm

from .autoquant import (
    ALL_AUTOQUANT_CLASS_LIST,
    DEFAULT_AUTOQUANT_CLASS_LIST,
    DEFAULT_FLOAT_AUTOQUANT_CLASS_LIST,
    DEFAULT_INT4_AUTOQUANT_CLASS_LIST,
    DEFAULT_SPARSE_AUTOQUANT_CLASS_LIST,
    GEMLITE_INT4_AUTOQUANT_CLASS_LIST,
    OTHER_AUTOQUANT_CLASS_LIST,
    autoquant,
)
from .GPTQ import Int4WeightOnlyGPTQQuantizer, MultiTensor, MultiTensorInputRecorder
from .granularity import (
    Granularity,
    PerAxis,
    PerBlock,
    PerGroup,
    PerRow,
    PerTensor,
    PerToken,
)
from .linear_activation_quantized_tensor import (
    LinearActivationQuantizedTensor,
    to_linear_activation_quantized,
)
from .linear_quant_modules import (
    Int4WeightOnlyQuantizer,
    Int8DynActInt4WeightLinear,
    Int8DynActInt4WeightQuantizer,
)
from .observer import AffineQuantizedMinMaxObserver, AffineQuantizedObserverBase
from .quant_api import (
    CutlassInt4PackedLayout,
    Float8DynamicActivationFloat8WeightConfig,
    Float8DynamicActivationInt4WeightConfig,
    Float8MMConfig,
    Float8StaticActivationFloat8WeightConfig,
    Float8WeightOnlyConfig,
    FPXWeightOnlyConfig,
    GemliteUIntXWeightOnlyConfig,
    Int4DynamicActivationInt4WeightConfig,
    Int4WeightOnlyConfig,
    Int8DynamicActivationInt4WeightConfig,
    Int8DynamicActivationInt8WeightConfig,
    Int8DynamicActivationIntxWeightConfig,
    Int8WeightOnlyConfig,
    IntxWeightOnlyConfig,
    ModuleFqnToConfig,
    PlainLayout,
    TensorCoreTiledLayout,
    UIntXWeightOnlyConfig,
    float8_dynamic_activation_float8_weight,
    float8_static_activation_float8_weight,
    float8_weight_only,
    fpx_weight_only,
    gemlite_uintx_weight_only,
    int4_dynamic_activation_int4_weight,
    int4_weight_only,
    int8_dynamic_activation_int4_weight,
    int8_dynamic_activation_int8_semi_sparse_weight,
    int8_dynamic_activation_int8_weight,
    int8_weight_only,
    intx_quantization_aware_training,
    quantize_,
    swap_conv2d_1x1_to_linear,
    uintx_weight_only,
)
from .quant_primitives import (
    MappingType,
    TorchAODType,
    ZeroPointDomain,
    choose_qparams_affine,
    choose_qparams_affine_with_min_max,
    dequantize_affine,
    quantize_affine,
)
from .quantize_.workflows import (
    Float8Tensor,
    Int4MarlinSparseTensor,
    Int4OpaqueTensor,
    Int4PlainInt32Tensor,
    Int4PreshuffledTensor,
    Int4Tensor,
    Int4TilePackedTo4dTensor,
    IntxOpaqueTensor,
    IntxUnpackedToInt8Tensor,
)
from .smoothquant import (
    SmoothFakeDynamicallyQuantizedLinear,
    SmoothFakeDynQuantMixin,
    get_scale,
    set_smooth_fq_attribute,
    smooth_fq_linear_to_inference,
    swap_linear_with_smooth_fq_linear,
)
from .subclass import *
from .transform_module import register_quantize_module_handler
from .unified import Quantizer, TwoStepQuantizer
from .utils import compute_error
from .weight_only import WeightOnlyInt8QuantLinear

AOPerModuleConfig = ModuleFqnToConfig
__all__ = [
    "ALL_AUTOQUANT_CLASS_LIST",
    "DEFAULT_AUTOQUANT_CLASS_LIST",
    "DEFAULT_FLOAT_AUTOQUANT_CLASS_LIST",
    "DEFAULT_INT4_AUTOQUANT_CLASS_LIST",
    "DEFAULT_SPARSE_AUTOQUANT_CLASS_LIST",
    "GEMLITE_INT4_AUTOQUANT_CLASS_LIST",
    "OTHER_AUTOQUANT_CLASS_LIST",
    "AOPerModuleConfig",
    "AffineQuantizedMinMaxObserver",
    "AffineQuantizedObserverBase",
    "CutlassInt4PackedLayout",
    "FPXWeightOnlyConfig",
    ...,
    "Float8DynamicActivationFloat8WeightConfig",
    "Float8DynamicActivationInt4WeightConfig",
    "Float8MMConfig",
    "Float8StaticActivationFloat8WeightConfig",
    "Float8Tensor",
    "Float8WeightOnlyConfig",
    "GemliteUIntXWeightOnlyConfig",
    "Granularity",
    "Int4DynamicActivationInt4WeightConfig",
    "Int4MarlinSparseTensor",
    "Int4OpaqueTensor",
    "Int4PlainInt32Tensor",
    "Int4PreshuffledTensor",
    "Int4Tensor",
    "Int4TilePackedTo4dTensor",
    "Int4WeightOnlyConfig",
    "Int4WeightOnlyGPTQQuantizer",
    "Int4WeightOnlyQuantizer",
    "Int8DynActInt4WeightLinear",
    "Int8DynActInt4WeightQuantizer",
    "Int8DynamicActivationInt4WeightConfig",
    "Int8DynamicActivationInt8WeightConfig",
    "Int8DynamicActivationIntxWeightConfig",
    "Int8WeightOnlyConfig",
    "IntxOpaqueTensor",
    "IntxUnpackedToInt8Tensor",
    "IntxWeightOnlyConfig",
    "LinearActivationQuantizedTensor",
    "MappingType",
    "ModuleFqnToConfig",
    "MultiTensor",
    "MultiTensorInputRecorder",
    "PerAxis",
    "PerBlock",
    "PerGroup",
    "PerRow",
    "PerTensor",
    "PerToken",
    "PlainLayout",
    "Quantizer",
    "SmoothFakeDynQuantMixin",
    "SmoothFakeDynamicallyQuantizedLinear",
    "TensorCoreTiledLayout",
    "TorchAODType",
    "TwoStepQuantizer",
    "UIntXWeightOnlyConfig",
    "WeightOnlyInt8QuantLinear",
    "ZeroPointDomain",
    "autoquant",
    "choose_qparams_affine",
    "choose_qparams_affine_with_min_max",
    "compute_error",
    "dequantize_affine",
    "float8_dynamic_activation_float8_weight",
    "float8_static_activation_float8_weight",
    "float8_weight_only",
    "fpx_weight_only",
    "gemlite_uintx_weight_only",
    "get_scale",
    "int4_dynamic_activation_int4_weight",
    "int4_weight_only",
    "int8_dynamic_activation_int4_weight",
    "int8_dynamic_activation_int8_semi_sparse_weight",
    "int8_dynamic_activation_int8_weight",
    "int8_weight_only",
    "int_scaled_matmul",
    "intx_quantization_aware_training",
    "quantize_",
    "quantize_affine",
    "register_quantize_module_handler",
    "safe_int_mm",
    "set_smooth_fq_attribute",
    "smooth_fq_linear_to_inference",
    "swap_conv2d_1x1_to_linear",
    "swap_linear_with_smooth_fq_linear",
    "to_linear_activation_quantized",
    ...,
    "uintx_weight_only",
]
