from collections import OrderedDict as OrderedDictType
from collections.abc import Callable
from dataclasses import dataclass

from torch import nn
from torchao.core.config import AOBaseConfig
from torchao.dtypes import TensorCoreTiledLayout
from torchao.dtypes.utils import Layout
from torchao.float8.inference import Float8MMConfig, FP8Granularity
from torchao.quantization.observer import AffineQuantizedObserverBase
from torchao.quantization.quantize_.common import KernelPreference
from torchao.quantization.quantize_.workflows import (
    Int4ChooseQParamsAlgorithm,
    Int4PackingFormat,
    IntxChooseQParamsAlgorithm,
    IntxPackingFormat,
)

import torch

from .granularity import Granularity
from .quant_primitives import MappingType, ZeroPointDomain

"""
Quantization APIs

Generally these APIs can be applied directly to any model
with Linear modules to obtain quantized linear ops. The intended
usage involves applying torch.compile to the model afterwards
both because primitives were designed based on the fusions that
come along with it and because that is how we access the intended quantized
and mixed GEMM kernels
"""
logger = ...
__all__ = [
    ...,
    "Int4WeightOnlyGPTQQuantizer",
    "Int4WeightOnlyQuantizer",
    "Int8DynActInt4WeightQuantizer",
    "ModuleFqnToConfig",
    "Quantizer",
    "TwoStepQuantizer",
    "_get_subclass_inserter",
    "autoquant",
    "float8_dynamic_activation_float8_weight",
    "float8_static_activation_float8_weight",
    "float8_weight_only",
    "fpx_weight_only",
    "gemlite_uintx_weight_only",
    "int4_weight_only",
    "int8_dynamic_activation_int4_weight",
    "int8_dynamic_activation_int8_semi_sparse_weight",
    "int8_dynamic_activation_int8_weight",
    "int8_weight_only",
    "intx_quantization_aware_training",
    "quantize_",
    "swap_conv2d_1x1_to_linear",
    "uintx_weight_only",
]
LAYOUT_TO_ZERO_POINT_DOMAIN = ...
LAYOUT_TO_PRESERVE_ZEROS = ...

def swap_conv2d_1x1_to_linear(model, filter_fn=...):  # -> None:

    ...
def insert_observers_(
    model: nn.Module,
    input_observer: AffineQuantizedObserverBase | None,
    weight_observer: AffineQuantizedObserverBase | None,
    *,
    filter_fn: Callable[[torch.nn.Module, str], bool] | None = ...,
):  # -> None:
    ...
def quantize_(
    model: torch.nn.Module,
    config: AOBaseConfig,
    filter_fn: Callable[[torch.nn.Module, str], bool] | None = ...,
    device: torch.types.Device | None = ...,
):  # -> None:
    ...

@dataclass
class Int8DynamicActivationInt4WeightConfig(AOBaseConfig):
    group_size: int = ...
    layout: Layout = ...
    mapping_type: MappingType = ...
    act_mapping_type: MappingType = ...
    set_inductor_config: bool = ...
    def __post_init__(self):  # -> None:
        ...

int8_dynamic_activation_int4_weight = ...

@dataclass
class Int8DynamicActivationIntxWeightConfig(AOBaseConfig):
    weight_dtype: torch.dtype = ...
    weight_granularity: Granularity = ...
    weight_mapping_type: MappingType = ...
    weight_scale_dtype: torch.dtype | None = ...
    act_mapping_type: MappingType = ...
    layout: Layout = ...
    intx_packing_format: IntxPackingFormat = ...
    intx_choose_qparams_algorithm: IntxChooseQParamsAlgorithm = ...
    version: int = ...
    def __post_init__(self):  # -> None:
        ...

@dataclass
class Int4DynamicActivationInt4WeightConfig(AOBaseConfig):
    layout: Layout = ...
    mapping_type: MappingType = ...
    act_mapping_type: MappingType = ...
    set_inductor_config: bool = ...
    def __post_init__(self):  # -> None:
        ...

int4_dynamic_activation_int4_weight = ...

@dataclass
class GemliteUIntXWeightOnlyConfig(AOBaseConfig):
    group_size: int | None = ...
    bit_width: int = ...
    packing_bitwidth: int | None = ...
    mode: str | None = ...
    set_inductor_config: bool = ...
    def __post_init__(self):  # -> None:
        ...

gemlite_uintx_weight_only = ...

@dataclass
class Int4WeightOnlyConfig(AOBaseConfig):
    group_size: int = ...
    layout: TensorCoreTiledLayout | None = ...
    use_hqq: bool = ...
    zero_point_domain: ZeroPointDomain | None = ...
    set_inductor_config: bool = ...
    preserve_zero: bool | None = ...
    int4_packing_format: Int4PackingFormat = ...
    int4_choose_qparams_algorithm: Int4ChooseQParamsAlgorithm = ...
    version: int = ...
    def __post_init__(self):  # -> None:
        ...

int4_weight_only = ...

@dataclass
class Float8DynamicActivationInt4WeightConfig(AOBaseConfig):
    int4_packing_format: Int4PackingFormat = ...

@dataclass
class Int8WeightOnlyConfig(AOBaseConfig):
    group_size: int | None = ...
    set_inductor_config: bool = ...
    def __post_init__(self):  # -> None:
        ...

int8_weight_only = ...

@dataclass
class Int8DynamicActivationInt8WeightConfig(AOBaseConfig):
    layout: Layout | None = ...
    act_mapping_type: MappingType | None = ...
    weight_only_decode: bool = ...
    set_inductor_config: bool = ...
    def __post_init__(self):  # -> None:
        ...

int8_dynamic_activation_int8_weight = ...

def int8_dynamic_activation_int8_semi_sparse_weight():  # -> Int8DynamicActivationInt8WeightConfig:
    ...

@dataclass
class Float8WeightOnlyConfig(AOBaseConfig):
    weight_dtype: torch.dtype = ...
    set_inductor_config: bool = ...
    version: int = ...
    def __post_init__(self):  # -> None:
        ...

float8_weight_only = ...

@dataclass
class Float8DynamicActivationFloat8WeightConfig(AOBaseConfig):
    activation_dtype: torch.dtype = ...
    weight_dtype: torch.dtype = ...
    granularity: FP8Granularity | list[FP8Granularity] | None = ...
    mm_config: Float8MMConfig | None = ...
    activation_value_lb: float | None = ...
    activation_value_ub: float | None = ...
    kernel_preference: KernelPreference = ...
    set_inductor_config: bool = ...
    version: int = ...
    def __post_init__(self):  # -> None:
        ...

float8_dynamic_activation_float8_weight = ...

@dataclass
class Float8DynamicActivationFloat8SemiSparseWeightConfig(AOBaseConfig):
    layout: Layout = ...
    activation_dtype: torch.dtype = ...
    weight_dtype: torch.dtype = ...
    def __post_init__(self):  # -> None:
        ...

@dataclass
class Float8StaticActivationFloat8WeightConfig(AOBaseConfig):
    scale: torch.Tensor
    activation_dtype: torch.dtype = ...
    weight_dtype: torch.dtype = ...
    granularity: FP8Granularity | tuple[FP8Granularity, FP8Granularity] | None = ...
    mm_config: Float8MMConfig | None = ...
    set_inductor_config: bool = ...
    def __post_init__(self):  # -> None:
        ...

float8_static_activation_float8_weight = ...

@dataclass
class UIntXWeightOnlyConfig(AOBaseConfig):
    dtype: torch.dtype
    group_size: int = ...
    pack_dim: int = ...
    use_hqq: bool = ...
    set_inductor_config: bool = ...
    def __post_init__(self):  # -> None:
        ...

uintx_weight_only = ...

@dataclass
class IntxWeightOnlyConfig(AOBaseConfig):
    weight_dtype: torch.dtype = ...
    granularity: Granularity = ...
    mapping_type: MappingType = ...
    scale_dtype: torch.dtype | None = ...
    layout: Layout = ...
    intx_packing_format: IntxPackingFormat = ...
    intx_choose_qparams_algorithm: IntxChooseQParamsAlgorithm = ...
    version: int = ...
    def __post_init__(self):  # -> None:
        ...

@dataclass
class FPXWeightOnlyConfig(AOBaseConfig):
    ebits: int
    mbits: int
    set_inductor_config: bool = ...
    def __post_init__(self):  # -> None:
        ...

fpx_weight_only = ...

@dataclass
class ModuleFqnToConfig(AOBaseConfig):
    module_fqn_to_config: OrderedDictType[str, AOBaseConfig | None] = ...
    def __post_init__(self):  # -> None:
        ...
