import torch

"""
Testing out accuracy-only implementation of SmoothQuant
(https://arxiv.org/pdf/2211.10438.pdf)
Note: this is an application of input-weight equalization, with the addition that the
multiplication by scale is fused into the preceding layer, specifically for relevant
parts of transformer blocks.
"""
__all__ = [
    "SmoothFakeDynQuantMixin",
    "SmoothFakeDynamicallyQuantizedLinear",
    "get_scale",
    "set_smooth_fq_attribute",
    "smooth_fq_linear_to_inference",
    "swap_linear_with_smooth_fq_linear",
]

def get_scale(X_absmax, W_absmax, alpha=...):  # -> Tensor:
    ...

class SmoothFakeDynQuantMixin(torch.nn.Module):
    def init_smoothquant_variables(self, alpha):  # -> None:
        ...
    def update_x_running_abs_max(self, X):  # -> None:
        ...
    def get_scaled_quantized_w(self):  # -> tuple[Tensor, Tensor, Tensor]:
        ...
    def to_inference(self): ...
    def fold_weight(self):  # -> None:
        ...
    def set_debug_x_absmax(self): ...

class SmoothFakeDynamicallyQuantizedLinear(SmoothFakeDynQuantMixin, torch.nn.Linear):
    def __init__(self, *args, **kwargs) -> None: ...
    def forward(self, X, *args, **kwargs):  # -> Tensor:
        ...
    @classmethod
    def from_float(cls, mod, alpha=...):  # -> Self:
        ...
    def to_inference(self):  # -> None:
        ...
    def set_debug_x_absmax(self):  # -> None:
        ...

source_cls_to_target_cls = ...

def swap_linear_with_smooth_fq_linear(
    model, skip_fqn_list=..., cur_fqn=..., alpha=...
) -> None: ...
def smooth_fq_linear_to_inference(model, debug_skip_calibration=...) -> None: ...
def set_smooth_fq_attribute(model, attribute_name, new_attribute_val):  # -> None:
    ...
