def shard(xs): ...
def shard_prng_key(prng_key): ...
def stack_forest(forest): ...
def get_metrics(device_metrics): ...
def onehot(labels, num_classes, on_value: float = 1.0, off_value: float = 0.0): ...
