from flax import struct as struct

class EarlyStopping(struct.PyTreeNode):
    min_delta: float = ...
    patience: int = ...
    best_metric: float = ...
    patience_count: int = ...
    should_stop: bool = ...
    has_improved: bool = ...
    def reset(self): ...
    def update(self, metric): ...
