from typing import Any

from jax.sharding import Mesh as Mesh

type PyTree = Any

def is_multi_device_array(value: Any) -> bool: ...
def save_args_from_target(target: Any) -> Any: ...
def maybe_construct_transformations(target: Any, transforms: Any | None) -> Any: ...
def restore_args_from_target(target: Any, mesh: Mesh | None = None) -> Any: ...
