from _typeshed import Incomplete

class PrefetchIterator:
    buffer_size: Incomplete
    def __init__(self, data_iter, buffer_size: int = 1) -> None: ...
    def __iter__(self): ...
    def __next__(self): ...
    def close(self) -> None: ...
