from transformers.configuration_utils import PretrainedConfig

class SambaConfig(PretrainedConfig):
    model_type = ...
    def __init__(
        self,
        hidden_size: int = ...,
        state_size: int = ...,
        num_hidden_layers: int = ...,
        norm_eps=...,
        pad_token_id: int = ...,
        bos_token_id: int = ...,
        eos_token_id: int = ...,
        expand: int = ...,
        conv_kernel: int = ...,
        use_bias: bool = ...,
        use_conv_bias: bool = ...,
        hidden_act: str = ...,
        initializer_range: float = ...,
        residual_in_fp32: bool = ...,
        time_step_rank: str = ...,
        time_step_scale: float = ...,
        time_step_min: float = ...,
        time_step_max: float = ...,
        time_step_init_scheme: str = ...,
        time_step_floor: float = ...,
        max_position_embeddings: int = ...,
        attn: dict | None = ...,
        hidden_ratio: int | None = ...,
        rescale_prenorm_residual: bool = ...,
        use_cache: bool = ...,
        fuse_norm: bool = ...,
        fuse_swiglu: bool = ...,
        fuse_cross_entropy: bool = ...,
        fuse_linear_cross_entropy: bool = ...,
        use_l2warp: bool = ...,
        vocab_size: int = ...,
        tie_word_embeddings: bool = ...,
        **kwargs,
    ) -> None: ...
