from collections.abc import (
    Callable as Callable,
    Sequence,
)
from typing import Any, Protocol

import dataclasses
import functools

from _typeshed import Incomplete
from jax._src import (
    ad_util as ad_util,
    core as core,
    dtypes as dtypes,
    effects as effects,
    pretty_printer as pp,
    traceback_util as traceback_util,
    tree_util as tree_util,
)
from jax._src.typing import Array as Array
from jax._src.util import (
    safe_map as safe_map,
    safe_zip as safe_zip,
)

map: Incomplete
unsafe_map: Incomplete
zip: Incomplete
unsafe_zip: Incomplete

class RefEffect(effects.JaxprInputEffect):
    name: str
    def __eq__(self, other): ...
    def __hash__(self): ...

class ReadEffect(RefEffect):
    name: str

class WriteEffect(RefEffect):
    name: str

class AccumEffect(RefEffect):
    name: str

type StateEffect = ReadEffect | WriteEffect | AccumEffect

class Transform(Protocol):
    def transform_type(self, x: core.AbstractValue) -> core.AbstractValue: ...
    def undo(self, x: core.AbstractValue) -> Transform: ...
    def pretty_print(self, context: core.JaxprPpContext) -> pp.Doc: ...

@dataclasses.dataclass(frozen=True)
class BitcastTransform(Transform):
    dtype: dtypes.DType = ...
    def transform_type(self, x): ...
    def undo(self, x: core.AbstractValue) -> Transform: ...
    def pretty_print(self, context: core.JaxprPpContext) -> pp.Doc: ...

@dataclasses.dataclass(frozen=True)
class ReshapeTransform(Transform):
    shape: tuple[int, ...] = ...
    def transform_type(self, x): ...
    def undo(self, x: core.AbstractValue) -> Transform: ...
    def pretty_print(self, context: core.JaxprPpContext) -> pp.Doc: ...

@dataclasses.dataclass(frozen=True)
class TransposeTransform(Transform):
    permutation: tuple[int, ...] = ...
    def undo(self, x: core.AbstractValue) -> Transform: ...
    def transform_type(self, x): ...
    def pretty_print(self, context: core.JaxprPpContext) -> pp.Doc: ...

@dataclasses.dataclass
class RefIndexer:
    ref_or_view: Any
    def __getitem__(self, slc) -> TransformedRef: ...

@dataclasses.dataclass(frozen=True)
class TransformedRef:
    ref: Any
    transforms: tuple[Transform, ...]
    @property
    def is_dynamic_size(self): ...
    @functools.cached_property
    def type(self) -> core.AbstractValue: ...
    @property
    def shape(self) -> tuple[int | Array, ...]: ...
    @property
    def dtype(self): ...
    ndim = ...
    size = ...
    T = ...
    @property
    def at(self) -> RefIndexer: ...
    def bitcast(self, dtype): ...
    def reshape(self, *shape): ...
    def transpose(self, permutation: Sequence[int]): ...
    def set(self, value, idx=()): ...
    def swap(self, value, idx=()): ...
    def get(self, idx=()): ...
    def __getattr__(self, name): ...
    def __getitem__(self, slc): ...
    def __setitem__(self, slc, value) -> None: ...

class TransformedRefAvalError(Exception): ...

def disallow_transformed_ref_avals(_) -> None: ...
def transform_type(
    ts: Sequence[Transform],
    ty: core.AbstractValue,
) -> core.AbstractValue: ...

class AbstractRef(core.AbstractValue):
    inner_aval: Incomplete
    memory_space: Incomplete
    kind: Incomplete
    def __init__(
        self,
        inner_aval: core.AbstractValue,
        memory_space: Any = None,
        kind: Any = None,
    ) -> None: ...
    @property
    def is_high(self): ...
    def lo_ty(self): ...
    def lower_val(self, ref): ...
    def raise_val(self, *vals): ...
    @property
    def weak_type(self) -> bool: ...
    def update_weak_type(self, weak_type): ...
    def update_vma(self, vma): ...
    def update(self, inner_aval=None, memory_space=None, kind=None): ...
    ndim: Incomplete
    size: Incomplete
    @property
    def shape(self): ...
    @property
    def dtype(self): ...
    @property
    def sharding(self): ...
    @property
    def vma(self): ...
    @core.aval_property
    def at(self): ...
    @core.aval_method
    def bitcast(self, dtype): ...
    @core.aval_method
    def reshape(self, *shape): ...
    @core.aval_method
    def transpose(self, *permutation): ...
    @core.aval_property
    def T(self): ...
    @core.aval_method
    @staticmethod
    def get(tracer, idx=()): ...
    @core.aval_method
    @staticmethod
    def swap(tracer, value, idx=()): ...
    @core.aval_method
    @staticmethod
    def set(tracer, value, idx=()): ...
    @core.aval_method
    @staticmethod
    def addupdate(tracer, value, idx=()) -> None: ...
    def str_short(
        self,
        short_dtypes: bool = False,
        mesh_axis_types: bool = False,
    ) -> str: ...
    def to_tangent_aval(self): ...
    def to_cotangent_aval(self): ...
    def __eq__(self, other): ...
    def __hash__(self): ...

def get_ref_state_effects(
    avals: Sequence[core.AbstractValue],
    effects: core.Effects,
) -> list[set[StateEffect]]: ...
def shaped_array_ref(
    shape: tuple[int, ...],
    dtype,
    weak_type: bool = False,
) -> AbstractRef: ...

class Uninitialized: ...

uninitialized: Incomplete

def get_ref_aval_from_value(x: Any): ...
def zeros_like_abstract_ref(aval: AbstractRef) -> core.Ref: ...

@dataclasses.dataclass(frozen=True)
class AbstractLinVal(core.AbstractValue):
    inner_aval: core.AbstractValue
    memory_space: Any = ...
    shape = ...
    dtype = ...
    ndim = ...
