from torch import Tensor, nn

def convert_boxes_to_roi_format(boxes: list[Tensor]) -> Tensor: ...
def check_roi_boxes_shape(boxes: Tensor | list[Tensor]):  # -> None:
    ...
def split_normalization_params(
    model: nn.Module, norm_classes: list[type] | None = ...
) -> tuple[list[Tensor], list[Tensor]]: ...
