from typing import Any

from torch import Tensor, nn

"""
This type stub file was generated by pyright.
"""

def deform_conv2d(
    input: Tensor,
    offset: Tensor,
    weight: Tensor,
    bias: Tensor | None = ...,
    stride: tuple[int, int] = ...,
    padding: tuple[int, int] = ...,
    dilation: tuple[int, int] = ...,
    mask: Tensor | None = ...,
) -> Tensor: ...

class DeformConv2d(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int,
        stride: int = ...,
        padding: int = ...,
        dilation: int = ...,
        groups: int = ...,
        bias: bool = ...,
    ) -> None: ...
    def reset_parameters(self) -> None: ...
    def forward(
        self, input: Tensor, offset: Tensor, mask: Tensor | None = ...
    ) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...
