from typing import Any

from torch import Tensor, nn

"""
This type stub file was generated by pyright.
"""

def drop_block2d(
    input: Tensor,
    p: float,
    block_size: int,
    inplace: bool = ...,
    eps: float = ...,
    training: bool = ...,
) -> Tensor: ...
def drop_block3d(
    input: Tensor,
    p: float,
    block_size: int,
    inplace: bool = ...,
    eps: float = ...,
    training: bool = ...,
) -> Tensor: ...

class DropBlock2d(nn.Module):
    def __init__(
        self, p: float, block_size: int, inplace: bool = ..., eps: float = ...
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class DropBlock3d(DropBlock2d):
    def __init__(
        self, p: float, block_size: int, inplace: bool = ..., eps: float = ...
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...
