from collections.abc import Callable
from typing import Any

from torch import Tensor, nn

"""
This type stub file was generated by pyright.
"""

class ExtraFPNBlock(nn.Module):
    def forward(
        self, results: list[Tensor], x: list[Tensor], names: list[str]
    ) -> tuple[list[Tensor], list[str]]: ...
    def __call__(self, *args: Any, **kwargs: Any) -> tuple[list[Tensor], list[str]]: ...

class FeaturePyramidNetwork(nn.Module):
    def __init__(
        self,
        in_channels_list: list[int],
        out_channels: int,
        extra_blocks: ExtraFPNBlock | None = ...,
        norm_layer: Callable[..., nn.Module] | None = ...,
    ) -> None: ...
    def get_result_from_inner_blocks(self, x: Tensor, idx: int) -> Tensor: ...
    def get_result_from_layer_blocks(self, x: Tensor, idx: int) -> Tensor: ...
    def forward(self, x: dict[str, Tensor]) -> dict[str, Tensor]: ...
    def __call__(self, *args: Any, **kwargs: Any) -> dict[str, Tensor]: ...

class LastLevelMaxPool(ExtraFPNBlock):
    def forward(
        self, x: list[Tensor], y: list[Tensor], names: list[str]
    ) -> tuple[list[Tensor], list[str]]: ...
    def __call__(self, *args: Any, **kwargs: Any) -> tuple[list[Tensor], list[str]]: ...

class LastLevelP6P7(ExtraFPNBlock):
    def __init__(self, in_channels: int, out_channels: int) -> None: ...
    def forward(
        self, p: list[Tensor], c: list[Tensor], names: list[str]
    ) -> tuple[list[Tensor], list[str]]: ...
    def __call__(self, *args: Any, **kwargs: Any) -> tuple[list[Tensor], list[str]]: ...
