import torch

"""
This type stub file was generated by pyright.
"""

def sigmoid_focal_loss(
    inputs: torch.Tensor,
    targets: torch.Tensor,
    alpha: float = ...,
    gamma: float = ...,
    reduction: str = ...,
) -> torch.Tensor: ...
