import torch

"""
This type stub file was generated by pyright.
"""

def generalized_box_iou_loss(
    boxes1: torch.Tensor, boxes2: torch.Tensor, reduction: str = ..., eps: float = ...
) -> torch.Tensor: ...
