from collections.abc import Callable
from typing import Any

from torch import Tensor

import torch

"""
This type stub file was generated by pyright.
"""
interpolate = ...

class FrozenBatchNorm2d(torch.nn.Module):
    def __init__(self, num_features: int, eps: float = ...) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class ConvNormActivation(torch.nn.Sequential):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int | tuple[int, ...] = ...,
        stride: int | tuple[int, ...] = ...,
        padding: int | tuple[int, ...] | str | None = ...,
        groups: int = ...,
        norm_layer: Callable[..., torch.nn.Module] | None = ...,
        activation_layer: Callable[..., torch.nn.Module] | None = ...,
        dilation: int | tuple[int, ...] = ...,
        inplace: bool | None = ...,
        bias: bool | None = ...,
        conv_layer: Callable[..., torch.nn.Module] = ...,
    ) -> None: ...

class Conv2dNormActivation(ConvNormActivation):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int | tuple[int, int] = ...,
        stride: int | tuple[int, int] = ...,
        padding: int | tuple[int, int] | str | None = ...,
        groups: int = ...,
        norm_layer: Callable[..., torch.nn.Module] | None = ...,
        activation_layer: Callable[..., torch.nn.Module] | None = ...,
        dilation: int | tuple[int, int] = ...,
        inplace: bool | None = ...,
        bias: bool | None = ...,
    ) -> None: ...

class Conv3dNormActivation(ConvNormActivation):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int | tuple[int, int, int] = ...,
        stride: int | tuple[int, int, int] = ...,
        padding: int | tuple[int, int, int] | str | None = ...,
        groups: int = ...,
        norm_layer: Callable[..., torch.nn.Module] | None = ...,
        activation_layer: Callable[..., torch.nn.Module] | None = ...,
        dilation: int | tuple[int, int, int] = ...,
        inplace: bool | None = ...,
        bias: bool | None = ...,
    ) -> None: ...

class SqueezeExcitation(torch.nn.Module):
    def __init__(
        self,
        input_channels: int,
        squeeze_channels: int,
        activation: Callable[..., torch.nn.Module] = ...,
        scale_activation: Callable[..., torch.nn.Module] = ...,
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class MLP(torch.nn.Sequential):
    def __init__(
        self,
        in_channels: int,
        hidden_channels: list[int],
        norm_layer: Callable[..., torch.nn.Module] | None = ...,
        activation_layer: Callable[..., torch.nn.Module] | None = ...,
        inplace: bool | None = ...,
        bias: bool = ...,
        dropout: float = ...,
    ) -> None: ...

class Permute(torch.nn.Module):
    def __init__(self, dims: list[int]) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...
