from typing import Any

from torch import Tensor, nn

"""
This type stub file was generated by pyright.
"""

def initLevelMapper(
    k_min: int,
    k_max: int,
    canonical_scale: int = ...,
    canonical_level: int = ...,
    eps: float = ...,
): ...

class LevelMapper:
    def __init__(
        self,
        k_min: int,
        k_max: int,
        canonical_scale: int = ...,
        canonical_level: int = ...,
        eps: float = ...,
    ) -> None: ...
    def __call__(self, boxlists: list[Tensor]) -> Tensor: ...

class MultiScaleRoIAlign(nn.Module):
    __annotations__ = ...
    def __init__(
        self,
        featmap_names: list[str],
        output_size: int | tuple[int] | list[int],
        sampling_ratio: int,
        *,
        canonical_scale: int = ...,
        canonical_level: int = ...,
    ) -> None: ...
    def forward(
        self,
        x: dict[str, Tensor],
        boxes: list[Tensor],
        image_shapes: list[tuple[int, int]],
    ) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...
