from typing import Any
from torch import Tensor, nn

import torch
import torch.fx

"""
This type stub file was generated by pyright.
"""

@torch.fx.wrap
def ps_roi_align(
    input: Tensor,
    boxes: Tensor,
    output_size: int,
    spatial_scale: float = ...,
    sampling_ratio: int = ...,
) -> Tensor: ...

class PSRoIAlign(nn.Module):
    def __init__(
        self, output_size: int, spatial_scale: float, sampling_ratio: int
    ) -> None: ...
    def forward(self, input: Tensor, rois: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...
