from typing import Any

from torch import Tensor, nn
from torch.jit.annotations import BroadcastingList2

import torch
import torch.fx

"""
This type stub file was generated by pyright.
"""

def lazy_compile(**compile_kwargs): ...
def maybe_cast(tensor): ...
@torch.fx.wrap
def roi_align(
    input: Tensor,
    boxes: Tensor | list[Tensor],
    output_size: BroadcastingList2[int],
    spatial_scale: float = ...,
    sampling_ratio: int = ...,
    aligned: bool = ...,
) -> Tensor: ...

class RoIAlign(nn.Module):
    def __init__(
        self,
        output_size: BroadcastingList2[int],
        spatial_scale: float,
        sampling_ratio: int,
        aligned: bool = ...,
    ) -> None: ...
    def forward(self, input: Tensor, rois: Tensor | list[Tensor]) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...
