from torch import Tensor, nn
from torch.jit.annotations import BroadcastingList2

import torch
import torch.fx

"""
This type stub file was generated by pyright.
"""

@torch.fx.wrap
def roi_pool(
    input: Tensor,
    boxes: Tensor | list[Tensor],
    output_size: BroadcastingList2[int],
    spatial_scale: float = ...,
) -> Tensor: ...

class RoIPool(nn.Module):
    def __init__(
        self, output_size: BroadcastingList2[int], spatial_scale: float
    ) -> None: ...
    def forward(self, input: Tensor, rois: Tensor | list[Tensor]) -> Tensor: ...
