from typing import Any

from torch import Tensor

from .._api import WeightsEnum, register_model
from .._utils import handle_legacy_interface
from ..googlenet import (
    BasicConv2d,
    GoogLeNet,
    GoogLeNet_Weights,
    GoogLeNetOutputs,
    Inception,
    InceptionAux,
)

"""
This type stub file was generated by pyright.
"""
__all__ = ["GoogLeNet_QuantizedWeights", "QuantizableGoogLeNet", "googlenet"]

class QuantizableBasicConv2d(BasicConv2d):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def fuse_model(self, is_qat: bool | None = ...) -> None: ...

class QuantizableInception(Inception):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class QuantizableInceptionAux(InceptionAux):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class QuantizableGoogLeNet(GoogLeNet):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def forward(self, x: Tensor) -> GoogLeNetOutputs: ...
    def fuse_model(self, is_qat: bool | None = ...) -> None: ...

class GoogLeNet_QuantizedWeights(WeightsEnum):
    IMAGENET1K_FBGEMM_V1 = ...
    DEFAULT = ...

@register_model(name="quantized_googlenet")
@handle_legacy_interface(
    weights=(
        "pretrained",
        lambda kwargs: (
            GoogLeNet_QuantizedWeights.IMAGENET1K_FBGEMM_V1
            if kwargs.get("quantize", False)
            else GoogLeNet_Weights.IMAGENET1K_V1
        ),
    )
)
def googlenet(
    *,
    weights: GoogLeNet_QuantizedWeights | GoogLeNet_Weights | None = ...,
    progress: bool = ...,
    quantize: bool = ...,
    **kwargs: Any,
) -> QuantizableGoogLeNet: ...
