from typing import Any

from torch import Tensor

from .._api import WeightsEnum, register_model
from .._utils import handle_legacy_interface
from ..mobilenetv3 import InvertedResidual, MobileNet_V3_Large_Weights, MobileNetV3
from ...ops.misc import SqueezeExcitation

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "MobileNet_V3_Large_QuantizedWeights",
    "QuantizableMobileNetV3",
    "mobilenet_v3_large",
]

class QuantizableSqueezeExcitation(SqueezeExcitation):
    _version = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def fuse_model(self, is_qat: bool | None = ...) -> None: ...

class QuantizableInvertedResidual(InvertedResidual):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class QuantizableMobileNetV3(MobileNetV3):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def fuse_model(self, is_qat: bool | None = ...) -> None: ...

class MobileNet_V3_Large_QuantizedWeights(WeightsEnum):
    IMAGENET1K_QNNPACK_V1 = ...
    DEFAULT = ...

@register_model(name="quantized_mobilenet_v3_large")
@handle_legacy_interface(
    weights=(
        "pretrained",
        lambda kwargs: (
            MobileNet_V3_Large_QuantizedWeights.IMAGENET1K_QNNPACK_V1
            if kwargs.get("quantize", False)
            else MobileNet_V3_Large_Weights.IMAGENET1K_V1
        ),
    )
)
def mobilenet_v3_large(
    *,
    weights: MobileNet_V3_Large_QuantizedWeights
    | MobileNet_V3_Large_Weights
    | None = ...,
    progress: bool = ...,
    quantize: bool = ...,
    **kwargs: Any,
) -> QuantizableMobileNetV3: ...
