from typing import Any

from torch import Tensor
from torchvision.models.mobilenetv2 import (
    InvertedResidual,
    MobileNet_V2_Weights,
    MobileNetV2,
)

from .._api import WeightsEnum, register_model
from .._utils import handle_legacy_interface

"""
This type stub file was generated by pyright.
"""
__all__ = ["MobileNet_V2_QuantizedWeights", "QuantizableMobileNetV2", "mobilenet_v2"]

class QuantizableInvertedResidual(InvertedResidual):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def fuse_model(self, is_qat: bool | None = ...) -> None: ...

class QuantizableMobileNetV2(MobileNetV2):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def fuse_model(self, is_qat: bool | None = ...) -> None: ...

class MobileNet_V2_QuantizedWeights(WeightsEnum):
    IMAGENET1K_QNNPACK_V1 = ...
    DEFAULT = ...

@register_model(name="quantized_mobilenet_v2")
@handle_legacy_interface(
    weights=(
        "pretrained",
        lambda kwargs: (
            MobileNet_V2_QuantizedWeights.IMAGENET1K_QNNPACK_V1
            if kwargs.get("quantize", False)
            else MobileNet_V2_Weights.IMAGENET1K_V1
        ),
    )
)
def mobilenet_v2(
    *,
    weights: MobileNet_V2_QuantizedWeights | MobileNet_V2_Weights | None = ...,
    progress: bool = ...,
    quantize: bool = ...,
    **kwargs: Any,
) -> QuantizableMobileNetV2: ...
