from typing import Any

from torch import Tensor
from torchvision.models.resnet import (
    BasicBlock,
    Bottleneck,
    ResNet,
    ResNet18_Weights,
    ResNet50_Weights,
    ResNeXt101_32X8D_Weights,
    ResNeXt101_64X4D_Weights,
)

from .._api import WeightsEnum, register_model
from .._utils import handle_legacy_interface

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "QuantizableResNet",
    "ResNeXt101_32X8D_QuantizedWeights",
    "ResNeXt101_64X4D_QuantizedWeights",
    "ResNet18_QuantizedWeights",
    "ResNet50_QuantizedWeights",
    "resnet18",
    "resnet50",
    "resnext101_32x8d",
    "resnext101_64x4d",
]

class QuantizableBasicBlock(BasicBlock):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def fuse_model(self, is_qat: bool | None = ...) -> None: ...

class QuantizableBottleneck(Bottleneck):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def fuse_model(self, is_qat: bool | None = ...) -> None: ...

class QuantizableResNet(ResNet):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def fuse_model(self, is_qat: bool | None = ...) -> None: ...

_COMMON_META = ...

class ResNet18_QuantizedWeights(WeightsEnum):
    IMAGENET1K_FBGEMM_V1 = ...
    DEFAULT = ...

class ResNet50_QuantizedWeights(WeightsEnum):
    IMAGENET1K_FBGEMM_V1 = ...
    IMAGENET1K_FBGEMM_V2 = ...
    DEFAULT = ...

class ResNeXt101_32X8D_QuantizedWeights(WeightsEnum):
    IMAGENET1K_FBGEMM_V1 = ...
    IMAGENET1K_FBGEMM_V2 = ...
    DEFAULT = ...

class ResNeXt101_64X4D_QuantizedWeights(WeightsEnum):
    IMAGENET1K_FBGEMM_V1 = ...
    DEFAULT = ...

@register_model(name="quantized_resnet18")
@handle_legacy_interface(
    weights=(
        "pretrained",
        lambda kwargs: (
            ResNet18_QuantizedWeights.IMAGENET1K_FBGEMM_V1
            if kwargs.get("quantize", False)
            else ResNet18_Weights.IMAGENET1K_V1
        ),
    )
)
def resnet18(
    *,
    weights: ResNet18_QuantizedWeights | ResNet18_Weights | None = ...,
    progress: bool = ...,
    quantize: bool = ...,
    **kwargs: Any,
) -> QuantizableResNet: ...
@register_model(name="quantized_resnet50")
@handle_legacy_interface(
    weights=(
        "pretrained",
        lambda kwargs: (
            ResNet50_QuantizedWeights.IMAGENET1K_FBGEMM_V1
            if kwargs.get("quantize", False)
            else ResNet50_Weights.IMAGENET1K_V1
        ),
    )
)
def resnet50(
    *,
    weights: ResNet50_QuantizedWeights | ResNet50_Weights | None = ...,
    progress: bool = ...,
    quantize: bool = ...,
    **kwargs: Any,
) -> QuantizableResNet: ...
@register_model(name="quantized_resnext101_32x8d")
@handle_legacy_interface(
    weights=(
        "pretrained",
        lambda kwargs: (
            ResNeXt101_32X8D_QuantizedWeights.IMAGENET1K_FBGEMM_V1
            if kwargs.get("quantize", False)
            else ResNeXt101_32X8D_Weights.IMAGENET1K_V1
        ),
    )
)
def resnext101_32x8d(
    *,
    weights: ResNeXt101_32X8D_QuantizedWeights | ResNeXt101_32X8D_Weights | None = ...,
    progress: bool = ...,
    quantize: bool = ...,
    **kwargs: Any,
) -> QuantizableResNet: ...
@register_model(name="quantized_resnext101_64x4d")
@handle_legacy_interface(
    weights=(
        "pretrained",
        lambda kwargs: (
            ResNeXt101_64X4D_QuantizedWeights.IMAGENET1K_FBGEMM_V1
            if kwargs.get("quantize", False)
            else ResNeXt101_64X4D_Weights.IMAGENET1K_V1
        ),
    )
)
def resnext101_64x4d(
    *,
    weights: ResNeXt101_64X4D_QuantizedWeights | ResNeXt101_64X4D_Weights | None = ...,
    progress: bool = ...,
    quantize: bool = ...,
    **kwargs: Any,
) -> QuantizableResNet: ...
