from typing import Any

from torch import Tensor
from torchvision.models import shufflenetv2

from .._api import WeightsEnum, register_model
from .._utils import handle_legacy_interface
from ..shufflenetv2 import (
    ShuffleNet_V2_X0_5_Weights,
    ShuffleNet_V2_X1_0_Weights,
    ShuffleNet_V2_X1_5_Weights,
    ShuffleNet_V2_X2_0_Weights,
)

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "QuantizableShuffleNetV2",
    "ShuffleNet_V2_X0_5_QuantizedWeights",
    "ShuffleNet_V2_X1_0_QuantizedWeights",
    "ShuffleNet_V2_X1_5_QuantizedWeights",
    "ShuffleNet_V2_X2_0_QuantizedWeights",
    "shufflenet_v2_x0_5",
    "shufflenet_v2_x1_0",
    "shufflenet_v2_x1_5",
    "shufflenet_v2_x2_0",
]

class QuantizableInvertedResidual(shufflenetv2.InvertedResidual):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class QuantizableShuffleNetV2(shufflenetv2.ShuffleNetV2):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def fuse_model(self, is_qat: bool | None = ...) -> None: ...

_COMMON_META = ...

class ShuffleNet_V2_X0_5_QuantizedWeights(WeightsEnum):
    IMAGENET1K_FBGEMM_V1 = ...
    DEFAULT = ...

class ShuffleNet_V2_X1_0_QuantizedWeights(WeightsEnum):
    IMAGENET1K_FBGEMM_V1 = ...
    DEFAULT = ...

class ShuffleNet_V2_X1_5_QuantizedWeights(WeightsEnum):
    IMAGENET1K_FBGEMM_V1 = ...
    DEFAULT = ...

class ShuffleNet_V2_X2_0_QuantizedWeights(WeightsEnum):
    IMAGENET1K_FBGEMM_V1 = ...
    DEFAULT = ...

@register_model(name="quantized_shufflenet_v2_x0_5")
@handle_legacy_interface(
    weights=(
        "pretrained",
        lambda kwargs: (
            ShuffleNet_V2_X0_5_QuantizedWeights.IMAGENET1K_FBGEMM_V1
            if kwargs.get("quantize", False)
            else ShuffleNet_V2_X0_5_Weights.IMAGENET1K_V1
        ),
    )
)
def shufflenet_v2_x0_5(
    *,
    weights: ShuffleNet_V2_X0_5_QuantizedWeights
    | ShuffleNet_V2_X0_5_Weights
    | None = ...,
    progress: bool = ...,
    quantize: bool = ...,
    **kwargs: Any,
) -> QuantizableShuffleNetV2: ...
@register_model(name="quantized_shufflenet_v2_x1_0")
@handle_legacy_interface(
    weights=(
        "pretrained",
        lambda kwargs: (
            ShuffleNet_V2_X1_0_QuantizedWeights.IMAGENET1K_FBGEMM_V1
            if kwargs.get("quantize", False)
            else ShuffleNet_V2_X1_0_Weights.IMAGENET1K_V1
        ),
    )
)
def shufflenet_v2_x1_0(
    *,
    weights: ShuffleNet_V2_X1_0_QuantizedWeights
    | ShuffleNet_V2_X1_0_Weights
    | None = ...,
    progress: bool = ...,
    quantize: bool = ...,
    **kwargs: Any,
) -> QuantizableShuffleNetV2: ...
@register_model(name="quantized_shufflenet_v2_x1_5")
@handle_legacy_interface(
    weights=(
        "pretrained",
        lambda kwargs: (
            ShuffleNet_V2_X1_5_QuantizedWeights.IMAGENET1K_FBGEMM_V1
            if kwargs.get("quantize", False)
            else ShuffleNet_V2_X1_5_Weights.IMAGENET1K_V1
        ),
    )
)
def shufflenet_v2_x1_5(
    *,
    weights: ShuffleNet_V2_X1_5_QuantizedWeights
    | ShuffleNet_V2_X1_5_Weights
    | None = ...,
    progress: bool = ...,
    quantize: bool = ...,
    **kwargs: Any,
) -> QuantizableShuffleNetV2: ...
@register_model(name="quantized_shufflenet_v2_x2_0")
@handle_legacy_interface(
    weights=(
        "pretrained",
        lambda kwargs: (
            ShuffleNet_V2_X2_0_QuantizedWeights.IMAGENET1K_FBGEMM_V1
            if kwargs.get("quantize", False)
            else ShuffleNet_V2_X2_0_Weights.IMAGENET1K_V1
        ),
    )
)
def shufflenet_v2_x2_0(
    *,
    weights: ShuffleNet_V2_X2_0_QuantizedWeights
    | ShuffleNet_V2_X2_0_Weights
    | None = ...,
    progress: bool = ...,
    quantize: bool = ...,
    **kwargs: Any,
) -> QuantizableShuffleNetV2: ...
