from _typeshed import Incomplete

np: Incomplete

class PyTreeDefKind:
    leaf: int
    none: int
    tuple: int
    list: int
    dict: int
    custom: int

class AbstractValueKind:
    shapedArray: int
    abstractToken: int

class DType:
    bool: int
    i8: int
    i16: int
    i32: int
    i64: int
    ui8: int
    ui16: int
    ui32: int
    ui64: int
    f16: int
    f32: int
    f64: int
    c64: int
    c128: int
    bf16: int
    i4: int
    ui4: int
    f8_e4m3b11fnuz: int
    f8_e4m3fn: int
    f8_e4m3fnuz: int
    f8_e5m2: int
    f8_e5m2fnuz: int
    f0: int
    f8_e4m3: int
    f8_e3m4: int
    f8_e8m0fnu: int
    f4_e2m1fn: int
    key_fry: int
    key_rbg: int
    key_unsafe_rbg: int

class MemorySpace:
    Missing: int
    Device: int
    Host: int
    Any: int

class AxisType:
    Missing: int
    Auto: int
    Explicit: int
    Manual: int

class ShardingKind:
    unspecified: int
    hlo_sharding: int
    named_sharding: int

class DisabledSafetyCheckKind:
    platform: int
    custom_call: int
    shape_assertions: int

class PyTreeDef:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsPyTreeDef(cls, buf, offset: int = 0): ...
    def Init(self, buf, pos) -> None: ...
    def Kind(self): ...
    def Children(self, j): ...
    def ChildrenLength(self): ...
    def ChildrenIsNone(self): ...
    def ChildrenNames(self, j): ...
    def ChildrenNamesLength(self): ...
    def ChildrenNamesIsNone(self): ...
    def CustomName(self): ...
    def CustomAuxdata(self, j): ...
    def CustomAuxdataAsNumpy(self): ...
    def CustomAuxdataLength(self): ...
    def CustomAuxdataIsNone(self): ...

def PyTreeDefStart(builder) -> None: ...
def PyTreeDefAddKind(builder, kind) -> None: ...
def PyTreeDefAddChildren(builder, children) -> None: ...
def PyTreeDefStartChildrenVector(builder, numElems): ...
def PyTreeDefAddChildrenNames(builder, childrenNames) -> None: ...
def PyTreeDefStartChildrenNamesVector(builder, numElems): ...
def PyTreeDefAddCustomName(builder, customName) -> None: ...
def PyTreeDefAddCustomAuxdata(builder, customAuxdata) -> None: ...
def PyTreeDefStartCustomAuxdataVector(builder, numElems): ...
def PyTreeDefEnd(builder): ...

class AbstractMesh:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsAbstractMesh(cls, buf, offset: int = 0): ...
    def Init(self, buf, pos) -> None: ...
    def AxisSizes(self, j): ...
    def AxisSizesAsNumpy(self): ...
    def AxisSizesLength(self): ...
    def AxisSizesIsNone(self): ...
    def AxisNames(self, j): ...
    def AxisNamesLength(self): ...
    def AxisNamesIsNone(self): ...
    def AxisTypes(self, j): ...
    def AxisTypesAsNumpy(self): ...
    def AxisTypesLength(self): ...
    def AxisTypesIsNone(self): ...

def AbstractMeshStart(builder) -> None: ...
def AbstractMeshAddAxisSizes(builder, axisSizes) -> None: ...
def AbstractMeshStartAxisSizesVector(builder, numElems): ...
def AbstractMeshAddAxisNames(builder, axisNames) -> None: ...
def AbstractMeshStartAxisNamesVector(builder, numElems): ...
def AbstractMeshAddAxisTypes(builder, axisTypes) -> None: ...
def AbstractMeshStartAxisTypesVector(builder, numElems): ...
def AbstractMeshEnd(builder): ...

class PartitionSpecOneAxis:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsPartitionSpecOneAxis(cls, buf, offset: int = 0): ...
    def Init(self, buf, pos) -> None: ...
    def Axes(self, j): ...
    def AxesLength(self): ...
    def AxesIsNone(self): ...

def PartitionSpecOneAxisStart(builder) -> None: ...
def PartitionSpecOneAxisAddAxes(builder, axes) -> None: ...
def PartitionSpecOneAxisStartAxesVector(builder, numElems): ...
def PartitionSpecOneAxisEnd(builder): ...

class PartitionSpec:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsPartitionSpec(cls, buf, offset: int = 0): ...
    def Init(self, buf, pos) -> None: ...
    def Partitions(self, j): ...
    def PartitionsLength(self): ...
    def PartitionsIsNone(self): ...
    def Reduced(self, j): ...
    def ReducedLength(self): ...
    def ReducedIsNone(self): ...
    def Unreduced(self, j): ...
    def UnreducedLength(self): ...
    def UnreducedIsNone(self): ...

def PartitionSpecStart(builder) -> None: ...
def PartitionSpecAddPartitions(builder, partitions) -> None: ...
def PartitionSpecStartPartitionsVector(builder, numElems): ...
def PartitionSpecAddReduced(builder, reduced) -> None: ...
def PartitionSpecStartReducedVector(builder, numElems): ...
def PartitionSpecAddUnreduced(builder, unreduced) -> None: ...
def PartitionSpecStartUnreducedVector(builder, numElems): ...
def PartitionSpecEnd(builder): ...

class NamedSharding:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsNamedSharding(cls, buf, offset: int = 0): ...
    def Init(self, buf, pos) -> None: ...
    def Mesh(self): ...
    def Spec(self): ...
    def MemoryKind(self): ...

def NamedShardingStart(builder) -> None: ...
def NamedShardingAddMesh(builder, mesh) -> None: ...
def NamedShardingAddSpec(builder, spec) -> None: ...
def NamedShardingAddMemoryKind(builder, memoryKind) -> None: ...
def NamedShardingEnd(builder): ...

class AbstractValue:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsAbstractValue(cls, buf, offset: int = 0): ...
    def Init(self, buf, pos) -> None: ...
    def Kind(self): ...
    def Shape(self, j): ...
    def ShapeLength(self): ...
    def ShapeIsNone(self): ...
    def Dtype(self): ...
    def MemorySpace(self): ...

def AbstractValueStart(builder) -> None: ...
def AbstractValueAddKind(builder, kind) -> None: ...
def AbstractValueAddShape(builder, shape) -> None: ...
def AbstractValueStartShapeVector(builder, numElems): ...
def AbstractValueAddDtype(builder, dtype) -> None: ...
def AbstractValueAddMemorySpace(builder, memorySpace) -> None: ...
def AbstractValueEnd(builder): ...

class Sharding:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsSharding(cls, buf, offset: int = 0): ...
    def Init(self, buf, pos) -> None: ...
    def Kind(self): ...
    def HloShardingProto(self, j): ...
    def HloShardingProtoAsNumpy(self): ...
    def HloShardingProtoLength(self): ...
    def HloShardingProtoIsNone(self): ...
    def NamedSharding(self): ...

def ShardingStart(builder) -> None: ...
def ShardingAddKind(builder, kind) -> None: ...
def ShardingAddHloShardingProto(builder, hloShardingProto) -> None: ...
def ShardingStartHloShardingProtoVector(builder, numElems): ...
def ShardingAddNamedSharding(builder, namedSharding) -> None: ...
def ShardingEnd(builder): ...

class Effect:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsEffect(cls, buf, offset: int = 0): ...
    def Init(self, buf, pos) -> None: ...
    def TypeName(self): ...

def EffectStart(builder) -> None: ...
def EffectAddTypeName(builder, typeName) -> None: ...
def EffectEnd(builder): ...

class DisabledSafetyCheck:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsDisabledSafetyCheck(cls, buf, offset: int = 0): ...
    def Init(self, buf, pos) -> None: ...
    def Kind(self): ...
    def CustomCallTarget(self): ...

def DisabledSafetyCheckStart(builder) -> None: ...
def DisabledSafetyCheckAddKind(builder, kind) -> None: ...
def DisabledSafetyCheckAddCustomCallTarget(builder, customCallTarget) -> None: ...
def DisabledSafetyCheckEnd(builder): ...

class Exported:
    @classmethod
    def GetRootAs(cls, buf, offset: int = 0): ...
    @classmethod
    def GetRootAsExported(cls, buf, offset: int = 0): ...
    def Init(self, buf, pos) -> None: ...
    def SerializationVersion(self): ...
    def FunctionName(self): ...
    def InTree(self): ...
    def InAvals(self, j): ...
    def InAvalsLength(self): ...
    def InAvalsIsNone(self): ...
    def OutTree(self): ...
    def OutAvals(self, j): ...
    def OutAvalsLength(self): ...
    def OutAvalsIsNone(self): ...
    def NrDevicesShort(self): ...
    def InShardings(self, j): ...
    def InShardingsLength(self): ...
    def InShardingsIsNone(self): ...
    def OutShardings(self, j): ...
    def OutShardingsLength(self): ...
    def OutShardingsIsNone(self): ...
    def Platforms(self, j): ...
    def PlatformsLength(self): ...
    def PlatformsIsNone(self): ...
    def OrderedEffects(self, j): ...
    def OrderedEffectsLength(self): ...
    def OrderedEffectsIsNone(self): ...
    def UnorderedEffects(self, j): ...
    def UnorderedEffectsLength(self): ...
    def UnorderedEffectsIsNone(self): ...
    def DisabledChecks(self, j): ...
    def DisabledChecksLength(self): ...
    def DisabledChecksIsNone(self): ...
    def MlirModuleSerialized(self, j): ...
    def MlirModuleSerializedAsNumpy(self): ...
    def MlirModuleSerializedLength(self): ...
    def MlirModuleSerializedIsNone(self): ...
    def CallingConventionVersion(self): ...
    def ModuleKeptVarIdx(self, j): ...
    def ModuleKeptVarIdxAsNumpy(self): ...
    def ModuleKeptVarIdxLength(self): ...
    def ModuleKeptVarIdxIsNone(self): ...
    def UsesGlobalConstants(self): ...
    def Vjp(self): ...
    def NrDevices(self): ...

def ExportedStart(builder) -> None: ...
def ExportedAddSerializationVersion(builder, serializationVersion) -> None: ...
def ExportedAddFunctionName(builder, functionName) -> None: ...
def ExportedAddInTree(builder, inTree) -> None: ...
def ExportedAddInAvals(builder, inAvals) -> None: ...
def ExportedStartInAvalsVector(builder, numElems): ...
def ExportedAddOutTree(builder, outTree) -> None: ...
def ExportedAddOutAvals(builder, outAvals) -> None: ...
def ExportedStartOutAvalsVector(builder, numElems): ...
def ExportedAddNrDevicesShort(builder, nrDevicesShort) -> None: ...
def ExportedAddInShardings(builder, inShardings) -> None: ...
def ExportedStartInShardingsVector(builder, numElems): ...
def ExportedAddOutShardings(builder, outShardings) -> None: ...
def ExportedStartOutShardingsVector(builder, numElems): ...
def ExportedAddPlatforms(builder, platforms) -> None: ...
def ExportedStartPlatformsVector(builder, numElems): ...
def ExportedAddOrderedEffects(builder, orderedEffects) -> None: ...
def ExportedStartOrderedEffectsVector(builder, numElems): ...
def ExportedAddUnorderedEffects(builder, unorderedEffects) -> None: ...
def ExportedStartUnorderedEffectsVector(builder, numElems): ...
def ExportedAddDisabledChecks(builder, disabledChecks) -> None: ...
def ExportedStartDisabledChecksVector(builder, numElems): ...
def ExportedAddMlirModuleSerialized(builder, mlirModuleSerialized) -> None: ...
def ExportedStartMlirModuleSerializedVector(builder, numElems): ...
def ExportedAddCallingConventionVersion(builder, callingConventionVersion) -> None: ...
def ExportedAddModuleKeptVarIdx(builder, moduleKeptVarIdx) -> None: ...
def ExportedStartModuleKeptVarIdxVector(builder, numElems): ...
def ExportedAddUsesGlobalConstants(builder, usesGlobalConstants) -> None: ...
def ExportedAddVjp(builder, vjp) -> None: ...
def ExportedAddNrDevices(builder, nrDevices) -> None: ...
def ExportedEnd(builder): ...
