from collections.abc import (
    Callable as Callable,
    Sequence,
)
from enum import Enum
from typing import Any, TypeAlias

import dataclasses
import enum
import tokenize

from _typeshed import Incomplete
from jax._src import (
    api as api,
    config as config,
    core as core,
    dtypes as dtypes,
    effects as effects,
    source_info_util as source_info_util,
    tree_util as tree_util,
    typing as typing,
    util as util,
)
from jax._src.interpreters import mlir as mlir

DimSize: TypeAlias
type TfVal = Any
DimVarEnv: Incomplete
type DType = Any
SortedTerms: TypeAlias
SortedFactors: TypeAlias
NormalizationRules: Incomplete

class InconclusiveDimensionOperation(core.InconclusiveDimensionOperation):
    def __init__(self, message: str) -> None: ...

class UnexpectedDimVar(Exception): ...

class Comparator(Enum):
    EQ = 1
    GEQ = 2

@dataclasses.dataclass(frozen=True)
class _SymbolicConstraint:
    cmp: Comparator
    debug_str: str
    e1: DimSize
    e2: DimSize
    diff: DimSize

class _DimFactor:
    FLOORDIV: str
    MOD: str
    MAX: str
    MIN: str
    var: Incomplete
    operation: Incomplete
    operands: Incomplete
    def __init__(
        self,
        *operands: _DimExpr,
        var: str | None = None,
        operation: str | None = None,
    ) -> None: ...
    @staticmethod
    def from_var(v: str) -> _DimFactor: ...
    @staticmethod
    def from_operation(
        operation: str,
        *operands: DimSize,
        scope: SymbolicScope,
    ) -> _DimFactor: ...
    def to_var(self) -> str | None: ...
    def get_vars(self) -> set[str]: ...
    def __hash__(self): ...
    def __eq__(self, other: object): ...
    def __lt__(self, other: _DimFactor): ...
    def __le__(self, other: _DimFactor): ...
    def __gt__(self, other: _DimFactor): ...
    def __ge__(self, other: _DimFactor): ...
    def evaluate(self, env: DimVarEnv, scope: SymbolicScope): ...
    def __deepcopy__(self, memo): ...

class _DimTerm:
    def __init__(self, sorted_factors: SortedFactors) -> None: ...
    def __hash__(self): ...
    @staticmethod
    def from_var(v: str) -> _DimTerm: ...
    @staticmethod
    def from_factor(f: _DimFactor, f_exp: int): ...
    @staticmethod
    def from_operation(
        operation: str,
        *operands: DimSize,
        scope: SymbolicScope,
    ) -> _DimTerm: ...
    def to_var(self) -> str | None: ...
    def to_factor(self) -> _DimFactor | None: ...
    def get_vars(self) -> set[str]: ...
    @property
    def is_constant(self): ...
    def __lt__(self, other: _DimTerm): ...
    def __le__(self, other: _DimTerm): ...
    def __gt__(self, other: _DimTerm): ...
    def __ge__(self, other: _DimTerm): ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def mul(self, other: _DimTerm) -> _DimTerm: ...
    def divide(self, divisor: _DimTerm) -> _DimTerm: ...
    def evaluate(self, env: DimVarEnv, scope: SymbolicScope): ...
    def __deepcopy__(self, memo): ...

class _DimExpr:
    __array_priority__: int
    def __init__(self, sorted_terms: SortedTerms, scope: SymbolicScope) -> None: ...
    @property
    def scope(self): ...
    get_vars: Incomplete
    def __hash__(self): ...
    def __add__(self, other): ...
    def __radd__(self, other): ...
    def __sub__(self, other): ...
    def __rsub__(self, other): ...
    def __neg__(self) -> DimSize: ...
    def __mul__(self, other): ...
    def __rmul__(self, other): ...
    def __pow__(self, power: core.DimSize, modulo=None): ...
    def __rpow__(self, other, modulo=None): ...
    def __floordiv__(self, divisor): ...
    def __rfloordiv__(self, other): ...
    def __truediv__(self, divisor): ...
    def __rtruediv__(self, dividend): ...
    def __mod__(self, divisor): ...
    def __rmod__(self, dividend): ...
    def __divmod__(self, divisor): ...
    def __rdivmod__(self, dividend): ...
    def __int__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __ge__(self, other: DimSize) -> bool: ...
    def __le__(self, other: DimSize): ...
    def __gt__(self, other: DimSize): ...
    def __lt__(self, other: DimSize): ...
    def max(self, other: DimSize) -> DimSize: ...
    def rmax(self, other: DimSize) -> DimSize: ...
    def min(self, other: DimSize) -> DimSize: ...
    def rmin(self, other: DimSize) -> DimSize: ...
    def dimension_as_value(self): ...
    def __jax_array__(self): ...
    def __deepcopy__(self, memo): ...

def cmp_comparable(i1, i2) -> int: ...
def cmp_sequence(s1, s2, elem_cmp) -> int: ...

class SymbolicScope:
    def __init__(self, constraints_str: Sequence[str] = ()) -> None: ...

class BoundsPrecision(enum.Enum):
    FOR_GEQ0_OR_LEQ0 = 0
    FOR_GEQ0_OR_LT0 = 1
    BEST = 2

def is_symbolic_dim(p: DimSize) -> bool: ...

shape_assertion_p: Incomplete

class ShapeAssertionEffect(effects.Effect): ...

shape_assertion_effect: Incomplete

def shape_assertion(
    assert_what: typing.Array,
    *error_message_inputs: typing.Array,
    error_message: str,
) -> None: ...

dim_as_value_p: Incomplete

def dim_as_value_impl(dim: DimSize): ...

class PolyShape(tuple):
    def __init__(self, *dim_specs) -> None: ...
    def __new__(cls, *dim_specs): ...

def symbolic_shape(
    shape_spec: str | None,
    *,
    constraints: Sequence[str] = (),
    scope: SymbolicScope | None = None,
    like: Sequence[int | None] | None = None,
) -> Sequence[DimSize]: ...
def symbolic_args_specs(
    args,
    shapes_specs,
    constraints: Sequence[str] = (),
    scope: SymbolicScope | None = None,
): ...
def shape_and_dtype_jax_array(a) -> tuple[Sequence[int | None], DType]: ...

class _Parser:
    shape_spec: Incomplete
    shape_spec_repr: Incomplete
    like_shape: Incomplete
    dimensions: list[DimSize]
    scope: Incomplete
    def __init__(
        self,
        shape_spec: str,
        like_shape: Sequence[int | None] | None,
        shape_spec_repr: str,
        scope: SymbolicScope,
    ) -> None: ...
    tokstream: Incomplete
    def parse(self) -> Sequence[DimSize]: ...
    def add_dim(self, expr: DimSize | None, tok: tokenize.TokenInfo): ...
    def parse_err(self, tok: tokenize.TokenInfo | None, detail: str) -> Exception: ...
    def next_tok(self) -> tokenize.TokenInfo: ...
    def expect_token(
        self,
        tok: tokenize.TokenInfo,
        expected: Sequence[int],
    ) -> None: ...
    def consume_token(
        self,
        tok: tokenize.TokenInfo,
        expected: int,
    ) -> tokenize.TokenInfo: ...
    def integer(self, tok: tokenize.TokenInfo) -> tuple[int, tokenize.TokenInfo]: ...
    FOLLOW_SHAPE: Incomplete
    def shape(
        self,
        tok: tokenize.TokenInfo,
    ) -> tuple[Sequence[DimSize], tokenize.TokenInfo]: ...
    FOLLOW_EXPR: Incomplete
    def expr(self, tok: tokenize.TokenInfo) -> tuple[DimSize, tokenize.TokenInfo]: ...
    FOLLOW_TERM: Incomplete
    def term(self, tok: tokenize.TokenInfo) -> tuple[DimSize, tokenize.TokenInfo]: ...
    def factor(self, tok: tokenize.TokenInfo) -> tuple[DimSize, tokenize.TokenInfo]: ...
    def factor_unary_op(
        self,
        op: str,
        tok: tokenize.TokenInfo,
    ) -> tuple[DimSize, tokenize.TokenInfo]: ...
    def factor_binary_op(self, op: str, tok) -> tuple[DimSize, tokenize.TokenInfo]: ...

dimension_size_p: Incomplete

def all_dim_vars(args_avals: Sequence[core.ShapedArray]) -> Sequence[str]: ...

class ShapeEvaluator:
    env: Incomplete
    def __init__(self, env: DimVarEnv) -> None: ...
    def evaluate(self, e: DimSize): ...

@dataclasses.dataclass(frozen=True)
class ShapeConstraint:
    comp: Comparator
    left: DimSize
    right: DimSize
    error_message_pieces: Sequence[str | DimSize]
    def check_statically(self, eval: ShapeEvaluator) -> None: ...
    def compute(self, eval: ShapeEvaluator) -> typing.Array | None: ...
    def error_message_and_inputs(
        self,
        eval: ShapeEvaluator,
    ) -> tuple[str, Sequence[Any]]: ...
    def make_error(self, eval: ShapeEvaluator) -> Exception: ...

class ShapeConstraints:
    constraints: list[ShapeConstraint]
    def __init__(self) -> None: ...
    def add_constraint(
        self,
        comp: Comparator,
        left: DimSize,
        right: DimSize,
        error_message_pieces: Sequence[str | DimSize],
    ): ...
    def check_statically(self, eval: ShapeEvaluator) -> None: ...
    def shape_assertions(self, eval: ShapeEvaluator) -> None: ...

@dataclasses.dataclass
class _DimEquation:
    aval_dim_expr: _DimExpr
    dim_name: str

def args_kwargs_path_to_str(path: tree_util.KeyPath) -> str: ...
def pretty_print_dimension_descriptor(
    args_kwargs_tree: tree_util.PyTreeDef,
    flat_arg_idx: int,
    dim_idx: int | None,
) -> str: ...
def solve_dim_vars(
    args_avals: Sequence[core.ShapedArray],
    args_kwargs_tree: tree_util.PyTreeDef,
) -> tuple[DimVarEnv, ShapeConstraints, Sequence[tuple[str, int, int]]]: ...
def compute_dim_vars_from_arg_shapes(
    args_avals: Sequence[core.ShapedArray],
    *actual_args: typing.Array,
    args_kwargs_tree: tree_util.PyTreeDef,
) -> Sequence[typing.Array]: ...
