from enum import Enum
from types import ModuleType
from typing import Any

class BackendFilter(Enum):
    INTERACTIVE = ...
    NON_INTERACTIVE = ...

class BackendRegistry:
    _BUILTIN_BACKEND_TO_GUI_FRAMEWORK = ...
    _GUI_FRAMEWORK_TO_BACKEND = ...
    def __init__(self) -> None: ...
    def backend_for_gui_framework(self, framework) -> str | None: ...
    def is_valid_backend(self, backend) -> bool: ...
    def list_all(self) -> list[str | Any]: ...
    def list_builtin(self, filter_=...) -> list[str]: ...
    def list_gui_frameworks(self) -> list[str]: ...
    def load_backend_module(self, backend) -> ModuleType: ...
    def resolve_backend(self, backend) -> tuple[str, Any | str | None]: ...
    def resolve_gui_or_backend(
        self,
        gui_or_backend,
    ) -> tuple[str, Any | None] | tuple[str, Any | str | None]: ...

backend_registry = ...
