from torchvision.transforms import InterpolationMode as InterpolationMode

from ._augment import (
    erase as erase,
    erase_image as erase_image,
    erase_video as erase_video,
    jpeg as jpeg,
    jpeg_image as jpeg_image,
    jpeg_video as jpeg_video,
)
from ._color import (
    adjust_brightness as adjust_brightness,
    adjust_brightness_image as adjust_brightness_image,
    adjust_brightness_video as adjust_brightness_video,
    adjust_contrast as adjust_contrast,
    adjust_contrast_image as adjust_contrast_image,
    adjust_contrast_video as adjust_contrast_video,
    adjust_gamma as adjust_gamma,
    adjust_gamma_image as adjust_gamma_image,
    adjust_gamma_video as adjust_gamma_video,
    adjust_hue as adjust_hue,
    adjust_hue_image as adjust_hue_image,
    adjust_hue_video as adjust_hue_video,
    adjust_saturation as adjust_saturation,
    adjust_saturation_image as adjust_saturation_image,
    adjust_saturation_video as adjust_saturation_video,
    adjust_sharpness as adjust_sharpness,
    adjust_sharpness_image as adjust_sharpness_image,
    adjust_sharpness_video as adjust_sharpness_video,
    autocontrast as autocontrast,
    autocontrast_image as autocontrast_image,
    autocontrast_video as autocontrast_video,
    equalize as equalize,
    equalize_image as equalize_image,
    equalize_video as equalize_video,
    grayscale_to_rgb as grayscale_to_rgb,
    grayscale_to_rgb_image as grayscale_to_rgb_image,
    invert as invert,
    invert_image as invert_image,
    invert_video as invert_video,
    permute_channels as permute_channels,
    permute_channels_image as permute_channels_image,
    permute_channels_video as permute_channels_video,
    posterize as posterize,
    posterize_image as posterize_image,
    posterize_video as posterize_video,
    rgb_to_grayscale as rgb_to_grayscale,
    rgb_to_grayscale_image as rgb_to_grayscale_image,
    solarize as solarize,
    solarize_image as solarize_image,
    solarize_video as solarize_video,
    to_grayscale as to_grayscale,
)
from ._deprecated import (
    get_image_size as get_image_size,
    to_tensor as to_tensor,
)
from ._geometry import (
    affine as affine,
    affine_bounding_boxes as affine_bounding_boxes,
    affine_image as affine_image,
    affine_keypoints as affine_keypoints,
    affine_mask as affine_mask,
    affine_video as affine_video,
    center_crop as center_crop,
    center_crop_bounding_boxes as center_crop_bounding_boxes,
    center_crop_image as center_crop_image,
    center_crop_keypoints as center_crop_keypoints,
    center_crop_mask as center_crop_mask,
    center_crop_video as center_crop_video,
    crop as crop,
    crop_bounding_boxes as crop_bounding_boxes,
    crop_image as crop_image,
    crop_keypoints as crop_keypoints,
    crop_mask as crop_mask,
    crop_video as crop_video,
    elastic as elastic,
    elastic_bounding_boxes as elastic_bounding_boxes,
    elastic_image as elastic_image,
    elastic_keypoints as elastic_keypoints,
    elastic_mask as elastic_mask,
    elastic_transform as elastic_transform,
    elastic_video as elastic_video,
    five_crop as five_crop,
    five_crop_image as five_crop_image,
    five_crop_video as five_crop_video,
    hflip as hflip,
    horizontal_flip as horizontal_flip,
    horizontal_flip_bounding_boxes as horizontal_flip_bounding_boxes,
    horizontal_flip_image as horizontal_flip_image,
    horizontal_flip_keypoints as horizontal_flip_keypoints,
    horizontal_flip_mask as horizontal_flip_mask,
    horizontal_flip_video as horizontal_flip_video,
    pad as pad,
    pad_bounding_boxes as pad_bounding_boxes,
    pad_image as pad_image,
    pad_keypoints as pad_keypoints,
    pad_mask as pad_mask,
    pad_video as pad_video,
    perspective as perspective,
    perspective_bounding_boxes as perspective_bounding_boxes,
    perspective_image as perspective_image,
    perspective_keypoints as perspective_keypoints,
    perspective_mask as perspective_mask,
    perspective_video as perspective_video,
    resize as resize,
    resize_bounding_boxes as resize_bounding_boxes,
    resize_image as resize_image,
    resize_keypoints as resize_keypoints,
    resize_mask as resize_mask,
    resize_video as resize_video,
    resized_crop as resized_crop,
    resized_crop_bounding_boxes as resized_crop_bounding_boxes,
    resized_crop_image as resized_crop_image,
    resized_crop_keypoints as resized_crop_keypoints,
    resized_crop_mask as resized_crop_mask,
    resized_crop_video as resized_crop_video,
    rotate as rotate,
    rotate_bounding_boxes as rotate_bounding_boxes,
    rotate_image as rotate_image,
    rotate_keypoints as rotate_keypoints,
    rotate_mask as rotate_mask,
    rotate_video as rotate_video,
    ten_crop as ten_crop,
    ten_crop_image as ten_crop_image,
    ten_crop_video as ten_crop_video,
    vertical_flip as vertical_flip,
    vertical_flip_bounding_boxes as vertical_flip_bounding_boxes,
    vertical_flip_image as vertical_flip_image,
    vertical_flip_keypoints as vertical_flip_keypoints,
    vertical_flip_mask as vertical_flip_mask,
    vertical_flip_video as vertical_flip_video,
    vflip as vflip,
)
from ._meta import (
    clamp_bounding_boxes as clamp_bounding_boxes,
    clamp_keypoints as clamp_keypoints,
    convert_bounding_box_format as convert_bounding_box_format,
    get_dimensions as get_dimensions,
    get_dimensions_image as get_dimensions_image,
    get_dimensions_video as get_dimensions_video,
    get_image_num_channels as get_image_num_channels,
    get_num_channels as get_num_channels,
    get_num_channels_image as get_num_channels_image,
    get_num_channels_video as get_num_channels_video,
    get_num_frames as get_num_frames,
    get_num_frames_video as get_num_frames_video,
    get_size as get_size,
    get_size_bounding_boxes as get_size_bounding_boxes,
    get_size_image as get_size_image,
    get_size_keypoints as get_size_keypoints,
    get_size_mask as get_size_mask,
    get_size_video as get_size_video,
)
from ._misc import (
    convert_image_dtype as convert_image_dtype,
    gaussian_blur as gaussian_blur,
    gaussian_blur_image as gaussian_blur_image,
    gaussian_blur_video as gaussian_blur_video,
    gaussian_noise as gaussian_noise,
    gaussian_noise_image as gaussian_noise_image,
    gaussian_noise_video as gaussian_noise_video,
    normalize as normalize,
    normalize_image as normalize_image,
    normalize_video as normalize_video,
    sanitize_bounding_boxes as sanitize_bounding_boxes,
    to_dtype as to_dtype,
    to_dtype_image as to_dtype_image,
    to_dtype_video as to_dtype_video,
)
from ._temporal import (
    uniform_temporal_subsample as uniform_temporal_subsample,
    uniform_temporal_subsample_video as uniform_temporal_subsample_video,
)
from ._type_conversion import (
    pil_to_tensor as pil_to_tensor,
    to_image as to_image,
    to_pil_image as to_pil_image,
)
from ._utils import (
    is_pure_tensor as is_pure_tensor,
    register_kernel as register_kernel,
)
