from typing import Any

import torch

"""
This type stub file was generated by pyright.
"""

@torch.jit.unused
def to_tensor(inpt: Any) -> torch.Tensor: ...
def get_image_size(inpt: torch.Tensor) -> list[int]: ...
