from torchvision import tv_tensors
from torchvision.transforms.functional import InterpolationMode
from torchvision.tv_tensors._bounding_boxes import CLAMPING_MODE_TYPE

import torch

from ._utils import (
    _FillTypeJIT,
    _register_five_ten_crop_kernel_internal,
    _register_kernel_internal,
)

"""
This type stub file was generated by pyright.
"""

def horizontal_flip(inpt: torch.Tensor) -> torch.Tensor: ...
@_register_kernel_internal(horizontal_flip, torch.Tensor)
@_register_kernel_internal(horizontal_flip, tv_tensors.Image)
def horizontal_flip_image(image: torch.Tensor) -> torch.Tensor: ...
@_register_kernel_internal(horizontal_flip, tv_tensors.Mask)
def horizontal_flip_mask(mask: torch.Tensor) -> torch.Tensor: ...
def horizontal_flip_keypoints(
    keypoints: torch.Tensor, canvas_size: tuple[int, int]
): ...
def horizontal_flip_bounding_boxes(
    bounding_boxes: torch.Tensor,
    format: tv_tensors.BoundingBoxFormat,
    canvas_size: tuple[int, int],
) -> torch.Tensor: ...
@_register_kernel_internal(horizontal_flip, tv_tensors.Video)
def horizontal_flip_video(video: torch.Tensor) -> torch.Tensor: ...
def vertical_flip(inpt: torch.Tensor) -> torch.Tensor: ...
@_register_kernel_internal(vertical_flip, torch.Tensor)
@_register_kernel_internal(vertical_flip, tv_tensors.Image)
def vertical_flip_image(image: torch.Tensor) -> torch.Tensor: ...
@_register_kernel_internal(vertical_flip, tv_tensors.Mask)
def vertical_flip_mask(mask: torch.Tensor) -> torch.Tensor: ...
def vertical_flip_keypoints(
    keypoints: torch.Tensor, canvas_size: tuple[int, int]
) -> torch.Tensor: ...
def vertical_flip_bounding_boxes(
    bounding_boxes: torch.Tensor,
    format: tv_tensors.BoundingBoxFormat,
    canvas_size: tuple[int, int],
) -> torch.Tensor: ...
@_register_kernel_internal(vertical_flip, tv_tensors.Video)
def vertical_flip_video(video: torch.Tensor) -> torch.Tensor: ...

hflip = ...
vflip = ...

def resize(
    inpt: torch.Tensor,
    size: list[int] | None,
    interpolation: InterpolationMode | int = ...,
    max_size: int | None = ...,
    antialias: bool | None = ...,
) -> torch.Tensor: ...
@_register_kernel_internal(resize, torch.Tensor)
@_register_kernel_internal(resize, tv_tensors.Image)
def resize_image(
    image: torch.Tensor,
    size: list[int] | None,
    interpolation: InterpolationMode | int = ...,
    max_size: int | None = ...,
    antialias: bool | None = ...,
) -> torch.Tensor: ...
def resize_mask(
    mask: torch.Tensor, size: list[int] | None, max_size: int | None = ...
) -> torch.Tensor: ...
def resize_keypoints(
    keypoints: torch.Tensor,
    size: list[int] | None,
    canvas_size: tuple[int, int],
    max_size: int | None = ...,
): ...
def resize_bounding_boxes(
    bounding_boxes: torch.Tensor,
    canvas_size: tuple[int, int],
    size: list[int] | None,
    max_size: int | None = ...,
    format: tv_tensors.BoundingBoxFormat = ...,
    clamping_mode: CLAMPING_MODE_TYPE = ...,
) -> tuple[torch.Tensor, tuple[int, int]]: ...
@_register_kernel_internal(resize, tv_tensors.Video)
def resize_video(
    video: torch.Tensor,
    size: list[int] | None,
    interpolation: InterpolationMode | int = ...,
    max_size: int | None = ...,
    antialias: bool | None = ...,
) -> torch.Tensor: ...
def affine(
    inpt: torch.Tensor,
    angle: float,
    translate: list[float],
    scale: float,
    shear: list[float],
    interpolation: InterpolationMode | int = ...,
    fill: _FillTypeJIT = ...,
    center: list[float] | None = ...,
) -> torch.Tensor: ...
@_register_kernel_internal(affine, torch.Tensor)
@_register_kernel_internal(affine, tv_tensors.Image)
def affine_image(
    image: torch.Tensor,
    angle: float,
    translate: list[float],
    scale: float,
    shear: list[float],
    interpolation: InterpolationMode | int = ...,
    fill: _FillTypeJIT = ...,
    center: list[float] | None = ...,
) -> torch.Tensor: ...
def affine_keypoints(
    keypoints: torch.Tensor,
    canvas_size: tuple[int, int],
    angle: float,
    translate: list[float],
    scale: float,
    shear: list[float],
    center: list[float] | None = ...,
): ...
def affine_bounding_boxes(
    bounding_boxes: torch.Tensor,
    format: tv_tensors.BoundingBoxFormat,
    canvas_size: tuple[int, int],
    angle: float,
    translate: list[float],
    scale: float,
    shear: list[float],
    center: list[float] | None = ...,
    clamping_mode: CLAMPING_MODE_TYPE = ...,
) -> torch.Tensor: ...
def affine_mask(
    mask: torch.Tensor,
    angle: float,
    translate: list[float],
    scale: float,
    shear: list[float],
    fill: _FillTypeJIT = ...,
    center: list[float] | None = ...,
) -> torch.Tensor: ...
@_register_kernel_internal(affine, tv_tensors.Video)
def affine_video(
    video: torch.Tensor,
    angle: float,
    translate: list[float],
    scale: float,
    shear: list[float],
    interpolation: InterpolationMode | int = ...,
    fill: _FillTypeJIT = ...,
    center: list[float] | None = ...,
) -> torch.Tensor: ...
def rotate(
    inpt: torch.Tensor,
    angle: float,
    interpolation: InterpolationMode | int = ...,
    expand: bool = ...,
    center: list[float] | None = ...,
    fill: _FillTypeJIT = ...,
) -> torch.Tensor: ...
@_register_kernel_internal(rotate, torch.Tensor)
@_register_kernel_internal(rotate, tv_tensors.Image)
def rotate_image(
    image: torch.Tensor,
    angle: float,
    interpolation: InterpolationMode | int = ...,
    expand: bool = ...,
    center: list[float] | None = ...,
    fill: _FillTypeJIT = ...,
) -> torch.Tensor: ...
def rotate_keypoints(
    keypoints: torch.Tensor,
    canvas_size: tuple[int, int],
    angle: float,
    expand: bool = ...,
    center: list[float] | None = ...,
) -> tuple[torch.Tensor, tuple[int, int]]: ...
def rotate_bounding_boxes(
    bounding_boxes: torch.Tensor,
    format: tv_tensors.BoundingBoxFormat,
    canvas_size: tuple[int, int],
    angle: float,
    expand: bool = ...,
    center: list[float] | None = ...,
    clamping_mode: CLAMPING_MODE_TYPE = ...,
) -> tuple[torch.Tensor, tuple[int, int]]: ...
def rotate_mask(
    mask: torch.Tensor,
    angle: float,
    expand: bool = ...,
    center: list[float] | None = ...,
    fill: _FillTypeJIT = ...,
) -> torch.Tensor: ...
@_register_kernel_internal(rotate, tv_tensors.Video)
def rotate_video(
    video: torch.Tensor,
    angle: float,
    interpolation: InterpolationMode | int = ...,
    expand: bool = ...,
    center: list[float] | None = ...,
    fill: _FillTypeJIT = ...,
) -> torch.Tensor: ...
def pad(
    inpt: torch.Tensor,
    padding: list[int],
    fill: float | list[float] | None = ...,
    padding_mode: str = ...,
) -> torch.Tensor: ...
@_register_kernel_internal(pad, torch.Tensor)
@_register_kernel_internal(pad, tv_tensors.Image)
def pad_image(
    image: torch.Tensor,
    padding: list[int],
    fill: float | list[float] | None = ...,
    padding_mode: str = ...,
) -> torch.Tensor: ...

_pad_image_pil = ...

@_register_kernel_internal(pad, tv_tensors.Mask)
def pad_mask(
    mask: torch.Tensor,
    padding: list[int],
    fill: float | list[float] | None = ...,
    padding_mode: str = ...,
) -> torch.Tensor: ...
def pad_keypoints(
    keypoints: torch.Tensor,
    canvas_size: tuple[int, int],
    padding: list[int],
    padding_mode: str = ...,
): ...
def pad_bounding_boxes(
    bounding_boxes: torch.Tensor,
    format: tv_tensors.BoundingBoxFormat,
    canvas_size: tuple[int, int],
    padding: list[int],
    padding_mode: str = ...,
    clamping_mode: CLAMPING_MODE_TYPE = ...,
) -> tuple[torch.Tensor, tuple[int, int]]: ...
@_register_kernel_internal(pad, tv_tensors.Video)
def pad_video(
    video: torch.Tensor,
    padding: list[int],
    fill: float | list[float] | None = ...,
    padding_mode: str = ...,
) -> torch.Tensor: ...
def crop(
    inpt: torch.Tensor, top: int, left: int, height: int, width: int
) -> torch.Tensor: ...
@_register_kernel_internal(crop, torch.Tensor)
@_register_kernel_internal(crop, tv_tensors.Image)
def crop_image(
    image: torch.Tensor, top: int, left: int, height: int, width: int
) -> torch.Tensor: ...

_crop_image_pil = ...

def crop_keypoints(
    keypoints: torch.Tensor, top: int, left: int, height: int, width: int
) -> tuple[torch.Tensor, tuple[int, int]]: ...
def crop_bounding_boxes(
    bounding_boxes: torch.Tensor,
    format: tv_tensors.BoundingBoxFormat,
    top: int,
    left: int,
    height: int,
    width: int,
    clamping_mode: CLAMPING_MODE_TYPE = ...,
) -> tuple[torch.Tensor, tuple[int, int]]: ...
@_register_kernel_internal(crop, tv_tensors.Mask)
def crop_mask(
    mask: torch.Tensor, top: int, left: int, height: int, width: int
) -> torch.Tensor: ...
@_register_kernel_internal(crop, tv_tensors.Video)
def crop_video(
    video: torch.Tensor, top: int, left: int, height: int, width: int
) -> torch.Tensor: ...
def perspective(
    inpt: torch.Tensor,
    startpoints: list[list[int]] | None,
    endpoints: list[list[int]] | None,
    interpolation: InterpolationMode | int = ...,
    fill: _FillTypeJIT = ...,
    coefficients: list[float] | None = ...,
) -> torch.Tensor: ...
@_register_kernel_internal(perspective, torch.Tensor)
@_register_kernel_internal(perspective, tv_tensors.Image)
def perspective_image(
    image: torch.Tensor,
    startpoints: list[list[int]] | None,
    endpoints: list[list[int]] | None,
    interpolation: InterpolationMode | int = ...,
    fill: _FillTypeJIT = ...,
    coefficients: list[float] | None = ...,
) -> torch.Tensor: ...
def perspective_keypoints(
    keypoints: torch.Tensor,
    canvas_size: tuple[int, int],
    startpoints: list[list[int]] | None,
    endpoints: list[list[int]] | None,
    coefficients: list[float] | None = ...,
): ...
def perspective_bounding_boxes(
    bounding_boxes: torch.Tensor,
    format: tv_tensors.BoundingBoxFormat,
    canvas_size: tuple[int, int],
    startpoints: list[list[int]] | None,
    endpoints: list[list[int]] | None,
    coefficients: list[float] | None = ...,
    clamping_mode: CLAMPING_MODE_TYPE = ...,
) -> torch.Tensor: ...
def perspective_mask(
    mask: torch.Tensor,
    startpoints: list[list[int]] | None,
    endpoints: list[list[int]] | None,
    fill: _FillTypeJIT = ...,
    coefficients: list[float] | None = ...,
) -> torch.Tensor: ...
@_register_kernel_internal(perspective, tv_tensors.Video)
def perspective_video(
    video: torch.Tensor,
    startpoints: list[list[int]] | None,
    endpoints: list[list[int]] | None,
    interpolation: InterpolationMode | int = ...,
    fill: _FillTypeJIT = ...,
    coefficients: list[float] | None = ...,
) -> torch.Tensor: ...
def elastic(
    inpt: torch.Tensor,
    displacement: torch.Tensor,
    interpolation: InterpolationMode | int = ...,
    fill: _FillTypeJIT = ...,
) -> torch.Tensor: ...

elastic_transform = ...

@_register_kernel_internal(elastic, torch.Tensor)
@_register_kernel_internal(elastic, tv_tensors.Image)
def elastic_image(
    image: torch.Tensor,
    displacement: torch.Tensor,
    interpolation: InterpolationMode | int = ...,
    fill: _FillTypeJIT = ...,
) -> torch.Tensor: ...
def elastic_keypoints(
    keypoints: torch.Tensor, canvas_size: tuple[int, int], displacement: torch.Tensor
) -> torch.Tensor: ...
def elastic_bounding_boxes(
    bounding_boxes: torch.Tensor,
    format: tv_tensors.BoundingBoxFormat,
    canvas_size: tuple[int, int],
    displacement: torch.Tensor,
    clamping_mode: CLAMPING_MODE_TYPE = ...,
) -> torch.Tensor: ...
def elastic_mask(
    mask: torch.Tensor, displacement: torch.Tensor, fill: _FillTypeJIT = ...
) -> torch.Tensor: ...
@_register_kernel_internal(elastic, tv_tensors.Video)
def elastic_video(
    video: torch.Tensor,
    displacement: torch.Tensor,
    interpolation: InterpolationMode | int = ...,
    fill: _FillTypeJIT = ...,
) -> torch.Tensor: ...
def center_crop(inpt: torch.Tensor, output_size: list[int]) -> torch.Tensor: ...
@_register_kernel_internal(center_crop, torch.Tensor)
@_register_kernel_internal(center_crop, tv_tensors.Image)
def center_crop_image(image: torch.Tensor, output_size: list[int]) -> torch.Tensor: ...
def center_crop_keypoints(
    inpt: torch.Tensor, canvas_size: tuple[int, int], output_size: list[int]
): ...
def center_crop_bounding_boxes(
    bounding_boxes: torch.Tensor,
    format: tv_tensors.BoundingBoxFormat,
    canvas_size: tuple[int, int],
    output_size: list[int],
    clamping_mode: CLAMPING_MODE_TYPE = ...,
) -> tuple[torch.Tensor, tuple[int, int]]: ...
@_register_kernel_internal(center_crop, tv_tensors.Mask)
def center_crop_mask(mask: torch.Tensor, output_size: list[int]) -> torch.Tensor: ...
@_register_kernel_internal(center_crop, tv_tensors.Video)
def center_crop_video(video: torch.Tensor, output_size: list[int]) -> torch.Tensor: ...
def resized_crop(
    inpt: torch.Tensor,
    top: int,
    left: int,
    height: int,
    width: int,
    size: list[int],
    interpolation: InterpolationMode | int = ...,
    antialias: bool | None = ...,
) -> torch.Tensor: ...
@_register_kernel_internal(resized_crop, torch.Tensor)
@_register_kernel_internal(resized_crop, tv_tensors.Image)
def resized_crop_image(
    image: torch.Tensor,
    top: int,
    left: int,
    height: int,
    width: int,
    size: list[int],
    interpolation: InterpolationMode | int = ...,
    antialias: bool | None = ...,
) -> torch.Tensor: ...
def resized_crop_keypoints(
    keypoints: torch.Tensor,
    top: int,
    left: int,
    height: int,
    width: int,
    size: list[int],
) -> tuple[torch.Tensor, tuple[int, int]]: ...
def resized_crop_bounding_boxes(
    bounding_boxes: torch.Tensor,
    format: tv_tensors.BoundingBoxFormat,
    top: int,
    left: int,
    height: int,
    width: int,
    size: list[int],
    clamping_mode: CLAMPING_MODE_TYPE = ...,
) -> tuple[torch.Tensor, tuple[int, int]]: ...
def resized_crop_mask(
    mask: torch.Tensor, top: int, left: int, height: int, width: int, size: list[int]
) -> torch.Tensor: ...
@_register_kernel_internal(resized_crop, tv_tensors.Video)
def resized_crop_video(
    video: torch.Tensor,
    top: int,
    left: int,
    height: int,
    width: int,
    size: list[int],
    interpolation: InterpolationMode | int = ...,
    antialias: bool | None = ...,
) -> torch.Tensor: ...
def five_crop(
    inpt: torch.Tensor, size: list[int]
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]: ...
@_register_five_ten_crop_kernel_internal(five_crop, torch.Tensor)
@_register_five_ten_crop_kernel_internal(five_crop, tv_tensors.Image)
def five_crop_image(
    image: torch.Tensor, size: list[int]
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]: ...
@_register_five_ten_crop_kernel_internal(five_crop, tv_tensors.Video)
def five_crop_video(
    video: torch.Tensor, size: list[int]
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]: ...
def ten_crop(
    inpt: torch.Tensor, size: list[int], vertical_flip: bool = ...
) -> tuple[
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
]: ...
@_register_five_ten_crop_kernel_internal(ten_crop, torch.Tensor)
@_register_five_ten_crop_kernel_internal(ten_crop, tv_tensors.Image)
def ten_crop_image(
    image: torch.Tensor, size: list[int], vertical_flip: bool = ...
) -> tuple[
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
]: ...
@_register_five_ten_crop_kernel_internal(ten_crop, tv_tensors.Video)
def ten_crop_video(
    video: torch.Tensor, size: list[int], vertical_flip: bool = ...
) -> tuple[
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
    torch.Tensor,
]: ...
