from torchvision import tv_tensors

import torch

from ._utils import _register_kernel_internal

"""
This type stub file was generated by pyright.
"""

def uniform_temporal_subsample(
    inpt: torch.Tensor, num_samples: int
) -> torch.Tensor: ...
@_register_kernel_internal(uniform_temporal_subsample, torch.Tensor)
@_register_kernel_internal(uniform_temporal_subsample, tv_tensors.Video)
def uniform_temporal_subsample_video(
    video: torch.Tensor, num_samples: int
) -> torch.Tensor: ...
