from torchvision import tv_tensors

import numpy as np
import PIL.Image
import torch

"""
This type stub file was generated by pyright.
"""

@torch.jit.unused
def to_image(
    inpt: torch.Tensor | PIL.Image.Image | np.ndarray,
) -> tv_tensors.Image: ...

to_pil_image = ...
pil_to_tensor = ...
