from collections.abc import Callable, Sequence
from typing import Any

"""
This type stub file was generated by pyright.
"""
type _FillType = int | float | Sequence[int] | Sequence[float] | None
type _FillTypeJIT = list[float] | None

def is_pure_tensor(inpt: Any) -> bool: ...

_KERNEL_REGISTRY: dict[Callable, dict[type, Callable]] = ...
_BUILTIN_DATAPOINT_TYPES = ...

def register_kernel(functional, tv_tensor_cls): ...
