from torchao.csrc_meta_ops import *
from torchao.quantization import autoquant, quantize_

from . import dtypes, optim, quantization, swizzle, testing

__version__ = ...
logger = ...
skip_loading_so_files = ...
force_skip_loading_so_files = ...
if force_skip_loading_so_files:
    skip_loading_so_files = ...
else:
    torchao_pytorch_compatible_versions = ...
    current_torch_version = ...
    current_torchao_version = ...
    skip_loading_so_files = ...
if skip_loading_so_files: ...
else:
    so_files = ...
__all__ = [
    "autoquant",
    "dtypes",
    "ops",
    "optim",
    "quantization",
    "quantize_",
    "swizzle",
    "testing",
]
