import torch

__all__ = [
    "TORCH_VERSION_AFTER_2_2",
    "TORCH_VERSION_AFTER_2_3",
    "TORCH_VERSION_AFTER_2_4",
    "TORCH_VERSION_AFTER_2_5",
    "TORCH_VERSION_AT_LEAST_2_2",
    "TORCH_VERSION_AT_LEAST_2_3",
    "TORCH_VERSION_AT_LEAST_2_4",
    "TORCH_VERSION_AT_LEAST_2_5",
    "TORCH_VERSION_AT_LEAST_2_6",
    "TORCH_VERSION_AT_LEAST_2_7",
    "DummyModule",
    "TorchAOBaseTensor",
    "_register_custom_op",
    "benchmark_model",
    "benchmark_torch_function_in_microseconds",
    "find_multiple",
    "get_available_devices",
    "get_compute_capability",
    "get_model_size_in_bytes",
    "is_MI300",
    "is_package_at_least",
    "is_sm_at_least_89",
    "is_sm_at_least_90",
    "profiler_runner",
    "unwrap_tensor_subclass",
]

def benchmark_model(model, num_runs, args=..., kwargs=..., device_type=...):  # -> None:
    ...
def profiler_runner(path, fn, *args, **kwargs): ...
def get_available_devices():  # -> list[str]:
    ...
def get_compute_capability():  # -> float:
    ...
def compute_max_diff(
    output: torch.Tensor, output_ref: torch.Tensor
) -> torch.Tensor: ...
def benchmark_torch_function_in_microseconds(f, *args, **kwargs):  # -> float:
    ...
def find_multiple(n: int, *args: int) -> int: ...
def get_model_size_in_bytes(model, ignore_embeddings=...):  # -> int:
    ...

class UnwrapTensorSubclass(torch.nn.Module):
    def forward(self, *tensors): ...
    def right_inverse(self, tensor):  # -> list[Any]:
        ...

def unwrap_tensor_subclass(model, filter_fn=...): ...
def parse_version(version_string):  # -> list[int]:
    ...
def is_fbcode():  # -> bool:
    ...
def torch_version_at_least(min_version):  # -> bool:
    ...

class _BoolDeprecationWrapper:
    def __init__(self, bool_value: bool, msg: str) -> None: ...
    def __bool__(self):  # -> bool:
        ...
    def __eq__(self, other) -> bool: ...

TORCH_VERSION_AT_LEAST_2_8 = ...
TORCH_VERSION_AT_LEAST_2_7 = ...
TORCH_VERSION_AT_LEAST_2_6 = ...
TORCH_VERSION_AT_LEAST_2_5 = ...
TORCH_VERSION_AT_LEAST_2_4 = ...
TORCH_VERSION_AT_LEAST_2_3 = ...
TORCH_VERSION_AT_LEAST_2_2 = ...
TORCH_VERSION_AFTER_2_5 = ...
TORCH_VERSION_AFTER_2_4 = ...
TORCH_VERSION_AFTER_2_3 = ...
TORCH_VERSION_AFTER_2_2 = ...

class _ConfigDeprecationWrapper:
    def __init__(self, deprecated_name: str, config_cls: type) -> None: ...
    def __call__(self, *args, **kwargs):  # -> Any:
        ...

class TorchAOBaseTensor(torch.Tensor):
    @classmethod
    def __init_subclass__(cls, **kwargs):  # -> None:
        ...

    implements = ...
    _implements_common_tensor_ops = ...
    __torch_dispatch__ = ...
    __torch_function__ = ...
    register_layout = ...
    get_tensor_impl_constructor = ...
    _get_to_kwargs = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __tensor_flatten__(self):  # -> tuple[Any, dict[Any, Any]]:
        ...
    @classmethod
    def __tensor_unflatten__(
        cls, tensor_data_dict, tensor_attributes, outer_size, outer_stride
    ):  # -> Self:
        ...
    def __repr__(self):  # -> str:
        ...
    def get_layout(self):  # -> None:
        ...

def fill_defaults(args, n, defaults_tail):  # -> list[Any]:
    ...
def is_ROCM():  # -> str | Literal[False] | None:
    ...
def is_MI300():  # -> bool:
    ...
def is_MI350():  # -> bool:
    ...
def is_Navi4():  # -> bool:
    ...
def is_sm_version(major: int, minor: int) -> bool: ...
def is_sm_at_least_89():  # -> bool | Literal[''] | None:
    ...
def is_sm_at_least_90():  # -> bool | Literal[''] | None:
    ...
def is_sm_at_least_100():  # -> bool | Literal[''] | None:
    ...
def check_cpu_version(device, version=...):  # -> bool:
    ...
def check_xpu_version(device, version=...):  # -> bool:
    ...
def ceil_div(a, b): ...
def is_package_at_least(package_name: str, min_version: str):  # -> bool:
    ...

class DummyModule(torch.nn.Module):
    def __init__(
        self, weight: torch.Tensor, bias: torch.Tensor | None = ...
    ) -> None: ...
