from collections.abc import Callable
from typing import Any

from torchvision import (
    transforms as _transforms,
    tv_tensors,
)
from torchvision.transforms.v2 import AutoAugmentPolicy, InterpolationMode, Transform
from torchvision.transforms.v2.functional._utils import _FillType

import PIL.Image
import torch

"""
This type stub file was generated by pyright.
"""
type ImageOrVideo = torch.Tensor | PIL.Image.Image | tv_tensors.Image | tv_tensors.Video

class _AutoAugmentBase(Transform):
    def __init__(
        self,
        *,
        interpolation: InterpolationMode | int = ...,
        fill: _FillType | dict[type | str, _FillType] = ...,
    ) -> None: ...

class AutoAugment(_AutoAugmentBase):
    _v1_transform_cls = _transforms.AutoAugment
    _AUGMENTATION_SPACE = ...
    def __init__(
        self,
        policy: AutoAugmentPolicy = ...,
        interpolation: InterpolationMode | int = ...,
        fill: _FillType | dict[type | str, _FillType] = ...,
    ) -> None: ...
    def forward(self, *inputs: Any) -> Any: ...

class RandAugment(_AutoAugmentBase):
    _v1_transform_cls = _transforms.RandAugment
    _AUGMENTATION_SPACE = ...
    def __init__(
        self,
        num_ops: int = ...,
        magnitude: int = ...,
        num_magnitude_bins: int = ...,
        interpolation: InterpolationMode | int = ...,
        fill: _FillType | dict[type | str, _FillType] = ...,
    ) -> None: ...
    def forward(self, *inputs: Any) -> Any: ...

class TrivialAugmentWide(_AutoAugmentBase):
    _v1_transform_cls = _transforms.TrivialAugmentWide
    _AUGMENTATION_SPACE = ...
    def __init__(
        self,
        num_magnitude_bins: int = ...,
        interpolation: InterpolationMode | int = ...,
        fill: _FillType | dict[type | str, _FillType] = ...,
    ) -> None: ...
    def forward(self, *inputs: Any) -> Any: ...

class AugMix(_AutoAugmentBase):
    _v1_transform_cls = _transforms.AugMix
    _PARTIAL_AUGMENTATION_SPACE = ...
    _AUGMENTATION_SPACE: dict[
        str, tuple[Callable[[int, int, int], torch.Tensor | None], bool]
    ] = ...
    def __init__(
        self,
        severity: int = ...,
        mixture_width: int = ...,
        chain_depth: int = ...,
        alpha: float = ...,
        all_ops: bool = ...,
        interpolation: InterpolationMode | int = ...,
        fill: _FillType | dict[type | str, _FillType] = ...,
    ) -> None: ...
    def forward(self, *inputs: Any) -> Any: ...
