from collections.abc import Sequence
from typing import Any

from torchvision import transforms as _transforms
from torchvision.transforms.v2 import Transform

from ._transform import _RandomApplyTransform

"""
This type stub file was generated by pyright.
"""

class Grayscale(Transform):
    _v1_transform_cls = _transforms.Grayscale
    def __init__(self, num_output_channels: int = ...) -> None: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class RandomGrayscale(_RandomApplyTransform):
    _v1_transform_cls = _transforms.RandomGrayscale
    def __init__(self, p: float = ...) -> None: ...
    def make_params(self, flat_inputs: list[Any]) -> dict[str, Any]: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class RGB(Transform):
    def __init__(self) -> None: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class ColorJitter(Transform):
    _v1_transform_cls = _transforms.ColorJitter
    def __init__(
        self,
        brightness: float | Sequence[float] | None = ...,
        contrast: float | Sequence[float] | None = ...,
        saturation: float | Sequence[float] | None = ...,
        hue: float | Sequence[float] | None = ...,
    ) -> None: ...
    def make_params(self, flat_inputs: list[Any]) -> dict[str, Any]: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class RandomChannelPermutation(Transform):
    def make_params(self, flat_inputs: list[Any]) -> dict[str, Any]: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class RandomPhotometricDistort(Transform):
    def __init__(
        self,
        brightness: tuple[float, float] = ...,
        contrast: tuple[float, float] = ...,
        saturation: tuple[float, float] = ...,
        hue: tuple[float, float] = ...,
        p: float = ...,
    ) -> None: ...
    def make_params(self, flat_inputs: list[Any]) -> dict[str, Any]: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class RandomEqualize(_RandomApplyTransform):
    _v1_transform_cls = _transforms.RandomEqualize
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class RandomInvert(_RandomApplyTransform):
    _v1_transform_cls = _transforms.RandomInvert
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class RandomPosterize(_RandomApplyTransform):
    _v1_transform_cls = _transforms.RandomPosterize
    def __init__(self, bits: int, p: float = ...) -> None: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class RandomSolarize(_RandomApplyTransform):
    _v1_transform_cls = _transforms.RandomSolarize
    def __init__(self, threshold: float, p: float = ...) -> None: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class RandomAutocontrast(_RandomApplyTransform):
    _v1_transform_cls = _transforms.RandomAutocontrast
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class RandomAdjustSharpness(_RandomApplyTransform):
    _v1_transform_cls = _transforms.RandomAdjustSharpness
    def __init__(self, sharpness_factor: float, p: float = ...) -> None: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...
