from typing import Any

from torchvision.transforms.v2 import Transform

import numpy as np
import PIL.Image
import torch

"""
This type stub file was generated by pyright.
"""

class ToTensor(Transform):
    def __init__(self) -> None: ...
    def transform(
        self, inpt: PIL.Image.Image | np.ndarray, params: dict[str, Any]
    ) -> torch.Tensor: ...
