from collections.abc import Sequence
from typing import Any, Literal

import numbers

from torchvision import transforms as _transforms
from torchvision.transforms.v2 import InterpolationMode, Transform
from torchvision.transforms.v2.functional._utils import _FillType

from ._transform import _RandomApplyTransform

"""
This type stub file was generated by pyright.
"""

class RandomHorizontalFlip(_RandomApplyTransform):
    _v1_transform_cls = _transforms.RandomHorizontalFlip
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class RandomVerticalFlip(_RandomApplyTransform):
    _v1_transform_cls = _transforms.RandomVerticalFlip
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class Resize(Transform):
    _v1_transform_cls = _transforms.Resize
    def __init__(
        self,
        size: int | Sequence[int] | None,
        interpolation: InterpolationMode | int = ...,
        max_size: int | None = ...,
        antialias: bool | None = ...,
    ) -> None: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class CenterCrop(Transform):
    _v1_transform_cls = _transforms.CenterCrop
    def __init__(self, size: int | Sequence[int]) -> None: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class RandomResizedCrop(Transform):
    _v1_transform_cls = _transforms.RandomResizedCrop
    def __init__(
        self,
        size: int | Sequence[int],
        scale: tuple[float, float] = ...,
        ratio: tuple[float, float] = ...,
        interpolation: InterpolationMode | int = ...,
        antialias: bool | None = ...,
    ) -> None: ...
    def make_params(self, flat_inputs: list[Any]) -> dict[str, Any]: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class FiveCrop(Transform):
    _v1_transform_cls = _transforms.FiveCrop
    def __init__(self, size: int | Sequence[int]) -> None: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...
    def check_inputs(self, flat_inputs: list[Any]) -> None: ...

class TenCrop(Transform):
    _v1_transform_cls = _transforms.TenCrop
    def __init__(
        self, size: int | Sequence[int], vertical_flip: bool = ...
    ) -> None: ...
    def check_inputs(self, flat_inputs: list[Any]) -> None: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class Pad(Transform):
    _v1_transform_cls = _transforms.Pad
    def __init__(
        self,
        padding: int | Sequence[int],
        fill: _FillType | dict[type | str, _FillType] = ...,
        padding_mode: Literal["constant", "edge", "reflect", "symmetric"] = ...,
    ) -> None: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class RandomZoomOut(_RandomApplyTransform):
    def __init__(
        self,
        fill: _FillType | dict[type | str, _FillType] = ...,
        side_range: Sequence[float] = ...,
        p: float = ...,
    ) -> None: ...
    def make_params(self, flat_inputs: list[Any]) -> dict[str, Any]: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class RandomRotation(Transform):
    _v1_transform_cls = _transforms.RandomRotation
    def __init__(
        self,
        degrees: numbers.Number | Sequence,
        interpolation: InterpolationMode | int = ...,
        expand: bool = ...,
        center: list[float] | None = ...,
        fill: _FillType | dict[type | str, _FillType] = ...,
    ) -> None: ...
    def make_params(self, flat_inputs: list[Any]) -> dict[str, Any]: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class RandomAffine(Transform):
    _v1_transform_cls = _transforms.RandomAffine
    def __init__(
        self,
        degrees: numbers.Number | Sequence,
        translate: Sequence[float] | None = ...,
        scale: Sequence[float] | None = ...,
        shear: float | Sequence[float] | None = ...,
        interpolation: InterpolationMode | int = ...,
        fill: _FillType | dict[type | str, _FillType] = ...,
        center: list[float] | None = ...,
    ) -> None: ...
    def make_params(self, flat_inputs: list[Any]) -> dict[str, Any]: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class RandomCrop(Transform):
    _v1_transform_cls = _transforms.RandomCrop
    def __init__(
        self,
        size: int | Sequence[int],
        padding: int | Sequence[int] | None = ...,
        pad_if_needed: bool = ...,
        fill: _FillType | dict[type | str, _FillType] = ...,
        padding_mode: Literal["constant", "edge", "reflect", "symmetric"] = ...,
    ) -> None: ...
    def make_params(self, flat_inputs: list[Any]) -> dict[str, Any]: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class RandomPerspective(_RandomApplyTransform):
    _v1_transform_cls = _transforms.RandomPerspective
    def __init__(
        self,
        distortion_scale: float = ...,
        p: float = ...,
        interpolation: InterpolationMode | int = ...,
        fill: _FillType | dict[type | str, _FillType] = ...,
    ) -> None: ...
    def make_params(self, flat_inputs: list[Any]) -> dict[str, Any]: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class ElasticTransform(Transform):
    _v1_transform_cls = _transforms.ElasticTransform
    def __init__(
        self,
        alpha: float | Sequence[float] = ...,
        sigma: float | Sequence[float] = ...,
        interpolation: InterpolationMode | int = ...,
        fill: _FillType | dict[type | str, _FillType] = ...,
    ) -> None: ...
    def make_params(self, flat_inputs: list[Any]) -> dict[str, Any]: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class RandomIoUCrop(Transform):
    def __init__(
        self,
        min_scale: float = ...,
        max_scale: float = ...,
        min_aspect_ratio: float = ...,
        max_aspect_ratio: float = ...,
        sampler_options: list[float] | None = ...,
        trials: int = ...,
    ) -> None: ...
    def check_inputs(self, flat_inputs: list[Any]) -> None: ...
    def make_params(self, flat_inputs: list[Any]) -> dict[str, Any]: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class ScaleJitter(Transform):
    def __init__(
        self,
        target_size: tuple[int, int],
        scale_range: tuple[float, float] = ...,
        interpolation: InterpolationMode | int = ...,
        antialias: bool | None = ...,
    ) -> None: ...
    def make_params(self, flat_inputs: list[Any]) -> dict[str, Any]: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class RandomShortestSize(Transform):
    def __init__(
        self,
        min_size: list[int] | tuple[int] | int,
        max_size: int | None = ...,
        interpolation: InterpolationMode | int = ...,
        antialias: bool | None = ...,
    ) -> None: ...
    def make_params(self, flat_inputs: list[Any]) -> dict[str, Any]: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...

class RandomResize(Transform):
    def __init__(
        self,
        min_size: int,
        max_size: int,
        interpolation: InterpolationMode | int = ...,
        antialias: bool | None = ...,
    ) -> None: ...
    def make_params(self, flat_inputs: list[Any]) -> dict[str, Any]: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...
