from typing import Any

from torchvision import tv_tensors
from torchvision.transforms.v2 import Transform
from torchvision.tv_tensors._bounding_boxes import CLAMPING_MODE_TYPE

"""
This type stub file was generated by pyright.
"""

class ConvertBoundingBoxFormat(Transform):
    def __init__(self, format: str | tv_tensors.BoundingBoxFormat) -> None: ...
    def transform(
        self, inpt: tv_tensors.BoundingBoxes, params: dict[str, Any]
    ) -> tv_tensors.BoundingBoxes: ...

class ClampBoundingBoxes(Transform):
    def __init__(self, clamping_mode: CLAMPING_MODE_TYPE | str = ...) -> None: ...
    def transform(
        self, inpt: tv_tensors.BoundingBoxes, params: dict[str, Any]
    ) -> tv_tensors.BoundingBoxes: ...

class ClampKeyPoints(Transform):
    def transform(
        self, inpt: tv_tensors.KeyPoints, params: dict[str, Any]
    ) -> tv_tensors.KeyPoints: ...

class SetClampingMode(Transform):
    def __init__(self, clamping_mode: CLAMPING_MODE_TYPE) -> None: ...
    def transform(
        self, inpt: tv_tensors.BoundingBoxes, params: dict[str, Any]
    ) -> tv_tensors.BoundingBoxes: ...
