from typing import Any

from torchvision.transforms.v2 import Transform

"""
This type stub file was generated by pyright.
"""

class UniformTemporalSubsample(Transform):
    _transformed_types = ...
    def __init__(self, num_samples: int) -> None: ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> Any: ...
