from typing import Any

from torchvision import tv_tensors
from torchvision.transforms.v2 import Transform

import numpy as np
import PIL.Image
import torch

"""
This type stub file was generated by pyright.
"""

class PILToTensor(Transform):
    _transformed_types = ...
    def transform(
        self, inpt: PIL.Image.Image, params: dict[str, Any]
    ) -> torch.Tensor: ...

class ToImage(Transform):
    _transformed_types = ...
    def transform(
        self,
        inpt: torch.Tensor | PIL.Image.Image | np.ndarray,
        params: dict[str, Any],
    ) -> tv_tensors.Image: ...

class ToPILImage(Transform):
    _transformed_types = ...
    def __init__(self, mode: str | None = ...) -> None: ...
    def transform(
        self,
        inpt: torch.Tensor | PIL.Image.Image | np.ndarray,
        params: dict[str, Any],
    ) -> PIL.Image.Image: ...

class ToPureTensor(Transform):
    _transformed_types = ...
    def transform(self, inpt: Any, params: dict[str, Any]) -> torch.Tensor: ...
