from collections.abc import Callable
from typing import Any

from torchvision import tv_tensors

"""
This type stub file was generated by pyright.
"""

def get_bounding_boxes(flat_inputs: list[Any]) -> tv_tensors.BoundingBoxes: ...
def query_chw(flat_inputs: list[Any]) -> tuple[int, int, int]: ...
def query_size(flat_inputs: list[Any]) -> tuple[int, int]: ...
def check_type(
    obj: Any, types_or_checks: tuple[type | Callable[[Any], bool], ...]
) -> bool: ...
def has_any(
    flat_inputs: list[Any], *types_or_checks: type | Callable[[Any], bool]
) -> bool: ...
def has_all(
    flat_inputs: list[Any], *types_or_checks: type | Callable[[Any], bool]
) -> bool: ...
