from torch import nn

import torch

def fft_conv(u, k, dropout_mask, gelu=..., k_rev=...) -> Tensor: ...

class LongConvolution(nn.Module):
    def __init__(self, hidden_size: int, max_len: int, **kwargs) -> None: ...
    def forward(self, x: torch.Tensor, *args, **kwargs) -> Tensor | Any: ...

class PositionalEmbedding(nn.Module):
    def __init__(self, emb_dim: int, seq_len: int, **kwargs) -> None: ...
    def forward(self, L) -> Tensor: ...

class ImplicitLongConvolution(nn.Module):
    def __init__(
        self,
        hidden_size: int,
        max_len: int,
        d_emb: int = ...,
        d_hidden: int = ...,
        **kwargs,
    ) -> None: ...
    def filter(self, seq_len: int, *args, **kwargs) -> Any: ...
    def forward(self, x: torch.Tensor, *args, **kwargs) -> Tensor | Any: ...
