from _typeshed import Incomplete
from absl.testing import parameterized

def projection_simplex_jacobian(projection): ...

class ProjectionsTest(parameterized.TestCase):
    data: Incomplete
    fns: Incomplete
    def setUp(self) -> None: ...
    def test_projection_non_negative(self) -> None: ...
    def test_projection_box(self) -> None: ...
    def test_projection_hypercube(self) -> None: ...
    def test_projection_simplex_array(self, scale) -> None: ...
    def test_projection_simplex_pytree(self, scale) -> None: ...
    def test_projection_simplex_edge_case(self, scale) -> None: ...
    def test_projection_simplex_jacobian(self) -> None: ...
    def test_projection_simplex_vmap(self, scale) -> None: ...
    def test_projection_l1_sphere(self, data_key, scale) -> None: ...
    def test_projection_l2_sphere(self, data_key, scale) -> None: ...
    def test_projection_ball(self, data_key, norm) -> None: ...
    def test_projection_l2_ball_grad_at_zero(self) -> None: ...
    def test_projection_l1_ball_grad_at_zero(self) -> None: ...
    def test_projection_vector(self) -> None: ...
    def test_projection_hyperplane(self) -> None: ...
    def test_projection_halfspace_1(self) -> None: ...
    def test_projection_halfspace_2(self) -> None: ...

def tree_allclose(
    a,
    b,
    rtol: float = 1e-05,
    atol: float = 1e-08,
    equal_nan: bool = False,
): ...
