from typing import Any

import chex

def projection_non_negative(tree: Any) -> Any: ...
def projection_box(tree: Any, lower: Any, upper: Any) -> Any: ...
def projection_hypercube(tree: Any, scale: Any = 1) -> Any: ...
def projection_simplex(tree: Any, scale: chex.Numeric = 1) -> Any: ...
def projection_l1_sphere(tree: Any, scale: chex.Numeric = 1) -> Any: ...
def projection_l1_ball(tree: Any, scale: chex.Numeric = 1) -> Any: ...
def projection_l2_sphere(tree: Any, scale: chex.Numeric = 1) -> Any: ...
def projection_l2_ball(tree: Any, scale: chex.Numeric = 1) -> Any: ...
def projection_linf_ball(tree: Any, scale: chex.Numeric = 1) -> Any: ...
def projection_vector(x: Any, a: Any) -> Any: ...
def projection_hyperplane(x: Any, a: Any, b: chex.Numeric) -> Any: ...
def projection_halfspace(x: Any, a: Any, b: chex.Numeric) -> Any: ...
