from collections.abc import Callable, Sequence
from dataclasses import dataclass
from typing import Any

from torch import nn

import torch

from .._api import WeightsEnum, register_model
from .._utils import handle_legacy_interface

"""
This type stub file was generated by pyright.
"""
__all__ = ["MViT", "MViT_V1_B_Weights", "MViT_V2_S_Weights", "mvit_v1_b", "mvit_v2_s"]

@dataclass
class MSBlockConfig:
    num_heads: int
    input_channels: int
    output_channels: int
    kernel_q: list[int]
    kernel_kv: list[int]
    stride_q: list[int]
    stride_kv: list[int]

class Pool(nn.Module):
    def __init__(
        self,
        pool: nn.Module,
        norm: nn.Module | None,
        activation: nn.Module | None = ...,
        norm_before_pool: bool = ...,
    ) -> None: ...
    def forward(
        self, x: torch.Tensor, thw: tuple[int, int, int]
    ) -> tuple[torch.Tensor, tuple[int, int, int]]: ...

class MultiscaleAttention(nn.Module):
    def __init__(
        self,
        input_size: list[int],
        embed_dim: int,
        output_dim: int,
        num_heads: int,
        kernel_q: list[int],
        kernel_kv: list[int],
        stride_q: list[int],
        stride_kv: list[int],
        residual_pool: bool,
        residual_with_cls_embed: bool,
        rel_pos_embed: bool,
        dropout: float = ...,
        norm_layer: Callable[..., nn.Module] = ...,
    ) -> None: ...
    def forward(
        self, x: torch.Tensor, thw: tuple[int, int, int]
    ) -> tuple[torch.Tensor, tuple[int, int, int]]: ...

class MultiscaleBlock(nn.Module):
    def __init__(
        self,
        input_size: list[int],
        cnf: MSBlockConfig,
        residual_pool: bool,
        residual_with_cls_embed: bool,
        rel_pos_embed: bool,
        proj_after_attn: bool,
        dropout: float = ...,
        stochastic_depth_prob: float = ...,
        norm_layer: Callable[..., nn.Module] = ...,
    ) -> None: ...
    def forward(
        self, x: torch.Tensor, thw: tuple[int, int, int]
    ) -> tuple[torch.Tensor, tuple[int, int, int]]: ...

class PositionalEncoding(nn.Module):
    def __init__(
        self,
        embed_size: int,
        spatial_size: tuple[int, int],
        temporal_size: int,
        rel_pos_embed: bool,
    ) -> None: ...
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...

class MViT(nn.Module):
    def __init__(
        self,
        spatial_size: tuple[int, int],
        temporal_size: int,
        block_setting: Sequence[MSBlockConfig],
        residual_pool: bool,
        residual_with_cls_embed: bool,
        rel_pos_embed: bool,
        proj_after_attn: bool,
        dropout: float = ...,
        attention_dropout: float = ...,
        stochastic_depth_prob: float = ...,
        num_classes: int = ...,
        block: Callable[..., nn.Module] | None = ...,
        norm_layer: Callable[..., nn.Module] | None = ...,
        patch_embed_kernel: tuple[int, int, int] = ...,
        patch_embed_stride: tuple[int, int, int] = ...,
        patch_embed_padding: tuple[int, int, int] = ...,
    ) -> None: ...
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...

class MViT_V1_B_Weights(WeightsEnum):
    KINETICS400_V1 = ...
    DEFAULT = ...

class MViT_V2_S_Weights(WeightsEnum):
    KINETICS400_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(weights=("pretrained", MViT_V1_B_Weights.KINETICS400_V1))
def mvit_v1_b(
    *, weights: MViT_V1_B_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> MViT: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", MViT_V2_S_Weights.KINETICS400_V1))
def mvit_v2_s(
    *, weights: MViT_V2_S_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> MViT: ...
