from collections.abc import Callable, Sequence
from typing import Any

from torch import Tensor, nn

from .._api import WeightsEnum, register_model
from .._utils import handle_legacy_interface

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "MC3_18_Weights",
    "R2Plus1D_18_Weights",
    "R3D_18_Weights",
    "VideoResNet",
    "mc3_18",
    "r2plus1d_18",
    "r3d_18",
]

class Conv3DSimple(nn.Conv3d):
    def __init__(
        self,
        in_planes: int,
        out_planes: int,
        midplanes: int | None = ...,
        stride: int = ...,
        padding: int = ...,
    ) -> None: ...
    @staticmethod
    def get_downsample_stride(stride: int) -> tuple[int, int, int]: ...

class Conv2Plus1D(nn.Sequential):
    def __init__(
        self,
        in_planes: int,
        out_planes: int,
        midplanes: int,
        stride: int = ...,
        padding: int = ...,
    ) -> None: ...
    @staticmethod
    def get_downsample_stride(stride: int) -> tuple[int, int, int]: ...

class Conv3DNoTemporal(nn.Conv3d):
    def __init__(
        self,
        in_planes: int,
        out_planes: int,
        midplanes: int | None = ...,
        stride: int = ...,
        padding: int = ...,
    ) -> None: ...
    @staticmethod
    def get_downsample_stride(stride: int) -> tuple[int, int, int]: ...

class BasicBlock(nn.Module):
    expansion = ...
    def __init__(
        self,
        inplanes: int,
        planes: int,
        conv_builder: Callable[..., nn.Module],
        stride: int = ...,
        downsample: nn.Module | None = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class Bottleneck(nn.Module):
    expansion = ...
    def __init__(
        self,
        inplanes: int,
        planes: int,
        conv_builder: Callable[..., nn.Module],
        stride: int = ...,
        downsample: nn.Module | None = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class BasicStem(nn.Sequential):
    def __init__(self) -> None: ...

class R2Plus1dStem(nn.Sequential):
    def __init__(self) -> None: ...

class VideoResNet(nn.Module):
    def __init__(
        self,
        block: type[BasicBlock | Bottleneck],
        conv_makers: Sequence[type[Conv3DSimple | Conv3DNoTemporal | Conv2Plus1D]],
        layers: list[int],
        stem: Callable[..., nn.Module],
        num_classes: int = ...,
        zero_init_residual: bool = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

_COMMON_META = ...

class R3D_18_Weights(WeightsEnum):
    KINETICS400_V1 = ...
    DEFAULT = ...

class MC3_18_Weights(WeightsEnum):
    KINETICS400_V1 = ...
    DEFAULT = ...

class R2Plus1D_18_Weights(WeightsEnum):
    KINETICS400_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(weights=("pretrained", R3D_18_Weights.KINETICS400_V1))
def r3d_18(
    *, weights: R3D_18_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> VideoResNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", MC3_18_Weights.KINETICS400_V1))
def mc3_18(
    *, weights: MC3_18_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> VideoResNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", R2Plus1D_18_Weights.KINETICS400_V1))
def r2plus1d_18(
    *, weights: R2Plus1D_18_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> VideoResNet: ...

model_urls = ...
