from collections.abc import Callable
from typing import Any

from torch import nn

import torch

from .._api import WeightsEnum, register_model
from .._utils import handle_legacy_interface

"""
This type stub file was generated by pyright.
"""
__all__ = ["S3D", "S3D_Weights", "s3d"]

class TemporalSeparableConv(nn.Sequential):
    def __init__(
        self,
        in_planes: int,
        out_planes: int,
        kernel_size: int,
        stride: int,
        padding: int,
        norm_layer: Callable[..., nn.Module],
    ) -> None: ...

class SepInceptionBlock3D(nn.Module):
    def __init__(
        self,
        in_planes: int,
        b0_out: int,
        b1_mid: int,
        b1_out: int,
        b2_mid: int,
        b2_out: int,
        b3_out: int,
        norm_layer: Callable[..., nn.Module],
    ) -> None: ...
    def forward(self, x): ...

class S3D(nn.Module):
    def __init__(
        self,
        num_classes: int = ...,
        dropout: float = ...,
        norm_layer: Callable[..., torch.nn.Module] | None = ...,
    ) -> None: ...
    def forward(self, x): ...

class S3D_Weights(WeightsEnum):
    KINETICS400_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(weights=("pretrained", S3D_Weights.KINETICS400_V1))
def s3d(
    *, weights: S3D_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> S3D: ...
