from collections.abc import Callable
from typing import Any

from torch import Tensor, nn

import torch

from .._api import WeightsEnum, register_model
from .._utils import handle_legacy_interface

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "Swin3D_B_Weights",
    "Swin3D_S_Weights",
    "Swin3D_T_Weights",
    "SwinTransformer3d",
    "swin3d_b",
    "swin3d_s",
    "swin3d_t",
]

def shifted_window_attention_3d(
    input: Tensor,
    qkv_weight: Tensor,
    proj_weight: Tensor,
    relative_position_bias: Tensor,
    window_size: list[int],
    num_heads: int,
    shift_size: list[int],
    attention_dropout: float = ...,
    dropout: float = ...,
    qkv_bias: Tensor | None = ...,
    proj_bias: Tensor | None = ...,
    training: bool = ...,
) -> Tensor: ...

class ShiftedWindowAttention3d(nn.Module):
    def __init__(
        self,
        dim: int,
        window_size: list[int],
        shift_size: list[int],
        num_heads: int,
        qkv_bias: bool = ...,
        proj_bias: bool = ...,
        attention_dropout: float = ...,
        dropout: float = ...,
    ) -> None: ...
    def define_relative_position_bias_table(self) -> None: ...
    def define_relative_position_index(self) -> None: ...
    def get_relative_position_bias(self, window_size: list[int]) -> torch.Tensor: ...
    def forward(self, x: Tensor) -> Tensor: ...

class PatchEmbed3d(nn.Module):
    def __init__(
        self,
        patch_size: list[int],
        in_channels: int = ...,
        embed_dim: int = ...,
        norm_layer: Callable[..., nn.Module] | None = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class SwinTransformer3d(nn.Module):
    def __init__(
        self,
        patch_size: list[int],
        embed_dim: int,
        depths: list[int],
        num_heads: list[int],
        window_size: list[int],
        mlp_ratio: float = ...,
        dropout: float = ...,
        attention_dropout: float = ...,
        stochastic_depth_prob: float = ...,
        num_classes: int = ...,
        norm_layer: Callable[..., nn.Module] | None = ...,
        block: Callable[..., nn.Module] | None = ...,
        downsample_layer: Callable[..., nn.Module] = ...,
        patch_embed: Callable[..., nn.Module] | None = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

_COMMON_META = ...

class Swin3D_T_Weights(WeightsEnum):
    KINETICS400_V1 = ...
    DEFAULT = ...

class Swin3D_S_Weights(WeightsEnum):
    KINETICS400_V1 = ...
    DEFAULT = ...

class Swin3D_B_Weights(WeightsEnum):
    KINETICS400_V1 = ...
    KINETICS400_IMAGENET22K_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(weights=("pretrained", Swin3D_T_Weights.KINETICS400_V1))
def swin3d_t(
    *, weights: Swin3D_T_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> SwinTransformer3d: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", Swin3D_S_Weights.KINETICS400_V1))
def swin3d_s(
    *, weights: Swin3D_S_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> SwinTransformer3d: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", Swin3D_B_Weights.KINETICS400_V1))
def swin3d_b(
    *, weights: Swin3D_B_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> SwinTransformer3d: ...
