from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

from jax._src import (
    api as api,
    dtypes as dtypes,
    lax as lax,
    random as random,
)
from jax._src.numpy.util import (
    check_arraylike as check_arraylike,
    promote_dtypes_inexact as promote_dtypes_inexact,
)
from jax._src.scipy import (
    linalg as linalg,
    special as special,
)
from jax._src.tree_util import register_pytree_node_class as register_pytree_node_class
from jax._src.typing import Array as Array

type BwMethod = str | Array | Callable[[Any], Array] | None

@dataclass(frozen=True, init=False)
class gaussian_kde:
    neff: Any
    dataset: Any
    weights: Any
    covariance: Any
    inv_cov: Any
    def __init__(self, dataset, bw_method: BwMethod = None, weights=None) -> None: ...
    def tree_flatten(self): ...
    @classmethod
    def tree_unflatten(cls, aux_data, children): ...
    @property
    def d(self): ...
    @property
    def n(self): ...
    def evaluate(self, points): ...
    def __call__(self, points): ...
    def integrate_gaussian(self, mean, cov): ...
    def integrate_box_1d(self, low, high): ...
    def integrate_kde(self, other): ...
    def resample(self, key, shape=()): ...
    def pdf(self, x): ...
    def logpdf(self, x): ...
    def integrate_box(self, low_bounds, high_bounds, maxpts=None) -> None: ...
    def set_bandwidth(self, bw_method=None) -> None: ...
