import torch

class SwizzleTensor(torch.Tensor):
    def __new__(cls, original: torch.Tensor, shallow: bool = ...):  # -> Self:
        ...
    def __init__(self, original, shallow=...) -> None: ...
    def __repr__(self):  # -> str:
        ...
    def unswizzle(self):  # -> Tensor | None:
        ...
    def as_tensor(self):  # -> Tensor | None:
        ...
    def shallow_transpose(self):  # -> SwizzleTensor:
        ...
    @property
    def shape(self):  # -> Size:
        ...
    def stride(self):  # -> tuple[Literal[1], Any] | tuple[Any, Literal[1]]:
        ...
    @classmethod
    def __torch_dispatch__(cls, func, types, args, kwargs=...):  # -> Any:
        ...

    __torch_function__ = ...
