from typing import Any

aten = ...
SWIZZLE_OPS_TABLE: dict[Any, Any] = ...

def implements(aten_ops):  # -> Callable[..., Any]:
    ...
@implements([aten.mm.default, aten.matmul.default])
def swizzle_mm(aten_op, args, kwargs=...):  # -> Tensor:
    ...
@implements([aten.bmm.default])
def swizzle_bmm(aten_op, args, kwargs=...): ...
@implements([aten.addmm.default])
def swizzle_addmm(aten_op, args, kwargs=...): ...
@implements([aten._scaled_mm.default])
def swizzle_scaled_mm(aten_op, args, kwargs=...): ...
@implements([aten.permute.default])
def swizzle_permute(aten_op, args, kwargs=...): ...
@implements([aten.numpy_T.default])
def swizzle_numpy_T(aten_op, args, kwargs=...): ...
