from absl.testing import parameterized

import jax.numpy as jnp

def one_hot_argmax(inputs: jnp.ndarray) -> jnp.ndarray: ...
def argmax_tree(x): ...
def simple_make_perturbed_fun(
    f,
    num_samples: int = 1000,
    sigma: float = 0.1,
    noise=...,
): ...

class MakePertTest(parameterized.TestCase):
    def test_pert_argmax(self, xtype, sigma): ...
    def test_values_on_tree(self): ...
    def test_pert_linear_function(self, sigma): ...
    def test_pert_differentiable(self, sigma, noise): ...
    def test_fun_derivative_not_used(self): ...
    def test_nonflat_shape(self): ...
    def test_hessian(self, sigma, noise): ...
