from torch import Tensor, nn

import torch

class BalancedPositiveNegativeSampler:
    def __init__(self, batch_size_per_image: int, positive_fraction: float) -> None: ...
    def __call__(
        self, matched_idxs: list[Tensor]
    ) -> tuple[list[Tensor], list[Tensor]]: ...

@torch.jit._script_if_tracing
def encode_boxes(
    reference_boxes: Tensor, proposals: Tensor, weights: Tensor
) -> Tensor: ...

class BoxCoder:
    def __init__(
        self, weights: tuple[float, float, float, float], bbox_xform_clip: float = ...
    ) -> None: ...
    def encode(
        self, reference_boxes: list[Tensor], proposals: list[Tensor]
    ) -> list[Tensor]: ...
    def encode_single(self, reference_boxes: Tensor, proposals: Tensor) -> Tensor: ...
    def decode(self, rel_codes: Tensor, boxes: list[Tensor]) -> Tensor: ...
    def decode_single(self, rel_codes: Tensor, boxes: Tensor) -> Tensor: ...

class BoxLinearCoder:
    def __init__(self, normalize_by_size: bool = ...) -> None: ...
    def encode(self, reference_boxes: Tensor, proposals: Tensor) -> Tensor: ...
    def decode(self, rel_codes: Tensor, boxes: Tensor) -> Tensor: ...

class Matcher:
    BELOW_LOW_THRESHOLD = ...
    BETWEEN_THRESHOLDS = ...
    __annotations__ = ...
    def __init__(
        self,
        high_threshold: float,
        low_threshold: float,
        allow_low_quality_matches: bool = ...,
    ) -> None: ...
    def __call__(self, match_quality_matrix: Tensor) -> Tensor: ...
    def set_low_quality_matches_(
        self, matches: Tensor, all_matches: Tensor, match_quality_matrix: Tensor
    ) -> None: ...

class SSDMatcher(Matcher):
    def __init__(self, threshold: float) -> None: ...
    def __call__(self, match_quality_matrix: Tensor) -> Tensor: ...

def overwrite_eps(model: nn.Module, eps: float) -> None: ...
def retrieve_out_channels(model: nn.Module, size: tuple[int, int]) -> list[int]: ...
