from typing import Any
from torch import Tensor, nn

import torch

from .image_list import ImageList

"""
This type stub file was generated by pyright.
"""

class AnchorGenerator(nn.Module):
    __annotations__ = ...
    def __init__(self, sizes=..., aspect_ratios=...) -> None: ...
    def generate_anchors(
        self,
        scales: list[int],
        aspect_ratios: list[float],
        dtype: torch.dtype = ...,
        device: torch.device = ...,
    ) -> Tensor: ...
    def set_cell_anchors(self, dtype: torch.dtype, device: torch.device): ...
    def num_anchors_per_location(self) -> list[int]: ...
    def grid_anchors(
        self, grid_sizes: list[list[int]], strides: list[list[Tensor]]
    ) -> list[Tensor]: ...
    def forward(
        self, image_list: ImageList, feature_maps: list[Tensor]
    ) -> list[Tensor]: ...
    def __call__(self, *args: Any, **kwargs: Any) -> list[Tensor]: ...

class DefaultBoxGenerator(nn.Module):
    def __init__(
        self,
        aspect_ratios: list[list[int]],
        min_ratio: float = ...,
        max_ratio: float = ...,
        scales: list[float] | None = ...,
        steps: list[int] | None = ...,
        clip: bool = ...,
    ) -> None: ...
    def num_anchors_per_location(self) -> list[int]: ...
    def forward(
        self, image_list: ImageList, feature_maps: list[Tensor]
    ) -> list[Tensor]: ...
    def __call__(self, *args: Any, **kwargs: Any) -> list[Tensor]: ...
