from collections.abc import Callable
from typing import Any

from torch import nn

from .generalized_rcnn import GeneralizedRCNN
from .._api import WeightsEnum, register_model
from .._utils import handle_legacy_interface
from ..mobilenetv3 import MobileNet_V3_Large_Weights
from ..resnet import ResNet50_Weights

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "FasterRCNN",
    "FasterRCNN_MobileNet_V3_Large_320_FPN_Weights",
    "FasterRCNN_MobileNet_V3_Large_FPN_Weights",
    "FasterRCNN_ResNet50_FPN_V2_Weights",
    "FasterRCNN_ResNet50_FPN_Weights",
    "fasterrcnn_mobilenet_v3_large_320_fpn",
    "fasterrcnn_mobilenet_v3_large_fpn",
    "fasterrcnn_resnet50_fpn",
    "fasterrcnn_resnet50_fpn_v2",
]

class FasterRCNN(GeneralizedRCNN):
    def __init__(
        self,
        backbone,
        num_classes=...,
        min_size=...,
        max_size=...,
        image_mean=...,
        image_std=...,
        rpn_anchor_generator=...,
        rpn_head=...,
        rpn_pre_nms_top_n_train=...,
        rpn_pre_nms_top_n_test=...,
        rpn_post_nms_top_n_train=...,
        rpn_post_nms_top_n_test=...,
        rpn_nms_thresh=...,
        rpn_fg_iou_thresh=...,
        rpn_bg_iou_thresh=...,
        rpn_batch_size_per_image=...,
        rpn_positive_fraction=...,
        rpn_score_thresh=...,
        box_roi_pool=...,
        box_head=...,
        box_predictor=...,
        box_score_thresh=...,
        box_nms_thresh=...,
        box_detections_per_img=...,
        box_fg_iou_thresh=...,
        box_bg_iou_thresh=...,
        box_batch_size_per_image=...,
        box_positive_fraction=...,
        bbox_reg_weights=...,
        **kwargs,
    ) -> None: ...

class TwoMLPHead(nn.Module):
    def __init__(self, in_channels, representation_size) -> None: ...
    def forward(self, x): ...

class FastRCNNConvFCHead(nn.Sequential):
    def __init__(
        self,
        input_size: tuple[int, int, int],
        conv_layers: list[int],
        fc_layers: list[int],
        norm_layer: Callable[..., nn.Module] | None = ...,
    ) -> None: ...

class FastRCNNPredictor(nn.Module):
    def __init__(self, in_channels, num_classes) -> None: ...
    def forward(self, x): ...

_COMMON_META = ...

class FasterRCNN_ResNet50_FPN_Weights(WeightsEnum):
    COCO_V1 = ...
    DEFAULT = ...

class FasterRCNN_ResNet50_FPN_V2_Weights(WeightsEnum):
    COCO_V1 = ...
    DEFAULT = ...

class FasterRCNN_MobileNet_V3_Large_FPN_Weights(WeightsEnum):
    COCO_V1 = ...
    DEFAULT = ...

class FasterRCNN_MobileNet_V3_Large_320_FPN_Weights(WeightsEnum):
    COCO_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(
    weights=("pretrained", FasterRCNN_ResNet50_FPN_Weights.COCO_V1),
    weights_backbone=("pretrained_backbone", ResNet50_Weights.IMAGENET1K_V1),
)
def fasterrcnn_resnet50_fpn(
    *,
    weights: FasterRCNN_ResNet50_FPN_Weights | None = ...,
    progress: bool = ...,
    num_classes: int | None = ...,
    weights_backbone: ResNet50_Weights | None = ...,
    trainable_backbone_layers: int | None = ...,
    **kwargs: Any,
) -> FasterRCNN: ...
@register_model()
@handle_legacy_interface(
    weights=("pretrained", FasterRCNN_ResNet50_FPN_V2_Weights.COCO_V1),
    weights_backbone=("pretrained_backbone", ResNet50_Weights.IMAGENET1K_V1),
)
def fasterrcnn_resnet50_fpn_v2(
    *,
    weights: FasterRCNN_ResNet50_FPN_V2_Weights | None = ...,
    progress: bool = ...,
    num_classes: int | None = ...,
    weights_backbone: ResNet50_Weights | None = ...,
    trainable_backbone_layers: int | None = ...,
    **kwargs: Any,
) -> FasterRCNN: ...
@register_model()
@handle_legacy_interface(
    weights=("pretrained", FasterRCNN_MobileNet_V3_Large_320_FPN_Weights.COCO_V1),
    weights_backbone=("pretrained_backbone", MobileNet_V3_Large_Weights.IMAGENET1K_V1),
)
def fasterrcnn_mobilenet_v3_large_320_fpn(
    *,
    weights: FasterRCNN_MobileNet_V3_Large_320_FPN_Weights | None = ...,
    progress: bool = ...,
    num_classes: int | None = ...,
    weights_backbone: MobileNet_V3_Large_Weights | None = ...,
    trainable_backbone_layers: int | None = ...,
    **kwargs: Any,
) -> FasterRCNN: ...
@register_model()
@handle_legacy_interface(
    weights=("pretrained", FasterRCNN_MobileNet_V3_Large_FPN_Weights.COCO_V1),
    weights_backbone=("pretrained_backbone", MobileNet_V3_Large_Weights.IMAGENET1K_V1),
)
def fasterrcnn_mobilenet_v3_large_fpn(
    *,
    weights: FasterRCNN_MobileNet_V3_Large_FPN_Weights | None = ...,
    progress: bool = ...,
    num_classes: int | None = ...,
    weights_backbone: MobileNet_V3_Large_Weights | None = ...,
    trainable_backbone_layers: int | None = ...,
    **kwargs: Any,
) -> FasterRCNN: ...
