from collections.abc import Callable
from typing import Any

from torch import Tensor, nn

import torch

from .anchor_utils import AnchorGenerator
from .._api import WeightsEnum, register_model
from .._utils import handle_legacy_interface
from ..resnet import ResNet50_Weights

"""
This type stub file was generated by pyright.
"""
__all__ = ["FCOS", "FCOS_ResNet50_FPN_Weights", "fcos_resnet50_fpn"]

class FCOSHead(nn.Module):
    __annotations__ = ...
    def __init__(
        self,
        in_channels: int,
        num_anchors: int,
        num_classes: int,
        num_convs: int | None = ...,
    ) -> None: ...
    def compute_loss(
        self,
        targets: list[dict[str, Tensor]],
        head_outputs: dict[str, Tensor],
        anchors: list[Tensor],
        matched_idxs: list[Tensor],
    ) -> dict[str, Tensor]: ...
    def forward(self, x: list[Tensor]) -> dict[str, Tensor]: ...

class FCOSClassificationHead(nn.Module):
    def __init__(
        self,
        in_channels: int,
        num_anchors: int,
        num_classes: int,
        num_convs: int = ...,
        prior_probability: float = ...,
        norm_layer: Callable[..., nn.Module] | None = ...,
    ) -> None: ...
    def forward(self, x: list[Tensor]) -> Tensor: ...

class FCOSRegressionHead(nn.Module):
    def __init__(
        self,
        in_channels: int,
        num_anchors: int,
        num_convs: int = ...,
        norm_layer: Callable[..., nn.Module] | None = ...,
    ) -> None: ...
    def forward(self, x: list[Tensor]) -> tuple[Tensor, Tensor]: ...

class FCOS(nn.Module):
    __annotations__ = ...
    def __init__(
        self,
        backbone: nn.Module,
        num_classes: int,
        min_size: int = ...,
        max_size: int = ...,
        image_mean: list[float] | None = ...,
        image_std: list[float] | None = ...,
        anchor_generator: AnchorGenerator | None = ...,
        head: nn.Module | None = ...,
        center_sampling_radius: float = ...,
        score_thresh: float = ...,
        nms_thresh: float = ...,
        detections_per_img: int = ...,
        topk_candidates: int = ...,
        **kwargs,
    ) -> None: ...
    @torch.jit.unused
    def eager_outputs(
        self, losses: dict[str, Tensor], detections: list[dict[str, Tensor]]
    ) -> tuple[dict[str, Tensor], list[dict[str, Tensor]]]: ...
    def compute_loss(
        self,
        targets: list[dict[str, Tensor]],
        head_outputs: dict[str, Tensor],
        anchors: list[Tensor],
        num_anchors_per_level: list[int],
    ) -> dict[str, Tensor]: ...
    def postprocess_detections(
        self,
        head_outputs: dict[str, list[Tensor]],
        anchors: list[list[Tensor]],
        image_shapes: list[tuple[int, int]],
    ) -> list[dict[str, Tensor]]: ...
    def forward(
        self, images: list[Tensor], targets: list[dict[str, Tensor]] | None = ...
    ) -> tuple[dict[str, Tensor], list[dict[str, Tensor]]]: ...

class FCOS_ResNet50_FPN_Weights(WeightsEnum):
    COCO_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(
    weights=("pretrained", FCOS_ResNet50_FPN_Weights.COCO_V1),
    weights_backbone=("pretrained_backbone", ResNet50_Weights.IMAGENET1K_V1),
)
def fcos_resnet50_fpn(
    *,
    weights: FCOS_ResNet50_FPN_Weights | None = ...,
    progress: bool = ...,
    num_classes: int | None = ...,
    weights_backbone: ResNet50_Weights | None = ...,
    trainable_backbone_layers: int | None = ...,
    **kwargs: Any,
) -> FCOS: ...
