from typing import Any

from torch import nn

import torch

"""
This type stub file was generated by pyright.
"""

class GeneralizedRCNN(nn.Module):
    def __init__(
        self,
        backbone: nn.Module,
        rpn: nn.Module,
        roi_heads: nn.Module,
        transform: nn.Module,
    ) -> None: ...
    @torch.jit.unused
    def eager_outputs(
        self, losses: dict[str, torch.Tensor], detections: list[dict[str, torch.Tensor]]
    ) -> dict[str, torch.Tensor] | list[dict[str, torch.Tensor]]: ...
    def forward(
        self,
        images: list[torch.Tensor],
        targets: list[dict[str, torch.Tensor]] | None = ...,
    ) -> tuple[dict[str, torch.Tensor], list[dict[str, torch.Tensor]]]: ...
    def __call__(
        self, *args: Any, **kwargs: Any
    ) -> tuple[dict[str, torch.Tensor], list[dict[str, torch.Tensor]]]: ...
