from torch import Tensor

import torch

"""
This type stub file was generated by pyright.
"""

class ImageList:
    def __init__(self, tensors: Tensor, image_sizes: list[tuple[int, int]]) -> None: ...
    def to(self, device: torch.device) -> ImageList: ...
