from collections.abc import Callable
from typing import Any

from torch import nn

from .faster_rcnn import FasterRCNN
from .._api import WeightsEnum, register_model
from .._utils import handle_legacy_interface
from ..resnet import ResNet50_Weights

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "MaskRCNN",
    "MaskRCNN_ResNet50_FPN_V2_Weights",
    "MaskRCNN_ResNet50_FPN_Weights",
    "maskrcnn_resnet50_fpn",
    "maskrcnn_resnet50_fpn_v2",
]

class MaskRCNN(FasterRCNN):
    def __init__(
        self,
        backbone,
        num_classes=...,
        min_size=...,
        max_size=...,
        image_mean=...,
        image_std=...,
        rpn_anchor_generator=...,
        rpn_head=...,
        rpn_pre_nms_top_n_train=...,
        rpn_pre_nms_top_n_test=...,
        rpn_post_nms_top_n_train=...,
        rpn_post_nms_top_n_test=...,
        rpn_nms_thresh=...,
        rpn_fg_iou_thresh=...,
        rpn_bg_iou_thresh=...,
        rpn_batch_size_per_image=...,
        rpn_positive_fraction=...,
        rpn_score_thresh=...,
        box_roi_pool=...,
        box_head=...,
        box_predictor=...,
        box_score_thresh=...,
        box_nms_thresh=...,
        box_detections_per_img=...,
        box_fg_iou_thresh=...,
        box_bg_iou_thresh=...,
        box_batch_size_per_image=...,
        box_positive_fraction=...,
        bbox_reg_weights=...,
        mask_roi_pool=...,
        mask_head=...,
        mask_predictor=...,
        **kwargs,
    ) -> None: ...

class MaskRCNNHeads(nn.Sequential):
    _version = ...
    def __init__(
        self,
        in_channels,
        layers,
        dilation,
        norm_layer: Callable[..., nn.Module] | None = ...,
    ) -> None: ...

class MaskRCNNPredictor(nn.Sequential):
    def __init__(self, in_channels, dim_reduced, num_classes) -> None: ...

_COMMON_META = ...

class MaskRCNN_ResNet50_FPN_Weights(WeightsEnum):
    COCO_V1 = ...
    DEFAULT = ...

class MaskRCNN_ResNet50_FPN_V2_Weights(WeightsEnum):
    COCO_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(
    weights=("pretrained", MaskRCNN_ResNet50_FPN_Weights.COCO_V1),
    weights_backbone=("pretrained_backbone", ResNet50_Weights.IMAGENET1K_V1),
)
def maskrcnn_resnet50_fpn(
    *,
    weights: MaskRCNN_ResNet50_FPN_Weights | None = ...,
    progress: bool = ...,
    num_classes: int | None = ...,
    weights_backbone: ResNet50_Weights | None = ...,
    trainable_backbone_layers: int | None = ...,
    **kwargs: Any,
) -> MaskRCNN: ...
@register_model()
@handle_legacy_interface(
    weights=("pretrained", MaskRCNN_ResNet50_FPN_V2_Weights.COCO_V1),
    weights_backbone=("pretrained_backbone", ResNet50_Weights.IMAGENET1K_V1),
)
def maskrcnn_resnet50_fpn_v2(
    *,
    weights: MaskRCNN_ResNet50_FPN_V2_Weights | None = ...,
    progress: bool = ...,
    num_classes: int | None = ...,
    weights_backbone: ResNet50_Weights | None = ...,
    trainable_backbone_layers: int | None = ...,
    **kwargs: Any,
) -> MaskRCNN: ...
