from collections.abc import Callable
from typing import Any

from torch import Tensor, nn

import torch

from .._api import WeightsEnum, register_model
from .._utils import handle_legacy_interface
from ..resnet import ResNet50_Weights

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "RetinaNet",
    "RetinaNet_ResNet50_FPN_V2_Weights",
    "RetinaNet_ResNet50_FPN_Weights",
    "retinanet_resnet50_fpn",
    "retinanet_resnet50_fpn_v2",
]

class RetinaNetHead(nn.Module):
    def __init__(
        self,
        in_channels,
        num_anchors,
        num_classes,
        norm_layer: Callable[..., nn.Module] | None = ...,
    ) -> None: ...
    def compute_loss(
        self,
        targets: list[dict[str, Tensor]],
        head_outputs: dict[str, Tensor],
        anchors: list[Tensor],
        matched_idxs: list[Tensor],
    ) -> dict[str, Tensor]: ...
    def forward(self, x: list[Tensor]) -> dict[str, Tensor]: ...

class RetinaNetClassificationHead(nn.Module):
    _version = ...
    def __init__(
        self,
        in_channels,
        num_anchors,
        num_classes,
        prior_probability=...,
        norm_layer: Callable[..., nn.Module] | None = ...,
    ) -> None: ...
    def compute_loss(
        self,
        targets: list[dict[str, Tensor]],
        head_outputs: dict[str, Tensor],
        matched_idxs: list[Tensor],
    ) -> Tensor: ...
    def forward(self, x: list[Tensor]) -> Tensor: ...

class RetinaNetRegressionHead(nn.Module):
    _version = ...
    __annotations__ = ...
    def __init__(
        self,
        in_channels,
        num_anchors,
        norm_layer: Callable[..., nn.Module] | None = ...,
    ) -> None: ...
    def compute_loss(
        self,
        targets: list[dict[str, Tensor]],
        head_outputs: dict[str, Tensor],
        anchors: list[Tensor],
        matched_idxs: list[Tensor],
    ) -> Tensor: ...
    def forward(self, x: list[Tensor]) -> Tensor: ...

class RetinaNet(nn.Module):
    __annotations__ = ...
    def __init__(
        self,
        backbone,
        num_classes,
        min_size=...,
        max_size=...,
        image_mean=...,
        image_std=...,
        anchor_generator=...,
        head=...,
        proposal_matcher=...,
        score_thresh=...,
        nms_thresh=...,
        detections_per_img=...,
        fg_iou_thresh=...,
        bg_iou_thresh=...,
        topk_candidates=...,
        **kwargs,
    ) -> None: ...
    @torch.jit.unused
    def eager_outputs(
        self, losses: dict[str, Tensor], detections: list[dict[str, Tensor]]
    ) -> tuple[dict[str, Tensor], list[dict[str, Tensor]]]: ...
    def compute_loss(
        self,
        targets: list[dict[str, Tensor]],
        head_outputs: dict[str, Tensor],
        anchors: list[Tensor],
    ) -> dict[str, Tensor]: ...
    def postprocess_detections(
        self,
        head_outputs: dict[str, list[Tensor]],
        anchors: list[list[Tensor]],
        image_shapes: list[tuple[int, int]],
    ) -> list[dict[str, Tensor]]: ...
    def forward(
        self, images: list[Tensor], targets: list[dict[str, Tensor]] | None = ...
    ) -> tuple[dict[str, Tensor], list[dict[str, Tensor]]]: ...

_COMMON_META = ...

class RetinaNet_ResNet50_FPN_Weights(WeightsEnum):
    COCO_V1 = ...
    DEFAULT = ...

class RetinaNet_ResNet50_FPN_V2_Weights(WeightsEnum):
    COCO_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(
    weights=("pretrained", RetinaNet_ResNet50_FPN_Weights.COCO_V1),
    weights_backbone=("pretrained_backbone", ResNet50_Weights.IMAGENET1K_V1),
)
def retinanet_resnet50_fpn(
    *,
    weights: RetinaNet_ResNet50_FPN_Weights | None = ...,
    progress: bool = ...,
    num_classes: int | None = ...,
    weights_backbone: ResNet50_Weights | None = ...,
    trainable_backbone_layers: int | None = ...,
    **kwargs: Any,
) -> RetinaNet: ...
@register_model()
@handle_legacy_interface(
    weights=("pretrained", RetinaNet_ResNet50_FPN_V2_Weights.COCO_V1),
    weights_backbone=("pretrained_backbone", ResNet50_Weights.IMAGENET1K_V1),
)
def retinanet_resnet50_fpn_v2(
    *,
    weights: RetinaNet_ResNet50_FPN_V2_Weights | None = ...,
    progress: bool = ...,
    num_classes: int | None = ...,
    weights_backbone: ResNet50_Weights | None = ...,
    trainable_backbone_layers: int | None = ...,
    **kwargs: Any,
) -> RetinaNet: ...
