from typing import Any

from torch import Tensor, nn

import torch

from .anchor_utils import DefaultBoxGenerator
from .._api import WeightsEnum, register_model
from .._utils import handle_legacy_interface
from ..vgg import VGG16_Weights

"""
This type stub file was generated by pyright.
"""
__all__ = ["SSD300_VGG16_Weights", "ssd300_vgg16"]

class SSD300_VGG16_Weights(WeightsEnum):
    COCO_V1 = ...
    DEFAULT = ...

class SSDHead(nn.Module):
    def __init__(
        self, in_channels: list[int], num_anchors: list[int], num_classes: int
    ) -> None: ...
    def forward(self, x: list[Tensor]) -> dict[str, Tensor]: ...

class SSDScoringHead(nn.Module):
    def __init__(self, module_list: nn.ModuleList, num_columns: int) -> None: ...
    def forward(self, x: list[Tensor]) -> Tensor: ...

class SSDClassificationHead(SSDScoringHead):
    def __init__(
        self, in_channels: list[int], num_anchors: list[int], num_classes: int
    ) -> None: ...

class SSDRegressionHead(SSDScoringHead):
    def __init__(self, in_channels: list[int], num_anchors: list[int]) -> None: ...

class SSD(nn.Module):
    __annotations__ = ...
    def __init__(
        self,
        backbone: nn.Module,
        anchor_generator: DefaultBoxGenerator,
        size: tuple[int, int],
        num_classes: int,
        image_mean: list[float] | None = ...,
        image_std: list[float] | None = ...,
        head: nn.Module | None = ...,
        score_thresh: float = ...,
        nms_thresh: float = ...,
        detections_per_img: int = ...,
        iou_thresh: float = ...,
        topk_candidates: int = ...,
        positive_fraction: float = ...,
        **kwargs: Any,
    ) -> None: ...
    @torch.jit.unused
    def eager_outputs(
        self, losses: dict[str, Tensor], detections: list[dict[str, Tensor]]
    ) -> tuple[dict[str, Tensor], list[dict[str, Tensor]]]: ...
    def compute_loss(
        self,
        targets: list[dict[str, Tensor]],
        head_outputs: dict[str, Tensor],
        anchors: list[Tensor],
        matched_idxs: list[Tensor],
    ) -> dict[str, Tensor]: ...
    def forward(
        self, images: list[Tensor], targets: list[dict[str, Tensor]] | None = ...
    ) -> tuple[dict[str, Tensor], list[dict[str, Tensor]]]: ...
    def postprocess_detections(
        self,
        head_outputs: dict[str, Tensor],
        image_anchors: list[Tensor],
        image_shapes: list[tuple[int, int]],
    ) -> list[dict[str, Tensor]]: ...

class SSDFeatureExtractorVGG(nn.Module):
    def __init__(self, backbone: nn.Module, highres: bool) -> None: ...
    def forward(self, x: Tensor) -> dict[str, Tensor]: ...

@register_model()
@handle_legacy_interface(
    weights=("pretrained", SSD300_VGG16_Weights.COCO_V1),
    weights_backbone=("pretrained_backbone", VGG16_Weights.IMAGENET1K_FEATURES),
)
def ssd300_vgg16(
    *,
    weights: SSD300_VGG16_Weights | None = ...,
    progress: bool = ...,
    num_classes: int | None = ...,
    weights_backbone: VGG16_Weights | None = ...,
    trainable_backbone_layers: int | None = ...,
    **kwargs: Any,
) -> SSD: ...
