from collections.abc import Callable
from typing import Any

from torch import Tensor, nn

from .ssd import SSD, SSDScoringHead
from .._api import WeightsEnum, register_model
from .._utils import handle_legacy_interface
from ..mobilenetv3 import MobileNet_V3_Large_Weights

"""
This type stub file was generated by pyright.
"""
__all__ = ["SSDLite320_MobileNet_V3_Large_Weights", "ssdlite320_mobilenet_v3_large"]

class SSDLiteHead(nn.Module):
    def __init__(
        self,
        in_channels: list[int],
        num_anchors: list[int],
        num_classes: int,
        norm_layer: Callable[..., nn.Module],
    ) -> None: ...
    def forward(self, x: list[Tensor]) -> dict[str, Tensor]: ...
    def __call__(self, *args: Any, **kwargs: Any) -> dict[str, Tensor]: ...

class SSDLiteClassificationHead(SSDScoringHead):
    def __init__(
        self,
        in_channels: list[int],
        num_anchors: list[int],
        num_classes: int,
        norm_layer: Callable[..., nn.Module],
    ) -> None: ...

class SSDLiteRegressionHead(SSDScoringHead):
    def __init__(
        self,
        in_channels: list[int],
        num_anchors: list[int],
        norm_layer: Callable[..., nn.Module],
    ) -> None: ...

class SSDLiteFeatureExtractorMobileNet(nn.Module):
    def __init__(
        self,
        backbone: nn.Module,
        c4_pos: int,
        norm_layer: Callable[..., nn.Module],
        width_mult: float = ...,
        min_depth: int = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> dict[str, Tensor]: ...
    def __call__(self, *args: Any, **kwargs: Any) -> dict[str, Tensor]: ...

class SSDLite320_MobileNet_V3_Large_Weights(WeightsEnum):
    COCO_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(
    weights=("pretrained", SSDLite320_MobileNet_V3_Large_Weights.COCO_V1),
    weights_backbone=("pretrained_backbone", MobileNet_V3_Large_Weights.IMAGENET1K_V1),
)
def ssdlite320_mobilenet_v3_large(
    *,
    weights: SSDLite320_MobileNet_V3_Large_Weights | None = ...,
    progress: bool = ...,
    num_classes: int | None = ...,
    weights_backbone: MobileNet_V3_Large_Weights | None = ...,
    trainable_backbone_layers: int | None = ...,
    norm_layer: Callable[..., nn.Module] | None = ...,
    **kwargs: Any,
) -> SSD: ...
