from typing import Any

from torch import Tensor, nn

from .image_list import ImageList

class GeneralizedRCNNTransform(nn.Module):
    def __init__(
        self,
        min_size: int,
        max_size: int,
        image_mean: list[float],
        image_std: list[float],
        size_divisible: int = ...,
        fixed_size: tuple[int, int] | None = ...,
        **kwargs: Any,
    ) -> None: ...
    def forward(
        self, images: list[Tensor], targets: list[dict[str, Tensor]] | None = ...
    ) -> tuple[ImageList, list[dict[str, Tensor]] | None]: ...
    def normalize(self, image: Tensor) -> Tensor: ...
    def torch_choice(self, k: list[int]) -> int: ...
    def resize(
        self, image: Tensor, target: dict[str, Tensor] | None = ...
    ) -> tuple[Tensor, dict[str, Tensor] | None]: ...
    def max_by_axis(self, the_list: list[list[int]]) -> list[int]: ...
    def batch_images(
        self, images: list[Tensor], size_divisible: int = ...
    ) -> Tensor: ...
    def postprocess(
        self,
        result: list[dict[str, Tensor]],
        image_shapes: list[tuple[int, int]],
        original_image_sizes: list[tuple[int, int]],
    ) -> list[dict[str, Tensor]]: ...

def resize_keypoints(
    keypoints: Tensor, original_size: list[int], new_size: list[int]
) -> Tensor: ...
def resize_boxes(
    boxes: Tensor, original_size: list[int], new_size: list[int]
) -> Tensor: ...
