from optax._src import (
    alias as alias,
    numerics as numerics,
    update as update,
)

import chex

class ScheduleFreeTest(chex.TestCase):
    def test_learning_rate_zero(self): ...
    def test_schedule_free_adamw(self): ...
    def test_scalar_preservance(self) -> None: ...
    def test_buffer_donation(self): ...
    def test_explicit_dtype(self, params_dtype, state_dtype) -> None: ...
