Normalizer = ...
BertNormalizer = ...
NFD = ...
NFKD = ...
NFC = ...
NFKC = ...
Sequence = ...
Lowercase = ...
Prepend = ...
Strip = ...
StripAccents = ...
Nmt = ...
Precompiled = ...
Replace = ...
ByteLevel = ...
NORMALIZERS = ...

def unicode_normalizer_from_str(normalizer: str) -> Normalizer: ...
