from torch import Tensor

def create_dynamic_map(
    signed=..., max_exponent_bits=..., total_bits=...
):  # -> list[Any]:
    ...
def scale_tensor(input: Tensor, block_size: int):  # -> tuple[Tensor, Tensor]:
    ...
def quantize_8bit_with_qmap(input: Tensor, qmap: Tensor):  # -> Tensor:
    ...
def quantize_4bit_with_qmap(input: Tensor, qmap: Tensor):  # -> Tensor:
    ...
def dequant_with_qmap(codes: Tensor, qmap: Tensor, scale: Tensor):  # -> Tensor:
    ...
