from functools import lru_cache

from torch import Tensor
from torchao.utils import TorchAOBaseTensor

aten = ...
c10d_functional = ...
_c10d_functional = ...

@lru_cache(maxsize=1)
def get_qmap_signed():  # -> list[Any]:
    ...
@lru_cache(maxsize=1)
def get_qmap_unsigned():  # -> list[Any]:
    ...

class OptimState8bit(TorchAOBaseTensor):
    tensor_attrs = ...
    @staticmethod
    def __new__(cls, codes: Tensor, scale: Tensor, qmap: Tensor, signed: bool): ...
    def __init__(
        self, codes: Tensor, scale: Tensor, qmap: Tensor, signed: bool
    ) -> None: ...
    def __tensor_flatten__(self):  # -> tuple[list[str], list[bool]]:
        ...
    @classmethod
    def __tensor_unflatten__(
        cls, tensor_data_dict, tensor_attributes, outer_size=..., outer_stride=...
    ):  # -> Self:
        ...
    def dequantize(self, output_dtype=...):  # -> Tensor:
        ...
    @classmethod
    def zeros(
        cls, shape, signed: bool = ..., block_size: int = ..., device=...
    ):  # -> Self:
        ...
    def __repr__(self):  # -> str:
        ...

@OptimState8bit.implements(aten.copy_.default)
def _(func, types, args, kwargs):  # -> OptimState8bit:
    ...
@OptimState8bit.implements(aten._to_copy.default)
def _(func, types, args, kwargs):  # -> tuple[Any, ...] | Any:
    ...
@OptimState8bit.implements(aten.lerp.Scalar)
def _(func, types, args, kwargs): ...
@OptimState8bit.implements(aten.view.default)
def _(func, types, args, kwargs):  # -> OptimState8bit:
    ...
@OptimState8bit.implements(
    [
        c10d_functional.all_gather_into_tensor.default,
        _c10d_functional.all_gather_into_tensor.default,
        c10d_functional.wait_tensor.default,
        _c10d_functional.wait_tensor.default,
        aten.detach.default,
    ]
)
def _(func, types, args, kwargs):  # -> OptimState8bit:
    ...
@OptimState8bit.implements(aten.is_pinned.default)
def _(func, types, args, kwargs): ...
@OptimState8bit.implements(aten.slice.Tensor)
def _(func, types, args, kwargs):  # -> OptimState8bit:
    ...
