from torch import Tensor
from torchao.utils import TorchAOBaseTensor

aten = ...
c10d_functional = ...
_c10d_functional = ...
DTYPE = ...

def quantize_fp8(input: Tensor, block_size: int):  # -> tuple[Tensor, Tensor]:
    ...

class OptimStateFp8(TorchAOBaseTensor):
    tensor_attrs = ...
    @staticmethod
    def __new__(cls, codes: Tensor, scale: Tensor): ...
    def __init__(self, codes: Tensor, scale: Tensor) -> None: ...
    def __tensor_flatten__(self):  # -> tuple[list[str], list[Any]]:
        ...
    @classmethod
    def __tensor_unflatten__(
        cls, tensor_data_dict, tensor_attributes, outer_size=..., outer_stride=...
    ):  # -> Self:
        ...
    def dequantize(self, output_dtype=...):  # -> Tensor:
        ...
    @classmethod
    def zeros(cls, shape, block_size: int = ..., device=...):  # -> Self:
        ...
    def __repr__(self):  # -> str:
        ...

@OptimStateFp8.implements(aten.copy_.default)
def _(func, types, args, kwargs):  # -> OptimStateFp8:
    ...
@OptimStateFp8.implements(aten._to_copy.default)
def _(func, types, args, kwargs):  # -> tuple[Any, ...] | Any:
    ...
@OptimStateFp8.implements(aten.lerp.Scalar)
def _(func, types, args, kwargs): ...
@OptimStateFp8.implements(aten.view.default)
def _(func, types, args, kwargs):  # -> OptimStateFp8:
    ...
@OptimStateFp8.implements(
    [
        c10d_functional.all_gather_into_tensor.default,
        _c10d_functional.all_gather_into_tensor.default,
        c10d_functional.wait_tensor.default,
        _c10d_functional.wait_tensor.default,
        aten.detach.default,
    ]
)
def _(func, types, args, kwargs):  # -> OptimStateFp8:
    ...
@OptimStateFp8.implements(aten.is_pinned.default)
def _(func, types, args, kwargs): ...
@OptimStateFp8.implements(aten.slice.Tensor)
def _(func, types, args, kwargs):  # -> OptimStateFp8:
    ...
