from collections.abc import Iterable, Iterator, Mapping
from pathlib import Path
from typing import Any

type _NodeView[N] = _Nodes[N]

class _Nodes[N]:
    def __iter__(self) -> Iterator[N]: ...
    def __getitem__(self, node: N) -> dict[str, Any]: ...

class DiGraph[N]:
    def __init__(self) -> None: ...
    @property
    def nodes(self) -> _Nodes[N]: ...
    def add_node(self, node: N, **attr: Any) -> None: ...
    def add_edge(self, u: N, v: N, **attr: Any) -> None: ...
    def add_edges_from(self, edges: Iterable[tuple[N, N]]) -> None: ...
    def number_of_nodes(self) -> int: ...
    def in_degree(self, node: N) -> int: ...
    def reverse(self, copy: bool = ...) -> DiGraph[N]: ...

def pagerank[N](graph: DiGraph[N], alpha: float = ...) -> Mapping[N, float]: ...
def write_graphml(graph: DiGraph[Any], path: str | Path) -> None: ...
def read_graphml(path: str | Path) -> DiGraph[str]: ...
