from _typeshed import Incomplete
from jax.experimental import jax2tf as jax2tf

def jax_to_ir(fn, input_shapes, *, constants=None, format): ...
def tf_wrap_with_input_names(f, input_shapes): ...

jax_to_hlo: Incomplete
jax_to_tf: Incomplete

def main(argv) -> None: ...
def parse_shape_str(s): ...
def set_up_flags() -> None: ...
