from collections.abc import Callable, Iterable, Mapping
from dataclasses import dataclass
from enum import Enum
from types import ModuleType
from typing import Any, TypeVar

from torch import nn

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "Weights",
    "WeightsEnum",
    "get_model",
    "get_model_builder",
    "get_model_weights",
    "get_weight",
    "list_models",
]

@dataclass
class Weights:
    url: str
    transforms: Callable
    meta: dict[str, Any]
    def __eq__(self, other: object) -> bool: ...

class WeightsEnum(Enum):
    @classmethod
    def verify(cls, obj: Any) -> Any: ...
    def get_state_dict(self, *args: Any, **kwargs: Any) -> Mapping[str, Any]: ...
    @property
    def url(self): ...
    @property
    def transforms(self): ...
    @property
    def meta(self): ...

def get_weight(name: str) -> WeightsEnum: ...
def get_model_weights(name: Callable | str) -> type[WeightsEnum]: ...

M = TypeVar("M", bound=nn.Module)
BUILTIN_MODELS = ...

def register_model(
    name: str | None = ...,
) -> Callable[[Callable[..., M]], Callable[..., M]]: ...
def list_models(
    module: ModuleType | None = ...,
    include: Iterable[str] | str | None = ...,
    exclude: Iterable[str] | str | None = ...,
) -> list[str]: ...
def get_model_builder(name: str) -> Callable[..., nn.Module]: ...
def get_model(name: str, **config: Any) -> nn.Module: ...
