from collections.abc import Callable
from typing import Any, TypeVar

from torch import nn

from ._api import WeightsEnum

"""
This type stub file was generated by pyright.
"""

class IntermediateLayerGetter(nn.ModuleDict):
    __annotations__ = ...
    def __init__(self, model: nn.Module, return_layers: dict[str, str]) -> None: ...
    def forward(self, x): ...

D = TypeVar("D")

def kwonly_to_pos_or_kw(fn: Callable[..., D]) -> Callable[..., D]: ...

W = TypeVar("W", bound=WeightsEnum)
M = TypeVar("M", bound=nn.Module)
V = TypeVar("V")

def handle_legacy_interface(
    **weights: tuple[str, W | None | Callable[[dict[str, Any]], W | None]],
): ...

class _ModelURLs(dict):
    def __getitem__(self, item): ...
