from typing import Any

from torch import nn

import torch

from ._api import WeightsEnum, register_model
from ._utils import handle_legacy_interface

"""
This type stub file was generated by pyright.
"""
__all__ = ["AlexNet", "AlexNet_Weights", "alexnet"]

class AlexNet(nn.Module):
    def __init__(self, num_classes: int = ..., dropout: float = ...) -> None: ...
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class AlexNet_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(weights=("pretrained", AlexNet_Weights.IMAGENET1K_V1))
def alexnet(
    *, weights: AlexNet_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> AlexNet: ...
