from collections.abc import Callable
from typing import Any

from torch import Tensor, nn

from ._api import WeightsEnum, register_model
from ._utils import handle_legacy_interface

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "ConvNeXt",
    "ConvNeXt_Base_Weights",
    "ConvNeXt_Large_Weights",
    "ConvNeXt_Small_Weights",
    "ConvNeXt_Tiny_Weights",
    "convnext_base",
    "convnext_large",
    "convnext_small",
    "convnext_tiny",
]

class LayerNorm2d(nn.LayerNorm):
    def forward(self, x: Tensor) -> Tensor: ...

class CNBlock(nn.Module):
    def __init__(
        self,
        dim,
        layer_scale: float,
        stochastic_depth_prob: float,
        norm_layer: Callable[..., nn.Module] | None = ...,
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class CNBlockConfig:
    def __init__(
        self, input_channels: int, out_channels: int | None, num_layers: int
    ) -> None: ...

class ConvNeXt(nn.Module):
    def __init__(
        self,
        block_setting: list[CNBlockConfig],
        stochastic_depth_prob: float = ...,
        layer_scale: float = ...,
        num_classes: int = ...,
        block: Callable[..., nn.Module] | None = ...,
        norm_layer: Callable[..., nn.Module] | None = ...,
        **kwargs: Any,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

_COMMON_META = ...

class ConvNeXt_Tiny_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class ConvNeXt_Small_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class ConvNeXt_Base_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class ConvNeXt_Large_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(weights=("pretrained", ConvNeXt_Tiny_Weights.IMAGENET1K_V1))
def convnext_tiny(
    *,
    weights: ConvNeXt_Tiny_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> ConvNeXt: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", ConvNeXt_Small_Weights.IMAGENET1K_V1))
def convnext_small(
    *,
    weights: ConvNeXt_Small_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> ConvNeXt: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", ConvNeXt_Base_Weights.IMAGENET1K_V1))
def convnext_base(
    *,
    weights: ConvNeXt_Base_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> ConvNeXt: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", ConvNeXt_Large_Weights.IMAGENET1K_V1))
def convnext_large(
    *,
    weights: ConvNeXt_Large_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> ConvNeXt: ...
