from typing import Any

from torch import Tensor, nn

import torch

from ._api import WeightsEnum, register_model
from ._utils import handle_legacy_interface

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "DenseNet",
    "DenseNet121_Weights",
    "DenseNet161_Weights",
    "DenseNet169_Weights",
    "DenseNet201_Weights",
    "densenet121",
    "densenet161",
    "densenet169",
    "densenet201",
]

class _DenseLayer(nn.Module):
    def __init__(
        self,
        num_input_features: int,
        growth_rate: int,
        bn_size: int,
        drop_rate: float,
        memory_efficient: bool = ...,
    ) -> None: ...
    def bn_function(self, inputs: list[Tensor]) -> Tensor: ...
    def any_requires_grad(self, input: list[Tensor]) -> bool: ...
    @torch.jit.unused
    def call_checkpoint_bottleneck(self, input: list[Tensor]) -> Tensor: ...
    @torch.jit._overload_method
    def forward(self, input: list[Tensor]) -> Tensor: ...
    @torch.jit._overload_method
    def forward(self, input: Tensor) -> Tensor: ...
    def forward(self, input: Tensor) -> Tensor: ...

class _DenseBlock(nn.ModuleDict):
    _version = ...
    def __init__(
        self,
        num_layers: int,
        num_input_features: int,
        bn_size: int,
        growth_rate: int,
        drop_rate: float,
        memory_efficient: bool = ...,
    ) -> None: ...
    def forward(self, init_features: Tensor) -> Tensor: ...

class _Transition(nn.Sequential):
    def __init__(self, num_input_features: int, num_output_features: int) -> None: ...

class DenseNet(nn.Module):
    def __init__(
        self,
        growth_rate: int = ...,
        block_config: tuple[int, int, int, int] = ...,
        num_init_features: int = ...,
        bn_size: int = ...,
        drop_rate: float = ...,
        num_classes: int = ...,
        memory_efficient: bool = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

_COMMON_META = ...

class DenseNet121_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class DenseNet161_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class DenseNet169_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class DenseNet201_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(weights=("pretrained", DenseNet121_Weights.IMAGENET1K_V1))
def densenet121(
    *, weights: DenseNet121_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> DenseNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", DenseNet161_Weights.IMAGENET1K_V1))
def densenet161(
    *, weights: DenseNet161_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> DenseNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", DenseNet169_Weights.IMAGENET1K_V1))
def densenet169(
    *, weights: DenseNet169_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> DenseNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", DenseNet201_Weights.IMAGENET1K_V1))
def densenet201(
    *, weights: DenseNet201_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> DenseNet: ...
