from collections.abc import Callable, Sequence
from dataclasses import dataclass
from typing import Any

from torch import Tensor, nn

from ._api import WeightsEnum, register_model
from ._utils import handle_legacy_interface

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "EfficientNet",
    "EfficientNet_B0_Weights",
    "EfficientNet_B1_Weights",
    "EfficientNet_B2_Weights",
    "EfficientNet_B3_Weights",
    "EfficientNet_B4_Weights",
    "EfficientNet_B5_Weights",
    "EfficientNet_B6_Weights",
    "EfficientNet_B7_Weights",
    "EfficientNet_V2_L_Weights",
    "EfficientNet_V2_M_Weights",
    "EfficientNet_V2_S_Weights",
    "efficientnet_b0",
    "efficientnet_b1",
    "efficientnet_b2",
    "efficientnet_b3",
    "efficientnet_b4",
    "efficientnet_b5",
    "efficientnet_b6",
    "efficientnet_b7",
    "efficientnet_v2_l",
    "efficientnet_v2_m",
    "efficientnet_v2_s",
]

@dataclass
class _MBConvConfig:
    expand_ratio: float
    kernel: int
    stride: int
    input_channels: int
    out_channels: int
    num_layers: int
    block: Callable[..., nn.Module]
    @staticmethod
    def adjust_channels(
        channels: int, width_mult: float, min_value: int | None = ...
    ) -> int: ...

class MBConvConfig(_MBConvConfig):
    def __init__(
        self,
        expand_ratio: float,
        kernel: int,
        stride: int,
        input_channels: int,
        out_channels: int,
        num_layers: int,
        width_mult: float = ...,
        depth_mult: float = ...,
        block: Callable[..., nn.Module] | None = ...,
    ) -> None: ...
    @staticmethod
    def adjust_depth(num_layers: int, depth_mult: float): ...

class FusedMBConvConfig(_MBConvConfig):
    def __init__(
        self,
        expand_ratio: float,
        kernel: int,
        stride: int,
        input_channels: int,
        out_channels: int,
        num_layers: int,
        block: Callable[..., nn.Module] | None = ...,
    ) -> None: ...

class MBConv(nn.Module):
    def __init__(
        self,
        cnf: MBConvConfig,
        stochastic_depth_prob: float,
        norm_layer: Callable[..., nn.Module],
        se_layer: Callable[..., nn.Module] = ...,
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class FusedMBConv(nn.Module):
    def __init__(
        self,
        cnf: FusedMBConvConfig,
        stochastic_depth_prob: float,
        norm_layer: Callable[..., nn.Module],
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class EfficientNet(nn.Module):
    def __init__(
        self,
        inverted_residual_setting: Sequence[MBConvConfig | FusedMBConvConfig],
        dropout: float,
        stochastic_depth_prob: float = ...,
        num_classes: int = ...,
        norm_layer: Callable[..., nn.Module] | None = ...,
        last_channel: int | None = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

_COMMON_META: dict[str, Any] = ...
_COMMON_META_V1 = ...
_COMMON_META_V2 = ...

class EfficientNet_B0_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class EfficientNet_B1_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

class EfficientNet_B2_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class EfficientNet_B3_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class EfficientNet_B4_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class EfficientNet_B5_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class EfficientNet_B6_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class EfficientNet_B7_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class EfficientNet_V2_S_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class EfficientNet_V2_M_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class EfficientNet_V2_L_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(weights=("pretrained", EfficientNet_B0_Weights.IMAGENET1K_V1))
def efficientnet_b0(
    *,
    weights: EfficientNet_B0_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> EfficientNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", EfficientNet_B1_Weights.IMAGENET1K_V1))
def efficientnet_b1(
    *,
    weights: EfficientNet_B1_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> EfficientNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", EfficientNet_B2_Weights.IMAGENET1K_V1))
def efficientnet_b2(
    *,
    weights: EfficientNet_B2_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> EfficientNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", EfficientNet_B3_Weights.IMAGENET1K_V1))
def efficientnet_b3(
    *,
    weights: EfficientNet_B3_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> EfficientNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", EfficientNet_B4_Weights.IMAGENET1K_V1))
def efficientnet_b4(
    *,
    weights: EfficientNet_B4_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> EfficientNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", EfficientNet_B5_Weights.IMAGENET1K_V1))
def efficientnet_b5(
    *,
    weights: EfficientNet_B5_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> EfficientNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", EfficientNet_B6_Weights.IMAGENET1K_V1))
def efficientnet_b6(
    *,
    weights: EfficientNet_B6_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> EfficientNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", EfficientNet_B7_Weights.IMAGENET1K_V1))
def efficientnet_b7(
    *,
    weights: EfficientNet_B7_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> EfficientNet: ...
@register_model()
@handle_legacy_interface(
    weights=("pretrained", EfficientNet_V2_S_Weights.IMAGENET1K_V1)
)
def efficientnet_v2_s(
    *,
    weights: EfficientNet_V2_S_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> EfficientNet: ...
@register_model()
@handle_legacy_interface(
    weights=("pretrained", EfficientNet_V2_M_Weights.IMAGENET1K_V1)
)
def efficientnet_v2_m(
    *,
    weights: EfficientNet_V2_M_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> EfficientNet: ...
@register_model()
@handle_legacy_interface(
    weights=("pretrained", EfficientNet_V2_L_Weights.IMAGENET1K_V1)
)
def efficientnet_v2_l(
    *,
    weights: EfficientNet_V2_L_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> EfficientNet: ...
