from collections.abc import Callable
from typing import Any

from torch import Tensor, nn

import torch

from ._api import WeightsEnum, register_model
from ._utils import handle_legacy_interface

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "GoogLeNet",
    "GoogLeNetOutputs",
    "GoogLeNet_Weights",
    "_GoogLeNetOutputs",
    "googlenet",
]
GoogLeNetOutputs = ...
_GoogLeNetOutputs = ...

class GoogLeNet(nn.Module):
    __constants__ = ...
    def __init__(
        self,
        num_classes: int = ...,
        aux_logits: bool = ...,
        transform_input: bool = ...,
        init_weights: bool | None = ...,
        blocks: list[Callable[..., nn.Module]] | None = ...,
        dropout: float = ...,
        dropout_aux: float = ...,
    ) -> None: ...
    @torch.jit.unused
    def eager_outputs(
        self, x: Tensor, aux2: Tensor, aux1: Tensor | None
    ) -> GoogLeNetOutputs: ...
    def forward(self, x: Tensor) -> GoogLeNetOutputs: ...

class Inception(nn.Module):
    def __init__(
        self,
        in_channels: int,
        ch1x1: int,
        ch3x3red: int,
        ch3x3: int,
        ch5x5red: int,
        ch5x5: int,
        pool_proj: int,
        conv_block: Callable[..., nn.Module] | None = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class InceptionAux(nn.Module):
    def __init__(
        self,
        in_channels: int,
        num_classes: int,
        conv_block: Callable[..., nn.Module] | None = ...,
        dropout: float = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class BasicConv2d(nn.Module):
    def __init__(self, in_channels: int, out_channels: int, **kwargs: Any) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class GoogLeNet_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(weights=("pretrained", GoogLeNet_Weights.IMAGENET1K_V1))
def googlenet(
    *, weights: GoogLeNet_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> GoogLeNet: ...
