from collections.abc import Callable
from typing import Any

from torch import Tensor, nn

import torch

from ._api import WeightsEnum, register_model
from ._utils import handle_legacy_interface

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "Inception3",
    "InceptionOutputs",
    "Inception_V3_Weights",
    "_InceptionOutputs",
    "inception_v3",
]
InceptionOutputs = ...
_InceptionOutputs = ...

class Inception3(nn.Module):
    def __init__(
        self,
        num_classes: int = ...,
        aux_logits: bool = ...,
        transform_input: bool = ...,
        inception_blocks: list[Callable[..., nn.Module]] | None = ...,
        init_weights: bool | None = ...,
        dropout: float = ...,
    ) -> None: ...
    @torch.jit.unused
    def eager_outputs(self, x: Tensor, aux: Tensor | None) -> InceptionOutputs: ...
    def forward(self, x: Tensor) -> InceptionOutputs: ...

class InceptionA(nn.Module):
    def __init__(
        self,
        in_channels: int,
        pool_features: int,
        conv_block: Callable[..., nn.Module] | None = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class InceptionB(nn.Module):
    def __init__(
        self, in_channels: int, conv_block: Callable[..., nn.Module] | None = ...
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class InceptionC(nn.Module):
    def __init__(
        self,
        in_channels: int,
        channels_7x7: int,
        conv_block: Callable[..., nn.Module] | None = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class InceptionD(nn.Module):
    def __init__(
        self, in_channels: int, conv_block: Callable[..., nn.Module] | None = ...
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class InceptionE(nn.Module):
    def __init__(
        self, in_channels: int, conv_block: Callable[..., nn.Module] | None = ...
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class InceptionAux(nn.Module):
    def __init__(
        self,
        in_channels: int,
        num_classes: int,
        conv_block: Callable[..., nn.Module] | None = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class BasicConv2d(nn.Module):
    def __init__(self, in_channels: int, out_channels: int, **kwargs: Any) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class Inception_V3_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(weights=("pretrained", Inception_V3_Weights.IMAGENET1K_V1))
def inception_v3(
    *,
    weights: Inception_V3_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> Inception3: ...
