from collections.abc import Callable
from typing import Any

from torch import Tensor, nn
from torchvision.models._api import WeightsEnum, register_model
from torchvision.models._utils import handle_legacy_interface

import torch

"""
This type stub file was generated by pyright.
"""
__all__ = ["MaxVit", "MaxVit_T_Weights", "maxvit_t"]

class MBConv(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        expansion_ratio: float,
        squeeze_ratio: float,
        stride: int,
        activation_layer: Callable[..., nn.Module],
        norm_layer: Callable[..., nn.Module],
        p_stochastic_dropout: float = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class RelativePositionalMultiHeadAttention(nn.Module):
    def __init__(self, feat_dim: int, head_dim: int, max_seq_len: int) -> None: ...
    def get_relative_positional_bias(self) -> torch.Tensor: ...
    def forward(self, x: Tensor) -> Tensor: ...

class SwapAxes(nn.Module):
    def __init__(self, a: int, b: int) -> None: ...
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...

class WindowPartition(nn.Module):
    def __init__(self) -> None: ...
    def forward(self, x: Tensor, p: int) -> Tensor: ...

class WindowDepartition(nn.Module):
    def __init__(self) -> None: ...
    def forward(
        self, x: Tensor, p: int, h_partitions: int, w_partitions: int
    ) -> Tensor: ...

class PartitionAttentionLayer(nn.Module):
    def __init__(
        self,
        in_channels: int,
        head_dim: int,
        partition_size: int,
        partition_type: str,
        grid_size: tuple[int, int],
        mlp_ratio: int,
        activation_layer: Callable[..., nn.Module],
        norm_layer: Callable[..., nn.Module],
        attention_dropout: float,
        mlp_dropout: float,
        p_stochastic_dropout: float,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class MaxVitLayer(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        squeeze_ratio: float,
        expansion_ratio: float,
        stride: int,
        norm_layer: Callable[..., nn.Module],
        activation_layer: Callable[..., nn.Module],
        head_dim: int,
        mlp_ratio: int,
        mlp_dropout: float,
        attention_dropout: float,
        p_stochastic_dropout: float,
        partition_size: int,
        grid_size: tuple[int, int],
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class MaxVitBlock(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        squeeze_ratio: float,
        expansion_ratio: float,
        norm_layer: Callable[..., nn.Module],
        activation_layer: Callable[..., nn.Module],
        head_dim: int,
        mlp_ratio: int,
        mlp_dropout: float,
        attention_dropout: float,
        partition_size: int,
        input_grid_size: tuple[int, int],
        n_layers: int,
        p_stochastic: list[float],
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class MaxVit(nn.Module):
    def __init__(
        self,
        input_size: tuple[int, int],
        stem_channels: int,
        partition_size: int,
        block_channels: list[int],
        block_layers: list[int],
        head_dim: int,
        stochastic_depth_prob: float,
        norm_layer: Callable[..., nn.Module] | None = ...,
        activation_layer: Callable[..., nn.Module] = ...,
        squeeze_ratio: float = ...,
        expansion_ratio: float = ...,
        mlp_ratio: int = ...,
        mlp_dropout: float = ...,
        attention_dropout: float = ...,
        num_classes: int = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class MaxVit_T_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(weights=("pretrained", MaxVit_T_Weights.IMAGENET1K_V1))
def maxvit_t(
    *, weights: MaxVit_T_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> MaxVit: ...
