from typing import Any

from torch import Tensor, nn

import torch

from ._api import WeightsEnum, register_model
from ._utils import handle_legacy_interface

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "MNASNet",
    "MNASNet0_5_Weights",
    "MNASNet0_75_Weights",
    "MNASNet1_0_Weights",
    "MNASNet1_3_Weights",
    "mnasnet0_5",
    "mnasnet0_75",
    "mnasnet1_0",
    "mnasnet1_3",
]
_BN_MOMENTUM = ...

class _InvertedResidual(nn.Module):
    def __init__(
        self,
        in_ch: int,
        out_ch: int,
        kernel_size: int,
        stride: int,
        expansion_factor: int,
        bn_momentum: float = ...,
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class MNASNet(torch.nn.Module):
    _version = ...
    def __init__(
        self, alpha: float, num_classes: int = ..., dropout: float = ...
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

_COMMON_META = ...

class MNASNet0_5_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class MNASNet0_75_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class MNASNet1_0_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class MNASNet1_3_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(weights=("pretrained", MNASNet0_5_Weights.IMAGENET1K_V1))
def mnasnet0_5(
    *, weights: MNASNet0_5_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> MNASNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", MNASNet0_75_Weights.IMAGENET1K_V1))
def mnasnet0_75(
    *, weights: MNASNet0_75_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> MNASNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", MNASNet1_0_Weights.IMAGENET1K_V1))
def mnasnet1_0(
    *, weights: MNASNet1_0_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> MNASNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", MNASNet1_3_Weights.IMAGENET1K_V1))
def mnasnet1_3(
    *, weights: MNASNet1_3_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> MNASNet: ...
