from collections.abc import Callable
from typing import Any

from torch import Tensor, nn

from ._api import WeightsEnum, register_model
from ._utils import handle_legacy_interface

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "MobileNetV3",
    "MobileNet_V3_Large_Weights",
    "MobileNet_V3_Small_Weights",
    "mobilenet_v3_large",
    "mobilenet_v3_small",
]

class InvertedResidualConfig:
    def __init__(
        self,
        input_channels: int,
        kernel: int,
        expanded_channels: int,
        out_channels: int,
        use_se: bool,
        activation: str,
        stride: int,
        dilation: int,
        width_mult: float,
    ) -> None: ...
    @staticmethod
    def adjust_channels(channels: int, width_mult: float): ...

class InvertedResidual(nn.Module):
    def __init__(
        self,
        cnf: InvertedResidualConfig,
        norm_layer: Callable[..., nn.Module],
        se_layer: Callable[..., nn.Module] = ...,
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class MobileNetV3(nn.Module):
    def __init__(
        self,
        inverted_residual_setting: list[InvertedResidualConfig],
        last_channel: int,
        num_classes: int = ...,
        block: Callable[..., nn.Module] | None = ...,
        norm_layer: Callable[..., nn.Module] | None = ...,
        dropout: float = ...,
        **kwargs: Any,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

_COMMON_META = ...

class MobileNet_V3_Large_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

class MobileNet_V3_Small_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(
    weights=("pretrained", MobileNet_V3_Large_Weights.IMAGENET1K_V1)
)
def mobilenet_v3_large(
    *,
    weights: MobileNet_V3_Large_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> MobileNetV3: ...
@register_model()
@handle_legacy_interface(
    weights=("pretrained", MobileNet_V3_Small_Weights.IMAGENET1K_V1)
)
def mobilenet_v3_small(
    *,
    weights: MobileNet_V3_Small_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> MobileNetV3: ...
