from collections.abc import Callable
from typing import Any

from torch import Tensor, nn

from ._api import WeightsEnum, register_model
from ._utils import handle_legacy_interface

"""
This type stub file was generated by pyright.
"""
__all__ = ["MobileNetV2", "MobileNet_V2_Weights", "mobilenet_v2"]

class InvertedResidual(nn.Module):
    def __init__(
        self,
        inp: int,
        oup: int,
        stride: int,
        expand_ratio: int,
        norm_layer: Callable[..., nn.Module] | None = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class MobileNetV2(nn.Module):
    def __init__(
        self,
        num_classes: int = ...,
        width_mult: float = ...,
        inverted_residual_setting: list[list[int]] | None = ...,
        round_nearest: int = ...,
        block: Callable[..., nn.Module] | None = ...,
        norm_layer: Callable[..., nn.Module] | None = ...,
        dropout: float = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

_COMMON_META = ...

class MobileNet_V2_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(weights=("pretrained", MobileNet_V2_Weights.IMAGENET1K_V1))
def mobilenet_v2(
    *,
    weights: MobileNet_V2_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> MobileNetV2: ...
