from collections.abc import Callable
from typing import Any

from torch import Tensor, nn

from ._api import WeightsEnum, register_model
from ._utils import handle_legacy_interface
from ..ops.misc import Conv2dNormActivation

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "RegNet",
    "RegNet_X_1_6GF_Weights",
    "RegNet_X_3_2GF_Weights",
    "RegNet_X_8GF_Weights",
    "RegNet_X_16GF_Weights",
    "RegNet_X_32GF_Weights",
    "RegNet_X_400MF_Weights",
    "RegNet_X_800MF_Weights",
    "RegNet_Y_1_6GF_Weights",
    "RegNet_Y_3_2GF_Weights",
    "RegNet_Y_8GF_Weights",
    "RegNet_Y_16GF_Weights",
    "RegNet_Y_32GF_Weights",
    "RegNet_Y_128GF_Weights",
    "RegNet_Y_400MF_Weights",
    "RegNet_Y_800MF_Weights",
    "regnet_x_1_6gf",
    "regnet_x_3_2gf",
    "regnet_x_8gf",
    "regnet_x_16gf",
    "regnet_x_32gf",
    "regnet_x_400mf",
    "regnet_x_800mf",
    "regnet_y_1_6gf",
    "regnet_y_3_2gf",
    "regnet_y_8gf",
    "regnet_y_16gf",
    "regnet_y_32gf",
    "regnet_y_128gf",
    "regnet_y_400mf",
    "regnet_y_800mf",
]

class SimpleStemIN(Conv2dNormActivation):
    def __init__(
        self,
        width_in: int,
        width_out: int,
        norm_layer: Callable[..., nn.Module],
        activation_layer: Callable[..., nn.Module],
    ) -> None: ...

class BottleneckTransform(nn.Sequential):
    def __init__(
        self,
        width_in: int,
        width_out: int,
        stride: int,
        norm_layer: Callable[..., nn.Module],
        activation_layer: Callable[..., nn.Module],
        group_width: int,
        bottleneck_multiplier: float,
        se_ratio: float | None,
    ) -> None: ...

class ResBottleneckBlock(nn.Module):
    def __init__(
        self,
        width_in: int,
        width_out: int,
        stride: int,
        norm_layer: Callable[..., nn.Module],
        activation_layer: Callable[..., nn.Module],
        group_width: int = ...,
        bottleneck_multiplier: float = ...,
        se_ratio: float | None = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

class AnyStage(nn.Sequential):
    def __init__(
        self,
        width_in: int,
        width_out: int,
        stride: int,
        depth: int,
        block_constructor: Callable[..., nn.Module],
        norm_layer: Callable[..., nn.Module],
        activation_layer: Callable[..., nn.Module],
        group_width: int,
        bottleneck_multiplier: float,
        se_ratio: float | None = ...,
        stage_index: int = ...,
    ) -> None: ...

class BlockParams:
    def __init__(
        self,
        depths: list[int],
        widths: list[int],
        group_widths: list[int],
        bottleneck_multipliers: list[float],
        strides: list[int],
        se_ratio: float | None = ...,
    ) -> None: ...
    @classmethod
    def from_init_params(
        cls,
        depth: int,
        w_0: int,
        w_a: float,
        w_m: float,
        group_width: int,
        bottleneck_multiplier: float = ...,
        se_ratio: float | None = ...,
        **kwargs: Any,
    ) -> BlockParams: ...

class RegNet(nn.Module):
    def __init__(
        self,
        block_params: BlockParams,
        num_classes: int = ...,
        stem_width: int = ...,
        stem_type: Callable[..., nn.Module] | None = ...,
        block_type: Callable[..., nn.Module] | None = ...,
        norm_layer: Callable[..., nn.Module] | None = ...,
        activation: Callable[..., nn.Module] | None = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

_COMMON_META: dict[str, Any] = ...
_COMMON_SWAG_META = ...

class RegNet_Y_400MF_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

class RegNet_Y_800MF_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

class RegNet_Y_1_6GF_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

class RegNet_Y_3_2GF_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

class RegNet_Y_8GF_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

class RegNet_Y_16GF_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    IMAGENET1K_SWAG_E2E_V1 = ...
    IMAGENET1K_SWAG_LINEAR_V1 = ...
    DEFAULT = ...

class RegNet_Y_32GF_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    IMAGENET1K_SWAG_E2E_V1 = ...
    IMAGENET1K_SWAG_LINEAR_V1 = ...
    DEFAULT = ...

class RegNet_Y_128GF_Weights(WeightsEnum):
    IMAGENET1K_SWAG_E2E_V1 = ...
    IMAGENET1K_SWAG_LINEAR_V1 = ...
    DEFAULT = ...

class RegNet_X_400MF_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

class RegNet_X_800MF_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

class RegNet_X_1_6GF_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

class RegNet_X_3_2GF_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

class RegNet_X_8GF_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

class RegNet_X_16GF_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

class RegNet_X_32GF_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(weights=("pretrained", RegNet_Y_400MF_Weights.IMAGENET1K_V1))
def regnet_y_400mf(
    *,
    weights: RegNet_Y_400MF_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> RegNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", RegNet_Y_800MF_Weights.IMAGENET1K_V1))
def regnet_y_800mf(
    *,
    weights: RegNet_Y_800MF_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> RegNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", RegNet_Y_1_6GF_Weights.IMAGENET1K_V1))
def regnet_y_1_6gf(
    *,
    weights: RegNet_Y_1_6GF_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> RegNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", RegNet_Y_3_2GF_Weights.IMAGENET1K_V1))
def regnet_y_3_2gf(
    *,
    weights: RegNet_Y_3_2GF_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> RegNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", RegNet_Y_8GF_Weights.IMAGENET1K_V1))
def regnet_y_8gf(
    *,
    weights: RegNet_Y_8GF_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> RegNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", RegNet_Y_16GF_Weights.IMAGENET1K_V1))
def regnet_y_16gf(
    *,
    weights: RegNet_Y_16GF_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> RegNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", RegNet_Y_32GF_Weights.IMAGENET1K_V1))
def regnet_y_32gf(
    *,
    weights: RegNet_Y_32GF_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> RegNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", None))
def regnet_y_128gf(
    *,
    weights: RegNet_Y_128GF_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> RegNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", RegNet_X_400MF_Weights.IMAGENET1K_V1))
def regnet_x_400mf(
    *,
    weights: RegNet_X_400MF_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> RegNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", RegNet_X_800MF_Weights.IMAGENET1K_V1))
def regnet_x_800mf(
    *,
    weights: RegNet_X_800MF_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> RegNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", RegNet_X_1_6GF_Weights.IMAGENET1K_V1))
def regnet_x_1_6gf(
    *,
    weights: RegNet_X_1_6GF_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> RegNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", RegNet_X_3_2GF_Weights.IMAGENET1K_V1))
def regnet_x_3_2gf(
    *,
    weights: RegNet_X_3_2GF_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> RegNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", RegNet_X_8GF_Weights.IMAGENET1K_V1))
def regnet_x_8gf(
    *,
    weights: RegNet_X_8GF_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> RegNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", RegNet_X_16GF_Weights.IMAGENET1K_V1))
def regnet_x_16gf(
    *,
    weights: RegNet_X_16GF_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> RegNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", RegNet_X_32GF_Weights.IMAGENET1K_V1))
def regnet_x_32gf(
    *,
    weights: RegNet_X_32GF_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> RegNet: ...
