from collections.abc import Callable
from typing import Any

from torch import Tensor, nn

from ._api import WeightsEnum, register_model
from ._utils import handle_legacy_interface

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "ResNeXt50_32X4D_Weights",
    "ResNeXt101_32X8D_Weights",
    "ResNeXt101_64X4D_Weights",
    "ResNet",
    "ResNet18_Weights",
    "ResNet34_Weights",
    "ResNet50_Weights",
    "ResNet101_Weights",
    "ResNet152_Weights",
    "Wide_ResNet50_2_Weights",
    "Wide_ResNet101_2_Weights",
    "resnet18",
    "resnet34",
    "resnet50",
    "resnet101",
    "resnet152",
    "resnext50_32x4d",
    "resnext101_32x8d",
    "resnext101_64x4d",
    "wide_resnet50_2",
    "wide_resnet101_2",
]

def conv3x3(
    in_planes: int,
    out_planes: int,
    stride: int = ...,
    groups: int = ...,
    dilation: int = ...,
) -> nn.Conv2d: ...
def conv1x1(in_planes: int, out_planes: int, stride: int = ...) -> nn.Conv2d: ...

class BasicBlock(nn.Module):
    expansion: int = ...
    def __init__(
        self,
        inplanes: int,
        planes: int,
        stride: int = ...,
        downsample: nn.Module | None = ...,
        groups: int = ...,
        base_width: int = ...,
        dilation: int = ...,
        norm_layer: Callable[..., nn.Module] | None = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class Bottleneck(nn.Module):
    expansion: int = ...
    def __init__(
        self,
        inplanes: int,
        planes: int,
        stride: int = ...,
        downsample: nn.Module | None = ...,
        groups: int = ...,
        base_width: int = ...,
        dilation: int = ...,
        norm_layer: Callable[..., nn.Module] | None = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class ResNet(nn.Module):
    def __init__(
        self,
        block: type[BasicBlock | Bottleneck],
        layers: list[int],
        num_classes: int = ...,
        zero_init_residual: bool = ...,
        groups: int = ...,
        width_per_group: int = ...,
        replace_stride_with_dilation: list[bool] | None = ...,
        norm_layer: Callable[..., nn.Module] | None = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

_COMMON_META = ...

class ResNet18_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class ResNet34_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class ResNet50_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

class ResNet101_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

class ResNet152_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

class ResNeXt50_32X4D_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

class ResNeXt101_32X8D_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

class ResNeXt101_64X4D_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class Wide_ResNet50_2_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

class Wide_ResNet101_2_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_V2 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(weights=("pretrained", ResNet18_Weights.IMAGENET1K_V1))
def resnet18(
    *, weights: ResNet18_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> ResNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", ResNet34_Weights.IMAGENET1K_V1))
def resnet34(
    *, weights: ResNet34_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> ResNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", ResNet50_Weights.IMAGENET1K_V1))
def resnet50(
    *, weights: ResNet50_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> ResNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", ResNet101_Weights.IMAGENET1K_V1))
def resnet101(
    *, weights: ResNet101_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> ResNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", ResNet152_Weights.IMAGENET1K_V1))
def resnet152(
    *, weights: ResNet152_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> ResNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", ResNeXt50_32X4D_Weights.IMAGENET1K_V1))
def resnext50_32x4d(
    *,
    weights: ResNeXt50_32X4D_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> ResNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", ResNeXt101_32X8D_Weights.IMAGENET1K_V1))
def resnext101_32x8d(
    *,
    weights: ResNeXt101_32X8D_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> ResNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", ResNeXt101_64X4D_Weights.IMAGENET1K_V1))
def resnext101_64x4d(
    *,
    weights: ResNeXt101_64X4D_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> ResNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", Wide_ResNet50_2_Weights.IMAGENET1K_V1))
def wide_resnet50_2(
    *,
    weights: Wide_ResNet50_2_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> ResNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", Wide_ResNet101_2_Weights.IMAGENET1K_V1))
def wide_resnet101_2(
    *,
    weights: Wide_ResNet101_2_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> ResNet: ...
