from collections.abc import Callable
from typing import Any

from torch import Tensor, nn

from ._api import WeightsEnum, register_model
from ._utils import handle_legacy_interface

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "ShuffleNetV2",
    "ShuffleNet_V2_X0_5_Weights",
    "ShuffleNet_V2_X1_0_Weights",
    "ShuffleNet_V2_X1_5_Weights",
    "ShuffleNet_V2_X2_0_Weights",
    "shufflenet_v2_x0_5",
    "shufflenet_v2_x1_0",
    "shufflenet_v2_x1_5",
    "shufflenet_v2_x2_0",
]

def channel_shuffle(x: Tensor, groups: int) -> Tensor: ...

class InvertedResidual(nn.Module):
    def __init__(self, inp: int, oup: int, stride: int) -> None: ...
    @staticmethod
    def depthwise_conv(
        i: int,
        o: int,
        kernel_size: int,
        stride: int = ...,
        padding: int = ...,
        bias: bool = ...,
    ) -> nn.Conv2d: ...
    def forward(self, x: Tensor) -> Tensor: ...

class ShuffleNetV2(nn.Module):
    def __init__(
        self,
        stages_repeats: list[int],
        stages_out_channels: list[int],
        num_classes: int = ...,
        inverted_residual: Callable[..., nn.Module] = ...,
    ) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...

_COMMON_META = ...

class ShuffleNet_V2_X0_5_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class ShuffleNet_V2_X1_0_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class ShuffleNet_V2_X1_5_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class ShuffleNet_V2_X2_0_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(
    weights=("pretrained", ShuffleNet_V2_X0_5_Weights.IMAGENET1K_V1)
)
def shufflenet_v2_x0_5(
    *,
    weights: ShuffleNet_V2_X0_5_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> ShuffleNetV2: ...
@register_model()
@handle_legacy_interface(
    weights=("pretrained", ShuffleNet_V2_X1_0_Weights.IMAGENET1K_V1)
)
def shufflenet_v2_x1_0(
    *,
    weights: ShuffleNet_V2_X1_0_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> ShuffleNetV2: ...
@register_model()
@handle_legacy_interface(
    weights=("pretrained", ShuffleNet_V2_X1_5_Weights.IMAGENET1K_V1)
)
def shufflenet_v2_x1_5(
    *,
    weights: ShuffleNet_V2_X1_5_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> ShuffleNetV2: ...
@register_model()
@handle_legacy_interface(
    weights=("pretrained", ShuffleNet_V2_X2_0_Weights.IMAGENET1K_V1)
)
def shufflenet_v2_x2_0(
    *,
    weights: ShuffleNet_V2_X2_0_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> ShuffleNetV2: ...
