from typing import Any

from torch import nn

import torch

from ._api import WeightsEnum, register_model
from ._utils import handle_legacy_interface

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "SqueezeNet",
    "SqueezeNet1_0_Weights",
    "SqueezeNet1_1_Weights",
    "squeezenet1_0",
    "squeezenet1_1",
]

class Fire(nn.Module):
    def __init__(
        self,
        inplanes: int,
        squeeze_planes: int,
        expand1x1_planes: int,
        expand3x3_planes: int,
    ) -> None: ...
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class SqueezeNet(nn.Module):
    def __init__(
        self, version: str = ..., num_classes: int = ..., dropout: float = ...
    ) -> None: ...
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

_COMMON_META = ...

class SqueezeNet1_0_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class SqueezeNet1_1_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(weights=("pretrained", SqueezeNet1_0_Weights.IMAGENET1K_V1))
def squeezenet1_0(
    *,
    weights: SqueezeNet1_0_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> SqueezeNet: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", SqueezeNet1_1_Weights.IMAGENET1K_V1))
def squeezenet1_1(
    *,
    weights: SqueezeNet1_1_Weights | None = ...,
    progress: bool = ...,
    **kwargs: Any,
) -> SqueezeNet: ...
