from collections.abc import Callable
from typing import Any

from torch import Tensor, nn

import torch

from ._api import WeightsEnum, register_model
from ._utils import handle_legacy_interface

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "SwinTransformer",
    "Swin_B_Weights",
    "Swin_S_Weights",
    "Swin_T_Weights",
    "Swin_V2_B_Weights",
    "Swin_V2_S_Weights",
    "Swin_V2_T_Weights",
    "swin_b",
    "swin_s",
    "swin_t",
    "swin_v2_b",
    "swin_v2_s",
    "swin_v2_t",
]

class PatchMerging(nn.Module):
    def __init__(
        self, dim: int, norm_layer: Callable[..., nn.Module] = ...
    ) -> None: ...
    def forward(self, x: Tensor): ...

class PatchMergingV2(nn.Module):
    def __init__(
        self, dim: int, norm_layer: Callable[..., nn.Module] = ...
    ) -> None: ...
    def forward(self, x: Tensor): ...

def shifted_window_attention(
    input: Tensor,
    qkv_weight: Tensor,
    proj_weight: Tensor,
    relative_position_bias: Tensor,
    window_size: list[int],
    num_heads: int,
    shift_size: list[int],
    attention_dropout: float = ...,
    dropout: float = ...,
    qkv_bias: Tensor | None = ...,
    proj_bias: Tensor | None = ...,
    logit_scale: torch.Tensor | None = ...,
    training: bool = ...,
) -> Tensor: ...

class ShiftedWindowAttention(nn.Module):
    def __init__(
        self,
        dim: int,
        window_size: list[int],
        shift_size: list[int],
        num_heads: int,
        qkv_bias: bool = ...,
        proj_bias: bool = ...,
        attention_dropout: float = ...,
        dropout: float = ...,
    ) -> None: ...
    def define_relative_position_bias_table(self): ...
    def define_relative_position_index(self): ...
    def get_relative_position_bias(self) -> torch.Tensor: ...
    def forward(self, x: Tensor) -> Tensor: ...

class ShiftedWindowAttentionV2(ShiftedWindowAttention):
    def __init__(
        self,
        dim: int,
        window_size: list[int],
        shift_size: list[int],
        num_heads: int,
        qkv_bias: bool = ...,
        proj_bias: bool = ...,
        attention_dropout: float = ...,
        dropout: float = ...,
    ) -> None: ...
    def define_relative_position_bias_table(self): ...
    def get_relative_position_bias(self) -> torch.Tensor: ...
    def forward(self, x: Tensor): ...

class SwinTransformerBlock(nn.Module):
    def __init__(
        self,
        dim: int,
        num_heads: int,
        window_size: list[int],
        shift_size: list[int],
        mlp_ratio: float = ...,
        dropout: float = ...,
        attention_dropout: float = ...,
        stochastic_depth_prob: float = ...,
        norm_layer: Callable[..., nn.Module] = ...,
        attn_layer: Callable[..., nn.Module] = ...,
    ) -> None: ...
    def forward(self, x: Tensor): ...

class SwinTransformerBlockV2(SwinTransformerBlock):
    def __init__(
        self,
        dim: int,
        num_heads: int,
        window_size: list[int],
        shift_size: list[int],
        mlp_ratio: float = ...,
        dropout: float = ...,
        attention_dropout: float = ...,
        stochastic_depth_prob: float = ...,
        norm_layer: Callable[..., nn.Module] = ...,
        attn_layer: Callable[..., nn.Module] = ...,
    ) -> None: ...
    def forward(self, x: Tensor): ...

class SwinTransformer(nn.Module):
    def __init__(
        self,
        patch_size: list[int],
        embed_dim: int,
        depths: list[int],
        num_heads: list[int],
        window_size: list[int],
        mlp_ratio: float = ...,
        dropout: float = ...,
        attention_dropout: float = ...,
        stochastic_depth_prob: float = ...,
        num_classes: int = ...,
        norm_layer: Callable[..., nn.Module] | None = ...,
        block: Callable[..., nn.Module] | None = ...,
        downsample_layer: Callable[..., nn.Module] = ...,
    ) -> None: ...
    def forward(self, x): ...

_COMMON_META = ...

class Swin_T_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class Swin_S_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class Swin_B_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class Swin_V2_T_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class Swin_V2_S_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class Swin_V2_B_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(weights=("pretrained", Swin_T_Weights.IMAGENET1K_V1))
def swin_t(
    *, weights: Swin_T_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> SwinTransformer: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", Swin_S_Weights.IMAGENET1K_V1))
def swin_s(
    *, weights: Swin_S_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> SwinTransformer: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", Swin_B_Weights.IMAGENET1K_V1))
def swin_b(
    *, weights: Swin_B_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> SwinTransformer: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", Swin_V2_T_Weights.IMAGENET1K_V1))
def swin_v2_t(
    *, weights: Swin_V2_T_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> SwinTransformer: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", Swin_V2_S_Weights.IMAGENET1K_V1))
def swin_v2_s(
    *, weights: Swin_V2_S_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> SwinTransformer: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", Swin_V2_B_Weights.IMAGENET1K_V1))
def swin_v2_b(
    *, weights: Swin_V2_B_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> SwinTransformer: ...
