from typing import Any

from torch import nn

import torch

from ._api import WeightsEnum, register_model
from ._utils import handle_legacy_interface

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "VGG",
    "VGG11_BN_Weights",
    "VGG11_Weights",
    "VGG13_BN_Weights",
    "VGG13_Weights",
    "VGG16_BN_Weights",
    "VGG16_Weights",
    "VGG19_BN_Weights",
    "VGG19_Weights",
    "vgg11",
    "vgg11_bn",
    "vgg13",
    "vgg13_bn",
    "vgg16",
    "vgg16_bn",
    "vgg19",
    "vgg19_bn",
]

class VGG(nn.Module):
    def __init__(
        self,
        features: nn.Module,
        num_classes: int = ...,
        init_weights: bool = ...,
        dropout: float = ...,
    ) -> None: ...
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...

def make_layers(cfg: list[str | int], batch_norm: bool = ...) -> nn.Sequential: ...

cfgs: dict[str, list[str | int]] = ...
_COMMON_META = ...

class VGG11_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class VGG11_BN_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class VGG13_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class VGG13_BN_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class VGG16_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_FEATURES = ...
    DEFAULT = ...

class VGG16_BN_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class VGG19_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class VGG19_BN_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(weights=("pretrained", VGG11_Weights.IMAGENET1K_V1))
def vgg11(
    *, weights: VGG11_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> VGG: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", VGG11_BN_Weights.IMAGENET1K_V1))
def vgg11_bn(
    *, weights: VGG11_BN_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> VGG: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", VGG13_Weights.IMAGENET1K_V1))
def vgg13(
    *, weights: VGG13_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> VGG: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", VGG13_BN_Weights.IMAGENET1K_V1))
def vgg13_bn(
    *, weights: VGG13_BN_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> VGG: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", VGG16_Weights.IMAGENET1K_V1))
def vgg16(
    *, weights: VGG16_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> VGG: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", VGG16_BN_Weights.IMAGENET1K_V1))
def vgg16_bn(
    *, weights: VGG16_BN_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> VGG: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", VGG19_Weights.IMAGENET1K_V1))
def vgg19(
    *, weights: VGG19_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> VGG: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", VGG19_BN_Weights.IMAGENET1K_V1))
def vgg19_bn(
    *, weights: VGG19_BN_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> VGG: ...
