from collections import OrderedDict
from collections.abc import Callable
from typing import Any, NamedTuple

from torch import nn

import torch

from ._api import WeightsEnum, register_model
from ._utils import handle_legacy_interface
from ..ops.misc import MLP

"""
This type stub file was generated by pyright.
"""
__all__ = [
    "ViT_B_16_Weights",
    "ViT_B_32_Weights",
    "ViT_H_14_Weights",
    "ViT_L_16_Weights",
    "ViT_L_32_Weights",
    "VisionTransformer",
    "vit_b_16",
    "vit_b_32",
    "vit_h_14",
    "vit_l_16",
    "vit_l_32",
]

class ConvStemConfig(NamedTuple):
    out_channels: int
    kernel_size: int
    stride: int
    norm_layer: Callable[..., nn.Module] = ...
    activation_layer: Callable[..., nn.Module] = ...

class MLPBlock(MLP):
    _version = ...
    def __init__(self, in_dim: int, mlp_dim: int, dropout: float) -> None: ...

class EncoderBlock(nn.Module):
    def __init__(
        self,
        num_heads: int,
        hidden_dim: int,
        mlp_dim: int,
        dropout: float,
        attention_dropout: float,
        norm_layer: Callable[..., torch.nn.Module] = ...,
    ) -> None: ...
    def forward(self, input: torch.Tensor): ...

class Encoder(nn.Module):
    def __init__(
        self,
        seq_length: int,
        num_layers: int,
        num_heads: int,
        hidden_dim: int,
        mlp_dim: int,
        dropout: float,
        attention_dropout: float,
        norm_layer: Callable[..., torch.nn.Module] = ...,
    ) -> None: ...
    def forward(self, input: torch.Tensor): ...

class VisionTransformer(nn.Module):
    def __init__(
        self,
        image_size: int,
        patch_size: int,
        num_layers: int,
        num_heads: int,
        hidden_dim: int,
        mlp_dim: int,
        dropout: float = ...,
        attention_dropout: float = ...,
        num_classes: int = ...,
        representation_size: int | None = ...,
        norm_layer: Callable[..., torch.nn.Module] = ...,
        conv_stem_configs: list[ConvStemConfig] | None = ...,
    ) -> None: ...
    def forward(self, x: torch.Tensor): ...

_COMMON_META: dict[str, Any] = ...
_COMMON_SWAG_META = ...

class ViT_B_16_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_SWAG_E2E_V1 = ...
    IMAGENET1K_SWAG_LINEAR_V1 = ...
    DEFAULT = ...

class ViT_B_32_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class ViT_L_16_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    IMAGENET1K_SWAG_E2E_V1 = ...
    IMAGENET1K_SWAG_LINEAR_V1 = ...
    DEFAULT = ...

class ViT_L_32_Weights(WeightsEnum):
    IMAGENET1K_V1 = ...
    DEFAULT = ...

class ViT_H_14_Weights(WeightsEnum):
    IMAGENET1K_SWAG_E2E_V1 = ...
    IMAGENET1K_SWAG_LINEAR_V1 = ...
    DEFAULT = ...

@register_model()
@handle_legacy_interface(weights=("pretrained", ViT_B_16_Weights.IMAGENET1K_V1))
def vit_b_16(
    *, weights: ViT_B_16_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> VisionTransformer: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", ViT_B_32_Weights.IMAGENET1K_V1))
def vit_b_32(
    *, weights: ViT_B_32_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> VisionTransformer: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", ViT_L_16_Weights.IMAGENET1K_V1))
def vit_l_16(
    *, weights: ViT_L_16_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> VisionTransformer: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", ViT_L_32_Weights.IMAGENET1K_V1))
def vit_l_32(
    *, weights: ViT_L_32_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> VisionTransformer: ...
@register_model()
@handle_legacy_interface(weights=("pretrained", None))
def vit_h_14(
    *, weights: ViT_H_14_Weights | None = ..., progress: bool = ..., **kwargs: Any
) -> VisionTransformer: ...
def interpolate_embeddings(
    image_size: int,
    patch_size: int,
    model_state: OrderedDict[str, torch.Tensor],
    interpolation_mode: str = ...,
    reset_heads: bool = ...,
) -> OrderedDict[str, torch.Tensor]: ...
