from collections.abc import Callable, Sequence
from typing import Any, Literal

import dataclasses
import threading

from _typeshed import Incomplete
from jax._src.pallas.mosaic.interpret import vector_clock as vc

import numpy as np

class Semaphore:
    shared_memory: Incomplete
    id: int
    cv: Incomplete
    count_by_core: Incomplete
    clocks: list[vc.VectorClock | None]
    def __init__(self, shared_memory: SharedMemory, semaphore_id: int) -> None: ...
    @property
    def num_cores(self) -> int: ...
    @property
    def detect_races(self) -> bool: ...
    @property
    def dma_execution_mode(self) -> str: ...
    def get_global_core_id(self, device_id: int, local_core_id: int) -> int: ...
    def signal(self, inc, global_core_id, clock) -> None: ...
    def read(self, global_core_id): ...
    def wait(self, value, global_core_id, *, has_tasks: bool = False) -> None: ...

type SemaphoreTask = Callable[[], None]

@dataclasses.dataclass(init=False)
class Allocation: ...

@dataclasses.dataclass
class Buffer(Allocation):
    content: np.ndarray
    _: dataclasses.KW_ONLY
    ref_count: int = ...
    def decrease_ref_count(self) -> None: ...
    def has_zero_ref_count(self) -> bool: ...
    def size(self) -> int: ...

@dataclasses.dataclass(frozen=True)
class ShapeAndDtype:
    shape: Sequence[int]
    dtype: np.dtype
    def __iter__(self): ...

@dataclasses.dataclass
class SharedMemory:
    num_devices: int
    num_cores_per_device: int
    out_of_bounds_reads: str
    dma_execution_mode: str
    uninitialized_memory: Literal["nan", "zero"]
    detect_races: bool
    vector_clock_size: int
    clocks: list[vc.VectorClock]
    barrier: threading.Barrier
    clean_up_barrier: threading.Barrier
    mem: dict[tuple[str, int, int, int], Allocation] = ...
    sem: dict[int, Semaphore] = ...
    tasks_by_sem: dict[tuple[int, int], list[SemaphoreTask]] = ...
    lock: threading.Lock = ...
    next_buffer_id: dict[tuple[int, int], int] = ...
    next_semaphore_id: dict[int, int] = ...
    deallocated_bytes: int = ...
    output_ranges: dict[tuple[int, int], list] = ...
    fixed_id_sem: dict[int, Semaphore] = ...
    @property
    def num_cores(self) -> int: ...
    def get_global_core_id(self, device_id: int, local_core_id: int) -> int: ...
    def get_global_core_ids(self, device_id: int) -> Sequence[int]: ...
    def append_semaphore_task(
        self,
        semaphore_id: int,
        global_core_id: int,
        task: SemaphoreTask,
    ): ...
    def get_random_virtual_device_id(self) -> int: ...
    def print(self, device_id: int): ...
    def get_semaphores_and_increment_clock(
        self,
        sem_ids: Sequence[int | None],
        global_core_id: int,
    ) -> tuple[list[Semaphore | None], vc.VectorClock | None]: ...
    def get_sempahores_with_nonzero_count(
        self,
        device_id: int,
    ) -> list[tuple[Semaphore, int]]: ...
    def get_next_buffer_id(self, device_id: int, local_core_id: int) -> int: ...
    def allocate_buffer(self, key: Any, ref_count: int, value: np.ndarray): ...
    def deallocate_buffer(self, key: Any): ...
    def allocate_semaphores(self, key: Any, num_semaphores: int) -> int: ...
    def guarantee_semaphore_with_fixed_id(self, semaphore_id: int): ...
    def get_buffer_content(
        self,
        key: Any,
        rnge: tuple[slice | int, ...],
        global_core_id: int,
    ) -> tuple[np.ndarray | None, ShapeAndDtype, vc.VectorClock | None]: ...
    def store_buffer_content(
        self,
        key: Any,
        rnge: tuple[slice | int, ...],
        value: np.ndarray,
        global_core_id: int,
    ) -> tuple[bool, ShapeAndDtype, vc.VectorClock | None]: ...
    def swap_buffer_content(
        self,
        key: Any,
        rnge: tuple[slice | int, ...],
        value: np.ndarray,
        mask: np.ndarray | None,
        global_core_id: int,
    ) -> tuple[np.ndarray | None, ShapeAndDtype, vc.VectorClock | None]: ...
    def update_clocks(self, low_global_core_id, high_global_core_id) -> None: ...
    def update_clocks_for_device_barrier(self, device_id) -> None: ...
