from collections.abc import Sequence
from typing import Any, Literal

import dataclasses
import enum

from _typeshed import Incomplete
from jax import lax as lax
from jax._src import core as jax_core
from jax._src.pallas import primitives as primitives
from jax._src.util import safe_map as safe_map

import jax.numpy as jnp

def get_uninitialized_value(dtype, uninitialized_memory: Literal["nan", "zero"]): ...

@dataclasses.dataclass(frozen=True, kw_only=True)
class InterpretParams:
    detect_races: bool = ...
    out_of_bounds_reads: Literal["raise", "uninitialized"] = ...
    skip_floating_point_ops: bool = ...
    uninitialized_memory: Literal["nan", "zero"] = ...
    num_cores_or_threads: int = ...
    vector_clock_size: int | None = ...
    def __post_init__(self) -> None: ...
    def get_vector_clock_size(self, num_devices) -> int: ...
    def get_uninitialized_array(self, shape, dtype): ...
    def pad_to_block_dimension(self, value, block_shape): ...

class LoggingMode(enum.Flag):
    BARRIER = ...
    SHARED_MEMORY = ...

@dataclasses.dataclass(frozen=True, kw_only=True)
class InterpretGPUParams(InterpretParams):
    logging_mode: LoggingMode | None = ...

class Counter:
    value: Incomplete
    lock: Incomplete
    def __init__(self, initial_value: int) -> None: ...
    def get_next(self): ...

def device_coords_to_logical_id(device_coords, axis_sizes, axis_indices): ...
def is_int(dtype): ...
def is_float(dtype): ...

@dataclasses.dataclass(frozen=True)
class Placeholder:
    shape: tuple[int, ...]
    dtype: jnp.dtype

class JaxprEnv:
    def __init__(
        self,
        *,
        vars: Sequence[jax_core.Var] | None = None,
        values: Sequence[Any] | None = None,
        sentinel_for_floating_point_values: Any = None,
    ) -> None: ...
    def read(self, var): ...
    def read_many(self, vars): ...
    def write(self, var, value) -> None: ...
    def write_many(self, vars, values) -> None: ...

def to_range(transforms) -> tuple[slice | int, ...]: ...
def get_next_indices(grid, indices): ...
def get_indices(grid, loop_index): ...
