import numpy as np

VectorClock = np.ndarray

def make_vector_clock(vector_clock_size: int) -> VectorClock: ...
def copy_vector_clock(x: VectorClock | None) -> VectorClock | None: ...
def update_vector_clock(x: VectorClock, y: VectorClock): ...
def lt(x: VectorClock, y: VectorClock) -> bool: ...
def ordered(x: VectorClock, y: VectorClock) -> bool: ...
def inc_vector_clock(x: VectorClock, global_core_id: int): ...
