from typing import Any

from jax._src import (
    lax as lax,
    tree_util as tree_util,
)

class Stack:
    def __init__(self, size, data) -> None: ...
    @staticmethod
    def create(capacity: int, prototype: Any) -> Stack: ...
    def empty(self) -> Any: ...
    def push(self, elem: Any) -> Stack: ...
    def pop(self) -> tuple[Any, Stack]: ...
    def flatten(self): ...
    @staticmethod
    def unflatten(treedef, leaves): ...
