from lpips.lpips import *
from lpips.trainer import *

def normalize_tensor(in_feat, eps=...): ...
def l2(p0, p1, range=...): ...
def psnr(p0, p1, peak=...) -> Any: ...
def dssim(p0, p1, range=...): ...
def rgb2lab(in_img, mean_cent=...): ...
def tensor2np(tensor_obj): ...
def np2tensor(np_obj) -> Tensor: ...
def tensor2tensorlab(image_tensor, to_norm=..., mc_only=...) -> Tensor: ...
def tensorlab2tensor(
    lab_tensor, return_inbnd=...
) -> tuple[Tensor, Tensor] | Tensor: ...
def load_image(path) -> ndarray[_AnyShape, dtype[integer[Any] | floating[Any]]]: ...
def rgb2lab(input): ...
def tensor2im(
    image_tensor, imtype=..., cent=..., factor=...
) -> ndarray[_AnyShape, dtype[unsignedinteger[_8Bit]]]: ...
def im2tensor(image, imtype=..., cent=..., factor=...) -> Tensor: ...
def tensor2vec(vector_tensor): ...
def tensor2im(
    image_tensor, imtype=..., cent=..., factor=...
) -> ndarray[_AnyShape, dtype[unsignedinteger[_8Bit]]]: ...
def im2tensor(image, imtype=..., cent=..., factor=...) -> Tensor: ...
def voc_ap(rec, prec, use_07_metric=...) -> float | Incomplete: ...
