from typing import Any

import torch

class squeezenet(torch.nn.Module):
    def __init__(self, requires_grad=..., pretrained=...) -> None: ...
    def forward(self, X) -> SqueezeOutputs: ...
    def __call__(self, *args: Any, **kwargs: Any) -> SqueezeOutputs: ...

class alexnet(torch.nn.Module):
    def __init__(self, requires_grad=..., pretrained=...) -> None: ...
    def forward(self, X) -> AlexnetOutputs: ...
    def __call__(self, *args: Any, **kwargs: Any) -> AlexnetOutputs: ...

class vgg16(torch.nn.Module):
    def __init__(self, requires_grad=..., pretrained=...) -> None: ...
    def forward(self, X) -> VggOutputs: ...
    def __call__(self, *args: Any, **kwargs: Any) -> VggOutputs: ...

class resnet(torch.nn.Module):
    def __init__(self, requires_grad=..., pretrained=..., num=...) -> None: ...
    def forward(self, X) -> Outputs: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Outputs: ...
