import torch

class squeezenet(torch.nn.Module):
    def __init__(self, requires_grad=..., pretrained=...) -> None: ...
    def forward(self, X) -> SqueezeOutputs: ...

class alexnet(torch.nn.Module):
    def __init__(self, requires_grad=..., pretrained=...) -> None: ...
    def forward(self, X) -> AlexnetOutputs: ...

class vgg16(torch.nn.Module):
    def __init__(self, requires_grad=..., pretrained=...) -> None: ...
    def forward(self, X) -> VggOutputs: ...

class resnet(torch.nn.Module):
    def __init__(self, requires_grad=..., pretrained=..., num=...) -> None: ...
    def forward(self, X) -> Outputs: ...
