from collections import OrderedDict
from typing import Any, Literal

from numpy.typing import NDArray
from torch import Tensor

class Trainer:
    def name(self) -> str: ...
    def initialize(
        self,
        model=...,
        net=...,
        colorspace=...,
        pnet_rand=...,
        pnet_tune=...,
        model_path=...,
        use_gpu=...,
        printNet=...,
        spatial=...,
        is_train=...,
        lr=...,
        beta1=...,
        version=...,
        gpu_ids=...,
    ) -> None: ...
    def forward(
        self, in0, in1, retPerLayer=...
    ) -> tuple[Any | Literal[0], list[Any]] | Tensor | Variable | Literal[0] | None: ...
    def optimize_parameters(self) -> None: ...
    def clamp_weights(self) -> None: ...
    def set_input(self, data) -> None: ...
    def forward_train(self): ...
    def backward_train(self) -> None: ...
    def compute_accuracy(self, d0, d1, judge): ...
    def get_current_errors(
        self,
    ) -> OrderedDict[Literal[loss_total, acc_r], Any]: ...
    def get_current_visuals(
        self,
    ) -> OrderedDict[Literal[ref, p0, p1], _FloatArrayOut]: ...
    def save(self, path, label) -> None: ...
    def save_network(self, network, path, network_label, epoch_label) -> None: ...
    def load_network(self, network, network_label, epoch_label) -> None: ...
    def update_learning_rate(self, nepoch_decay) -> None: ...
    def get_image_paths(self): ...
    def save_done(self, flag=...) -> None: ...

def score_2afc_dataset(data_loader, func, name=...) -> tuple[Any, dict[str, Any]]: ...
def score_jnd_dataset(
    data_loader, func, name=...
) -> tuple[float | Any | Incomplete, dict[str, NDArray[Any]]]: ...
